/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2014-09-22 10:10:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"icons/FB.png\" />\r\n");
      out.write("<title>Social Networking Site by Milson Munakami \"Milstein\"</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.validate.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#update\").focus(function() {\r\n");
      out.write("\t\t\t$(this).animate({\r\n");
      out.write("\t\t\t\t\"height\" : \"50px\",\r\n");
      out.write("\t\t\t}, \"fast\");\r\n");
      out.write("\t\t\t$(\"#button_bar\").slideDown(\"fast\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// \t$(\"#update\").blur(function() {\r\n");
      out.write("\t\t// \t\t\t$(this).animate({\r\n");
      out.write("\t\t// \t\t\t\t\"height\" : \"30px\",\r\n");
      out.write("\t\t// \t\t\t}, \"fast\");\r\n");
      out.write("\t\t// \t\t\t$(\"#button_bar\").slideUp(\"fast\");\r\n");
      out.write("\t\t// \t\t\treturn false;\r\n");
      out.write("\t\t// \t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar BASE_URL = \"http://localhost:8080/SocialNetwork/\";\r\n");
      out.write("\r\n");
      out.write("\tonload = function() {\r\n");
      out.write("\t\tvar url = document.URL;\r\n");
      out.write("\t\tgetFeed();\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction getFeed() {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\tvar request = new XMLHttpRequest();\r\n");
      out.write("\t\t\trequest.open(\"GET\", BASE_URL + 'REST/tweet/GetFeeds', false);\r\n");
      out.write("\t\t\trequest.onreadystatechange = function() {\r\n");
      out.write("\t\t\t\tif (request.status === 200) {\r\n");
      out.write("\t\t\t\t\tvar det = eval(\"(\" + request.responseText + \")\");\r\n");
      out.write("\t\t\t\t\tvar content = \"\";\r\n");
      out.write("\t\t\t\t\tfor (var int = 0; int < det.length; int++) {\r\n");
      out.write("\t\t\t\t\t\t//alert(det[int].message + det[int].uid + det[int].msg_id);\r\n");
      out.write("\t\t\t\t\t\tcontent += '<div class=\"stbody\"><div class=\"sttext\"><a title=\"Delete Update\" id='+det[int].msg_id+' href=\"#\" class=\"stdelete\"></a></b>'\r\n");
      out.write("\t\t\t\t\t\t\t\t+ det[int].message\r\n");
      out.write("\t\t\t\t\t\t\t\t+ '<div class=\"sttime\"><span id=\"retweet\"><a title=\"Retweet\" id='+det[int].msg_id+' class=\"retweet_button\" href=\"#\">Retweet</a></span></div></div></div>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"content\").innerHTML = content;\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"content\").innerHTML = \"Unable to load the button\";\r\n");
      out.write("\t\t\t\t\talert('Error');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\trequest.send();\r\n");
      out.write("\t\t} catch (err) {\r\n");
      out.write("\t\t\talert(err);\r\n");
      out.write("\t\t\tdocument.getElementById(\"content\").innerHTML += \"\\nXMLHttprequest error: \"\r\n");
      out.write("\t\t\t\t\t+ err.description;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"container\">\r\n");
      out.write("\t\t<div id=\"nav_bar\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"float: right;\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"http://www.gravatar.com/avatar.php?gravatar_id=e9b0831929db8a935e979dc07750b0d6\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"logout.jsp\">Logout</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style='width: 400px; float: left;'>\r\n");
      out.write("\t\t\t\t<a href=\"home.jsp\">Home</a>&nbsp;|&nbsp; <a href=\"show_user.jsp\">Users</a>&nbsp;|&nbsp;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"profile.jsp?id=1\">Profile</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"wall_container\">\r\n");
      out.write("\t\t\t<div id=\"updateboxarea\">\r\n");
      out.write("\t\t\t\t<form id=\"updateStatus\" action=\"REST/tweet/PostMessage\"\r\n");
      out.write("\t\t\t\t\tmethod=\"POST\">\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-bottom: 5px; font-weight: bold;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"icons/2.png\">&nbsp;Update Status\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<textarea name=\"update\" id=\"update\" maxlength=\"128\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"What's on your mind ?\" title=\"What's on your mind ?\" required></textarea>\r\n");
      out.write("\t\t\t\t\t<div id=\"button_bar\" style=\"width: 100%; clear: both;\">\r\n");
      out.write("\t\t\t\t\t\t<br> <input type=\"submit\" value=\" Update \" id=\"update_button\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"update_button\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				String message = request.getParameter("msg");
				if (message != null) {
			
      out.write("\r\n");
      out.write("\t\t\t<div id=\"flashmessage\">\r\n");
      out.write("\t\t\t\t<div align=\"center\" class=\"error_msg\">Status updated\r\n");
      out.write("\t\t\t\t\tsuccessfully!</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"footer\">\r\n");
      out.write("\t\t\t&copy; Milson Munakami | <b><a href=\"http://www.milson.com.np\"\r\n");
      out.write("\t\t\t\ttarget=\"_blank\">Milstein</a></b>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
