(function(l,f){var r,q,u,x,v,y,w,z;q=function(t){t.a={p:"edge.simplereach.com",Ia:"d8rk54i4mohrb.cloudfront.net",ba:"/n",eb:"/t",S:"/event",L:"/pixel?bad=true&error=",Pa:"/iframe.html",Ja:"/container.html",Ba:"000000000000000000000000",za:"SPR-ERROR: ",Na:"100 - Missing url",Xa:"__reach_config",Ha:"cache_buster",ab:"__srret",J:"__srui",u:"0",Ua:"1",$:"img",ka:"1px",width:"width",oa:f.location.protocol,c:"undefined",error:"error",info:"info",j:"SPR_DEBUG",ya:"//",s:"string",referrer:"referrer",uid:"uid",b:"callback",i:"jsonp",
url:"url",G:"pid",ua:"s",Wa:"r",cb:"t",Ma:"e",x:"x",Sa:"n",Qa:"ignore_errors",Va:"preview",m:"authors",n:"channels",t:"tags",k:"date",aa:"inframe",Oa:"iframe",Ka:"custom_tracking",Ya:"reach_tracking",Za:"ref_url",D:"page_url",fb:"user_id",pa:"rd",w:"fb",O:"de",da:"li",Ca:"tw",la:"pi",T:"graph.facebook.com",P:"feeds.delicious.com",Da:"cdn.api.twitter.com",ea:"www.linkedin.com",ma:"partners-api.pinterest.com",qa:"www.reddit.com",U:"/fql",ra:"/api/info.json",Q:"/v2/json/urlinfo/data",Ea:"/1/urls/count.json",
fa:"/countserv/count/share",na:"/v1/urls/count.json",V:"SELECT url,total_count,share_count,comment_count,like_count,",W:'click_count,commentsbox_count FROM link_stat WHERE url in ("',X:'")'};return t}({});r=function(f,h){var e=f.a;h.a={ta:function(){return Math.floor(8675309*Math.random())},r:function(c){return Array.isArray?Array.isArray(c):"[object Array]"===Object.prototype.toString.call(c)},log:function(c){l.console&&console.log(c)},Ra:function(c){return"[object String]"===Object.prototype.toString.call(c)},
I:function(c){var b={},a;for(a in c)c.hasOwnProperty(a)&&(b[a]=c[a]);return b},ga:function(c,b){for(var a in b)b.hasOwnProperty(a)&&(c[a]=b[a])},o:function(c){typeof c===e.s&&(c=c.split(","));if(this.r(c)){for(var b=0;b<c.length;b+=1)typeof c[b]===e.s&&(c[b]=c[b].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return c.join("|")}},C:function(){},A:function(){return l.location.protocol+"//"}};return h}(q,{});u=function(t,h,e){var c=t.a,b=h.a;e.a={v:!1,info:b.C,error:b.log,B:function(){l[c.j]&&
(this.v=!0,l[c.j][c.info]&&(this[c.info]=l[c.j][c.info]),l[c.j][c.error]&&(this[c.error]=l[c.j][c.error]))},reset:function(){this.v=!1;this.info=b.C;this.error=b.log},wa:function(a){var b=f.createElement(c.$);b.src=c.oa+c.ya+c.p+c.L+a.message;b.setAttribute(c.width,c.ka);f.body?f.body.appendChild(b):f.head.appendChild(b)}};return e}(q,r,{});x=function(t,h,e){var c=t.a,b=h.a,b={c:"undefined",info:"info"};e.a={u:0,N:{x:0,y:0},ca:!0,B:function(){function a(){k.ca=f[d]?!1:!0}function c(){k.flush();l.removeEventListener("DOMContentLoaded",
c,!1)}function g(){/loaded|interactive|complete/.test(f.readyState)&&(f.detachEvent("onreadystatechange",g),p&&(p=!1,k.flush()))}var k=this,d,e;k.u=0;this.ia(l,"mousemove",function(a){k.N={x:a.clientX,y:a.clientY}});typeof f.hidden!==b.c?(d="hidden",e="visibilitychange"):typeof f.mozHidden!==b.c?(d="mozHidden",e="mozvisibilitychange"):typeof f.msHidden!==b.c?(d="msHidden",e="msvisibilitychange"):typeof f.webkitHidden!==b.c&&(d="webkitHidden",e="webkitvisibilitychange");typeof f.addEventListener!==
b.c&&typeof d!==b.c&&f.addEventListener(e,a,!1);var p=!0;l.addEventListener&&l.addEventListener("DOMContentLoaded",c,!1);f.attachEvent&&f.attachEvent("onreadystatechange",g)},Fa:function(a,m){var g=f.createElement("iframe"),k=f.body;g.setAttribute("name","spr");g.src=a;g.setAttribute("height","1");g.setAttribute("width","1");g.setAttribute("visible","false");g.setAttribute("id","spr-iframe-"+m);g.style.display="none";k||(k=this.h("BODY")[0]);k||(k=this.h("HEAD")[0]);c[b.info](a);k.appendChild(g);
return g},$a:function(a){var b=f.body,g=this.h("BODY")[0],c=this.h("HEAD")[0];b&&b.contains(a)?b.removeChild(a):g&&g.contains(a)?g.removeChild(a):c&&c.contains(a)&&c.removeChild(a)},K:function(a){var m=this,g=f.createElement("script");g.type="text/javascript";g.setAttribute("async",!0);g.setAttribute("name","spr");g.setAttribute("id","spr-script");g.src=a;c[b.info](a);this.ja(function(){setTimeout(function(){m.h("HEAD")[0].appendChild(g)},1)});return g},g:[],ready:/loaded|interactive|complete/.test(f.readyState),
flush:function(){var a=this.g.shift();for(this.ready=!0;a;)a(),a=this.g.shift()},ja:function(a){this.ready?(this.g.push(a),this.flush()):f.documentElement.doScroll?l.self===l.top?function(){if(!f.uniqueID&&f.expando)return this.g.push(a);try{f.documentElement.doScroll("left"),a()}catch(b){setTimeout(arguments.callee,0)}}():this.g.push(a):this.g.push(a)},ia:function(a,b,g){a.addEventListener?a.addEventListener(b,g,!1):a.attachEvent("on"+b,g);return a},Ta:function(a,b,g){a.addEventListener?a.removeEventListener(b,
g,!1):a.detachEvent("on"+b,g);return a},bb:function(){var a=0,a=l.pageYOffset?l.pageYOffset:f.documentElement?f.documentElement.scrollTop:0;return a-this.u},h:function(a){var b=[],g,c=0,d;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(f.getElementById(a.substring(1)));break;case ".":g=f.getElementsByTagName("*");for(d=" "+a.substring(1)+" ";c<g.length;c+=1)a=(" "+g[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(d)&&b.push(g[c]);break;default:b=f.getElementsByTagName(a)}return b}};
return e}(u,q,{});v=function(f,h,e){var c=f.a,b=h.a;e.a={l:function(a,b){var g=[];if(c.r(a))for(var k=0,d;k<a.length;k+=1)d=a[k],/\[\]$/.test(b)?g.push(encodeURIComponent(b)+"="+encodeURIComponent(d)):g.push(this.l(d,b+"["+("object"===typeof d?k:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)g.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(k in a)Object.prototype.hasOwnProperty.call(a,k)&&(b?g.push(this.l(a[k],b+"["+k+"]")):g.push(this.l(a[k],k)));return g.join("&")},
R:function(a){var f={},g=0,k={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");g<a.length;g+=1){var d=a[g].split("="),e=decodeURIComponent(d[0]),p=f,s=0,n=e.split("]["),h=n.length-1;/\[/.test(n[0])&&/\]$/.test(n[h])?(n[h]=n[h].replace(/\]$/,""),n=n.shift().split("[").concat(n),h=n.length-1):h=0;if(2===d.length)if(d=(d=decodeURIComponent(d[1]))&&!isNaN(d)?+d:d===b.c?void 0:void 0!==k[d]?k[d]:d,h)for(;s<=h;s+=1)e=""===n[s]?p.length:n[s],p=p[e]=s<h?p[e]||(n[s+1]&&isNaN(n[s+1])?
{}:[]):d;else c.r(f[e])?f[e].push(d):f[e]=void 0!==f[e]?[f[e],d]:d;else e&&(f[e]=void 0)}return f}};return e}(r,q,{});y=function(l,h){h.a={F:{},Z:function(e){var c=f.cookie||"",b=this.F[e];b||(b=e.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),b=new RegExp("(?:^|;)\\s?"+b+"=(.*?)(?:;|$)","i"),this.F[e]=b);return(e=c.match(b))&&decodeURIComponent(e[1])},H:function(e,c,b){var a="";b&&(a="; expires="+b.toGMTString());f.cookie=e+"="+c+a+"; path=/"},La:function(e){this.H(e,"",new Date(1982,5,13))}};return h}(v,
{});w=function(f,h,e,c){var b=f.a,a=h.a,m=e.a;c.a={callbacks:{},i:function(c,e,d,f,p){f=f||function(){};p||(p="cb");var h="cb"+m.ta(),n=this;d[p]="SPR.API.callbacks."+h;p=m.A();"file://"===p&&(p="http://");d=b.l(d);var l=a.K(p+c+e+"?"+d);n.callbacks[h]=function(a){setTimeout(function(){l.parentNode.removeChild(l)},0);f(a);try{delete n.callbacks[h]}catch(b){n.callbacks[h]=null}}}};return c}(v,x,r,{});z=function(f,h,e,c){var b=f.a,a=h.a,m=e.a;c.a={ha:[{name:a.w,d:a.T,e:a.U,b:a.b,f:!1},{name:a.O,d:a.P,
e:a.Q,b:a.b,f:!0},{name:a.da,d:a.ea,e:a.fa,b:a.b,f:!1},{name:a.la,d:a.ma,e:a.na,b:a.b,f:!1},{name:a.Ca,d:a.Da,e:a.Ea,b:a.b,f:!1},{name:a.pa,d:a.qa,e:a.ra,b:a.i,f:!1}],sa:function(b,c){return b===a.w?{q:a.V+a.W+c+a.X}:{url:c}},Aa:function(c,f){return function(d){d={event:a.ua,url:c.url,cid:c.id,pid:c.pid,sn:c.name,data:d};m.ga(d,f);b.i(a.p,a.S,d)}},M:function(a,c){for(var d=this.ha,f="https://"===m.A()?!0:!1,e=null,h=0;h<d.length;h+=1){var e=d[h],n=m.I(a);n.name=e.name;!a[e.name]||f&&e.f||b.i(e.d,
e.e,this.sa(e.name,n.url),this.Aa(n,c),e.b)}}};return c}(w,q,r,{});(function(q,h,e,c){var b=q.a,a=h.a,m=e.a;c.a={Ga:function(c){var e,d;d=a.I(c);d[b.m]&&(d[b.m]=a.o(d[b.m]));d[b.n]&&(d[b.n]=a.o(d[b.n]));d[b.t]&&(d[b.t]=a.o(d[b.t]));d[b.k]&&typeof d[b.k]!==b.s&&(d[b.k]=d[b.k].toString());d[b.referrer]=c[b.aa]?d[b.referrer]:d[b.referrer]||f.referrer;d[b.D]=d[b.D]||l.location.toString();d[b.uid]?d[b.uid]=d[b.uid]:(e=this.Y())&&(d[b.uid]=e);d[b.url]&&(d[b.url]=this.va(d[b.url]),c[b.url]=d[b.url]);return d},
Y:function(){return m.Z(b.J)},va:function(a){var b=a;if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))b=decodeURIComponent(a);return b}};return c})(q,r,y,{});r=function(f,h,e,c,b,a){var m=f.a,g=h.a,k=e.a,d=c.a,l=b.a;a.a={track:function(a){var b=this;0===a[m.G]&&(a[m.G]=m.Ba);k.i(m.p,m.ba,a,function(c){if(c.error)g[m.error](m.za+c.error.code+" - "+c.error.message);else c.uid&&b.xa(c.uid),l.M(c,a)})},xa:function(a){d.H(m.J,a,new Date(2042,5,13))}};return a}(q,u,w,y,z,{});q=function(f,h,e,c,b,a,
m){var g=e.a,k=c.a,d=b.a,l=a.a;m.a={collect:function(a){try{k.B();var b=d.R(a);l.track(b)}catch(c){g.wa(c)}},API:h.a};return m}(q,w,u,x,v,r,{});l.SPR=q.a})(window,document);
