(function(window,document){'use strict';function p(e,g){var d,f,h,l,n="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" ");this.window=e;this.document=g;this.D=[];this.g=4E3;this.J=1E4;this.window.cedexis=this.window.cedexis||{};this.window.cedexis.callbacks=
this.window.cedexis.callbacks||[];this.X=function(){return d};this.Y=function(){return g};this.Da=function(a,b){for(var c=[],d=0;100>d&&(0<a.length||0<b.length);)0<a.length&&c.push(a.shift()),0<b.length&&c.push(b.shift()),d+=1;return c};this.A=function(){return(new Date).getTime()};this.l=function(a,b){return setTimeout(a,b)};this.h=function(a){clearTimeout(a)};this.Ha=function(){return function(a){var b="",c,d,f,e,g,h,m=0;a=a.replace(/\r\n/g,"\n");d="";for(f=0;f<a.length;f+=1)e=a.charCodeAt(f),128>
e?d+=String.fromCharCode(e):(127<e&&2048>e?d+=String.fromCharCode(e>>6|192):(d+=String.fromCharCode(e>>12|224),d+=String.fromCharCode(e>>6&63|128)),d+=String.fromCharCode(e&63|128));for(a=d;m<a.length;)c=a.charCodeAt(m),m+=1,d=a.charCodeAt(m),m+=1,f=a.charCodeAt(m),m+=1,e=c>>2,c=(c&3)<<4|d>>4,g=(d&15)<<2|f>>6,h=f&63,isNaN(d)?g=h=64:isNaN(f)&&(h=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(c)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(h);return b}}();this.N=function(a){var b=/radar_(tags|impact)_(\w{3,})/i,c;if(("radar_tags_"===a.slice(0,11)||"radar_impact_"===a.slice(0,13))&&(b=b.exec(a))&&3===b.length){try{c=JSON.stringify(e[a])}catch(d){return null}return b[2]+":"+this.Ha(c)}return null};this.o=function(){var a,b,c=[];if(!e.JSON||!e.JSON.stringify)return"1";for(a in e)b=null,
void 0!==e.hasOwnProperty?e.hasOwnProperty(a)&&(b=this.N(a)):void 0!==e[a]&&(b=this.N(a)),b&&c.push(b);return 1>c.length?"0":c.join("@")};this.n=function(a){var b=g.getElementById("cdx");b||(b=g.createElement("div"),b.id="cdx",g.body.appendChild(b));b.appendChild(a)};this.O=function(){return Math.random()};this.$=function(a){return Math.floor(this.O()*(a-0+1))+0};this.G=function(a,b){var c,d=[];b=b||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(c=0;c<a;c+=1)d.push(b.charAt(this.$(b.length-
1)));return d.join("")};this.ya=function(a){return/http:/i.test(a)?"http":/https:/i.test(a)?"https":/\/\//.test(a)?e.location.protocol.replace(":",""):null};this.wa=function(){var a=[],b=d.p.p,c;b.a&&b.a.a?a.push({a:"cold",b:1,f:!!b.d,t:b.a.a.t,u:b.a.a.u}):b.b&&b.b.a&&a.push({a:"cold",b:1,f:!!b.d,t:b.b.a.t,u:b.b.a.u});b.d&&a.push({a:"uni",t:b.d.t,u:b.d.u});b.a?(b.a.b&&a.push({a:"rtt",b:0,f:!!b.d,t:b.a.b.t,u:b.a.b.u}),b.a.c&&a.push({a:"kbps",b:14,f:!!b.d,t:b.a.c.t,u:b.a.c.u})):b.b&&(b.b.b&&a.push({a:"rtt",
b:0,f:!!b.d,t:b.b.b.t,u:b.b.b.u}),b.b.c&&a.push({a:"kbps",b:14,f:!!b.d,t:b.b.c.t,u:b.b.c.u}));b.c&&(c=this.ya(b.c.u))&&("http:"!==this.window.location.protocol&&"https"!==c||a.push({a:"custom",b:2,f:!!b.d,t:b.c.t,u:b.c.u}));d.C=a};this.xa=function(a){var b=[];a.connect&&b.push({a:"cold",b:1,f:!1,t:1,u:a.connect});a.response_time&&b.push({a:"rtt",b:0,f:!1,t:1,u:a.response_time});a.kbps&&b.push({a:"kbps",b:14,f:!1,t:1,u:a.kbps});d.C=b};this.na=function(a){return"uni"===a?[d.requestor.zoneId,d.requestor.customerId,
d.p.z,d.p.c,d.p.i,this.G(8),d.requestor.requestSignature].join("-"):[a,d.requestor.zoneId,d.requestor.customerId,d.p.z,d.p.c,d.p.i,d.requestor.transactionId,d.requestor.requestSignature].join("-")};this.k=function(a){var b="",c;a=a||f.u;!1!==d.a&&(b="?rnd=",-1<a.indexOf("?",0)&&(b="&rnd="),c="uni"===f.a?"uni":f.b,b+=this.na(c));return a+b};this.da=function(a){var b=a.indexOf("//");if(-1<b){var c=a.substring(b+2),d="//";0<b&&(d=a.substring(0,b)+"//");a=c.split("/");a[0]=this.G(63,"abcdefghijklmnopqrstuvwxyz")+
"."+a[0];return d+a.join("/")}return null};this.K=function(a,b){var c=/(\d+)kb\./i.exec(b);return!c||2>c.length?0:Math.floor(8E3*parseInt(c[1],10)/a)};this.F=function(a){var b,c,e;d.c?(b=d.c.a,c=d.c.b,e=d.c.c):(b=d.p.z,c=d.p.c,e=d.p.i);q(this,"sendSuccessReport",{providerOwnerZoneId:b,providerOwnerCustomerId:c,providerId:e,probeId:f.b,resultCode:0,value:a});a=[d.requestor.domains.report,"f1",d.requestor.requestSignature,b,c,e,f.b,0,a,h||"0",this.o()];r(this,"//"+a.join("/"),this.H())};this.H=function(){var a=
this;return function(){a.v()}};this.ha=function(){var a=this;return function(){a.w()}};this.j=function(a){var b,c,e;d&&f&&(d.c?(b=d.c.a,c=d.c.b,e=d.c.c):(b=d.p.z,c=d.p.c,e=d.p.i),q(this,"sendErrorReport",{providerOwnerZoneId:b,providerOwnerCustomerId:c,providerId:e,probeId:f.b,resultCode:a,value:0}),a=[d.requestor.domains.report,"f1",d.requestor.requestSignature,b,c,e,f.b,a,0,h||"0",this.o()],r(this,"//"+a.join("/"),this.ha()))};this.Ca=function(a){return!0===a.f&&null===h};this.L=function(a,b,c){a===
f&&(b=c.call(null,b),0<b&&b<=this.g?(c=b,14===a.b&&(c=this.K(b,a.u)),this.Ca(a)?(l={probe:a,measurement:c},this.v()):this.F(c)):this.j(1))};this.pa=function(a,b,c){var d=this;return function(){a.c||(d.h(a.e),d.L(a,b,c))}};this.I=function(a){var b,c;b=g.createElement("script");b.async=!0;b.src=this.k();f.c=!1;f.d="loading";c=this.A();void 0!==b.onreadystatechange?b.onreadystatechange=function(b,d){var e=!1;return function(){e||"loaded"!==this.readyState&&"complete"!==this.readyState||(e=!0,d!==f||
d.c||(b.h(d.e),b.L(d,c,a)))}}(this,f):b.onload=this.pa(f,c,a);b.onerror=function(a,b){return function(){b===f&&(a.h(b.e),b.c=!0,b.d="error",a.j(4))}}(this,f);f.e=this.l(this.q(),this.g);e.radar.stoppedAt=e.cedexis.radar.stopped_at=null;this.n(b)};this.P=function(){var a=this;return function(b){return a.A()-b}};this.q=function(a){var b=this,c=f;return function(){var d=1;c.c||(a&&a.call(null),c===f&&("loaded"===c.d&&(d=4),c.c=!0,c.d="timeout",b.j(d)))}};this.ca=function(){var a=this;return function(){h=
"2";a.B()}};this.fa=function(){var a=this,b=f,c;return c=function(){a.h(b.e);this.removeEventListener("load",c,!1);b.c||(b.d="loaded")}};this.ga=function(a,b){return function(){a.removeEventListener("load",b,!1)}};this.ea=function(){var a=this,b=f,c;return c=function(g){var k,l;if(b===f){try{k=JSON.parse(g.data)}catch(n){}if(k&&k.source&&"dsa"===k.source&&"l"!==k.s&&"s"===k.s){if(!b.c){l=k.m.responseEnd-k.m.domainLookupStart;g=[d.requestor.domains.report,"f1",d.requestor.requestSignature,k.p.z,k.p.c,
k.p.i,k.m.probe_id];var s=0;a.g<l&&(s=1,l=0);g.push(s);g.push(l);q(a,"sendDsaReport",{providerOwnerZoneId:k.p.z,providerOwnerCustomerId:k.p.c,providerId:k.p.i,probeId:k.m.probe_id,resultCode:s,value:l});g.push(h||"0");g.push(a.o());g.push(k.m.ciphertext);r(a,"//"+g.join("/"),a.H())}e.removeEventListener("message",c,!1)}}}};this.S=function(){var a=g.createElement("iframe"),b=this.k(),c=this.fa();e.addEventListener("message",this.ea(),!1);a.addEventListener("load",c,!1);a.src=b;a.style.display="none";
f.c=!1;f.d="loading";f.e=this.l(this.q(this.ga(a,c)),this.g);this.n(a)};this.U=function(){this.I(function(a){return e.radar.stoppedAt?e.radar.stoppedAt.getTime()-a:e.cedexis.radar.stopped_at?e.cedexis.radar.stopped_at.getTime()-a:null})};this.ia=function(a,b){var c=this;return function(){c.h(a.e);c.F(c.A()-b)}};this.R=function(){var a=this.Y().createElement("iframe"),b=this.A();a.src=this.k();a.style.display="none";f.c=!1;f.d="loading";a.onload=this.ia(f,b);f.e=this.l(this.q(),this.g);this.n(a)};
this.M=function(a){if(this.window.performance&&this.window.performance.getEntriesByType)for(var b=this.window.performance.getEntriesByType("resource"),c=b.length;c--;)if(b[c].name===a)return b[c];return null};this.ja=function(a){var b=this;return function(){b.h(a.e);if(!a.c){var c=b.M(this.src);if(c){var d=14===a.b,c=0<c.requestStart?d?Math.round(c.responseEnd-c.requestStart):Math.round(c.responseStart-c.requestStart):Math.round(c.duration);if(0<c&&c<=b.g){var e=c;d&&(e=b.K(c,a.u));b.F(e)}else b.j(1)}}}};
this.ka=function(a){var b=this;return function(){b.h(a.e);if(!a.c){var c=b.M(this.src);c&&(c=0<c.requestStart?Math.round(c.domainLookupEnd-c.domainLookupStart):Math.round(c.duration),0===c?b.w():c<=b.g?b.F(c):b.j(1))}}};this.Q=function(a){var b=this;return function(){b.h(a.e);a.c=!0;a.d="error";b.j(4)}};this.T=function(){var a;a=new Image;a.onload=this.ja(f);a.onerror=this.Q(f);f.c=!1;f.d="loading";f.e=this.l(this.q(),this.g);a.src=this.k()};this.ua=function(){var a=new Image;a.onload=this.ka(f);
a.onerror=this.Q(f);f.c=!1;f.d="loading";f.e=this.l(this.q(),this.g);a.src=this.k(this.da(f.u))};this.B=function(){var a;l?(a=[d.requestor.domains.report,"f1",d.requestor.requestSignature,d.p.z,d.p.c,d.p.i,l.probe.b,0,l.measurement,h||"0",this.o()],r(this,"//"+a.join("/"),this.H())):this.v()};this.ra=function(a){var b=this;return function(c){f!==a||d.p.i!==c.id||a.c||(a.d="loaded",h=c.node,b.B())}};this.ta=function(){return function(){}};this.sa=function(){return function(){}};this.Ga=function(){var a,
b;a=g.createElement("script");b=this.k();e.cdx=e.cdx||{};e.cdx.s=e.cdx.s||{};e.cdx.s.b=this.ra(f);a.onload=this.ta();a.onerror=this.sa();f.c=!1;f.d="loading";a.type="text/javascript";a.async=!0;a.src=b;this.n(a)};this.qa=function(){var a=this;return function(b){var c,e,g;if(d&&f){try{c=JSON.parse(b.data)}catch(l){}c&&"uni"===c.source&&(b=parseInt(c.p.z,10),e=parseInt(c.p.c,10),g=parseInt(c.p.i,10),g===d.p.i&&e===d.p.c&&b===d.p.z&&c.r.z===d.r.z&&c.r.c===d.r.c&&(a.h(f.e),"l"===c.s?f.d="loaded":-1<"es".indexOf(c.s)&&
("e"===c.s?(f.d="error",h="2"):"s"===c.s&&(h=c.node_id),a.B())))}}};this.W=function(){return"function"===typeof e.postMessage&&"function"===typeof e.addEventListener};this.Fa=function(){var a;this.W()?(f.c=!1,f.d="loading",a=g.createElement("iframe"),a.style.display="none",a.src=this.k(),f.e=this.l(this.ca(),this.g),this.n(a)):(h="1",this.B())};this.Z=function(a){a=a.slice(a.lastIndexOf("/")+1);var b=[/cdx10b/,/rdr12/,/radar\.js/,/r\d+(-\d+kb)?\.js/i,/r\d+\w+(-\d+kb)?\.js/i],c;if("d17.html"===a)return 4;
for(c=0;c<b.length;c+=1)if(b[c].test(a))return 1;return/\.js(\?)?/i.test(a)?5:/\.(ico|png|bmp|gif|jpg|jpeg)(\?)?/i.test(a)?2:/\.(htm(l)?)(\?)?/i.test(a)?3:null};this.Ea=function(){var a;if(f)switch(f.t){case 1:this.U();break;case 2:this.T();break;case 3:this.R();break;case 4:this.S();break;case 5:this.I(this.P());break;case 6:a=this.Z(f.u);switch(a){case 1:this.U();break;case 2:this.T();break;case 3:this.R();break;case 4:this.S();break;case 5:this.I(this.P());break;default:this.j(5)}break;case 7:this.Fa();
break;case 8:this.Ga();break;case 9:this.ua();break;default:this.j(6)}};this.v=function(){d&&(0<d.C.length?(f=d.C.shift(),this.Ea()):(d=null,this.w()))};this.w=function(){d=f=null;0<this.D.length?(l=h=null,d=this.D.shift(),q(this,"measureProvider",{providerOwnerZoneId:d.p.z,providerOwnerCustomerId:d.p.c,providerId:d.p.i}),d.p.source_url?this.za():(this.wa(),this.v())):q(this,"radarSessionFinished")};this.za=function(){var a,b,c;e.XMLHttpRequest&&(b=new e.XMLHttpRequest)&&(a=d.p.source_url,c=Math.ceil(99999999*
this.O()),a=0>a.indexOf("?",0)?a+("?rnd="+c):a+("&rnd="+c),b.open("GET",a,!0),b.onreadystatechange=this.oa(),b.send())};this.oa=function(){var a=this,b=d;return function(){var c;200===this.status&&4===this.readyState&&(c=JSON.parse(this.responseText),b===d&&(a.xa(c),0<d.C.length?a.v():a.w()))}};this.Ba=function(a){var b,c,d;if(b=(this.window.performance||{}).timing){c=[a.domains.report,"n1",0];for(d=0;d<n.length;d+=1){var e=b[n[d]];c.push(void 0===e?0:e)}c.push(a.requestSignature);c.push(this.o());
c.push(this.aa());b.connectEnd<b.connectStart||b.domainLookupEnd<b.domainLookupStart||b.domComplete<b.domLoading||b.fetchStart<b.navigationStart||b.loadEventEnd<b.loadEventStart||b.loadEventEnd<b.navigationStart||b.responseEnd<b.responseStart||b.responseStart<b.requestStart||r(this,"//"+c.join("/"),this.ma(a))}else t(this,a)};this.ma=function(a){var b=this;return function(){t(b,a)}};this.aa=function(){var a=0;e.chrome&&e.chrome.loadTimes?(a=e.chrome.loadTimes(),a=Math.round(1E3*a.firstPaintTime)):
e.performance&&e.performance.timing&&e.performance.timing.va&&(a=Math.round(e.performance.timing.va));return a};this.la=function(a){var b=[],c=[],d;if(this.window.location&&this.window.location.protocol)return d="https:"===this.window.location.protocol?"s":"i",b.push("i1"),b.push(this.V),b.push(18),b.push(4),b.push(a.zoneId),b.push(a.customerId),b.push(a.transactionId.toString(10)),b.push(d),b=b.join("-"),c.push(b+".init."+a.domains.init),c.push("i1"),c.push(Math.floor((new Date).getTime()/1E3).toString(10)),
c.push(a.transactionId.toString(10)),c.push("xml"),c="//"+c.join("/"),c+("?seed="+b)};this.ba=function(a,b){var c;for(c=0;c<a.length;c+=1)a[c].requestor=b;this.D=this.Da(this.D,a);this.X()||this.w()};this.Aa=function(){var a=u;a.runCalledAt=(new Date).getTime();v({a:this.la(a),b:w(this,a),d:this.J})};"function"===typeof e.addEventListener&&e.addEventListener("message",this.qa(),!1)}p.prototype.V="j0";
function q(e,g,d){for(var f=e.window.cedexis.callbacks,h=f.length;h--;)"function"===typeof f[h]&&f[h].call(e.window,g,d)};p.prototype.V="j1";function v(e){var g=new XMLHttpRequest;e.c=e.c||{};if(g)try{g.open("GET",e.a,!0),g.onreadystatechange=function(){return function(){200===this.status&&4===this.readyState&&e.b.call(this)}}(),g.ontimeout=function(){return function(){}}(),g.timeout=e.d,g.send()}catch(d){}}function w(e,g){return function(){var d;this.responseText&&(d=/<requestSignature>([\w@]+)</.exec(this.responseText))&&2===d.length&&(g.requestSignature=d[1],g.sendPLT?e.Ba(g):t(e,g))}}
function r(e,g,d){v({a:g,b:d,d:e.J})}
function t(e,g){var d,f;d=[];var h="";f=g.deviceCaps.call(g);for(var l=Object.keys(f),n=l.length;n--;)d.push(l[n]+"="+f[l[n]]);window.location&&window.location.search&&(f=/radar-location=\w+-\w+-\w+/.exec(window.location.search))&&d.push(f[0]);0<d.length&&(h="?"+d.join("&"));d=[g.domains.code,g.zoneId,g.customerId,"radar",g.buildTimestamp,e.G(20),"providers.json"];d="//"+d.join("/")+h;v({a:d,b:function(a){return function(){var b;try{b=JSON.parse(this.responseText)}catch(c){return}a.ba(b,g)}}(e),c:e.J})}
;window.cedexis.main=window.cedexis.main||new p(window,document);var x,y,u;if(window.cedexis.requestors)for(x=Object.keys(window.cedexis.requestors),y=x.length;y--;)u=window.cedexis.requestors[x[y]],u.runCalledAt||window.cedexis.main.Aa();}(window,document));
