var _yt_www={};(function(m){var window=this;var pa,aaa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.h=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.k=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.fb?a.fb:a.fb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.la=function(a){return"number"==typeof a};m.ma=function(a){return"function"==m.ha(a)};m.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.oa=function(a){return a[pa]||(a[pa]=++aaa)};
var baa=function(a,b,c){return a.call.apply(a.bind,arguments)};var caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.l=function(a,b,c){m.l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return m.l.apply(null,arguments)};
m.qa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.p=function(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};m.ra=function(a){m.ra[" "](a);return a};
m.sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.ua=function(a){return(0,window.encodeURIComponent)(String(a))};
m.va=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};m.wa=function(a,b){return-1!=a.indexOf(b)};
m.xa=function(a,b){for(var c=0,d=(0,m.ya)(String(a)).split("."),e=(0,m.ya)(String(b)).split("."),g=Math.max(d.length,e.length),n=0;0==c&&n<g;n++){var q=d[n]||"",t=e[n]||"",y=RegExp("(\\d*)(\\D*)","g"),G=RegExp("(\\d*)(\\D*)","g");do{var T=y.exec(q)||["","",""],da=G.exec(t)||["","",""];if(0==T[0].length&&0==da[0].length)break;c=za(0==T[1].length?0:(0,window.parseInt)(T[1],10),0==da[1].length?0:(0,window.parseInt)(da[1],10))||za(0==T[2].length,0==da[2].length)||za(T[2],da[2])}while(0==c)}return c};
var za=function(a,b){return a<b?-1:a>b?1:0};m.Aa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ba=function(a){var b=m.ka(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Ca=function(a,b,c){b=m.Da(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Da=function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return g;return-1};m.Ea=function(a,b){return 0<=(0,m.Fa)(a,b)};m.Ga=function(a,b){var c=(0,m.Fa)(a,b),d;(d=0<=c)&&m.Ha(a,c);return d};m.Ha=function(a,b){m.Ia.splice.call(a,b,1)};m.Ja=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Ka=function(a,b,c){return 2>=arguments.length?m.Ia.slice.call(a,b):m.Ia.slice.call(a,b,c)};
m.La=function(){this.zb=this.zb;this.za=this.za};m.Ma=function(a,b){m.Na(a,m.qa(m.Oa,b))};m.Na=function(a,b){a.za||(a.za=[]);a.za.push(m.ca(void 0)?(0,m.l)(b,void 0):b)};m.Oa=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.Pa=function(){m.La.call(this);this.ya=[];this.Nb={}};m.Ra=function(a){Sa(m.Ta,arguments)};m.r=function(a,b){return a in m.Ta?m.Ta[a]:b};m.s=function(a,b){m.ma(a)&&(a=m.Ua(a));return window.setTimeout(a,b)};
m.Va=function(a,b){m.ma(a)&&(a=m.Ua(a));return window.setInterval(a,b)};m.Wa=function(a){window.clearTimeout(a)};m.Xa=function(a){window.clearInterval(a)};m.Ua=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.Ya(b),b;}}:a};m.Ya=function(a,b){if(window&&window.yterr){var c=m.k("yt.www.errors.log");c?c(a,b):(c=m.r("ERRORS")||[],c.push([a,b]),m.Ra("ERRORS",c))}};m.Za=function(a){Sa(m.$a,arguments)};m.ab=function(a){return a in m.$a};
m.bb=function(a,b,c){var d=b||{};if(a=a in m.$a?m.$a[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var Sa=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.u=function(a,b,c){var d=cb();if(d){var e=d.subscribe(a,function(){if(!m.db||m.db!=e){var d=arguments,n=function(){eb[e]&&b.apply(c||window,d)};try{fb[a]?n():m.s(n,0)}catch(q){m.Ya(q)}}},c);eb[e]=!0;gb[a]||(gb[a]=[]);gb[a].push(e);return e}return 0};
m.hb=function(a){var b=cb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.v)(a,function(a){b.unsubscribeByKey(a);delete eb[a]}))};m.w=function(a,b){var c=cb();return c?c.publish.apply(c,arguments):!1};m.ib=function(a,b){fb[a]=!0;var c=cb(),c=c?c.publish.apply(c,arguments):!1;fb[a]=!1;return c};var cb=function(){return m.k("yt.pubsub.instance_")};m.jb=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};
m.x=function(a,b){return a.classList?a.classList.contains(b):m.Ea(m.jb(a),b)};m.z=function(a,b){a.classList?a.classList.add(b):m.x(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.kb=function(a,b){if(a.classList)(0,m.v)(b,function(b){m.z(a,b)});else{var c={};(0,m.v)(m.jb(a),function(a){c[a]=!0});(0,m.v)(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}};
m.A=function(a,b){a.classList?a.classList.remove(b):m.x(a,b)&&(a.className=(0,m.lb)(m.jb(a),function(a){return a!=b}).join(" "))};m.mb=function(a,b,c){c?m.z(a,b):m.A(a,b)};m.nb=function(a,b,c){return Math.min(Math.max(a,b),c)};m.ob=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.pb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.qb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.rb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
m.sb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<tb.length;g++)c=tb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.ub=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return m.ub.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var vb=function(){var a=m.ea.document;return a?a.documentMode:void 0};m.wb=function(a){return xb[a]||(xb[a]=0<=m.xa(yb,a))};
m.zb=function(a){return m.B&&m.Ab>=a};m.C=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Bb=function(a){return m.ka(a)?window.document.getElementById(a):a};m.D=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Cb("*",a,b)[0];return d||null};
m.Cb=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,g=0,n;n=c[g];g++)a==n.nodeName&&(d[e++]=n);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=e=0;n=c[g];g++)a=n.className,"function"==typeof a.split&&m.Ea(a.split(/\s+/),b)&&(d[e++]=n);d.length=e;return d}return c};
m.Db=function(a,b){m.ob(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Eb?a.setAttribute(Eb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Fb=function(a,b,c){return m.Gb(window.document,arguments)};
m.Gb=function(a,b){var c=b[0],d=b[1];if(!kaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.va(d.name),'"');if(d.type){c.push(' type="',m.va(d.type),'"');var e={};m.sb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Db(c,d));2<b.length&&m.Hb(a,c,b,2);return c};
m.Hb=function(a,b,c,d){function e(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!m.ja(g)||m.na(g)&&0<g.nodeType?e(g):(0,m.v)(laa(g)?m.Ja(g):g,e)}};m.Ib=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};var maa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var naa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.Jb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var laa=function(a){if(a&&"number"==typeof a.length){if(m.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.ma(a))return"function"==typeof a.item}return!1};m.Kb=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};
m.Lb=function(a){return function(){return a}};m.Mb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.Nb=function(){};m.Ob=function(a){if(a instanceof m.Nb)return a;if("function"==typeof a.eb)return a.eb(!1);if(m.ja(a)){var b=0,c=new m.Nb;c.next=function(){for(;;){if(b>=a.length)throw m.Pb;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.Qb=function(a,b,c){if(m.ja(a))try{(0,m.v)(a,b,c)}catch(d){if(d!==m.Pb)throw d;}else{a=m.Ob(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.Pb)throw e;}}};m.Rb=function(a){if(m.ja(a))return m.Ja(a);a=m.Ob(a);var b=[];m.Qb(a,function(a){b.push(a)});return b};m.Sb=function(a,b,c,d,e,g,n){var q="";a&&(q+=a+":");c&&(q+="//",b&&(q+=b+"@"),q+=c,d&&(q+=":"+d));e&&(q+=e);g&&(q+="?"+g);n&&(q+="#"+n);return q};
m.Tb=function(a){if(Ub){Ub=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.Vb(c))&&c!=b.hostname)throw Ub=!0,Error();}}return a.match(oaa)};m.Wb=function(a){return a?(0,window.decodeURI)(a):a};m.Vb=function(a){return m.Wb(m.Tb(a)[3]||null)};m.Xb=function(a){a=m.Tb(a);return m.Sb(null,null,null,null,a[5],a[6],a[7])};m.Zb=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.$b=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.$b(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.ua(b))};var ac=function(a,b){for(var c in b)m.$b(c,b[c],a);return a};m.bc=function(a){a=ac([],a);a[0]="";return a.join("")};m.cc=function(a,b){return m.Zb(ac([a],b))};m.dc=function(a,b,c){a&&(c?a&&(a=m.Fb("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.Jb(a).body.appendChild(a)):paa(a,b))};
var paa=function(a,b){var c=new window.Image,d=""+qaa++;ec[d]=c;c.onload=c.onerror=function(){b&&ec[d]&&b();delete ec[d]};c.src=a;c=eval("null")};m.fc=function(a,b,c){gc(c)[a]=b||(0,m.E)();b||hc(a)};var ic=function(a,b){jc("yt_sts",a,void 0);m.fc("_start",b,void 0)};var kc=function(a,b,c){var d=lc(c).span;c=gc(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.E)()-c[b])};var jc=function(a,b,c){lc(c).info[a]=b};
var mc=function(a){var b=gc(a),c=lc(a).span,d=lc(a).info,e=m.k("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))nc(e),oc(a),pc();return window.NaN}e={v:2,s:"youtube",action:m.r("TIMING_ACTION")};if(qc.now&&qc.timing){var g=qc.timing.navigationStart+qc.now(),g=Math.round((0,m.E)()-g);d.yt_hrd=g}var g=m.r("TIMING_INFO")||{},n;for(n in g)d[n]=g[n];n=d.srt;delete d.srt;var q;n||0===n||(q=qc.timing||{},n=Math.max(0,q.responseStart-q.navigationStart),(0,window.isNaN)(n)&&d.pt&&(n=d.pt));if(n||0===n)d.srt=
n;d.h5jse&&(g=window.location.protocol+m.k("ytplayer.config.assets.js"),(g=qc.getEntriesByName?qc.getEntriesByName(g)[0]:null)?d.h5jse=Math.round(d.h5jse-g.responseEnd):delete d.h5jse);g=!1;b.aft||(b.pbr&&b.pbs>b.pbr?(b.aft=b.pbr,g=!0):b.pbs?(b.aft=b.pbs,g=!0):b.vr?(b.aft=b.vr,g=!0):b.aft=b.ol);b.gv&&g&&(c.vl=Math.round(b.aft-b.gv));g=b._start;if(!rc){q||(q=qc.timing||{});var t;e:if(t=q,t.msFirstPaint)t=Math.max(0,t.msFirstPaint);else{var y=window.chrome;if(y&&(y=y.loadTimes,m.ma(y))){var y=y(),G=
1E3*Math.min(y.requestTime||window.Infinity,y.startLoadTime||window.Infinity),G=window.Infinity===G?0:t.navigationStart-G;t=Math.max(0,Math.round(1E3*y.firstPaintTime+G)||0);break e}t=0}0<t&&t>g&&(b.fpt=t);t=q.redirectEnd-q.redirectStart;0<t&&(c.rtime_=t);t=q.domainLookupEnd-q.domainLookupStart;0<t&&(c.dns_=t);t=q.connectEnd-q.connectStart;0<t&&(c.tcp_=t);t=q.connectEnd-q.secureConnectionStart;q.secureConnectionStart&&0<t&&(c.stcp_=t);t=q.responseStart-q.requestStart;0<t&&(c.req_=t);t=q.responseEnd-
q.responseStart;0<t&&(c.rcv_=t);rc=!0}for(var T in d)"_"!=T.charAt(0)&&(e[T]=d[T]);d={};T=[];for(var da in b)"_"!=da.charAt(0)&&(t=Math.max(Math.round(b[da]-g),0),d[da]=t,T.push(da+"."+t));e.rt=T.join(",");b={};da=[];for(var ta in c)"_"!=ta.charAt(0)&&(b[ta]=c[ta],da.push(ta+"."+c[ta]));e.it=da.join(",");(c=m.k("ytdebug.logTiming"))&&c(e,d,b);oc(a);pc();m.r("EXP_DEFER_CSI_PING")?(sc(),tc=e,uc=m.s(sc,0)):nc(e);return d.aft+(n||0)};
var vc=function(a,b){var c=m.r("TIMING_ACTION"),d=gc(b);if(c&&d._start)if(c=m.r("TIMING_WAIT",[]),!a&&c.length){for(var e=!0,g=0,n=c.length;g<n;++g)if(!(c[g]in d)){e=!1;break}if(e)return mc(b)}else if(d.ol||d.aft)return mc(b);return window.NaN};var wc=function(a){if(m.r("TIMING_WAIT"))a=vc(!1,a);else e:{var b=m.r("TIMING_ACTION"),c=!!m.r("TIMING_WFF"),d=gc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=mc(a);break e}a&&mc(a)}a=window.NaN}return a};
var nc=function(a){m.r("EXP_DEFER_CSI_PING")&&(m.Wa(uc),tc=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.dc(b+"?"+c.substring(1))};var sc=function(a){tc&&(a&&(tc.yt_fss=a),nc(tc))};var gc=function(a){return lc(a).tick};var lc=function(a){return m.k("ytcsi."+(a||"")+"data_")||oc(a)};var oc=function(a){var b={tick:{},span:{},info:{}};m.h("ytcsi."+(a||"")+"data_",b,void 0);return b};m.xc=function(){return!!m.k("yt.scheduler.instance")};
m.yc=function(){return m.xc()&&m.x(window.document.body,"exp-js-scheduler-more")};m.zc=function(a,b){void 0===b&&(b=window.NaN);var c=m.k("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.s(a,b||0)};m.Ac=function(a,b){return m.zc(a,b)};m.Bc=function(a){var b=m.k("yt.scheduler.instance.cancelJob");b?b(a):m.Wa(a)};m.Cc=function(a){for(var b=0,c=a.length;b<c;b++)m.Bc(a[b])};
m.Dc=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.F=d?m.Ua(d):null;this.C=e?m.Ua(e):null;this.ya=[];this.k=this.B=0};m.Ec=function(a){m.yc()?(m.Bc(a.B),a.B=m.Ac((0,m.l)(a.init,a))):a.init()};m.Fc=function(a){a.name in Gc&&Hc(a.name);Gc[a.name]={reqs:[],disable:(0,m.l)(a.disable,a)};(0,m.v)(a.deps,function(b){if(!(b in Gc))throw Error("Module "+b+" required by "+a.name);Gc[b].reqs.push(a.name)});a.enable()};
var Hc=function(a){if(a in Gc){var b=Gc[a];(0,m.v)(b.reqs,function(a){Hc(a)});try{b.disable()}catch(c){}delete Gc[a]}};m.Ic=function(a){return a&&"readyState"in a?a.readyState:0};var raa=function(){if(m.r("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!Jc){Kc=m.r("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;Lc=a.prototype.abort;Mc=a.prototype.open;Jc=a.prototype.send;a.prototype.abort=saa;a.prototype.open=taa;a.prototype.send=uaa}};var saa=function(){Nc(!0);Lc.call(this)};
var taa=function(){this.url=arguments[1];Mc.apply(this,arguments)};var uaa=function(){var a=this,b=arguments;if(a.url&&a.url.match(vaa))Jc.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==m.Ic(a)&&Nc(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==m.Ic(a)&&Nc(!0);c&&c.apply(this,arguments)}}Oc.push(function(){Jc.apply(a,b)});Nc()}};
var Nc=function(a){a&&(Pc=!1,m.Wa(Qc));if(!Pc&&Oc.length)if(Kc&&!waa())m.Wa(Rc),Rc=m.s(Nc,100);else{Pc=!0;a=Oc.shift();try{a()}catch(b){Nc(!0)}Qc=m.s(m.qa(Nc,!0),5E3)}};
var waa=function(){var a=Kc,b=m.k("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=m.r("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||.3<b.getVideoLoadedFraction()):!0};m.F=function(a,b){return a?a.dataset?a.dataset[m.Sc(b)]:a.getAttribute("data-"+b):null};
m.Tc=function(a,b){return a?a.dataset?m.Sc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.Sc=function(a){return Uc[a]||(Uc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.Vc=function(a,b){var c=m.Wc(a);window.spf.script.load(a,c,b)};m.Xc=function(a,b){var c=m.Wc(a);window.spf.script.ignore(c,b)};m.Yc=function(a){a&&(m.ka(a)?m.Vc(a):m.ia(a)?(0,m.v)(a,function(a){m.Yc(a)}):m.ob(a,function(a,c){m.Vc(c,function(){m.Yc(a)})}))};
m.Wc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(xaa,""),b=b.replace(yaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var zaa=function(a){a=(0,m.Zc)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.$c=function(a,b){m.dc("/gen_204?"+a,b)};var ad=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.rb(Aaa);this.assets=a.assets||{};this.attrs=a.attrs||m.rb(Baa);this.params=a.params||m.rb(Caa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
m.bd=function(a){a instanceof ad||(a=new ad(a));return a};m.cd=function(a){this.j=a};m.dd=function(a){a=(a.j.cookie||"").split(m.ed);for(var b=[],c=[],d,e,g=0;e=a[g];g++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};m.fd=function(a,b,c){m.gd.set(""+a,b,c,"/","youtube.com")};m.hd=function(a,b){return m.gd.get(""+a,b)};
m.id=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.v)(a.childNodes,function(a){b.appendChild(m.id(a))}):b.innerHTML=a.innerHTML;return b};
m.jd=function(a){if(a=a||window.event){for(var b in a)b in Daa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.va=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.wk=a.pageX;this.xk=a.pageY}};m.kd=function(a,b,c,d){return m.qb(m.ld,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.H=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.kd(a,b,c,d);if(e)return e;var e=++md.count+"",g=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),n;n=g?function(d){d=new m.jd(d);if(!m.Kb(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.jd(b);b.currentTarget=a;return c.call(a,b)};n=m.Ua(n);m.ld[e]=[a,b,c,n,d];a.addEventListener?"mouseenter"==b&&g?a.addEventListener("mouseover",
n,d):"mouseleave"==b&&g?a.addEventListener("mouseout",n,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",n,d):a.addEventListener(b,n,d):a.attachEvent("on"+b,n);return e};m.I=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.v)(a,function(a){if(a in m.ld){var c=m.ld[a],d=c[0],e=c[1],g=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,g,c):d.detachEvent&&d.detachEvent("on"+e,g);delete m.ld[a]}}))};
m.nd=function(a,b){a=!!a;m.h("_lactCookie",a,window);if(null==m.k("_lact",window)){if(a&&b){var c=m.hd("ACTIVITY","-1");m.h("_lact",(0,window.parseInt)(c,10),window)}else m.h("_lact",-1,window),od();m.H(window.document,"keypress",od);m.H(window.document,"mousedown",od);m.H(window.document,"mouseup",od)}};var od=function(){var a=m.k("_lact",window);null==a&&(m.nd(),a=m.k("_lact",window));var b=(0,m.E)();m.h("_lact",b,window);m.k("_lactCookie",window)&&1E3<=b-a&&m.fd("ACTIVITY",""+b)};
m.pd=function(){var a=m.k("_lact",window);return null==a?-1:Math.max((0,m.E)()-a,0)};m.qd=function(a,b,c){var d=m.Vb(a);if(d==m.Vb(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.Xb(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&rd(a,b,c)):rd(a,b)};var rd=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d=31*d+a.charCodeAt(e),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.bc(b):"";m.fd(a,b,c)};
m.sd=function(a,b,c){c=c||"";window.location=m.cc(a,b||{})+c};m.td=function(a,b){var c=window.ytspf||{};b&&m.qd(a,b);c.enabled?window.spf.navigate(a):m.sd(a)};m.ud=function(a,b,c){var d=m.r("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.qd(a,b);if(c)return!1;m.td(a);return!0};var vd=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Eaa=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.l)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!m.wa(m.wd,"Trident")&&!m.wa(m.wd,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.ca(c.next)){c=c.next;var a=c.Lp;c.Lp=null;a()}};return function(a){d.next={Lp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var xd=function(a,b){yd||Faa();zd||(yd(),zd=!0);Ad.push(new Gaa(a,b))};
var Faa=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();yd=function(){a.then(Bd)}}else yd=function(){var a=Bd;!m.ma(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(Cd||(Cd=Eaa()),Cd(a)):m.ea.setImmediate(a)}};var Bd=function(){for(;Ad.length;){var a=Ad;Ad=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.se.call(c.scope)}catch(d){vd(d)}}}zd=!1};var Gaa=function(a,b){this.se=a;this.scope=b};
m.Dd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.Ed=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.Fd=function(a,b){this.k=0;this.G=void 0;this.j=this.B=null;this.C=this.F=!1;try{var c=this;a.call(b,function(a){Gd(c,2,a)},function(a){Gd(c,3,a)})}catch(d){Gd(this,3,d)}};m.Hd=function(a){return new m.Fd(function(b){b(a)})};
var Id=function(a,b){if(0==a.k)if(a.B){var c=a.B;if(c.j){for(var d=0,e=-1,g=0,n;n=c.j[g];g++)if(n=n.fh)if(d++,n==a&&(e=g),0<=e&&1<d)break;0<=e&&(0==c.k&&1==d?Id(c,b):(d=c.j.splice(e,1)[0],Jd(c,d,3,b)))}}else Gd(a,3,b)};var Haa=function(a,b){a.j&&a.j.length||2!=a.k&&3!=a.k||Kd(a);a.j||(a.j=[]);a.j.push(b)};
m.Ld=function(a,b,c,d){var e={fh:null,Kn:null,Ln:null};e.fh=new m.Fd(function(a,n){e.Kn=b?function(c){try{var e=b.call(d,c);a(e)}catch(y){n(y)}}:a;e.Ln=c?function(b){try{var e=c.call(d,b);!m.ca(e)&&b instanceof Md?n(b):a(e)}catch(y){n(y)}}:n});e.fh.B=a;Haa(a,e);return e.fh};
var Gd=function(a,b,c){if(0==a.k){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.Ed(c)){a.k=1;c.then(a.H,a.J,a);return}if(m.na(c))try{var d=c.then;if(m.ma(d)){Iaa(a,c,d);return}}catch(e){b=3,c=e}}a.G=c;a.k=b;Kd(a);3!=b||c instanceof Md||Jaa(a,c)}};var Iaa=function(a,b,c){function d(b){g||(g=!0,a.J(b))}function e(b){g||(g=!0,a.H(b))}a.k=1;var g=!1;try{c.call(b,e,d)}catch(n){d(n)}};var Kd=function(a){a.F||(a.F=!0,xd(a.K,a))};
var Jd=function(a,b,c,d){if(2==c)b.Kn(d);else{for(;a&&a.C;a=a.B)a.C=!1;b.Ln(d)}};var Jaa=function(a,b){a.C=!0;xd(function(){a.C&&Kaa.call(null,b)})};var Md=function(a){m.sa.call(this,a)};var Nd=function(a){this.B=a;this.k=null;var b=this;a.then(function(a){b.k=a})};
var Od=function(a,b){var c=b||{},d=Laa().then(function(b){return b(a,{apiKey:c.mf||c.apiKey,environment:c.nf||c.environment,helpCenterPath:c.AB||c.helpCenterPath,locale:c.locale||c.locale,productData:c.BB||c.productData,receiverUri:c.CB||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new Nd(d)};
var Laa=function(){if(Pd)return Pd;var a=m.k("help.service.Lazy.create");return a?Pd=m.Hd(a):Pd=(new m.Fd(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.k("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var Qd=function(a,b,c){a.B.then(function(a){a[b].apply(a,c)})};var Rd=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Sd=function(a){return(a=a.exec(m.wd))?a[1]:""};
var Td=function(){this.B=this.k=this.j=0;this.C="";var a=m.k("window.navigator.plugins"),b=m.k("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,g=c.length;e<g;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.j=b[0];this.k=b[1];this.B=b[2];if(0>=this.j){var n,q,t,y;if(m.Ud)try{n=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(G){n=null}else t=window.document.body,y=window.document.createElement("object"),y.setAttribute("type","application/x-shockwave-flash"),n=t.appendChild(y);if(n&&"GetVariable"in n)try{q=n.GetVariable("$version")}catch(T){q=""}t&&y&&t.removeChild(y);(n=q||"")?(n=n.split(" ")[1].split(","),
n=[(0,window.parseInt)(n[0],10)||0,(0,window.parseInt)(n[1],10)||0,(0,window.parseInt)(n[2],10)||0]):n=[0,0,0];this.j=n[0];this.k=n[1];this.B=n[2]}};var Vd=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.B>=b[2]};
var Wd=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.B?!1:9<=a.j};var Maa=function(a){return m.Xd?!Vd(a,11,2):m.Yd?!Vd(a,11,3):!Wd(a)};m.Zd=function(){return m.$d?"Webkit":m.ae?"Moz":m.B?"ms":m.be?"O":null};m.ce=function(){return m.$d?"-webkit":m.ae?"-moz":m.B?"-ms":m.be?"-o":null};m.de=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.ee=function(a,b){return a&&b?b instanceof m.de?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.fe=function(a,b){var c=m.Aa(b);if(void 0===a.style[c]){var d=m.Zd()+m.Ba(c);if(void 0!==a.style[d])return d}return c};m.ge=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.he=function(a,b){a.style.display=b?"":"none"};m.ie=function(){this.j="";this.k=je};
var ke=function(a){return a instanceof m.ie&&a.constructor===m.ie&&a.k===je?a.j:"type_error:Const"};var le=function(){this.j="";this.k=me};var ne=function(a){var b=new le;b.j=a;return b};var oe=function(){this.j=pe};var qe=function(){this.j="";this.B=re;this.k=null};m.se=function(a){return a instanceof qe&&a.constructor===qe&&a.B===re?a.j:"type_error:SafeHtml"};
m.te=function(a,b){if(!ue.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in Naa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var e in b){if(!ue.test(e))throw Error('Invalid attribute name "'+e+'".');var g=b[e];if(null!=g){if(g instanceof m.ie)g=ke(g);else if("style"==e.toLowerCase()){if(!m.na(g))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof g+" given: "+g);if(!(g instanceof le)){var n=
"",q=void 0;for(q in g){if(!/^[-_a-zA-Z0-9]+$/.test(q))throw Error("Name allows only [-_a-zA-Z0-9], got: "+q);var t=g[q];null!=t&&(t instanceof m.ie?t=ke(t):Oaa.test(t)||(t="zClosurez"),n+=q+":"+t+";")}g=n?ne(n):Paa}g=g instanceof le&&g.constructor===le&&g.k===me?g.j:"type_error:SafeStyle"}else{if(/^on/i.test(e))throw Error('Attribute "'+e+'" requires goog.string.Const value, "'+g+'" given.');if(g instanceof oe)g=g instanceof oe&&g.constructor===oe&&g.j===pe?"":"type_error:SafeUrl";else if(e.toLowerCase()in
Qaa)throw Error('Attribute "'+e+'" requires goog.string.Const or goog.html.SafeUrl value, "'+g+'" given.');}d+=" "+e+'="'+m.va(String(g))+'"'}}e=void 0;m.ca(e)?m.ia(e)||(e=[e]):e=[];!0===Raa[a.toLowerCase()]?d+=">":(c=Saa(e),d+=">"+m.se(c)+"</"+a+">",c=c.sh());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return ve(d,c)};
var Saa=function(a){function b(a){if(m.ia(a))(0,m.v)(a,b);else{if(!(a instanceof qe)){var g=null;a.fp&&(g=a.sh());a=ve(m.va(a.oi?a.ni():String(a)),g)}d+=m.se(a);a=a.sh();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.v)(arguments,b);return ve(d,c)};var ve=function(a,b){var c=new qe;c.j=a;c.k=b;return c};m.we=function(a,b){(a=m.C(a))&&a.style&&(m.he(a,b),m.mb(a,"hid",!b))};m.J=function(a){(0,m.v)(arguments,function(a){m.we(a,!0)})};
var xe=function(a){var b=m.r("FEEDBACK_LOCALE_LANGUAGE"),c=m.ye,d=m.r("FEEDBACK_LOCALE_EXTRAS",{});a?m.sb(c,a):m.sb(c,d);try{var e,g=m.k("yt.player.getPlayerByElement");(e=g?g("player-api"):null)&&e.pauseVideo&&e.pauseVideo();var n=Td.getInstance();c.flashVersion=n.getVersion().join(".");e&&(c.playback_id=e.getVideoData().cpn)}catch(q){}return{helpCenterPath:"/youtube",locale:b,productData:c}};
var ze=function(){var a=m.r("SESSION_INDEX"),b=m.r("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.Ae=function(a,b){try{var c=(a||"59")+"",d=xe(b),e=ze();Od(c,d).C(e);return!1}catch(g){return!0}};
m.Be=function(a,b,c,d,e,g,n,q){b=(b||"59")+"";d=xe(d);a={context:c,anchor:a,enableSendFeedback:g?!1:!0,trackingParam:n,defaultHelpArticleId:q};m.sb(a,ze());try{var t=Od(b,d);if(e&&!Ce)try{t.j(a),Ce=!0}catch(y){}t.F(a);return!1}catch(G){return!0}};m.De=function(a,b,c,d){return m.Be(void 0,d,b,c,void 0,void 0,void 0,a)};m.Ee=function(){var a=m.hd("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Fe[d]=c.toString())}};
var Ge=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var He=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Ie=function(a){a=void 0!==m.Fe[a]?m.Fe[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Je=function(a,b){return!!((m.Ie("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Ke=function(a,b,c){if(b){a=m.ka(a)?m.Bb(a):a;c=m.bd(c);var d=m.rb(c.attrs);d.tabindex=0;var e=m.rb(c.params);e.flashvars=m.bc(c.args);if(m.Ud){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var g in d)b.setAttribute(g,d[g]);for(g in e)d=window.document.createElement("param"),d.setAttribute("name",g),d.setAttribute("value",e[g]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(g in d)b.setAttribute(g,d[g]);for(g in e)b.setAttribute(g,e[g])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Le=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Me();Vd(c,b.minVersion)?(c=Ne(b,c),Ke(a,c,b)):Oe(a,b,c)};
var Pe=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.bd(a);var d=!!b,e=m.C(a.attrs.id),g=e?e.parentNode:null;if(e&&g){if(window!=window.top){var n=null;if(window.document.referrer){var q=window.document.referrer.substring(0,128);zaa(q)||(n=q)}else n="unknown";n&&(d=!0,a.args.framer=n)}n=Me();if(Vd(n,a.minVersion)){var q=Ne(a,n),t="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(t=e.getAttribute("src")||e.movie);(t!=q||d)&&Ke(g,q,a);Maa(n)&&Taa()}else Oe(g,a,n);c&&c()}else m.s(function(){Pe(a,
b,c)},50)}};var Oe=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.bb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Ne=function(a,b){var c;(c=Wd(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Vd(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Me=function(){var a=Td.getInstance(),b=m.Ee.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Taa=function(){var a=m.C("flash10-promo-div"),b=m.Je(m.Ee.getInstance(),107);a&&!b&&m.J(a)};m.Qe=function(a,b){var c=a.match(Uaa);window.spf.style.load(a,c?c[1]:"",b)};
var Vaa=function(){if(2.2==Re)return!0;var a;a=m.k("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.h("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Waa=function(){};m.Te=function(){};m.Ue=function(a){this.j=a};m.Ve=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};
var We=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};m.Xe=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.Ye=function(a){return m.Ze(new m.$e(void 0),a)};
m.$e=function(a){this.j=a};m.Ze=function(a,b){var c=[];af(a,b,c);return c.join("")};
var af=function(a,b,c){switch(typeof b){case "string":bf(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],af(a,a.j?a.j.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&
(c.push(d),bf(g,c),c.push(":"),af(a,a.j?a.j.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var bf=function(a,b){b.push('"',a.replace(Xaa,function(a){if(a in cf)return cf[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return cf[a]=e+b.toString(16)}),'"')};m.df=function(a){this.j=a};var ef=function(a){this.j=a};var ff=function(a){this.data=a};var gf=function(a){return!m.ca(a)||a instanceof ff?a:new ff(a)};
var hf=function(a){this.j=a};m.jf=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.E)()||!!b&&b>(0,m.E)()};m.kf=function(a){this.j=a};m.lf=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.E)()+1E3*d:0;if((d=d?m.mf:m.nf)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.of=function(a){if(!m.nf&&!m.mf||!window.JSON)return null;var b;try{b=m.nf.get(a)}catch(c){}if(!m.ka(b))try{b=m.mf.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var pf=function(){var a={volume:100,muted:!1},b=m.of("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.nb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var qf=function(a,b){m.La.call(this);this.B=this.vf=a;this.K=b;this.G=!1;this.j={};this.T=this.J=null;this.R=new m.Pa;m.Ma(this,this.R);this.C={};this.F=this.V=this.k=this.ka=this.da=null;this.P=!1;this.ea=this.H=null;this.X={};this.Ha=["onReady"];this.Ba=null;this.Ca=0;this.na=!!m.r("PLAYER_PERSISTENCE_REFACTOR");rf(this);this.ve("onVolumeChange",(0,m.l)(this.Xp,this));this.ve("onError",(0,m.l)(this.Wp,this));this.ve("onTabOrderChange",(0,m.l)(this.Vp,this));this.ve("WATCH_LATER_VIDEO_ADDED",(0,m.l)(this.Yp,
this));this.ve("WATCH_LATER_VIDEO_REMOVED",(0,m.l)(this.Zp,this))};
var sf=function(a,b){a.ka=b;a.da=b.clone();a.k=a.da.attrs.id||a.k;"video-player"==a.k&&(a.k=a.K,a.da.attrs.id=a.K);a.B.id==a.k&&(a.k=a.k+"-player",a.da.attrs.id=a.k);var c=a.da.args,d;if(!(d=a.da.args.eurl)){d=window.document.location.toString();var e=!!d&&-1!=d.search(Yaa),g=-1!=d.indexOf("/embed/");e!=g&&m.Ya(Error(d+" behavior is not consistent"));d=g?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d}c.eurl=d;a.da.args.enablejsapi="1";a.da.args.playerapiid=a.K;a.V||
(a.V=tf(a,a.da.args.jsapicallback||"onYouTubePlayerReady"));a.da.args.jsapicallback=null;if(c=a.da.attrs.width)a.B.style.width=m.ge(Number(c)||c,!0);if(c=a.da.attrs.height)a.B.style.height=m.ge(Number(c)||c,!0);a.B.style.overflow="hidden"};var uf=function(a){a.da.loaded||(a.da.loaded=!0,"0"!=a.da.args.autoplay?a.j.loadVideoByPlayerVars(a.da.args):a.j.cueVideoByPlayerVars(a.da.args))};var vf=function(a){if(!m.ca(a.da.disable.flash)){var b=a.da.disable,c;c=Vd(Me(),a.da.minVersion);b.flash=!c}return!a.da.disable.flash};
var wf=function(a){var b=xf(a);b&&b.stopVideo&&b.stopVideo();if(vf(a)){var c=a.da;b&&b.getUpdatedConfigurationData&&(b=m.bd(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";sf(a,c);yf(a,"flash")}};
var yf=function(a,b){if(!a.ha()){if(!b){var c;if(!(c=!a.da.html5&&vf(a))){if(!m.ca(a.da.disable.html5)){if(c=Vaa())c=zf(a)||a.da.assets.js;a.da.disable.html5=!c;c||(a.da.args.html5_unavailable="1")}c=!!a.da.disable.html5}b=c?vf(a)?"flash":"unsupported":"html5"}("flash"==b?a.oy:"html5"==b?a.py:a.qy).call(a)}};var zf=function(a){var b=!0;if(a.na){var c=xf(a);c&&a.da&&(a=a.da,b=m.F(c,"version")==a.assets.js)}return b&&!!m.k("yt.player.Application.create")};
var xf=function(a){var b=m.C(a.k);!b&&a.B&&a.B.querySelector&&(b=a.B.querySelector("#"+a.k));return b};var Af=function(a,b,c){var d=b[c];return function(){try{return a.Ba=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&(e.message+=" ("+c+")",a.Ba=e,m.Ya(e,"WARNING"))}}};
var rf=function(a){a.G=!1;if(a.T)for(var b in a.C)a.T(b,a.C[b]);a.J=null;a.T=null;for(var c in a.j)a.j[c]=null;a.j.addEventListener=(0,m.l)(a.ve,a);a.j.removeEventListener=(0,m.l)(a.Xt,a);a.j.destroy=(0,m.l)(a.dispose,a);a.j.getLastError=(0,m.l)(a.Vt,a);a.j.getPlayerType=(0,m.l)(a.Wt,a);a.j.getCurrentVideoConfig=(0,m.l)(a.Ut,a);a.j.loadNewVideoConfig=(0,m.l)(a.sj,a);a.j.isReady=(0,m.l)(a.Yt,a)};
var tf=function(a,b){var c=b;if("string"==typeof b){if(a.X[b])return a.X[b];c=function(){var a=m.k(b);a&&a.apply(m.ea,arguments)};a.X[b]=c}return c?c:null};var Zaa=function(a,b){var c="ytPlayer"+b+a.K;a.C[b]=c;m.ea[c]=function(c){m.s(function(){a.ha()||a.R.publish(b,c)},0)};return c};var Bf=function(a){return(a=xf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Cf=function(a){m.fc("dcp");a.cancel();rf(a);a.F=null;a.da&&(a.da.loaded=!1);var b=xf(a);"html5"==Bf(a)?a.ea=b:b&&b.destroy&&b.destroy();m.Ib(a.vf)};m.Df=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);var c=Ef+"_"+m.oa(a),d=Ff[c];if(d)return d.sj(b),d.j;d=new qf(a,c);Ff[c]=d;m.w("player-added",d.j);m.Na(d,m.qa($aa,d));m.s(function(){d.sj(b)},0);return d.j};var Gf=function(){for(var a in Ff){var b=Ff[a];b&&b.cancel()}};m.Hf=function(a){if(a=m.C(a))a=Ef+"_"+m.oa(a),(a=Ff[a])&&a.dispose()};
var $aa=function(a){Ff[a.getId()]=null};m.If=function(a){a=m.C(a);if(!a)return null;var b=Ef+"_"+m.oa(a),c=Ff[b];c||(c=new qf(a,b),Ff[b]=c);return c.j};
var aba=function(){m.h("yt.player.exports.navigate",m.ud,void 0);m.h("yt.player.embed",m.Df,void 0);m.h("yt.player.destroy",m.Hf,void 0);m.h("yt.player.cancelAll",Gf,void 0);m.h("yt.player.getPlayerByElement",m.If,void 0);m.h("yt.player.exports.feedbackStart",m.Ae,void 0);m.h("yt.player.exports.feedbackShowArticle",m.De,void 0);m.h("yt.util.activity.init",m.nd,void 0);m.h("yt.util.activity.getTimeSinceActive",m.pd,void 0);m.h("yt.util.activity.setTimestamp",od,void 0);Jf=Jf||!!m.r("PLAYER_WATCH_WHILE")||
!!m.hd("watch_while");var a=m.k("ytplayer.config");Kf(a);m.k("ytspf.enabled")&&(Lf=m.Va(Mf,5E3),(a=m.Nf())?(a.addEventListener("onReady",Mf),a.addEventListener("onStateChange",Mf),Jf&&(a.addEventListener("onReady",Of),a.addEventListener("onStateChange",Of))):Pf("unable to init PP monitor"))};
var Kf=function(a){Gf();if(a=a||null){var b=m.Nf(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(Qf="",m.Df("player-api",a)):b.playVideo();a=m.bd(a);a.loaded=!0}Of();Mf();m.h("ytplayer.config",a,void 0)};m.Nf=function(){var a=m.k("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Mf=function(){var a=m.C("player"),b=m.Nf();if(a&&b){var a=a&&m.x(a,"off-screen"),b=1==(b&&b.isReady()?b.getPlayerState():void 0),c="watch"==m.r("PAGE_NAME");Rf&&!Jf&&b&&Pf("minimized PP playing");a&&c?Pf("PP off-screen on watch"):Jf||a||c||Pf("PP !off-screen off watch")}};var Of=function(){if(Jf){var a="watch"==m.r("PAGE_NAME"),b=m.Nf();1==(b&&b.isReady()?b.getPlayerState():void 0)?Sf(!0):a&&Sf(!1);Tf()}};
var Tf=function(){var a=m.C("player"),b=m.C("player-mole-container");Rf=!a||m.x(a,"off-screen")||!b||m.x(b,"watch-mole");(a=m.Nf())&&a.isReady()&&a.setMinimized(Rf)};var Pf=function(a){var b=m.r("PAGE_NAME");b&&(b=[b,Qf,m.k("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.h("yt.www.persistentplayer.issue",a,void 0),m.Ya(Error(a),"WARNING"))};var Sf=function(a){m.mb(m.C("player-mole-container"),"video-mole",a);Tf()};
var Uf=function(){m.fc("ol");Vf("init");var a=m.r("PAGE_NAME");a&&Vf("init-"+a);wc()};var Vf=function(a){m.xc()?Wf.push(m.zc(m.qa(m.ib,a),0)):m.w(a)};var Xf=function(){m.Cc(Wf);Wf.length=0;var a=m.r("PAGE_NAME");a&&m.ib("dispose-"+a);m.ib("dispose")};var bba=function(){Uf()};var cba=function(){m.r("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.r("EXP_DEFER_CSI_PING")&&sc("u");Xf()};
var dba=function(a,b,c,d,e){for(var g=window.document.getElementsByTagName("script"),n=!1,q=0,t=g.length;q<t;q++)if(0<g[q].src.indexOf("/debug-")){n=!0;break}n&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.Ya(e))};var Yf=function(){Zf=1;$f=0;m.r("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.r("EXP_DEFER_CSI_PING")&&sc("n");oc(void 0);pc();m.r("CSI_TRACK_ON_BEGIN")&&ic("nb");hc("mark_navigation_requested");ag(eba);m.ib("navigate")};
var bg=function(a){a=a.detail.part||a.detail.partial;m.fc("nc"+$f);++$f;var b=1==Zf;Zf=2;b?(ag(fba),cg()):ag(gba);(a=a.data&&a.data.swfcfg)&&dg(a)};var eg=function(){};var fg=function(a){a=a.detail.response;var b=1==Zf;Zf=3;b&&(ag(hba),cg());(a=a.data&&a.data.swfcfg)&&dg(a)};
var gg=function(a){m.fc("nd");a=a.detail.response.timing;var b=window._spf_state;jc("yt_nav",b&&b["nav-counter"]||0);ic("ne",a.responseStart);jc("srt",Math.max(0,a.responseStart-a.navigationStart));jc("yt_lt",a.spfCached?"hot":"warm");jc("yt_pft",+!!a.spfPrefetched);kc("req",a.responseStart-a.fetchStart);ag(hg);window.document.getElementById("content").style.height="";Uf();Zf=0};var ig=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.Ya(a)};
var jg=function(a){a=m.bc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.$c(a)};var iba=function(){jba()};var kba=function(){};
var cg=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Xf();for(var b in m.Ta)delete m.Ta[b];m.h("ytplayer.config",null,void 0);if(!Jf)if((a=m.Nf())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Qf=a,(a=m.C("movie_player"))&&a.stopVideo?(a.stopVideo(),Qf="recovered"):Qf="missing2"}else Qf="missing";Mf()};var dg=function(a){"cfg"in gc(void 0)||m.fc("cfg");Kf(a)};
var ag=function(a){function b(){var b=a[0],e=a[1],g=a[2];c.className="";var n=c.style;n.transitionDuration=n.webkitTransitionDuration=b+"ms";n.width=e+"%";m.Wa(kg);kg=m.s(function(){c.className=g},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.yc()?(m.Bc(lg),lg=m.zc(b,0)):(m.Wa(kg),kg=m.s(b,0))};
var jba=function(){var a=hg[0]+50;m.Wa(kg);kg=m.s(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
var lba=function(){"watch"!=m.r("PAGE_NAME")&&m.h("yt.www.skywatch.lastBrowsePage",window.location.href,void 0);if(m.r("SKYWATCH_ENABLED")){var a=m.C("skywatch-close-button");a||(a=window.document.createElement("button"),m.kb(a,["yt-uix-button","yt-uix-button-default"]),a.id="skywatch-minimize-button",a.innerHTML="\u21f2",m.C("player-mole-container").appendChild(a));mg.push(m.H(a,"click",mba))}};var mba=function(){m.td(m.k("yt.www.skywatch.lastBrowsePage")||"/")};
var ng=function(){m.Dc.call(this,"www/base");this.j=0};var og=function(a){(a=a.detail.name)&&Hc(a)};m.ba=[];m.pg=m.pg||{};m.ea=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;m.E=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.l.apply(null,c)}return(0,m.l)(this,a)};m.ra[" "]=m.fa;m.p(m.sa,Error);m.sa.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;m.ya=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;m.nba=2147483648*Math.random()|0;m.Ia=Array.prototype;m.Fa=m.Ia.indexOf?function(a,b,c){return m.Ia.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.oba=m.Ia.lastIndexOf?function(a,b,c){return m.Ia.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.v=m.Ia.forEach?function(a,b,c){m.Ia.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
m.lb=m.Ia.filter?function(a,b,c){return m.Ia.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,n=m.ka(a)?a.split(""):a,q=0;q<d;q++)if(q in n){var t=n[q];b.call(c,t,q,a)&&(e[g++]=t)}return e};m.qg=m.Ia.map?function(a,b,c){return m.Ia.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=m.ka(a)?a.split(""):a,n=0;n<d;n++)n in g&&(e[n]=b.call(c,g[n],n,a));return e};
m.rg=m.Ia.reduce?function(a,b,c,d){d&&(b=(0,m.l)(b,d));return m.Ia.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.v)(a,function(c,n){e=b.call(d,e,c,n,a)});return e};m.sg=m.Ia.some?function(a,b,c){return m.Ia.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&b.call(c,e[g],g,a))return!0;return!1};
m.tg=m.Ia.every?function(a,b,c){return m.Ia.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in e&&!b.call(c,e[g],g,a))return!1;return!0};m.La.prototype.zb=!1;m.La.prototype.ha=function(){return this.zb};m.La.prototype.dispose=function(){this.zb||(this.zb=!0,this.N())};m.La.prototype.N=function(){if(this.za)for(;this.za.length;)this.za.shift()()};m.p(m.Pa,m.La);m.f=m.Pa.prototype;m.f.Ro=1;m.f.Kh=0;m.f.subscribe=function(a,b,c){var d=this.Nb[a];d||(d=this.Nb[a]=[]);var e=this.Ro;this.ya[e]=a;this.ya[e+1]=b;this.ya[e+2]=c;this.Ro=e+3;d.push(e);return e};m.f.unsubscribe=function(a,b,c){if(a=this.Nb[a]){var d=this.ya;if(a=m.Ca(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Jb(a)}return!1};
m.f.Jb=function(a){if(0!=this.Kh)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.ya[a];if(b){var c=this.Nb[b];c&&m.Ga(c,a);delete this.ya[a];delete this.ya[a+1];delete this.ya[a+2]}return!!b};m.f.publish=function(a,b){var c=this.Nb[a];if(c){this.Kh++;for(var d=m.Ka(arguments,1),e=0,g=c.length;e<g;e++){var n=c[e];this.ya[n+1].apply(this.ya[n+2],d)}this.Kh--;if(this.j&&0==this.Kh)for(;c=this.j.pop();)this.Jb(c);return 0!=e}return!1};
m.f.clear=function(a){if(a){var b=this.Nb[a];b&&((0,m.v)(b,this.Jb,this),delete this.Nb[a])}else this.ya.length=0,this.Nb={}};m.f.pa=m.aa(3);m.f.N=function(){m.Pa.L.N.call(this);delete this.ya;delete this.Nb;delete this.j};m.Ta=window.yt&&window.yt.config_||{};m.h("yt.config_",m.Ta,void 0);m.h("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.$a=window.yt&&window.yt.msgs_||{};m.h("yt.msgs_",m.$a,void 0);m.Ud="Microsoft Internet Explorer"==window.navigator.appName;var pba=m.k("yt.pubsub.instance_")||new m.Pa;m.Pa.prototype.subscribe=m.Pa.prototype.subscribe;m.Pa.prototype.unsubscribeByKey=m.Pa.prototype.Jb;m.Pa.prototype.publish=m.Pa.prototype.publish;m.Pa.prototype.clear=m.Pa.prototype.clear;m.h("yt.pubsub.instance_",pba,void 0);var eb=m.k("yt.pubsub.subscribedKeys_")||{};m.h("yt.pubsub.subscribedKeys_",eb,void 0);var gb=m.k("yt.pubsub.topicToKeys_")||{};m.h("yt.pubsub.topicToKeys_",gb,void 0);var fb=m.k("yt.pubsub.isSynchronous_")||{};
m.h("yt.pubsub.isSynchronous_",fb,void 0);m.db=m.k("yt.pubsub.skipSubId_")||null;m.h("yt.pubsub.skipSubId_",m.db,void 0);var tb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");e:{var ug=m.ea.navigator;if(ug){var vg=ug.userAgent;if(vg){m.wd=vg;break e}}m.wd=""};var Dg,yb,xb,Eg;m.be=m.wa(m.wd,"Opera")||m.wa(m.wd,"OPR");m.B=m.wa(m.wd,"Trident")||m.wa(m.wd,"MSIE");m.ae=m.wa(m.wd,"Gecko")&&!m.wa(m.wd.toLowerCase(),"webkit")&&!(m.wa(m.wd,"Trident")||m.wa(m.wd,"MSIE"));m.$d=m.wa(m.wd.toLowerCase(),"webkit");m.$d&&m.wa(m.wd,"Mobile");var Ag=m.ea.navigator||null,Bg=Ag&&Ag.platform||"";m.Yd=m.wa(Bg,"Mac");m.Xd=m.wa(Bg,"Win");m.wg=m.wa(Bg,"Linux");var Cg=m.wd;m.xg=!!Cg&&m.wa(Cg,"Android");m.yg=!!Cg&&m.wa(Cg,"iPhone");m.zg=!!Cg&&m.wa(Cg,"iPad");
Dg=m.ea.navigator||null;m.qba=!!Dg&&m.wa(Dg.appVersion||"","X11");yb=function(){var a="",b;if(m.be&&m.ea.opera)return a=m.ea.opera.version,m.ma(a)?a():a;m.ae?b=/rv\:([^\);]+)(\)|;)/:m.B?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.$d&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.wd))?a[1]:"");return m.B&&(b=vb(),b>(0,window.parseFloat)(a))?String(b):a}();xb={};Eg=m.ea.document;m.Ab=Eg&&m.B?vb()||("CSS1Compat"==Eg.compatMode?(0,window.parseInt)(yb,10):5):void 0;var kaa;kaa=!m.B||m.zb(9);m.rba=!m.ae&&!m.B||m.B&&m.zb(9)||m.ae&&m.wb("1.9.1");m.Gg=m.B&&!m.wb("9");m.sba=m.B||m.be||m.$d;m.tba=m.B&&!m.zb(9);var Eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Hg=m.Lb(!1);m.Ig=m.Lb(!0);m.Pb="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.Nb.prototype.next=function(){throw m.Pb;};m.Nb.prototype.eb=function(){return this};var oaa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ub=m.$d;var Yaa=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/embed\//;var ec={},qaa=0,uba=m.k("yt.net.ping.workerUrl_")||null;m.h("yt.net.ping.workerUrl_",uba,void 0);var rc,tc,uc;var qc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},pc=(0,m.l)(qc.clearResourceTimings||qc.webkitClearResourceTimings||qc.mozClearResourceTimings||qc.msClearResourceTimings||qc.oClearResourceTimings||m.fa,qc),hc=qc.mark?function(a){qc.mark(a)}:m.fa;m.f=m.Dc.prototype;m.f.Uw=function(){2==this.k||this.init()};m.f.enable=function(){this.k=1;(0,m.v)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.Uw,this),this.subscribe("dispose-"+a,this.dispose,this),m.r("PAGE_NAME")==a&&m.Ec(this))},this)};m.f.init=function(){m.yc()&&m.Bc(this.B);this.k=2;this.F&&this.F()};m.f.dispose=function(){this.k=3;m.Bc(this.B);this.C&&this.C()};m.f.disable=function(){this.k=4;this.dispose();this.clear()};
m.f.subscribe=function(a,b,c){a=m.u(a,b,c);this.ya.push(a);return a};m.f.clear=function(){m.hb(this.ya);this.ya=[]};var Gc=m.k("yt.modules.registry_")||{};m.h("yt.modules.registry_",Gc,void 0);m.Jg=null;"undefined"!=typeof window.XMLHttpRequest?m.Jg=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.Jg=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var Jc,Kc,Lc,Mc,Pc,Rc=0,Qc=0,Oc=[],vaa=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var Uc={};var xaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,yaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.Zc=m.Vb;var Aaa={enablejsapi:1},Baa={},Caa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ad.prototype.clone=function(){var a=new ad,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.rb(c):a[b]=c}return a};m.ed=/\s*;\s*/;m.f=m.cd.prototype;m.f.isEnabled=m.aa(4);m.f.set=function(a,b,c,d,e,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.E)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+g};
m.f.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.ed),e=0,g;g=d[e];e++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};m.f.remove=function(a,b,c){var d=m.ca(this.get(a));this.set(a,"",0,b,c);return d};m.f.Ta=m.aa(5);m.f.ua=m.aa(6);m.f.isEmpty=m.aa(7);m.f.pa=m.aa(2);m.f.tf=m.aa(8);m.f.clear=function(){for(var a=m.dd(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.gd=new m.cd(window.document);m.gd.k=3950;m.vba=m.$d?"webkit":m.ae?"moz":m.B?"ms":m.be?"o":"";m.Kg=m.k("yt.dom.getNextId_");if(!m.Kg){m.Kg=function(){return++wba};m.h("yt.dom.getNextId_",m.Kg,void 0);var wba=0};m.f=m.jd.prototype;m.f.va=null;m.f.type="";m.f.target=null;m.f.relatedTarget=null;m.f.currentTarget=null;m.f.data=null;m.f.source=null;m.f.state=null;m.f.keyCode=0;m.f.charCode=0;m.f.altKey=!1;m.f.ctrlKey=!1;m.f.shiftKey=!1;m.f.clientX=0;m.f.clientY=0;m.f.wheelDeltaX=0;m.f.wheelDeltaY=0;m.f.rotation=0;m.f.scale=1;m.f.changedTouches=null;m.f.preventDefault=m.aa(9);m.f.stopPropagation=m.aa(10);m.f.stopImmediatePropagation=m.aa(11);
var Daa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.ld=m.k("yt.events.listeners_")||{};m.h("yt.events.listeners_",m.ld,void 0);var md=m.k("yt.events.counter_")||{count:0};m.h("yt.events.counter_",md,void 0);var Cd;var yd,zd=!1,Ad=[];m.Fd.prototype.then=function(a,b,c){return m.Ld(this,m.ma(a)?a:null,m.ma(b)?b:null,c)};m.Dd(m.Fd);m.Fd.prototype.cancel=function(a){0==this.k&&xd(function(){var b=new Md(a);Id(this,b)},this)};m.Fd.prototype.H=function(a){this.k=0;Gd(this,2,a)};m.Fd.prototype.J=function(a){this.k=0;Gd(this,3,a)};m.Fd.prototype.K=function(){for(;this.j&&this.j.length;){var a=this.j;this.j=[];for(var b=0;b<a.length;b++)Jd(this,a[b],this.k,this.G)}this.F=!1};var Kaa=vd;m.p(Md,m.sa);Md.prototype.name="cancel";var Pd=null;Nd.prototype.C=function(a){Qd(this,"startFeedback",arguments)};Nd.prototype.F=function(a){Qd(this,"startHelp",arguments)};Nd.prototype.j=function(a){Qd(this,"loadChatSupport",arguments)};var Lg=!1,Mg="";
if(window.navigator.plugins&&window.navigator.plugins.length){var Ng=window.navigator.plugins["Shockwave Flash"];Ng&&(Lg=!0,Ng.description&&(Mg=Rd(Ng.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(Lg=!0,Mg="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var Og=window.navigator.mimeTypes["application/x-shockwave-flash"];(Lg=Og&&Og.enabledPlugin)&&(Mg=Rd(Og.enabledPlugin.description))}else try{var Pg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),Lg=
!0,Mg=Rd(Pg.GetVariable("$version"))}catch(xba){try{Pg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),Lg=!0,Mg="6.0.21"}catch(yba){try{Pg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Lg=!0,Mg=Rd(Pg.GetVariable("$version"))}catch(zba){}}}m.Aba=Lg;m.Qg=Mg;var Rg,Sg,Tg,Ug,Vg,Wg,Xg,Bba,Cba;Xg=Wg=Vg=Ug=Tg=Sg=Rg=!1;var Yg=m.wd;Yg&&(-1!=Yg.indexOf("Firefox")?Rg=!0:-1!=Yg.indexOf("Camino")?Sg=!0:-1!=Yg.indexOf("iPhone")||-1!=Yg.indexOf("iPod")?Tg=!0:-1!=Yg.indexOf("iPad")?Ug=!0:-1!=Yg.indexOf("Chrome")?Wg=!0:-1!=Yg.indexOf("Android")?Vg=!0:-1!=Yg.indexOf("Safari")&&(Xg=!0));m.Zg=Rg;Bba=Sg;m.$g=Tg;m.ah=Ug;Cba=Vg;m.bh=Wg;m.ch=Xg;m.Dba=function(){if(m.Zg)return Sd(/Firefox\/([0-9.]+)/);if(m.B||m.be)return yb;if(m.bh)return Sd(/Chrome\/([0-9.]+)/);if(m.ch)return Sd(/Version\/([0-9.]+)/);if(m.$g||m.ah){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.wd))return a[1]+"."+a[2]}else{if(Cba)return(a=Sd(/Android\s+([0-9.]+)/))?a:Sd(/Version\/([0-9.]+)/);if(Bba)return Sd(/Camino\/([0-9.]+)/)}return""}();m.ga(Td);Td.prototype.getVersion=function(){return[this.j,this.k,this.B]};m.f=m.de.prototype;m.f.clone=function(){return new m.de(this.top,this.right,this.bottom,this.left)};m.f.contains=function(a){return m.ee(this,a)};m.f.ceil=m.aa(12);m.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.f.scale=function(a,b){var c=m.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Raa=m.ub("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Eba=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Fba=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.ie.prototype.oi=!0;m.ie.prototype.ni=function(){return this.j};m.ie.prototype.toString=function(){return"Const{"+this.j+"}"};var je={};le.prototype.oi=!0;var me={};le.prototype.ni=function(){return this.j};var Paa=ne(""),Oaa=/^[-.%_!# a-zA-Z0-9]+$/;oe.prototype.oi=!0;oe.prototype.ni=function(){return""};oe.prototype.fp=!0;oe.prototype.sh=function(){return 1};var pe={};var ue,Qaa,Naa,re;qe.prototype.fp=!0;qe.prototype.sh=function(){return this.k};qe.prototype.oi=!0;qe.prototype.ni=function(){return this.j};ue=/^[a-zA-Z0-9-]+$/;Qaa=m.ub("action","cite","data","formaction","href","manifest","poster","src");Naa=m.ub("link","script","style");re={};m.dh=ve("",0);m.eh=m.Mb(function(){if(m.B)return m.wb("10.0");var a=window.document.createElement("div"),b=m.ce(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=m.te("div",{style:c});a.innerHTML=m.se(b);a=a.firstChild;b=a.style[m.Aa("transition")];return""!=("undefined"!==typeof b?b:a.style[m.fe(a,"transition")]||"")});var Ce;m.ye={};Ce=!1;m.ga(m.Ee);m.Fe=m.k("yt.prefs.UserPrefs.prefs_")||{};m.h("yt.prefs.UserPrefs.prefs_",m.Fe,void 0);m.f=m.Ee.prototype;m.f.get=function(a,b){He(a);Ge(a);var c=void 0!==m.Fe[a]?m.Fe[a].toString():null;return null!=c?c:b?b:""};m.f.set=function(a,b){He(a);Ge(a);if(null==b)throw"ExpectedNotNull";m.Fe[a]=b.toString()};m.f.remove=function(a){He(a);Ge(a);delete m.Fe[a]};m.f.save=function(){var a;a=[];for(var b in m.Fe)a.push(b+"="+(0,window.escape)(m.Fe[b]));a=a.join("&");m.fd("PREF",a,63072E3)};
m.f.clear=function(){m.Fe={}};var Uaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Re;var fh=m.wd,fh=fh.toLowerCase();if(m.wa(fh,"android")){var gh=fh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(gh)Re=Number(gh[1]);else{var hh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},ih=fh.match("("+m.pb(hh).join("|")+")");Re=ih?hh[ih[0]]:0}}else Re=void 0;m.p(m.Te,Waa);m.Te.prototype.pa=m.aa(1);m.Te.prototype.clear=function(){var a=m.Rb(this.eb(!0)),b=this;(0,m.v)(a,function(a){b.remove(a)})};m.p(m.Ue,m.Te);m.f=m.Ue.prototype;m.f.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.f.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.f.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.f.remove=function(a){this.j.removeItem(a)};
m.f.pa=m.aa(0);m.f.eb=function(a){var b=0,c=this.j,d=new m.Nb;d.next=function(){if(b>=c.length)throw m.Pb;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.f.clear=function(){this.j.clear()};m.f.key=function(a){return this.j.key(a)};m.p(m.Ve,m.Ue);m.p(We,m.Ue);var cf={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.df.prototype.set=function(a,b){m.ca(b)?this.j.set(a,m.Ye(b)):this.j.remove(a)};m.df.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.Xe(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.df.prototype.remove=function(a){this.j.remove(a)};m.p(ef,m.df);ef.prototype.set=function(a,b){ef.L.set.call(this,a,gf(b))};ef.prototype.k=function(a){a=ef.L.get.call(this,a);if(!m.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};ef.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.p(hf,ef);hf.prototype.set=function(a,b,c){if(b=gf(b)){if(c){if(c<(0,m.E)()){hf.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.E)()}hf.L.set.call(this,a,b)};hf.prototype.k=function(a,b){var c=hf.L.k.call(this,a);if(c)if(!b&&m.jf(c))hf.prototype.remove.call(this,a);else return c};m.p(m.kf,hf);var jh,kh;jh=new m.Ve;m.mf=jh.isAvailable()?new m.kf(jh):null;kh=new We;m.nf=kh.isAvailable()?new m.kf(kh):null;m.p(qf,m.La);m.f=qf.prototype;m.f.getId=function(){return this.K};m.f.sj=function(a,b){this.ha()||(sf(this,a),yf(this,b),this.G&&uf(this))};m.f.Ut=function(){return this.ka};
m.f.py=function(){if(!this.P){var a=!0;this.na&&(a=zf(this));a&&"html5"==Bf(this)?(this.F="html5",this.G||this.Ke()):(Cf(this),this.F="html5",a&&this.ea?(this.vf.appendChild(this.ea),this.Ke()):(this.da.loaded=!0,this.H=(0,m.l)(function(){var a=this.vf,c=this.da.clone();m.k("yt.player.Application.create")(a,c);this.Ke()},this),this.P=!0,zf(this)?this.H():(m.Vc(this.da.assets.js,this.H),m.Qe(this.da.assets.css))))}};
m.f.oy=function(){var a=this.da.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Bf(this)?(this.F="flash",this.G||Pe(a,!1,(0,m.l)(this.Ke,this))):(Cf(this),this.F="flash",this.da.loaded=!0,m.Le(this.vf,a),this.Ke())};
m.f.Ke=function(){var a=xf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.P=!1,a.isNotServable&&a.isNotServable())wf(this);else{rf(this);this.G=!0;a=xf(this);a.addEventListener&&(this.J=Af(this,a,"addEventListener"));a.removeEventListener&&(this.T=Af(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.j[e]||(this.j[e]=Af(this,a,e))}for(var g in this.C)this.J(g,this.C[g]);uf(this);
this.V&&this.V(this.j);this.R.publish("onReady",this.j)}else this.Ca=m.s((0,m.l)(this.Ke,this),50)};m.f.Yt=function(){return this.G};m.f.ve=function(a,b){if(!this.ha()){var c=tf(this,b);if(c){if(!m.Ea(this.Ha,a)&&!this.C[a]){var d=Zaa(this,a);this.J&&this.J(a,d)}this.R.subscribe(a,c);"onReady"==a&&this.G&&m.s(m.qa(c,this.j),0)}}};m.f.Xt=function(a,b){if(!this.ha()){var c=tf(this,b);c&&this.R.unsubscribe(a,c)}};
m.f.Vp=function(a){a=a?naa:maa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.f.Xp=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?pf().volume:m.nb(a.volume,0,100);b.muted=void 0==a.muted?pf().muted:a.muted;m.lf("yt-player-volume",b,2592E3)};m.f.Wp=function(a){5==a&&wf(this)};m.f.Yp=function(a){m.w("WATCH_LATER_VIDEO_ADDED",a)};m.f.Zp=function(a){m.w("WATCH_LATER_VIDEO_REMOVED",a)};
m.f.qy=function(){Cf(this);this.F="unsupported";var a=this.da.messages.player_fallback||'Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a=this.da.messages.quicktime_fallback||'Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=m.C("player-unavailable");m.C("unavailable-submessage")&&b&&(m.C("unavailable-submessage").innerHTML=a,(a=m.D("icon",b))&&m.Tc(a,"icon")&&(a.src=m.F(a,"icon")),m.A(b,"hid"),m.z(m.C("player"),"off-screen-trigger"))};m.f.Wt=function(){return this.F||Bf(this)};m.f.Vt=function(){return this.Ba};m.f.cancel=function(){this.H&&m.Xc(this.da.assets.js,this.H);m.Wa(this.Ca);this.P=!1};
m.f.N=function(){Cf(this);this.X=null;for(var a in this.C)m.ea[this.C[a]]=null;this.j=null;delete this.vf;delete this.B;this.da&&(this.ka=this.da=this.da.fallback=null);qf.L.N.call(this)};var Ff={},Ef="player_uid_"+(1E9*Math.random()>>>0);var Gba=m.k("yt.player.exports.navigate")||m.ud;m.h("yt.player.exports.navigate",Gba,void 0);var Hba=m.k("yt.player.embed")||m.Df;m.h("yt.player.embed",Hba,void 0);var Iba=m.k("yt.player.destroy")||m.Hf;m.h("yt.player.destroy",Iba,void 0);var Jba=m.k("yt.player.cancelAll")||Gf;m.h("yt.player.cancelAll",Jba,void 0);var Kba=m.k("yt.player.getPlayerByElement")||m.If;m.h("yt.player.getPlayerByElement",Kba,void 0);var Lba=m.k("yt.player.exports.feedbackStart")||m.Ae;
m.h("yt.player.exports.feedbackStart",Lba,void 0);var Mba=m.k("yt.player.exports.feedbackShowArticle")||m.De;m.h("yt.player.exports.feedbackShowArticle",Mba,void 0);var Nba=m.k("yt.util.activity.init")||m.nd;m.h("yt.util.activity.init",Nba,void 0);var Oba=m.k("yt.util.activity.getTimeSinceActive")||m.pd;m.h("yt.util.activity.getTimeSinceActive",Oba,void 0);var Pba=m.k("yt.util.activity.setTimestamp")||od;m.h("yt.util.activity.setTimestamp",Pba,void 0);var Lf,Rf=!1,Qf="",Jf=!1;var Wf=[];var Zf,kg,lg,$f=0,eba=[900,60,"waiting"],hba=[500,99,"waiting"],fba=[300,60,"waiting"],gba=[400,99,"waiting"],hg=[300,101,"done"];var mg=[];window.yt=window.yt||{};m.h("yt.setConfig",m.Ra,void 0);m.h("yt.getConfig",m.r,void 0);m.h("yt.hasMsg",m.ab,void 0);m.h("yt.pubsub.publish",m.w,void 0);m.h("yt.pubsub.subscribe",m.u,void 0);m.h("yt.setMsg",m.Za,void 0);m.h("yt.setGoogMsg",function(a){Sa(m.$a,arguments)},void 0);m.h("yt.setAjaxToken",function(){},void 0);m.h("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)m.fc(e,a[e],d);if(c)for(var g in c)kc(g,c[g],d);if(b)for(var n in b)jc(n,b[n],d);return wc(d)},void 0);
m.h("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var g in b)"_"!=g.charAt(0)&&(c[g]=b[g]);a=m.r("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);nc(c)},void 0);m.p(ng,m.Dc);
ng.prototype.enable=function(){window.onload=bba;window.onunload=cba;window.onerror=dba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Yf),window.addEventListener("spfpartprocess",bg),window.addEventListener("spfpartdone",eg),window.addEventListener("spfprocess",fg),window.addEventListener("spfdone",gg),window.addEventListener("spferror",ig),window.addEventListener("spfreload",jg),window.addEventListener("spfjsbeforeunload",og)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",iba),this.subscribe("dispose",kba)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
ng.prototype.init=function(){ng.L.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();raa();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.r("PAGEFRAME_JS")?(b=m.r("PAGEFRAME_JS"),c=function(){m.k("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.k("yt.www.masthead.loadSearchbox"))&&a();var a=m.r("JS_COMMON_MODULE"),d=m.r("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.r("JS_DELAY_LOAD",void 0),0<a?(m.Wa(this.j),this.j=m.s(function(){b&&m.Vc(b,c);window.spf.script.require(d)},
a)):(b&&m.Vc(b,c),window.spf.script.require(d));else{var e={};e[a]=d;a=m.r("JS_DELAY_LOAD",void 0);0<a?(m.Wa(this.j),this.j=m.s(function(){b&&m.Vc(b,c);m.Yc(e)},a)):(b&&m.Vc(b,c),m.Yc(e))}lba();aba();var a=!!m.k("yt.reactLoaded"),g=m.r("REACT_JS");!a&&g&&m.Vc(g,function(){m.h("yt.reactLoaded",!0,void 0)})};
ng.prototype.dispose=function(){m.Wa(this.j);var a=m.k("ytbin.www.pageframe.cancelSetup");a&&a();m.I(mg);mg.length=0;m.Xa(Lf);if(a=m.Nf())a.removeEventListener("onReady",Mf),a.removeEventListener("onStateChange",Mf),a.removeEventListener("onReady",Of),a.removeEventListener("onStateChange",Of);ng.L.dispose.call(this)};
ng.prototype.disable=function(){ng.L.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Yf),window.removeEventListener("spfpartprocess",bg),window.removeEventListener("spfpartdone",eg),window.removeEventListener("spfprocess",fg),window.removeEventListener("spfdone",gg),window.removeEventListener("spferror",ig),window.removeEventListener("spfreload",jg),window.removeEventListener("spfjsbeforeunload",og));window.onload=null;window.onunload=null;window.onerror=null};
m.Fc(new ng);})(_yt_www);
