(function($){if(!$)return;if(window.corn&&window.corn.getp){window.getp=corn.getp;}else{window.getp=function(name){name=name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "));}}
var utm_source=location.host;
if(location.host==='cloudacademy.com'){ if(location.pathname.indexOf('/blog/')===0){ utm_source='blog'; $(function(){ $("a[href*='cloudacademy.com/']:not([href*='cloudacademy.com/blog/'])").each(function(){var $this=$(this),href=$this.attr('href'),has_utm=-1!==href.indexOf('utm_source='), symb=(has_utm||-1!==href.indexOf('?')?'&':'?');
if(!has_utm){var params=cloudacademy_utm('post',$this.text());$this.attr('href',href+symb+params);}});});}else{utm_source='homepage';}}
window.cloudacademy_utm=function(campaign,text){var t=encodeURIComponent(text);return $.param({'utm_source':utm_source,'utm_medium':'link','utm_campaign':utm_source+'-'+campaign,'utm_term':t,'utm_content':t});};$.extend($,{'injectCss':function(rules,id){$("<style>").prop("type","text/css").attr('id',id).html(rules).appendTo("head");}});})(window.$||window.jQuery);(function($){if(!$)return;$(function(){var items=$('.cloudacademy-blog.home .content .post:nth-child(odd),.cloudacademy-blog.single-post .content .widget#text-6,#home-courses .notebook');if(!window.API||!window.cloudacademy_utm||!items.length)return;$.injectCss('\
			.clouda-course { max-width: 710px; margin-left: auto; margin-right: auto; text-align:left;} \
			.clouda-course .entry-title{ font-size:30px;line-height:30px;margin-bottom:10px;} \
			.clouda-course .clouda-video-container{ position:relative;padding:5px 0 0;border-radius: 0;background-color: #333;box-shadow:0 0 6px #333;} \
			.clouda-course video{ max-height: 400px;} \
			.clouda-course .overlay{ display:none;box-sizing: border-box;border-radius:0;position:absolute;top:0;left:0;width:100%;height:100%;background-color:#999;z-index: 10;} \
			.clouda-course .overlay div {box-sizing: border-box; background-color: rgba(0, 0, 0, 0.8);position:absolute;left:0;top:0;width:100%;height:100%;padding-top:25%;} \
			.clouda-course .overlay a{ color:#fff;margin:0px auto;background-color: #0098d4;border-radius:3px;font-size:15px;outline:medium none;line-height: 20px; display: block; max-width:180px;font-weight:bold;text-transform:uppercase;text-align:center;padding: 10px 25px;text-decoration: none;} \
			.clouda-course .clouda-video-footer{ color: #fff; padding: 10px 15px;background-color: #333; border-radius: 0;box-shadow:0 0 6px #333;} \
			.clouda-course .clouda-video-footer p { margin: 0; line-height: 20px;font-size:17px; max-width:100%; } \
			.clouda-course .clouda-video-footer .member-btn { float: right; border-radius: 3px; outline: none; display: block; max-width: 180px; font-weight: bold; text-transform: uppercase; text-align: center; text-decoration: none; background-color: #1B992E; font-size: 14px; line-height: 18px; color: #fff; padding: 10px 15px; margin-left:5px;} \
			.clouda-course .clouda-video-footer a{ text-decoration: none;} \
			.clouda-course .clouda-video-footer span{ color:#0098d4;font-weight: bold;} \
		','clouda-course-style');function injectVideo(c,item){if(!item)return;var courseURL=c.url+"?"+cloudacademy_utm('video',c.title),afterURL=c.url+"?"+cloudacademy_utm('video',"Keep Learning"),fullURL=c.url+"?"+cloudacademy_utm('video',"Watch the full Course now"),html='<article class="entry clouda-course">';if(!$(item).data('notitle')){html+='<h2 class="entry-title"><a href="'+courseURL+'" title="'+c.title+'">'+c.title+'</a></h2>';}
html+='<div class="clouda-video-container">';html+='<video class="hidden-phone" controls preload="auto" width="100%" poster="'+(c.image||c.video.poster)+'">';$.each(c.video.sources||[],function(i,s){html+='<source src="'+s.url+'" type="'+s.type+'" data-res="'+s.label+'"/>';});$.each(c.video.subtitles||[],function(i,s){html+='<track kind="subtitles" src="'+s.url+'" srclang="'+s.lang+'" label="'+s.label+'"/>';});html+='</video>';html+='<div class="overlay" style="background-image:url(\''+(c.image||c.video.poster)+'\');">';html+='<div><a href="'+afterURL+'">Keep Learning</a></div>';html+='</div>';html+='</div>';html+='<div class="clouda-video-footer"><p>';html+='<a class="member-btn" href="https://cloudacademy.com/pricing/?'+cloudacademy_utm('video','Become a Member')+'">Become a Member</a>';html+='<a href="'+fullURL+'"><span>Watch the full Course now</span></a> and start enjoying our Courses Library.  Each course includes high-quality videos and quizzes.';html+='</p></div>';html+='</article>';$(html).hide().insertAfter(item).slideDown(800).find('video').on('ended',function(){$(this).siblings('.overlay').fadeIn();_gaq.push(['_trackEvent','blog-video','ended',c.title]);}).one('play',function(){_gaq.push(['_trackEvent','blog-video','play',c.title]);}).on('pause',function(){_gaq.push(['_trackEvent','blog-video','pause',c.title]);}).on('seeking',function(){_gaq.push(['_trackEvent','blog-video','seeking',c.title]);});new Image().src=(c.image||c.video.poster); if($(item).hasClass('notebook'))$(item).remove();}
API.getList('blog_courses',function(courses){$.each(courses.slice(0,5),function(i,c){injectVideo(c,items.get(i));});});});})(window.$||window.jQuery);(function($){if(!$)return;$(function(){var items=$(".cloudacademy-blog .site-inner aside section:first, .clouda-homepage-quiz a, #main #secondary aside:first"),ls=window.localStorage;if(!window.API||!window.cloudacademy_utm||!items.length)return;window._gaq=window._gaq||[];if(getp('noquiz'))return;if(getp('clear')&&ls)ls.clear();function getUID(){function newID(){return Math.random().toString(36).substring(2,10);} 
if(ls){if(!ls.getItem('clouda-uid')){var uid=newID()+newID()+newID();ls.setItem('clouda-uid',uid);}
return ls.getItem('clouda-uid');}else{return newID()+newID()+newID();}}
function saveUID(uid){if(ls)ls.setItem('clouda-uid',uid);}
function getQuestions(){if(ls&&ls.getItem('clouda-questions')){return JSON.parse(ls.getItem('clouda-questions'));}
return[];}
function saveQuestions(data){if(ls)ls.setItem('clouda-questions',JSON.stringify(data));}
$.injectCss('\
			.clouda-quiz { font-family: Helvetica;max-width:650px; min-width:300px; margin:35px auto;background-color:white;border-radius:2px 2px 0 0;box-shadow:0 0 5px #999; } \
			.clouda-quiz .q { padding:20px; } \
			.clouda-quiz .q-text{ margin:0 0 15px;font-size:20px;line-height:25px;color:#333;text-align:left; } \
			.clouda-quiz .q-text p{ margin:0 ; max-width:100%; } \
			.clouda-quiz .answers { list-style:none;font-size:16px;padding:0;text-align:left;margin:0; } \
			.clouda-quiz .answers li { border-top:1px solid #dce0e6;padding-left:30px;position:relative; } \
			.clouda-quiz .answers li:last-child { border-bottom:1px solid #dce0e6; } \
			.clouda-quiz .answers a { font-size:16px;text-transform:none;outline:none;font-weight:normal;display:block;vertical-align:middle;padding:10px 0;text-decoration:none;color:#585858; } \
			.clouda-quiz .answers a > span { box-sizing: border-box;width: 19px;height: 19px;border-radius:10px; border: 2px solid #d4d6d9;position: absolute; left: 0; top: 30%; } \
			.clouda-quiz .answers a span span { content:"";display:none;width:7px; height:7px; border-radius:5px;background-color: #d4d6d9;position:absolute;left:4px; top:4px; } \
			.clouda-quiz .answers a:hover {color: #1B75BB;} \
			.clouda-quiz .answers a:hover span span {display:block;} \
			.clouda-quiz .statement-container { display:none; } \
			.clouda-quiz .statement-big { text-align:left;background: white;padding: 35px 20px 40px;max-width: 90%;min-height: 50px;margin: 0 auto 20px;border: 1px solid #fafafa;border-radius: 2px;position: relative;font-size: 19px;line-height: 23px; } \
			.clouda-quiz .open-quote { position: absolute;left:8px;top:8px;width: 26px;height: 23px;background: url("https://d3ay7xm8v33lat.cloudfront.net/static/img/career/quote-open.png") no-repeat center transparent; } \
			.clouda-quiz .closed-quote { position: absolute;right:15px;bottom:30px;width: 26px;height: 23px;background: url("https://d3ay7xm8v33lat.cloudfront.net/static/img/career/quote-close.png") no-repeat center transparent; } \
			.clouda-quiz .s-text { color:#333;word-wrap: break-word;overflow:hidden; } \
			.clouda-quiz .information { text-align:left;color:#333;font-size: 14px;line-height: 16px;position: absolute;bottom: 0;min-height: 40px;max-width: 90%;overflow: hidden; } \
			.clouda-quiz .information a { font-size:14px;text-transform:none;padding:0;color:#C2342F;text-decoration:none;white-space:nowrap; } \
			.clouda-quiz a.next-question { color:#fff;margin:0 auto;background-color: #0098d4;border-radius:3px;font-size:15px;outline:none;line-height: 20px; display: block; max-width:180px;font-weight:bold;text-transform:uppercase;text-align:center;padding: 10px 25px;text-decoration: none; } \
			.clouda-quiz a.more-questions { display:none;color:#fff;margin:0 auto;background-color: #1B992E;border-radius:3px;font-size:15px;outline:none;line-height: 20px; max-width:200px;font-weight:bold;text-transform:uppercase;text-align:center;padding: 10px 15px;text-decoration: none; } \
			.clouda-quiz .clouda-quiz-footer { color: #fff; padding: 10px;background-color: #333; border-radius: 0;box-shadow:0 0 5px #999; } \
			.clouda-quiz .clouda-quiz-footer a { text-decoration: none;text-transform:none;padding:0;font-size:16px; } \
			.clouda-quiz .clouda-quiz-footer div { text-align:left;margin: 0; line-height: 20px;font-size:16px;overflow:hidden; } \
			.clouda-quiz .clouda-quiz-footer .member-btn { float: right; border-radius: 3px; outline: none; display: block; max-width: 180px; font-weight: bold; text-transform: uppercase; text-align: center; text-decoration: none; background-color: #1B992E; font-size: 14px; line-height: 18px; color: #fff; padding: 10px; margin-left:5px; } \
			.clouda-quiz .clouda-quiz-footer span { color:#0098d4;font-weight: bold; } \
		','clouda-quiz-style');function createQuiz(item){var html='';html+='<div class="clouda-quiz">';html+='<div class="q">';html+='<div class="text-answer-container">';html+='<div class="q-text"></div>';html+='<ol class="answers"></ol>';html+='</div>';html+='<div class="statement-container">';html+='<div class="statement-big">';html+='<div class="open-quote"></div><div class="closed-quote"></div>';html+='<div class="s-text"></div>';html+='<div class="information"><strong>Learn More</strong><br><a href="#" target="_blank"></a></div>';html+='</div>';html+='<a class="next-question" href="#">Next Question</a>';html+='<a class="more-questions" href="https://cloudacademy.com/cloud-computing-learning-quizzes/?'+cloudacademy_utm('quiz','More Quizzes')+'">More Quizzes on CloudAcademy.com</a>';html+='</div>';html+='</div>';html+='<div class="clouda-quiz-footer"><div>';html+='<a class="member-btn" href="https://cloudacademy.com/pricing/?'+cloudacademy_utm('quiz','Become a Member')+'">Become a Member</a>';html+='<a href="https://cloudacademy.com/cloud-computing-learning-quizzes/?'+cloudacademy_utm('quiz','Start Learning Now')+'"><span>Start learning now</span></a> with our Quizzes.';html+='</div></div>';html+='</div>';function showQ(question){q.data('id',question._id);qt.html(question.description);qa.empty();$.each(question.answers,function(i,answer){qa.append('<li><a href="#" data-id="'+answer.id+'" target="blank"><span><span></span></span>'+answer.description+'</a></li>');});s.fadeOut(function(){qq.fadeIn();});}
function showS(data){st.html(data.statement);if(data.information){sia.text(data.information).attr('href',data.information);si.show();}else{si.hide();}
if(q.data('is-last')){snext.hide();smore.css('display','block');}
qq.fadeOut(function(){s.fadeIn();});st.find('p').css({'margin':'0 0 8px'});}
function init(){_gaq.push(['_trackEvent','blog-quiz','init']);q.on('show-next',function(){var questions=q.data('questions');if(!questions.length)return;showQ(questions[0]);q.data('answered',false).data('is-last',questions.length==1);}).on('click','.answers a',function(e){e.preventDefault();if(q.data('answered'))return;var questions=q.data('questions').slice(1);q.data('answered',true).data('questions',questions);saveQuestions(questions);_gaq.push(['_trackEvent','blog-quiz','answer']);var $answer=$(this).css({'color':'#1B75BB'});API.post('quiz',function(json){q.trigger('result',[json,$answer]);},null,{'uid':getUID(),'_id':q.data('id'),'answer_id':$answer.data('id')},function(xhr){try{var json=xhr.responseJSON||JSON.parse(xhr.responseText);q.trigger('result',[json,$answer]);}catch(e){console.log(e);}});}).on('click','.next-question',function(e){e.preventDefault();_gaq.push(['_trackEvent','blog-quiz','next']);q.trigger('show-next');}).on('click','.more-questions',function(){_gaq.push(['_trackEvent','blog-quiz','more']);}).one('mouseenter',function(){_gaq.push(['_trackEvent','blog-quiz','focus']);}).on('result',function(_,data,$answer){$answer.css({'color':$answer.data('id')==data.correct_id?'#45b555':'#ae2727'});qa.find('[data-id="'+data.correct_id+'"]').css({'color':'#45b555'});setTimeout(function(){showS(data);},600);}).trigger('show-next');if($(item).data('trigger')){$(item).on('click',function(e){e.preventDefault();_gaq.push(['_trackEvent','blog-quiz','button-trigger']);$(this).fadeOut(300,function(){q.slideDown();});});}else{if($(item).hasClass('notebook'))$(item).remove();q.slideDown();}}
var q=$(html).insertAfter(item).hide(),qq=q.find('.text-answer-container'),qt=qq.find('.q-text'),qa=qq.find('.answers'),s=q.find('.statement-container'),st=s.find('.s-text'),si=s.find('.information'),sia=si.find('a'),snext=s.find('.next-question'),smore=s.find('.more-questions'),questions=getQuestions();if(!questions||!questions.length){_gaq.push(['_trackEvent','blog-quiz','fetch']);API.getList('quiz',function(data){if(data.length){q.data('questions',data);saveQuestions(data);init();}},null,{'uid':getUID()},function(){q.remove();});}else{q.data('questions',questions);init();}}
var url=API.domain+'/auth-check/';$.ajax({url:url,'xhrFields':{'withCredentials':true}}).fail(function(xhr){var json=xhr.responseJSON||JSON.parse(xhr.responseText);if(json&&json._id)saveUID(json._id);items.each(function(){createQuiz(this);});});});})(window.$||window.jQuery);(function($){if(!$)return;$(function(){var $form=$(".sidebar-primary .mc4wp-form").clone(),$email=$form.find('input[type="email"]').attr('placeholder','Your email address goes here.'),$btn=$form.find('input[type="submit"]').val('I want to be a Cloud Expert'),ls=window.localStorage;if(!$form.length||!haveToShow()){return;}
setTimeout(showPopup,30000);
function haveToShow(){if(ls&&ls.getItem('clouda-popup-newsletter')){var expire=new Date(ls.getItem('clouda-popup-newsletter'));return expire<=new Date();}
return true;}
function dontShowAgain(longOffset){if(ls){var offset=604800000; if(longOffset){offset*=8;}
ls.setItem('clouda-popup-newsletter',new Date(new Date().getTime()+offset).toUTCString());}}
$.injectCss('\
			.clouda-popup { position:fixed;width:100%;height:100%;top:0;z-index:99999; background-color: rgba(0,0,0,0.7); } \
			.clouda-popup .clouda-positioned { width:620px;margin:80px auto 0;position:relative; } \
			.clouda-popup .clouda-wrap { background: url("https://d3ay7xm8v33lat.cloudfront.net/static/img/popup-bg.png") no-repeat center 20px #fff; overflow: hidden; padding:85px 25px 15px; box-shadow:0 0 15px #222; } \
			.clouda-popup .clouda-content { text-align:left; } \
			.clouda-popup form { margin:0; padding: 0; } \
			.clouda-popup h1 { text-align: center; font-size: 24px; margin: 20px 0px 10px; letter-spacing: 0.2px; font-weight: lighter; } \
			.clouda-popup p { color: #333; font-weight: lighter; margin: 0 0 40px; padding: 0; font-size: 20px; line-height:22px; letter-spacing: 0.3px; text-align: center; } \
			.clouda-popup h1 strong, .clouda-popup p strong { font-weight: normal; } \
			.clouda-popup .mc4wp-form input { border-radius: 0; border: 0 none; box-sizing: border-box; display: block; font-size: 17px;  height: 60px !important; width: 100% !important; line-height: 20px; margin: 0 0 20px; outline: none; padding: 20px; text-align: center; } \
			.clouda-popup .mc4wp-form input[type="email"] { background-color: #f8f8f8; color: #333; } \
			.clouda-popup .mc4wp-form input[type="submit"] { border:1px solid #1874bd; background-color: #1874bd; color: #fff; text-transform: uppercase; cursor: pointer; } \
			.clouda-popup .mc4wp-form input[type="submit"]:hover { background-color: #fff; color: #1874bd; } \
			.clouda-popup a { text-decoration:none; font-size:12px; color:#666; letter-spacing: 0.2px; display:block; text-align:center; } \
			.clouda-popup ::-webkit-input-placeholder, .clouda-popup :-moz-placeholder, .clouda-popup ::-moz-placeholder, .clouda-popup :-ms-input-placeholder {color: #999;} \
		','clouda-popup-style');function showPopup(){var html='';html+='<div class="clouda-popup">';html+='<div class="clouda-positioned">';html+='<div class="clouda-wrap">';html+='<div class="clouda-content">';html+='<h1>Looking for <strong>educational material</strong> about the Cloud?</h1>';html+='<p>Sign up and get access to <strong>weekly premium content</strong>.</p>';html+='</div>';html+='<a href="#" title="Hide this message in the future">No Thanks, I prefer old-fashioned technologies.</a>';html+='</div>';html+='</div>';html+='</div>';function emailFocus(){$email.focus();}
var popup=$(html).hide().appendTo('body').fadeIn(600,emailFocus);popup.on('click',emailFocus);popup.find('.clouda-content').append($form);popup.find('a').click(function(e){e.preventDefault();popup.fadeOut();dontShowAgain(false);});popup.find('form').on('submit',function(e){dontShowAgain(true);});}});})(window.$||window.jQuery);