(function ensightenInit(){var ensightenOptions = {client: "msdn", clientId: 776, publishPath: "ch9prod", isPublic:0, serverComponentLocation: "nexus.ensighten.com/msdn/ch9prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/msdn/ch9prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Tue Dec 02 00:51:33 GMT 2014", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+
encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=
0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=
a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=
function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};
b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};
b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,
50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};
var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=
log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",
b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=
-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
	
if (!window[ensightenOptions.ns].data) {
/*
 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
(function(){function d(a){return 10>a?"0"+a:a}function m(a){g.lastIndex=0;return g.test(a)?'"'+a.replace(g,function(a){var c=f[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(f,d){var b,k,r,e,g=h,s,p=d[f];p&&"object"===typeof p&&"function"===typeof p.toJSON&&(p=p.toJSON(f));"function"===typeof c&&(p=c.call(d,f,p));switch(typeof p){case "string":return m(p);case "number":return isFinite(p)?String(p):"null";case "boolean":case "null":return String(p);
case "object":if(!p)return"null";h+=a;s=[];if("[object Array]"===Object.prototype.toString.apply(p)){e=p.length;for(b=0;b<e;b+=1)s[b]=l(b,p)||"null";r=0===s.length?"[]":h?"[\n"+h+s.join(",\n"+h)+"\n"+g+"]":"["+s.join(",")+"]";h=g;return r}if(c&&"object"===typeof c)for(e=c.length,b=0;b<e;b+=1)"string"===typeof c[b]&&(k=c[b],(r=l(k,p))&&s.push(m(k)+(h?": ":":")+r));else for(k in p)Object.prototype.hasOwnProperty.call(p,k)&&(r=l(k,p))&&s.push(m(k)+(h?": ":":")+r);r=0===s.length?"{}":h?"{\n"+h+s.join(",\n"+
h)+"\n"+g+"}":"{"+s.join(",")+"}";h=g;return r}}var b=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+d(this.getUTCMonth()+1)+"-"+d(this.getUTCDate())+"T"+d(this.getUTCHours())+":"+d(this.getUTCMinutes())+":"+d(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=
/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h,a,f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c;"function"!==typeof b.stringify&&(b.stringify=function(b,f,d){var k;a=h="";if("number"===typeof d)for(k=0;k<d;k+=1)a+=" ";else"string"===typeof d&&(a=d);if((c=f)&&"function"!==typeof f&&
("object"!==typeof f||"number"!==typeof f.length))throw Error("JSON.stringify");return l("",{"":b})});"function"!==typeof b.parse&&(b.parse=function(a,c){function f(a,b){var d,k,e=a[b];if(e&&"object"===typeof e)for(d in e)Object.prototype.hasOwnProperty.call(e,d)&&(k=f(e,d),void 0!==k?e[d]=k:delete e[d]);return c.call(a,b,e)}var b;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),"function"===typeof c?f({"":b},""):b;throw new SyntaxError("JSON.parse");})})();
window[ensightenOptions.ns].when=function(){function d(a,c,b,f){return l(a).then(c,b,f)}function m(a){this.then=a}function l(a){return b(function(c){c(a)})}function b(c){function d(a){n&&(t=e(a),f(n,t),n=u)}function k(a){d(h(a))}function r(c){n&&f(n,a(c))}var t,n=[];try{c(d,k,r)}catch(g){k(g)}return new m(function(a,c,f){return b(function(b,d,k){n?n.push(function(e){e.then(a,c,f).then(b,d,k)}):q(function(){t.then(a,c,f).then(b,d,k)})})})}function e(a){return a instanceof m?a:a!==Object(a)?g(a):b(function(c,
b,f){q(function(){try{var d=a.then;"function"===typeof d?A(d,a,c,b,f):c(g(a))}catch(k){b(k)}})})}function g(a){var c=new m(function(b){try{return"function"==typeof b?e(b(a)):c}catch(f){return h(f)}});return c}function h(a){var c=new m(function(b,f){try{return"function"==typeof f?e(f(a)):c}catch(d){return h(d)}});return c}function a(c){var b=new m(function(f,d,k){try{return"function"==typeof k?a(k(c)):b}catch(e){return a(e)}});return b}function f(a,c){q(function(){for(var b,f=0;b=a[f++];)b(c)})}function c(a,
c,f,k,e){r(2,arguments);return d(a,function(a){return b(function(b,f,k){function e(a){l(a)}function r(a){h(a)}var n,g,v,q,h,l,w,y;w=a.length>>>0;n=Math.max(0,Math.min(c,w));v=[];g=w-n+1;q=[];if(n)for(l=function(a){q.push(a);--g||(h=l=t,f(q))},h=function(a){v.push(a);--n||(h=l=t,b(v))},y=0;y<w;++y)y in a&&d(a[y],r,e,k);else b(v)}).then(f,k,e)})}function n(a,c,b,f){r(1,arguments);return v(a,w).then(c,b,f)}function v(a,c){return d(a,function(a){return b(function(b,f,k){var e,r,n,t,g;n=r=a.length>>>0;
e=[];if(n)for(t=function(a,r){d(a,c).then(function(a){e[r]=a;--n||b(e)},f,k)},g=0;g<r;g++)g in a?t(a[g],g):--n;else b(e)})})}function q(a){1===z.push(a)&&C(k)}function k(){for(var a,c=0;a=z[c++];)a();z=[]}function r(a,c){for(var b,f=c.length;f>a;)if(b=c[--f],null!=b&&"function"!=typeof b)throw Error("arg "+f+" must be a function");}function t(){}function w(a){return a}d.defer=function(){var a,c,f;a={promise:u,resolve:u,reject:u,notify:u,resolver:{resolve:u,reject:u,notify:u}};a.promise=c=b(function(b,
d,k){a.resolve=a.resolver.resolve=function(a){if(f)return l(a);f=!0;b(a);return c};a.reject=a.resolver.reject=function(a){if(f)return l(h(a));f=!0;d(a);return c};a.notify=a.resolver.notify=function(a){k(a);return a}});return a};d.resolve=l;d.reject=function(a){return d(a,h)};d.join=function(){return v(arguments,w)};d.all=n;d.map=v;d.reduce=function(a,c){var b=A(p,arguments,1);return d(a,function(a){var f;f=a.length;b[0]=function(a,b,k){return d(a,function(a){return d(b,function(b){return c(a,b,k,
f)})})};return s.apply(a,b)})};d.any=function(a,b,f,d){return c(a,1,function(a){return b?b(a[0]):a[0]},f,d)};d.some=c;d.isPromise=function(a){return a&&"function"===typeof a.then};m.prototype={otherwise:function(a){return this.then(u,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return n(b,function(b){return a.apply(u,b)})})},always:function(a,b){return this.then(a,
a,b)}};var s,p,A,C,z,D,x,B,u;z=[];D=setTimeout;C="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){D(a,0)};x=Function.prototype;B=x.call;A=x.bind?B.bind(B):function(a,b){return a.apply(b,p.call(arguments,2))};x=[];p=x.slice;s=x.reduce||function(a){var b,c,f,d,k;k=0;b=Object(this);d=b.length>>>0;c=arguments;if(1>=c.length)for(;;){if(k in b){f=b[k++];break}if(++k>=d)throw new TypeError;
}else f=c[1];for(;k<d;++k)k in b&&(f=a(f,b[k],k,b));return f};return d}();
(function(){function d(b,d){return l.all(d||[],function(d){return b.apply(null,d)})}function m(e){var g=b.call(arguments,1);return function(){return d(e,g.concat(b.call(arguments)))}}var l,b;l=window[ensightenOptions.ns].when;b=[].slice;l.apply=d;l.call=function(e){return d(e,b.call(arguments,1))};l.lift=m;l.bind=m;l.compose=function(e){var g=b.call(arguments,1);return function(){var h=b.call(arguments),h=d(e,h);return l.reduce(g,function(a,b){return b(a)},h)}}})();
window[ensightenOptions.ns].data=function(d,m){function l(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var b={engines:{memory:{get:function(a){if(e.utils.isArray(a)){for(var f=[],c=0;c<a.length;c++)f.push(b.data[a[c]]);return d[ensightenOptions.ns].when.resolve(f)}f=b.dataDefinitions[a]||{storage:{get:function(){}}};f=f.storage.get(f);null!=f&&f!=m&&""!=f&&(b.data[a]=f);return d[ensightenOptions.ns].when.resolve(b.data[a])},
set:function(a,f){if(e.utils.isArray(a))for(var c in a)b.data[a[c]]=f[c];else b.data[a]=f;return d[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(e.utils.isArray(a))for(var f in a)delete b.data[a[f]];else delete b.data[a];return d[ensightenOptions.ns].when.resolve(!0)},clear:function(a){b.data={};b.definitions={};return d[ensightenOptions.ns].when.resolve(!0)},all:function(){return d[ensightenOptions.ns].when.resolve(b.data)}}},normalizeInputArgs:function(a,b){var c={key:[],val:m},d;
if(e.utils.isPlainObject(a))for(d in c.val=[],a)c.key.push(d),c.val.push(a[d]);else e.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},e={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(b){return a}}}},g=function(){return d[ensightenOptions.ns].when.reject("Not Implemented.")};
l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;b.DataDefinitionException=l;b.checkForInvalidDataDefinitions=function(a){e.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(d[ensightenOptions.ns].reportException(new b.DataDefinitionException(a)),!0):!1};b.collectAvailableDataDefinitions=function(a){for(var f=[],c=0;c<a.length;c++){var n=parseInt(a[c],10),g=d[ensightenOptions.ns].dataDefinitions[n];if(null===g||g===m)if(g=e.storage.session.get({id:n}),
null!==g&&g!==m)e.set(n,g),b.dataDefinitions[n]={id:n,load:"visitor",storage:e.storage.visitor,missingDDFromCache:!0},f.push(d[ensightenOptions.ns].data.get(""+n));else return d[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Invalid data definition used: "+n)),{promises:[],isInvalid:!0};else f.push(d[ensightenOptions.ns].data.get(a[c]))}return{promises:f,isInvalid:!1}};b.getSync=function(a){function f(a){var b=a.extract||n,f=a.transform||g,d=!1,k=null,e=null;try{k=b()}catch(q){k=
null,d=!0}try{e=f(k)}catch(h){e=null,d=!0}d&&c.push(a.id);return e}var c=[],n=function(){return document},g=function(a){return null!==a&&a!==m?a.toString():null},q=parseInt(a);a="string"===typeof a?a.split("."):[];var k="";isNaN(q)?3==a.length&&(k=f(e.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2]))):k=f(e.getDataDefinitionById(q));0<c.length&&d[ensightenOptions.ns].reportException(new b.DataDefinitionException(c,"Error resolving data definitions synchronously: "+c));return k};b.dataDefinitions=
{};b.dataDefinitionsBySourceCollName={};e.defineEngine=function(a,f){var c,e=["get","set","remove","clear","all"];b.engines[a]=f;if(!f.returnsPromise)for(c=0;c<e.length;c++){var g=e[c];f[g]=d[ensightenOptions.ns].when.lift(f[g])}};e.storage={instance:{set:function(a,b){},get:function(a){return b.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return m}},session:{set:function(a,b){var c=e.storage.session.get({id:a}),g=new Date,h=g.getTime();g.setTime(h+18E5);null!=c&&(b=c);d[ensightenOptions.ns].data.cookie.utils.set(a,
b,{expires:g.toGMTString()});c={expires:g.getTime(),value:b};d[ensightenOptions.ns].data.local.utils.set(a,c)},get:function(a){var b=d[ensightenOptions.ns].data.cookie.utils.get(a.id),c=d.JSON&&d.JSON.stringify?d.JSON:d[ensightenOptions.ns].JSON,c=c||{},e,g=new Date,g=g.getTime();if(null===b){try{e=c.parse(d[ensightenOptions.ns].data.local.utils.get(a.id))}catch(h){e=null}null!=e&&(e.expires=+e.expires,g<=e.expires?b=e.value:""==e.expires&&e.value!=m?b=e.value:d[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},
visitor:{set:function(a,b){var c=e.storage.session.get({id:a});null!=c&&(b=c);d[ensightenOptions.ns].data.cookie.utils.set(a,b);d[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return e.storage.session.get(a)}}};e.getEngine=e.engine=function(a){return a?b.engines[a]||{get:g,set:g,remove:g,clear:g,all:g}:b.engines};e.all=function(a){return d[ensightenOptions.ns].data.engine(a||"memory").all()};e.get=function(a,f,c){f=f||"memory";c=c||{};-1<a.indexOf(",")&&(a=a.split(","));
a=b.normalizeInputArgs(a);return c.wait?b.getWait(a.key,d[ensightenOptions.ns].data.engine(f),c):b.data&&b.data.hasOwnProperty(a.key)?d[ensightenOptions.ns].data.engine(f).get(a.key):b.getWaitForKey(a.key,d[ensightenOptions.ns].data.engine(f),c)};b.getWait=function(a,b,c){var g=+new Date,h=d[ensightenOptions.ns].when.defer(),q=function(){var d=b.get(a);if(-1===c.wait)return d;d.then(function(a){c.setCheck(a)?h.resolve(a):setTimeout(k,c.interval)},function(a){setTimeout(k,c.interval)})},k=function(){var a=
+new Date-g;-1!==c.wait&&a<c.wait?q():h.reject("Timeout")};c.interval=c.interval||500;c.wait=c.wait||5E3;e.utils.isArray(a)?c.setCheck=c.setCheck||function(a){for(var b=!0,c=0;c<a.length;c++)b=b&&!!a[c];return b}:c.setCheck=c.setCheck||function(a){return!!a};q();return h.promise};b.getWaitForKey=function(a,f,c){var e=d[ensightenOptions.ns].when.defer(),g=function(){if(b.data&&b.data.hasOwnProperty(a)){var d=f.get(a);if(-1===c.wait)return d;d.then(function(a){e.resolve(a)},function(a){e.reject(a)})}else setTimeout(h,
c.interval)},h=function(){g()};c.interval=c.interval||100;c.wait=c.wait||1;g();return e.promise};e.set=function(a,f,c){var e=b.normalizeInputArgs(a,f);Array.prototype.slice.call(arguments);return d[ensightenOptions.ns].data.engine(c||"memory").set(e.key,e.val)};e.remove=function(a,b){return d[ensightenOptions.ns].data.engine(b||"memory").remove(a)};e.clear=function(a){return d[ensightenOptions.ns].data.engine(a||"memory").clear()};e.define=function(a,f){f&&(a.name=f.id||f.name);if(!a.name)return d[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));
a.id=a.name;var c=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return d[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=d[ensightenOptions.ns].data.engine("memory");a.storage=e.storage[c.toLowerCase()]||e.storage.page;var g=a.extract||function(){return document},h=a.transform||function(a){return a},q=function(b,c){var e=[];e.push(a.persist.set(b,
c));a.storage.set(a.id,c);"object"==typeof d[ensightenOptions.ns].data.dataExport&&d[ensightenOptions.ns].data.dataExport(b,c,a.collection);d[ensightenOptions.ns].when.all(e).then(function(a){k.resolve(a)},function(a){k.reject(a)})},k=d[ensightenOptions.ns].when.defer();a.trigger().then(function(){k.resolve(d[ensightenOptions.ns].when.reduce([g(),h,q],function(b,c,d,e){if(1==d)return c(b);2==d&&c(a.name,b)}))},function(a){k.reject(a)});b.dataDefinitions[a.id]=a;b.dataDefinitionsBySourceCollName[""+
a.source+"."+a.collection+"."+a.dataDefName]=a;return k.promise};e.checkConditions=function(a){var f,c={lt:function(a,c){var e=+a,f=+c;return isNaN(e)||isNaN(f)?(d[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+c)),!1):e<f},gt:function(a,c){var e=+a,f=+c;return isNaN(e)||isNaN(f)?(d[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
a+", compareTo: "+c)),!1):e>f},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==m||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(d){return!1}},starts:function(a,b,d){b=e.utils.escapeRegEx(b);return c.re(a,"^"+b,d)},ends:function(a,b,d){b=e.utils.escapeRegEx(b);return c.re(a,b+"$",d)},contains:function(a,b,d){b=e.utils.escapeRegEx(b);return c.re(a,".*"+b+".*",d)}};c.is=c.eql;c["starts with"]=c.starts;c["ends with"]=c.ends;c["is greater than"]=
c.gt;c["is less than"]=c.lt;c.matches=c.re;for(f=0;f<a.values.length;f++){var g=(a.customComparator?a.customComparator[f]?a.customComparator[f]:c[a.comparators[f]]:c[a.comparators[f]])(a.values[f],a.compareTo[f],a.caseInsensitive?a.caseInsensitive[f]||!1:!1);a.not[f]&&(g=!g);if(!g)return!1}return!0};e.triggerPromise=function(a,b,c){c=c||5E3;var e=+new Date,g=d[ensightenOptions.ns].when.defer();(function(){var d=a();d!=b?g.resolve(d):+new Date-e<c?setTimeout(arguments.callee,200):g.reject("timed out")})();
return g.promise};e.timeoutPromise=function(a,b){var c=d[ensightenOptions.ns].when.defer();b=b||800;a.then(c.resolve,c.reject);setTimeout(function(){c.reject(Error("timed out"))},b);return c.promise};e.delayTrigger=function(a){a=a||10;var b=d[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},a);return b.promise};e.delayUntilTrigger=function(a,b,c,e){c=c||null;e=e||200;var g=+new Date,h=d[ensightenOptions.ns].when.defer();(function(){var d=a();d!=b?h.resolve(d):c?+new Date-g<c?setTimeout(arguments.callee,
e):h.reject("timed out"):setTimeout(arguments.callee,e)})();return h.promise};b.applyTrigger=function(a){var b=d[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};e.bottomOfBodyTrigger=function(){return b.applyTrigger(d[ensightenOptions.ns].bindDOMParsed)};e.afterEnsightenCompleteTrigger=function(){return b.applyTrigger(d[ensightenOptions.ns].bindPageSpecificCompletion)};e.afterElementsDownloadedTrigger=function(){return b.applyTrigger(d[ensightenOptions.ns].bindDOMLoaded)};
e.getAllDataDefinitionsOnCurrentPage=function(){return b.dataDefinitions};e.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return b.dataDefinitionsBySourceCollName};e.getDataDefinitionById=function(a){return b.dataDefinitions[a||-1]||{}};e.getDataDefinitionBySourceCollectionName=function(a,d,c){return b.dataDefinitionsBySourceCollName[""+a+"."+d+"."+c]||{}};e.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:b.dataDefinitions[a[1]]||{}};e.resolve=function(a,
f){var c=this,g=null;if(!b.checkForInvalidDataDefinitions(a))if(f)d[ensightenOptions.ns].bindDataDefinitionComplete(function(){var e=b.collectAvailableDataDefinitions(a);e.isInvalid||d[ensightenOptions.ns].when.all(e.promises).then(function(e){try{f.apply(c,e)}catch(k){d[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+k))}},function(c){d[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+
a+". Details: "+c))})});else{var g=[],h=a;e.utils.isArray(a)||(h=[a]);for(var l=0;l<h.length;l++)g.push(b.getSync(h[l]));return g=e.utils.isArray(a)?g:g[0]}};e.extract=function(a,b){var c="",e=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",d=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(c?b.split("#")[0]:d?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==e&&0==d)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);
var f=a.firstChild;if(!f)return null;for(var k=0,d=0!=d?d-1:d;f;){if(1==f.nodeType){if(f.tagName.toLowerCase()==e&&""!=c&&f.id==c||f.tagName.toLowerCase()==e&&k==d&&""==c)return f;f.tagName.toLowerCase()==e&&k++}f=f.nextSibling}},g=function(a,b){a=a.split("/");for(var c=e(b||document,a[1]),d=2;d<a.length;d++){if(null==c)return null;c=e(c,a[d])}return c},h=function(){for(var a={},b=d.document.getElementsByTagName("META")||[],c=0,e=b.length;c<e;c++){var f=b[c].name||b[c].getAttribute("property")||"";
0!==f.length&&(a[f]=b[c].content)}return a}(),k=function(a){var b=h[a];if(b)return b;for(var b=d.document.getElementsByTagName("META")||[],c=0,e=b.length;c<e;c++){var f=b[c].name||b[c].getAttribute("property")||"";if(a==f)return b[c].content}},r=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(d.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},t=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(d.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=
m(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},m=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=g(a);else try{b=eval(a)}catch(c){b=""}return b};try{return b?"meta"==b?c=k(a):"cookie"==b?c=t(a):"param"==b?c=r(a):"content"==b?c=l(a):"event"==b?c=m(a):"var"==b&&(c=d[a]):c=k(a)||t(a)||r(a)||l(a)||m(a)||d[a]||"",c||""}catch(p){return""}};if("undefined"==typeof h)var h={exports:{}};return e}(window);
window[ensightenOptions.ns].data.defineEngine("store",function(){var d={},m=window,l=m.document,b,e,g=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};d.set=function(a,b){};d.get=function(a){};d.remove=function(a){};d.clear=function(){};try{if("localStorage"in m&&m.localStorage)b=m.localStorage,d.set=function(a,c){var d,e,f=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(g(a))for(d=0,e=a.length;d<e;d++)b.setItem(a[d],"string"===
typeof c[d]?c[d]:f.stringify(c[d]));else b.setItem(a,"string"===typeof c?c:f.stringify(c))},d.get=function(a){if(g(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b.getItem(a[d]);return c}return b.getItem(a)},d.remove=function(a){if(g(a)){var c,d;c=0;for(d=a.length;c<d;c++)b.removeItem(a[c])}else b.removeItem(a)},d.clear=function(){b.clear()},d.all=function(){return b};else if("globalStorage"in m&&m.globalStorage)b=m.globalStorage[m.location.hostname],d.set=function(a,c){if(g(a)){var d,e;d=0;
for(e=a.length;d<e;d++)b[a[d]]=c[d]}else b[a]=c},d.get=function(a){if(g(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b[a[d]]&&b[a[d]].value;return c}return b[a]&&b[a].value},d.remove=function(a){if(g(a)){var c,d;c=0;for(d=a.length;c<d;c++)delete b[a[c]]}else delete b[a]},d.clear=function(){for(var a in b)delete b[a]},d.all=function(){return b};else if(l.documentElement.addBehavior){var h,a;try{a=new ActiveXObject("htmlfile"),a.open(),a.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>'),
a.close(),h=a.w.frames[0].document,b=h.createElement("div")}catch(f){b=l.createElement("div"),h=l.body}var m=function(a){return function(){var c=Array.prototype.slice.call(arguments,0);c.unshift(b);h.appendChild(b);b.addBehavior("#default#userData");b.load("localStorage");c=a.apply(store,c);h.removeChild(b);return c}},c=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g"),n=function(a){return a.replace(c,"___")};d.set=m(function(a,b,c){if(g(b)){var e,f;e=0;for(f=b.length;e<f;e++){fixedKey=n(b[e]);
if(void 0===c[e])return d.remove(fixedKey);a.setAttribute(fixedKey,c[e]);a.save("localStorage")}}else{fixedKey=n(b);if(void 0===c)return d.remove(fixedKey);a.setAttribute(fixedKey,c);a.save("localStorage")}});d.get=m(function(a,b){if(g(b)){var c={},d,e,f;e=0;for(f=b.length;e<f;e++)d=n(b[e]),c[b[e]]=a.getAttribute(d);return c}b=n(b);return a.getAttribute(b)});d.remove=m(function(a,b){if(g(b)){var c,d;c=0;for(d=b.length;c<d;c++)a.removeAttribute(n(b[c])),a.save("localStorage")}else b=n(b),a.removeAttribute(b),
a.save("localStorage")});d.clear=m(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var c=0,d;d=b[c];c++)a.removeAttribute(d.name);a.save("localStorage")});d.all=m(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},d=0,e;e=b[d];++d){var f=n(e.name);c[e.name]=a.getAttribute(f)}return c})}}catch(v){}var q={};for(e in d)q[e]=d[e];q.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());q.set(a,"test");if("test"===q.get(a))return q.remove(a),
!0}catch(b){}return!1};d.utils=q;return window[ensightenOptions.ns].data.local=d}());
window[ensightenOptions.ns].data.defineEngine("cookie",function(d,m){var l=function(){return l.get.apply(l,arguments)},b=l.utils={isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(b){return Array.prototype.slice.call(b)},getKeys:Object.keys||function(b){var d=[],h="";for(h in b)b.hasOwnProperty(h)&&d.push(h);return d},escape:function(b){return String(b).replace(/[,;"\\=\s%]/g,
function(b){return encodeURIComponent(b)})},retrieve:function(b,d){return null==b?d:b},getAllCookies:function(){if(""===d.cookie)return{};for(var b=d.cookie.split("; "),g={},h=0,a=b.length;h<a;h++){var f=b[h].split("=");g[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return g},set:function(e,g,h){h=h||-1;if(b.isPlainObject(e))for(var a in e)e.hasOwnProperty(a)&&l.set(a,e[a],g);else if(b.isArray(e)){var f;a=0;for(f=e.length;a<f;a++)l.set(e[a],g[a],h)}else{a=h.expires!==m?h.expires:l.defaults.expires||
"";"number"===typeof a&&(a=new Date(a));a=b.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():b.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;f=(f=h.path||l.defaults.path)?";path="+f:"";var c=h.domain||l.defaults.domain,c=c?";domain="+c:"";h=h.secure||l.defaults.secure?";secure":"";d.cookie=b.escape(e)+"="+b.escape(g)+a+f+c+h}},get:function(d,g){g=g||m;var h=b.getAllCookies();if(b.isArray(d)){for(var a={},f=0,c=d.length;f<c;f++)a[d[f]]=b.retrieve(h[d[f]],
g),a[d[f]]===m&&(a[d[f]]=null);return a}a=b.retrieve(h[d],g);return a===m?null:a},getGMTString:function(b){var d=new Date;d.setTime(d.getTime()+864E5*b);return d.toGMTString()}};l.defaults={path:"/",expires:b.getGMTString(90)};l.set=function(d,g){b.set(d,g)};l.remove=function(d){d=b.isArray(d)?d:b.toArray(arguments);for(var g=0,h=d.length;g<h;g++)b.set(d[g],"",{expires:-1})};l.clear=function(){return l.remove(b.getKeys(b.getAllCookies()))};l.get=function(d,g){return b.get(d,g)};l.all=function(){return b.getAllCookies()};
l.utils=b;return window[ensightenOptions.ns].data.cookie=l}(document));
}
		Bootstrapper.dataDefinitionIds = [2348,2333];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return function(c){for(var a=document.getElementsByTagName("meta"),b=0;b<a.length;b++)if(c==a[b].name)return a[b].content;return false}("Search.ShortId")},load:"",dataDefName:"MSDN - ShortID - CR-INT",collection:"MSDN - CR",source:"Manage",priv:"false"},{id:"2333"})},2333)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.AF=function(){var g={data:{},_dataConfig:{},logHistory:[],debug:!0,dataObj:function(a){var b=a?[]:"";b.finalized=!1;b.type=a;return b},validateInput:function(a){if("object"!==typeof a||"number"!==typeof a.length)return this.log("Error, input must be type Array");/set|push|call|eval|finalize|join/.test(a[0])||this.log("Error, '"+a[0]+"' is not a valid command");
return!0},storeData:function(a,b,d,c,e){e=this.getConfig(b,d,e);b=this.data[b][d];if(e.finalized)return this.log("Error, cannot modify finalized key '"+d+"'"),b;if("undefined"!==typeof b&&e.multi)return"join"==a?b=b.concat(c):b.push(c),b;e.multi?(d=[c],"join"==a&&(d=[].concat(c))):d=c;return d},getConfig:function(a,b,d,c){a=this._dataConfig[a]||{};c={};return"undefined"==typeof a[b]?(c.multi=d,c.finalized=!1,c):a[b]},store:function(a,b,d,c,e){this.data[b]=this.data[b]||{};this.data[b][d]=this.storeData(a,
b,d,c,e);return this.data[b][d]},parseCode:function(a){return((a||function(){})+"").replace(/^function\s*\(\s*\)\s*\{|\}$/g,"")},callFn:function(a,b,d,c){if("function"==typeof a)if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(a)):eval.call(window,this.parseCode(a));else return a.apply(window,c);else if("function"==typeof this.data[a][b])if(d)"undefined"!=typeof window.execScript?window.execScript(this.parseCode(this.data[a][b])):eval.call(window,this.parseCode(this.data[a][b]));
else return c="object"==typeof c&&"number"==typeof c.length?c:[],this.data[a][b].apply(this.data[a],c);else return this.log("Error, '"+b+"' is not a function")},parse:function(a){if(this.validateInput(a)){a=Array.prototype.slice.call(a,0);var b=a.shift(),d=a.shift(),c=a.shift(),e=a[0];if(/set|push|join/.test(b))return this.store(b,d,c,e,/push|join/.test(b));if(/call|eval/.test(b))return this.callFn(d,c,"eval"==b,a);if("finalize"==b)return a=this._dataConfig[d]=this._dataConfig[d]||{},a=a[c]||{multi:!1},
a.finalized=!0,this._dataConfig[d][c]=a}},log:function(a){this.logHistory.push(a);return this.debug&&"object"==typeof console?console.log(a)&&!1:!1}};if("object"==typeof Bootstrapper.AF&&"[object Array]"!==Object.prototype.toString.call(Bootstrapper.AF))return Bootstrapper.AF;if("[object Array]"===Object.prototype.toString.call(Bootstrapper.AF))for(var h=Bootstrapper.AF,f=0;f<h.length;f++)try{g.parse(h[f])}catch(k){}return{push:function(a){return g.parse(a)}}}();Bootstrapper.ajaxListener=function(){var listeners=
{},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==
detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];
return _private.data},getDataElement:function(i,e){if(typeof this.data[i]=="undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=
d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=
this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},
getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.dataManager.map=function(){return{define:function(n,d){if(Bootstrapper.data)for(i in d){var v=typeof d[i]=="string"?Bootstrapper.data.extract(d[i]):d[i]();Bootstrapper.data.dataManagerPush(i,v,n)}}}}();window.$data=function(a,b){if(typeof b=="string")try{return Bootstrapper.dataManager.getDataElement(a,
b)}catch(e){}else if(typeof a=="string")return Bootstrapper.dataManager.getData()[a]||"";return""};Bootstrapper.bindOnGetServerComponent(function(){var DL=Bootstrapper.dataManager&&Bootstrapper.targetingExtension?Bootstrapper.dataManager.getData():{};if(~document.cookie.indexOf("VTP:enabled"))DL["ensightenVT"]=1;if(Bootstrapper.scDataObj)for(i in DL)Bootstrapper.scDataObj[i]=DL[i]});var ns=window[ensightenOptions.ns];ns.VTconfig=ns.VTconfig||{};ns.VTconfig["DM"]=this.deploymentId;(function(){function m(a,
b,d){if("_root"==b)return d;if(a!==d){var c;p||(a.matches&&(p=a.matches),a.webkitMatchesSelector&&(p=a.webkitMatchesSelector),a.mozMatchesSelector&&(p=a.mozMatchesSelector),a.msMatchesSelector&&(p=a.msMatchesSelector),a.oMatchesSelector&&(p=a.oMatchesSelector),p||(p=f.matchesSelector));c=p;if(c.call(a,b))return a;if(a.parentNode)return r++,m(a.parentNode,b,d)}}function s(a,b,d,c){g[a.id]||(g[a.id]={});g[a.id][b]||(g[a.id][b]={});g[a.id][b][d]||(g[a.id][b][d]=[]);g[a.id][b][d].push(c)}function c(a,
b,d,c){if(c||d)if(c)for(var f=0;f<g[a.id][b][d].length;f++){if(g[a.id][b][d][f]===c){g[a.id][b][d].pop(f,1);break}}else delete g[a.id][b][d];else g[a.id][b]={}}function e(a,b,d){if(g[a][d]){var c=b.target||b.srcElement,e,k,l={},h=k=0;r=0;for(e in g[a][d])g[a][d].hasOwnProperty(e)&&(k=m(c,e,n[a].element))&&f.matchesEvent(d,n[a].element,k,"_root"==e,b)&&(r++,g[a][d][e].match=k,l[r]=g[a][d][e]);b.stopPropagation=function(){b.cancelBubble=!0};for(k=0;k<=r;k++)if(l[k])for(h=0;h<l[k].length;h++){if(!1===
l[k][h].call(l[k].match,b)){f.cancel(b);return}if(b.cancelBubble)return}}}function h(a,b,d,h){function m(a){return function(b){e(k,b,a)}}a instanceof Array||(a=[a]);d||"function"!=typeof b||(d=b,b="_root");var k=this.id,l;for(l=0;l<a.length;l++)g[k]&&g[k][a[l]]||f.addEvent(this,a[l],m(a[l])),h?c(this,a[l],b,d):s(this,a[l],b,d);return this}function f(a,b,c,e){if("string"==typeof a&&"function"==typeof b||"string"==typeof b)f(document).on(a,b,c,e||!1);if(!(this instanceof f)){for(var g in n)if(n[g].element===
a)return n[g];q++;n[q]=new f(a,q);n[q]._on=n[q].on;n[q].on=function(a,b,c,d){var e="function"==typeof b?b:c;if("function"==typeof b?c:d)a=[a],"string"==typeof b&&a.push(b),a.push(function(a){return function(b){b.defaultPrevented||Bootstrapper.Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return a.call(this);"undefined"!=typeof b.preventDefault?b.preventDefault():b.returnValue=!1;a.call(this)}}(e)),this._on.apply(this,a);else return this._on.call(this,a,b,c)};return n[q]}this.element=
a;this.id=b}var p,r=0,q=0,g={},n={};f.prototype.on=function(a,b,c){return h.call(this,a,b,c)};f.prototype.off=function(a,b,c){return h.call(this,a,b,c,!0)};f.matchesSelector=function(){};f.cancel=function(a){a.preventDefault();a.stopPropagation()};f.addEvent=function(a,b,c){a.element.addEventListener(b,c,"blur"==b||"focus"==b)};f.matchesEvent=function(){return!0};f.load=function(a){setTimeout(function(a,c){return function(){if(a.nodeName&&"a"==a.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);
c&&(window.location.href=c)}}}(a,a.href||""),750)};window.Bootstrapper.Delegate=f})();(function(m){var s=m.addEvent;m.addEvent=function(c,e,h){if(c.element.addEventListener)return s(c,e,h);"focus"==e&&(e="focusin");"blur"==e&&(e="focusout");c.element.attachEvent("on"+e,h)};m.simpleMatchesSelector=function(c){return"."===c.charAt(0)?-1<(" "+this.className+" ").indexOf(" "+c.slice(1)+" "):"#"===c.charAt(0)?this.id===c.slice(1):this.tagName.toUpperCase()===c.toUpperCase()};m.matchesSelector=function(c){if(~c.indexOf(" ")||
~c.indexOf("\x3e")){var e=this;for(c=c.split(" ").reverse();c.length;){var h=c.shift();if(~h.indexOf("\x3e")){for(h=h.split("\x3e").reverse();h.length;)if(tempSel=h.shift(),m.simpleMatchesSelector.call(e,tempSel))e=e.parentNode;else return!1;if(!c.length)return!0}else for(;e!=document;){var f=m.simpleMatchesSelector.call(e,h),e=e.parentNode;if(f){if(!c.length)return!0;break}}}return!1}return m.simpleMatchesSelector.call(this,c)};m.cancel=function(c){c.preventDefault&&c.preventDefault();c.stopPropagation&&
c.stopPropagation();c.returnValue=!1;c.cancelBubble=!0}})(window.Bootstrapper.Delegate);Bootstrapper.on=Bootstrapper.Delegate;Bootstrapper.getQueryParam=function(key,loc){if(!this.params||loc){var search=loc||window.location.search;var params=search.replace(/^\?/,""),paramObj={};params=params.split("\x26");for(var i=0;i<params.length;i++){var t=params[i].split("\x3d");paramObj[t[0]]=t[1]}if(!loc)this.params=paramObj;else return paramObj[key]||""}return this.params[key]||""};Bootstrapper.getElementXPath=
function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,
1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==
c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?
s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=
this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:(true||
!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");
this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL not available")}},store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set","_ensCloak",o)}_log("*** Cloak:Storage updated")},
load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&
o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",
sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,
a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");
_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=
o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,
f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},
500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&
b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,
o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a=
"/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone==
"undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+
b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p==
"element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,
s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=this.deploymentId;Bootstrapper.propertyWatcher=function(options){var _private={watchers:[]},_public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;
_public.options=options;_public.change=function(oldVal,newVal){};return _public};_private.doChecks=function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i],p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}_private.resetTimer()};_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);
return w};_public={create:_private.addWatcher};_private.doChecks();return _public}();Bootstrapper.safeIframeInsert=function(u){var newFrame=document.createElement("iframe");newFrame.src=u;newFrame.width=newFrame.height="1px";newFrame.style.display="none";var rand=parseInt(1E5*1E4*Math.random()*Math.random());Bootstrapper["appendFrame"+rand]=setInterval(function(a,b){return function(){document.getElementsByTagName("body")&&0<document.getElementsByTagName("body").length&&(clearInterval(Bootstrapper["appendFrame"+
b]),document.getElementsByTagName("body")[0].appendChild(a))}}(newFrame,rand),250)};Bootstrapper.parseHTML=function(c){var d,b,a,e=!1,g=[];d=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi;var h=/<([\w:]+)/;a=/<|&#?\w+;/;b={option:[1,"\x3cselect multiple\x3d'multiple'\x3e","\x3c/select\x3e"],legend:[1,"\x3cfieldset\x3e","\x3c/fieldset\x3e"],thead:[1,"\x3ctable\x3e","\x3c/table\x3e"],tr:[2,"\x3ctable\x3e\x3ctbody\x3e","\x3c/tbody\x3e\x3c/table\x3e"],td:[3,"\x3ctable\x3e\x3ctbody\x3e\x3ctr\x3e",
"\x3c/tr\x3e\x3c/tbody\x3e\x3c/table\x3e"],col:[2,"\x3ctable\x3e\x3ctbody\x3e\x3c/tbody\x3e\x3ccolgroup\x3e","\x3c/colgroup\x3e\x3c/table\x3e"],area:[1,"\x3cmap\x3e","\x3c/map\x3e"]};b.optgroup=b.option;b.tbody=b.tfoot=b.colgroup=b.caption=b.thead;b.th=b.td;b._default=[1,"X\x3cdiv\x3e","\x3c/div\x3e"];f=document;if("string"==typeof c)if(a.test(c)){if(!(a=e))if(a=f,e="abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video".split(" "),
a=a.createDocumentFragment(),a.createElement)for(;e.length;)a.createElement(e.pop());e=a;a=f.createElement("div");e.appendChild(a);c=c.replace(d,"\x3c$1\x3e\x3c/$2\x3e");d=(h.exec(c)||["",""])[1].toLowerCase();b=b[d]||b._default;d=b[0];for(a.innerHTML=b[1]+c+b[2];d--;)a=a.lastChild;c=a.childNodes;a.parentNode.removeChild(a)}else c=f.createTextNode(c);if(c.nodeType)g.push(c);else{b=c.length;d=g.length;a=0;if("number"==typeof b)for(;a<b;a++)g[d++]=c[a];else for(;c[a]!==h;)g[d++]=c[a++];g.length=d}return g};
document.write=function(){var parse=Bootstrapper.parseHTML,parseHTML,head,target,tail,open=false,lastString="",lastNodes=[],configTarget=function(){if(document.getElementById("_ensDiv")===null){var d=document.createElement("div");d.style.display="none";d.id="_ensDiv";document.body.appendChild(d);target=d;return}target=document.getElementById("_ensDiv")};return function(x){if(target===undefined)configTarget();if(open){open=false,newS=lastString+x;newN=parse(newS);for(var i=newN.length-1;i>-1;i--)if(lastNodes[i]&&
newN[i].outerHTML==lastNodes[i].outerHTML)newN.splice(i,1);target.removeChild(tail);for(var i=0;i<newN.length;i++)document.body.appendChild(newN[i]);nodes=newN}var nodes=nodes||parse(x);for(var i=0;i<nodes.length;i++){if(nodes[i].nodeName=="SCRIPT"){var n=document.createElement("script");for(var k in nodes[i])try{if(typeof nodes[i][k]=="string"&&nodes[i][k]!=n[k]&&!/html$/i.test(k))n.setAttribute(k,nodes[i][k]);else if(typeof nodes[i][k]=="function"&&nodes[i][k]!=n[k])n[k]=nodes[i][k]}catch(e){}nodes[i]=
n}target.appendChild(nodes[i]),tail=nodes[i]}if(tail.nodeType==1&&!/\>$/.test(x)){open=true;lastString=x;lastNodes=nodes}}}()},522501,266625);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){try{return Bootstrapper.data.extract("Search.ShortId","meta")}catch(e){return"error"}},transform:function(v){return v},load:"",dataDefName:"MSDN - ShortID - Prod",collection:"MSDN - Prod",source:"Manage",priv:"false"},{id:"2348"})},2348)},-1,-1);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();