var _yt_www={};(function(m){var window=this;var pa,aaa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.h=function(a,b,c){a=a.split(".");c=c||m.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.k=function(a,b){for(var c=a.split("."),d=b||m.da,f;f=c.shift();)if(null!=d[f])d=d[f];else return null;return d};m.ea=function(){};m.ga=function(a){a.getInstance=function(){return a.hb?a.hb:a.hb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ja=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ka=function(a){return"string"==typeof a};m.la=function(a){return"number"==typeof a};m.ma=function(a){return"function"==m.ha(a)};m.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.oa=function(a){return a[pa]||(a[pa]=++aaa)};
var baa=function(a,b,c){return a.call.apply(a.bind,arguments)};var caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.l=function(a,b,c){m.l=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return m.l.apply(null,arguments)};
m.qa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.p=function(a,b){function c(){}c.prototype=b.prototype;a.J=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,g){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};m.ra=function(a){m.ra[" "](a);return a};
m.sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.ta=function(a){return(0,window.encodeURIComponent)(String(a))};
m.va=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};m.wa=function(a,b){return-1!=a.indexOf(b)};
m.xa=function(a,b){for(var c=0,d=(0,m.ya)(String(a)).split("."),f=(0,m.ya)(String(b)).split("."),g=Math.max(d.length,f.length),n=0;0==c&&n<g;n++){var q=d[n]||"",t=f[n]||"",z=RegExp("(\\d*)(\\D*)","g"),G=RegExp("(\\d*)(\\D*)","g");do{var T=z.exec(q)||["","",""],fa=G.exec(t)||["","",""];if(0==T[0].length&&0==fa[0].length)break;c=za(0==T[1].length?0:(0,window.parseInt)(T[1],10),0==fa[1].length?0:(0,window.parseInt)(fa[1],10))||za(0==T[2].length,0==fa[2].length)||za(T[2],fa[2])}while(0==c)}return c};
var za=function(a,b){return a<b?-1:a>b?1:0};m.Aa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ba=function(a){var b=m.ka(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,f){return b+f.toUpperCase()})};m.Ca=function(a,b,c){b=m.Da(a,b,c);return 0>b?null:m.ka(a)?a.charAt(b):a[b]};
m.Da=function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return g;return-1};m.Ea=function(a,b){return 0<=(0,m.Fa)(a,b)};m.Ga=function(a,b){var c=(0,m.Fa)(a,b),d;(d=0<=c)&&m.Ha(a,c);return d};m.Ha=function(a,b){m.Ia.splice.call(a,b,1)};m.Ja=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.Ka=function(a,b,c){return 2>=arguments.length?m.Ia.slice.call(a,b):m.Ia.slice.call(a,b,c)};
m.La=function(){this.Bb=this.Bb;this.Ba=this.Ba};m.Ma=function(a,b){m.Na(a,m.qa(m.Oa,b))};m.Na=function(a,b){a.Ba||(a.Ba=[]);a.Ba.push(m.ca(void 0)?(0,m.l)(b,void 0):b)};m.Oa=function(a){a&&"function"==typeof a.dispose&&a.dispose()};m.Qa=function(){m.La.call(this);this.Aa=[];this.Qb={}};m.Ra=function(a){Sa(m.Ta,arguments)};m.r=function(a,b){return a in m.Ta?m.Ta[a]:b};m.s=function(a,b){m.ma(a)&&(a=m.Ua(a));return window.setTimeout(a,b)};
m.Va=function(a,b){m.ma(a)&&(a=m.Ua(a));return window.setInterval(a,b)};m.Wa=function(a){window.clearTimeout(a)};m.Xa=function(a){window.clearInterval(a)};m.Ua=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.Ya(b),b;}}:a};m.Ya=function(a,b){var c=m.k("yt.www.errors.log");c?c(a,b):(c=m.r("ERRORS")||[],c.push([a,b]),m.Ra("ERRORS",c))};m.Za=function(a){Sa(m.$a,arguments)};m.ab=function(a){return a in m.$a};
m.bb=function(a,b,c){var d=b||{};if(a=a in m.$a?m.$a[a]:c)for(var f in d)a=a.replace(new RegExp("\\$"+f,"gi"),function(){return d[f]});return a};var Sa=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};m.u=function(a,b,c){var d=cb();if(d){var f=d.subscribe(a,function(){if(!m.db||m.db!=f){var d=arguments,n=function(){eb[f]&&b.apply(c||window,d)};try{fb[a]?n():m.s(n,0)}catch(q){m.Ya(q)}}},c);eb[f]=!0;gb[a]||(gb[a]=[]);gb[a].push(f);return f}return 0};
m.hb=function(a){var b=cb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.v)(a,function(a){b.unsubscribeByKey(a);delete eb[a]}))};m.w=function(a,b){var c=cb();return c?c.publish.apply(c,arguments):!1};m.ib=function(a,b){fb[a]=!0;var c=cb(),c=c?c.publish.apply(c,arguments):!1;fb[a]=!1;return c};var cb=function(){return m.k("yt.pubsub.instance_")};m.jb=function(a){if(a.classList)return a.classList;a=a.className;return m.ka(a)&&a.match(/\S+/g)||[]};
m.x=function(a,b){return a.classList?a.classList.contains(b):m.Ea(m.jb(a),b)};m.y=function(a,b){a.classList?a.classList.add(b):m.x(a,b)||(a.className+=0<a.className.length?" "+b:b)};m.kb=function(a,b){if(a.classList)(0,m.v)(b,function(b){m.y(a,b)});else{var c={};(0,m.v)(m.jb(a),function(a){c[a]=!0});(0,m.v)(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}};
m.A=function(a,b){a.classList?a.classList.remove(b):m.x(a,b)&&(a.className=(0,m.lb)(m.jb(a),function(a){return a!=b}).join(" "))};m.mb=function(a,b,c){c?m.y(a,b):m.A(a,b)};m.nb=function(a,b,c){return Math.min(Math.max(a,b),c)};m.ob=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.pb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.qb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.rb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
m.sb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<tb.length;g++)c=tb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.ub=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return m.ub.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var vb=function(){var a=m.da.document;return a?a.documentMode:void 0};m.wb=function(a){return xb[a]||(xb[a]=0<=m.xa(yb,a))};
m.zb=function(a){return m.B&&m.Ab>=a};m.C=function(a){return m.ka(a)?window.document.getElementById(a):a};m.Bb=function(a){var b=window.document;return m.ka(a)?b.getElementById(a):a};m.D=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.Cb("*",a,b)[0];return d||null};
m.Cb=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},f=0,g=0,n;n=c[g];g++)a==n.nodeName&&(d[f++]=n);d.length=f;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(g=f=0;n=c[g];g++)a=n.className,"function"==typeof a.split&&m.Ea(a.split(/\s+/),b)&&(d[f++]=n);d.length=f;return d}return c};
m.Db=function(a,b){m.ob(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Eb?a.setAttribute(Eb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.Fb=function(a,b,c){return m.Gb(window.document,arguments)};
m.Gb=function(a,b){var c=b[0],d=b[1];if(!kaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.va(d.name),'"');if(d.type){c.push(' type="',m.va(d.type),'"');var f={};m.sb(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ka(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.Db(c,d));2<b.length&&m.Hb(a,c,b,2);return c};
m.Hb=function(a,b,c,d){function f(c){c&&b.appendChild(m.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var g=c[d];!m.ja(g)||m.na(g)&&0<g.nodeType?f(g):(0,m.v)(laa(g)?m.Ja(g):g,f)}};m.Ib=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};var maa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var naa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.Jb=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var laa=function(a){if(a&&"number"==typeof a.length){if(m.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.ma(a))return"function"==typeof a.item}return!1};m.Kb=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var f=0;a&&(c||f<=d);){if(b(a))return a;a=a.parentNode;f++}return null};
m.Lb=function(a){return function(){return a}};m.Mb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.Nb=function(){};m.Ob=function(a){if(a instanceof m.Nb)return a;if("function"==typeof a.gb)return a.gb(!1);if(m.ja(a)){var b=0,c=new m.Nb;c.next=function(){for(;;){if(b>=a.length)throw m.Pb;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.Qb=function(a,b,c){if(m.ja(a))try{(0,m.v)(a,b,c)}catch(d){if(d!==m.Pb)throw d;}else{a=m.Ob(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(f){if(f!==m.Pb)throw f;}}};m.Rb=function(a){if(m.ja(a))return m.Ja(a);a=m.Ob(a);var b=[];m.Qb(a,function(a){b.push(a)});return b};m.Sb=function(a,b,c,d,f,g,n){var q="";a&&(q+=a+":");c&&(q+="//",b&&(q+=b+"@"),q+=c,d&&(q+=":"+d));f&&(q+=f);g&&(q+="?"+g);n&&(q+="#"+n);return q};
m.Tb=function(a){if(Ub){Ub=!1;var b=m.da.location;if(b){var c=b.href;if(c&&(c=m.Vb(c))&&c!=b.hostname)throw Ub=!0,Error();}}return a.match(oaa)};m.Wb=function(a){return a?(0,window.decodeURI)(a):a};m.Vb=function(a){return m.Wb(m.Tb(a)[3]||null)};m.Xb=function(a){a=m.Tb(a);return m.Sb(null,null,null,null,a[5],a[6],a[7])};m.Yb=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.Zb=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.Zb(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.ta(b))};var $b=function(a,b){for(var c in b)m.Zb(c,b[c],a);return a};m.bc=function(a){a=$b([],a);a[0]="";return a.join("")};m.cc=function(a,b){return m.Yb($b([a],b))};m.dc=function(a,b,c){a&&(c?a&&(a=m.Fb("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.Jb(a).body.appendChild(a)):paa(a,b))};
var paa=function(a,b){var c=new window.Image,d=""+qaa++;ec[d]=c;c.onload=c.onerror=function(){b&&ec[d]&&b();delete ec[d]};c.src=a;c=eval("null")};m.fc=function(a,b,c){gc(c)[a]=b||(0,m.E)();b||hc(a)};var ic=function(a,b){jc(void 0).yt_sts=a;m.fc("_start",b,void 0)};var kc=function(a,b,c){var d=lc(c).span;c=gc(c);"number"==typeof b?d[a]=b:b in c&&(d[a]=(0,m.E)()-c[b])};
var mc=function(a){var b=gc(a),c=lc(a).span,d=jc(a),f=m.k("yt.timing.reportbuilder_");if(f){if(f=f(b,c,d,a))nc(f),oc(a),pc();return window.NaN}f={v:2,s:"youtube",action:m.r("TIMING_ACTION")};if(qc.now&&qc.timing){var g=qc.timing.navigationStart+qc.now(),g=Math.round((0,m.E)()-g);d.yt_hrd=g}var g=m.r("TIMING_INFO")||{},n;for(n in g)d[n]=g[n];n=d.srt;delete d.srt;var q;n||0===n||(q=qc.timing||{},n=Math.max(0,q.responseStart-q.navigationStart),(0,window.isNaN)(n)&&d.pt&&(n=d.pt));if(n||0===n)d.srt=n;
d.h5jse&&(g=window.location.protocol+m.k("ytplayer.config.assets.js"),(g=qc.getEntriesByName?qc.getEntriesByName(g)[0]:null)?d.h5jse=Math.round(d.h5jse-g.responseEnd):delete d.h5jse);g=!1;b.aft||(b.pbr&&b.pbs>b.pbr?(b.aft=b.pbr,g=!0):b.pbs?(b.aft=b.pbs,g=!0):b.vr?(b.aft=b.vr,g=!0):b.aft=b.ol);b.gv&&g&&(c.vl=Math.round(b.aft-b.gv));g=b._start;if(!rc){q||(q=qc.timing||{});var t;e:if(t=q,t.msFirstPaint)t=Math.max(0,t.msFirstPaint);else{var z=window.chrome;if(z&&(z=z.loadTimes,m.ma(z))){var z=z(),G=1E3*
Math.min(z.requestTime||window.Infinity,z.startLoadTime||window.Infinity),G=window.Infinity===G?0:t.navigationStart-G;t=Math.max(0,Math.round(1E3*z.firstPaintTime+G)||0);break e}t=0}0<t&&t>g&&(b.fpt=t);t=q.redirectEnd-q.redirectStart;0<t&&(c.rtime_=t);t=q.domainLookupEnd-q.domainLookupStart;0<t&&(c.dns_=t);t=q.connectEnd-q.connectStart;0<t&&(c.tcp_=t);t=q.connectEnd-q.secureConnectionStart;q.secureConnectionStart&&0<t&&(c.stcp_=t);t=q.responseStart-q.requestStart;0<t&&(c.req_=t);t=q.responseEnd-q.responseStart;
0<t&&(c.rcv_=t);rc=!0}for(var T in d)"_"!=T.charAt(0)&&(f[T]=d[T]);d={};T=[];for(var fa in b)"_"!=fa.charAt(0)&&(t=Math.max(Math.round(b[fa]-g),0),d[fa]=t,T.push(fa+"."+t));f.rt=T.join(",");b={};fa=[];for(var ua in c)"_"!=ua.charAt(0)&&(b[ua]=c[ua],fa.push(ua+"."+c[ua]));f.it=fa.join(",");(c=m.k("ytdebug.logTiming"))&&c(f,d,b);oc(a);pc();m.r("EXP_DEFER_CSI_PING")?(sc(),tc=f,uc=m.s(sc,0)):nc(f);return d.aft+(n||0)};
var vc=function(a,b){var c=m.r("TIMING_ACTION"),d=gc(b);if(c&&d._start)if(c=m.r("TIMING_WAIT",[]),!a&&c.length){for(var f=!0,g=0,n=c.length;g<n;++g)if(!(c[g]in d)){f=!1;break}if(f)return mc(b)}else if(d.ol||d.aft)return mc(b);return window.NaN};var wc=function(a){if(m.r("TIMING_WAIT"))a=vc(!1,a);else e:{var b=m.r("TIMING_ACTION"),c=!!m.r("TIMING_WFF"),d=gc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=mc(a);break e}a&&mc(a)}a=window.NaN}return a};
var nc=function(a){m.r("EXP_DEFER_CSI_PING")&&(m.Wa(uc),tc=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.dc(b+"?"+c.substring(1))};var sc=function(a){tc&&(a&&(tc.yt_fss=a),nc(tc))};var gc=function(a){return lc(a).tick};var jc=function(a){return lc(a).info};var lc=function(a){return m.k("ytcsi."+(a||"")+"data_")||oc(a)};
var oc=function(a){var b={tick:{},span:{},info:{}};m.h("ytcsi."+(a||"")+"data_",b,void 0);return b};m.xc=function(){return!!m.k("yt.scheduler.instance")};m.yc=function(){return m.xc()&&m.x(window.document.body,"exp-js-scheduler-more")};m.zc=function(a,b){void 0===b&&(b=window.NaN);var c=m.k("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.s(a,b||0)};m.Ac=function(a,b){return m.zc(a,b)};
m.Bc=function(a){var b=m.k("yt.scheduler.instance.cancelJob");b?b(a):m.Wa(a)};m.Cc=function(a){for(var b=0,c=a.length;b<c;b++)m.Bc(a[b])};m.Dc=function(a,b,c,d,f){this.name=a;this.deps=b||[];this.page=c||"";this.F=d?m.Ua(d):null;this.C=f?m.Ua(f):null;this.Aa=[];this.k=this.B=0};m.Ec=function(a){m.yc()?(m.Bc(a.B),a.B=m.Ac((0,m.l)(a.init,a))):a.init()};
m.Fc=function(a){a.name in Gc&&Hc(a.name);Gc[a.name]={reqs:[],disable:(0,m.l)(a.disable,a)};(0,m.v)(a.deps,function(b){if(!(b in Gc))throw Error("Module "+b+" required by "+a.name);Gc[b].reqs.push(a.name)});a.enable()};var Hc=function(a){if(a in Gc){var b=Gc[a];(0,m.v)(b.reqs,function(a){Hc(a)});try{b.disable()}catch(c){}delete Gc[a]}};m.Ic=function(a){return a&&"readyState"in a?a.readyState:0};
var raa=function(){if(m.r("SCHEDULE_AJAX")&&window.XMLHttpRequest&&!Jc){Kc=m.r("SCHEDULER_BUFFER_LENGTH");var a=window.XMLHttpRequest;Lc=a.prototype.abort;Mc=a.prototype.open;Jc=a.prototype.send;a.prototype.abort=saa;a.prototype.open=taa;a.prototype.send=uaa}};var saa=function(){Nc(!0);Lc.call(this)};var taa=function(){this.url=arguments[1];Mc.apply(this,arguments)};
var uaa=function(){var a=this,b=arguments;if(a.url&&a.url.match(vaa))Jc.apply(a,b);else{if("onloadend"in a)a.addEventListener("loadend",function(){4==m.Ic(a)&&Nc(!0)},!1);else{var c=a.onreadystatechange;a.onreadystatechange=function(){4==m.Ic(a)&&Nc(!0);c&&c.apply(this,arguments)}}Oc.push(function(){Jc.apply(a,b)});Nc()}};var Nc=function(a){a&&(Pc=!1,m.Wa(Qc));if(!Pc&&Oc.length)if(Kc&&!waa())m.Wa(Rc),Rc=m.s(Nc,100);else{Pc=!0;a=Oc.shift();try{a()}catch(b){Nc(!0)}Qc=m.s(m.qa(Nc,!0),5E3)}};
var waa=function(){var a=Kc,b=m.k("yt.player.getPlayerByElement");if(!b)return!0;var b=b("player-api"),c=m.r("ADS_DATA");return b&&(!c||!c.show_instream)&&b.getVideoLoadedFraction&&b.getDuration&&b.getCurrentTime&&b.getPlayerState?(c=b.getVideoLoadedFraction()*b.getDuration()-b.getCurrentTime(),0>=b.getPlayerState()||c>a||.3<b.getVideoLoadedFraction()):!0};m.F=function(a,b){return a?a.dataset?a.dataset[m.Sc(b)]:a.getAttribute("data-"+b):null};
m.Tc=function(a,b){return a?a.dataset?m.Sc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.Sc=function(a){return Uc[a]||(Uc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.Vc=function(a,b){var c=m.Wc(a);window.spf.script.load(a,c,b)};m.Xc=function(a,b){var c=m.Wc(a);window.spf.script.ignore(c,b)};m.Yc=function(a){a&&(m.ka(a)?m.Vc(a):m.ia(a)?(0,m.v)(a,function(a){m.Yc(a)}):m.ob(a,function(a,c){m.Vc(c,function(){m.Yc(a)})}))};
m.Wc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),f=c+6;-1<c&&-1<d&&d>f&&(b=a.substring(f,d),b=b.replace(xaa,""),b=b.replace(yaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var zaa=function(a){a=(0,m.Zc)(a);a=null===a?null:a.split(".").reverse();return(null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
m.$c=function(a,b){m.dc("/gen_204?"+a,b)};var ad=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.rb(Aaa);this.assets=a.assets||{};this.attrs=a.attrs||m.rb(Baa);this.params=a.params||m.rb(Caa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
m.bd=function(a){a instanceof ad||(a=new ad(a));return a};m.cd=function(a){this.j=a};m.dd=function(a){a=(a.j.cookie||"").split(m.ed);for(var b=[],c=[],d,f,g=0;f=a[g];g++)d=f.indexOf("="),-1==d?(b.push(""),c.push(f)):(b.push(f.substring(0,d)),c.push(f.substring(d+1)));return{keys:b,values:c}};m.fd=function(a,b,c){m.gd.set(""+a,b,c,"/","youtube.com")};m.hd=function(a,b){return m.gd.get(""+a,b)};var id=function(){return null!=m.jd};var kd=function(){return m.jd?m.jd.invoke():null};
m.ld=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.v)(a.childNodes,function(a){b.appendChild(m.ld(a))}):b.innerHTML=a.innerHTML;return b};
m.md=function(a){if(a=a||window.event){for(var b in a)b in Daa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.xa=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.zk=a.pageX;this.Ak=a.pageY}};m.nd=function(a,b,c,d){return m.qb(m.od,function(f){return f[0]==a&&f[1]==b&&f[2]==c&&f[4]==!!d})};
m.H=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var f=m.nd(a,b,c,d);if(f)return f;var f=++pd.count+"",g=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),n;n=g?function(d){d=new m.md(d);if(!m.Kb(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.md(b);b.currentTarget=a;return c.call(a,b)};n=m.Ua(n);m.od[f]=[a,b,c,n,d];a.addEventListener?"mouseenter"==b&&g?a.addEventListener("mouseover",
n,d):"mouseleave"==b&&g?a.addEventListener("mouseout",n,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",n,d):a.addEventListener(b,n,d):a.attachEvent("on"+b,n);return f};m.I=function(a){a&&("string"==typeof a&&(a=[a]),(0,m.v)(a,function(a){if(a in m.od){var c=m.od[a],d=c[0],f=c[1],g=c[3],c=c[4];d.removeEventListener?d.removeEventListener(f,g,c):d.detachEvent&&d.detachEvent("on"+f,g);delete m.od[a]}}))};
m.qd=function(a,b){a=!!a;m.h("_lactCookie",a,window);if(null==m.k("_lact",window)){if(a&&b){var c=m.hd("ACTIVITY","-1");m.h("_lact",(0,window.parseInt)(c,10),window)}else m.h("_lact",-1,window),rd();m.H(window.document,"keypress",rd);m.H(window.document,"mousedown",rd);m.H(window.document,"mouseup",rd)}};var rd=function(){var a=m.k("_lact",window);null==a&&(m.qd(),a=m.k("_lact",window));var b=(0,m.E)();m.h("_lact",b,window);m.k("_lactCookie",window)&&1E3<=b-a&&m.fd("ACTIVITY",""+b)};
m.sd=function(){var a=m.k("_lact",window);return null==a?-1:Math.max((0,m.E)()-a,0)};m.td=function(a,b,c){var d=m.Vb(a);if(d==m.Vb(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.Xb(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&ud(a,b,c)):ud(a,b)};var ud=function(a,b,c){for(var d=0,f=0;f<a.length;++f)d=31*d+a.charCodeAt(f),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.bc(b):"";m.fd(a,b,c)};
m.vd=function(a,b,c){c=c||"";window.location=m.cc(a,b||{})+c};m.wd=function(a,b){var c=window.ytspf||{};b&&m.td(a,b);c.enabled?window.spf.navigate(a):m.vd(a)};m.xd=function(a,b,c){var d=m.r("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.td(a,b);if(c)return!1;m.wd(a);return!0};var yd=function(a){m.da.setTimeout(function(){throw a;},0)};
var Eaa=function(){var a=m.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.l)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!m.wa(m.zd,"Trident")&&!m.wa(m.zd,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.ca(c.next)){c=c.next;var a=c.Mp;c.Mp=null;a()}};return function(a){d.next={Mp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.da.setTimeout(a,0)}};var Ad=function(a,b){Bd||Faa();Cd||(Bd(),Cd=!0);Dd.push(new Gaa(a,b))};
var Faa=function(){if(m.da.Promise&&m.da.Promise.resolve){var a=m.da.Promise.resolve();Bd=function(){a.then(Ed)}}else Bd=function(){var a=Ed;!m.ma(m.da.setImmediate)||m.da.Window&&m.da.Window.prototype.setImmediate==m.da.setImmediate?(Fd||(Fd=Eaa()),Fd(a)):m.da.setImmediate(a)}};var Ed=function(){for(;Dd.length;){var a=Dd;Dd=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.ue.call(c.scope)}catch(d){yd(d)}}}Cd=!1};var Gaa=function(a,b){this.ue=a;this.scope=b};
m.Gd=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.Hd=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.Id=function(a,b){this.k=0;this.G=void 0;this.j=this.B=null;this.C=this.F=!1;try{var c=this;a.call(b,function(a){Jd(c,2,a)},function(a){Jd(c,3,a)})}catch(d){Jd(this,3,d)}};m.Kd=function(a){return new m.Id(function(b){b(a)})};
var Ld=function(a,b){if(0==a.k)if(a.B){var c=a.B;if(c.j){for(var d=0,f=-1,g=0,n;n=c.j[g];g++)if(n=n.If)if(d++,n==a&&(f=g),0<=f&&1<d)break;0<=f&&(0==c.k&&1==d?Ld(c,b):(d=c.j.splice(f,1)[0],Md(c,d,3,b)))}}else Jd(a,3,b)};var Haa=function(a,b){a.j&&a.j.length||2!=a.k&&3!=a.k||Nd(a);a.j||(a.j=[]);a.j.push(b)};
m.Od=function(a,b,c,d){var f={If:null,Nn:null,On:null};f.If=new m.Id(function(a,n){f.Nn=b?function(c){try{var f=b.call(d,c);a(f)}catch(z){n(z)}}:a;f.On=c?function(b){try{var f=c.call(d,b);!m.ca(f)&&b instanceof Pd?n(b):a(f)}catch(z){n(z)}}:n});f.If.B=a;Haa(a,f);return f.If};
var Jd=function(a,b,c){if(0==a.k){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.Hd(c)){a.k=1;c.then(a.H,a.L,a);return}if(m.na(c))try{var d=c.then;if(m.ma(d)){Iaa(a,c,d);return}}catch(f){b=3,c=f}}a.G=c;a.k=b;Nd(a);3!=b||c instanceof Pd||Jaa(a,c)}};var Iaa=function(a,b,c){function d(b){g||(g=!0,a.L(b))}function f(b){g||(g=!0,a.H(b))}a.k=1;var g=!1;try{c.call(b,f,d)}catch(n){d(n)}};var Nd=function(a){a.F||(a.F=!0,Ad(a.K,a))};
var Md=function(a,b,c,d){if(2==c)b.Nn(d);else{if(b.If)for(;a&&a.C;a=a.B)a.C=!1;b.On(d)}};var Jaa=function(a,b){a.C=!0;Ad(function(){a.C&&Kaa.call(null,b)})};var Pd=function(a){m.sa.call(this,a)};var Qd=function(a){this.B=a;this.k=null;var b=this;a.then(function(a){b.k=a})};
var Rd=function(a,b){var c=b||{},d=Laa().then(function(b){return b(a,{apiKey:c.of||c.apiKey,environment:c.pf||c.environment,helpCenterPath:c.EB||c.helpCenterPath,locale:c.locale||c.locale,productData:c.FB||c.productData,receiverUri:c.GB||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new Qd(d)};
var Laa=function(){if(Sd)return Sd;var a=m.k("help.service.Lazy.create");return a?Sd=m.Kd(a):Sd=(new m.Id(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.k("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var Td=function(a,b,c){a.B.then(function(a){a[b].apply(a,c)})};var Ud=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Vd=function(a){return(a=a.exec(m.zd))?a[1]:""};
var Wd=function(){this.B=this.k=this.j=0;this.C="";var a=m.k("window.navigator.plugins"),b=m.k("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",f=0,g=c.length;f<g;f++)if(d)if(a)break;else a=c[f];else d=c[f];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;f=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))f=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,f]}else a=[0,0,0];this.C=b;b=a;this.j=b[0];this.k=b[1];this.B=b[2];if(0>=this.j){var n,q,t,z;if(m.Xd)try{n=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(G){n=null}else t=window.document.body,z=window.document.createElement("object"),z.setAttribute("type","application/x-shockwave-flash"),n=t.appendChild(z);if(n&&"GetVariable"in n)try{q=n.GetVariable("$version")}catch(T){q=""}t&&z&&t.removeChild(z);(n=q||"")?(n=n.split(" ")[1].split(","),
n=[(0,window.parseInt)(n[0],10)||0,(0,window.parseInt)(n[1],10)||0,(0,window.parseInt)(n[2],10)||0]):n=[0,0,0];this.j=n[0];this.k=n[1];this.B=n[2]}};var Yd=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.B>=b[2]};
var Zd=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.B?!1:9<=a.j};var Maa=function(a){return m.$d?!Yd(a,11,2):m.ae?!Yd(a,11,3):!Zd(a)};m.be=function(){return m.ce?"Webkit":m.de?"Moz":m.B?"ms":m.ee?"O":null};m.fe=function(){return m.ce?"-webkit":m.de?"-moz":m.B?"-ms":m.ee?"-o":null};m.ge=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.he=function(a,b){return a&&b?b instanceof m.ge?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.ie=function(a,b){var c=m.Aa(b);if(void 0===a.style[c]){var d=m.be()+m.Ba(c);if(void 0!==a.style[d])return d}return c};m.je=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.ke=function(a,b){a.style.display=b?"":"none"};m.le=function(){this.j="";this.k=me};
var ne=function(a){return a instanceof m.le&&a.constructor===m.le&&a.k===me?a.j:"type_error:Const"};var oe=function(){this.j="";this.k=pe};var qe=function(a){var b=new oe;b.j=a;return b};var re=function(){this.j=se};var te=function(){this.j="";this.B=ue;this.k=null};m.ve=function(a){return a instanceof te&&a.constructor===te&&a.B===ue?a.j:"type_error:SafeHtml"};
m.we=function(a,b){if(!xe.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in Naa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var f in b){if(!xe.test(f))throw Error('Invalid attribute name "'+f+'".');var g=b[f];if(null!=g){if(g instanceof m.le)g=ne(g);else if("style"==f.toLowerCase()){if(!m.na(g))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof g+" given: "+g);if(!(g instanceof oe)){var n=
"",q=void 0;for(q in g){if(!/^[-_a-zA-Z0-9]+$/.test(q))throw Error("Name allows only [-_a-zA-Z0-9], got: "+q);var t=g[q];null!=t&&(t instanceof m.le?t=ne(t):Oaa.test(t)||(t="zClosurez"),n+=q+":"+t+";")}g=n?qe(n):Paa}g=g instanceof oe&&g.constructor===oe&&g.k===pe?g.j:"type_error:SafeStyle"}else{if(/^on/i.test(f))throw Error('Attribute "'+f+'" requires goog.string.Const value, "'+g+'" given.');if(g instanceof re)g=g instanceof re&&g.constructor===re&&g.j===se?"":"type_error:SafeUrl";else if(f.toLowerCase()in
Qaa)throw Error('Attribute "'+f+'" requires goog.string.Const or goog.html.SafeUrl value, "'+g+'" given.');}d+=" "+f+'="'+m.va(String(g))+'"'}}f=void 0;m.ca(f)?m.ia(f)||(f=[f]):f=[];!0===Raa[a.toLowerCase()]?d+=">":(c=Saa(f),d+=">"+m.ve(c)+"</"+a+">",c=c.uh());(f=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(f)?c=0:c=null);return ye(d,c)};
var Saa=function(a){function b(a){if(m.ia(a))(0,m.v)(a,b);else{if(!(a instanceof te)){var g=null;a.fp&&(g=a.uh());a=ye(m.va(a.ri?a.qi():String(a)),g)}d+=m.ve(a);a=a.uh();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.v)(arguments,b);return ye(d,c)};var ye=function(a,b){var c=new te;c.j=a;c.k=b;return c};m.ze=function(a,b){(a=m.C(a))&&a.style&&(m.ke(a,b),m.mb(a,"hid",!b))};m.J=function(a){(0,m.v)(arguments,function(a){m.ze(a,!0)})};
var Ae=function(a){var b=m.r("FEEDBACK_LOCALE_LANGUAGE"),c=m.Be,d=m.r("FEEDBACK_LOCALE_EXTRAS",{});a?m.sb(c,a):m.sb(c,d);try{var f,g=m.k("yt.player.getPlayerByElement");(f=g?g("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var n=Wd.getInstance();c.flashVersion=n.getVersion().join(".");f&&(c.playback_id=f.getVideoData().cpn)}catch(q){}return{helpCenterPath:"/youtube",locale:b,productData:c}};
var Ce=function(){var a=m.r("SESSION_INDEX"),b=m.r("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.De=function(a,b){try{var c=(a||"59")+"",d=Ae(b),f=Ce();Rd(c,d).C(f);return!1}catch(g){return!0}};
m.Ee=function(a,b,c,d,f,g,n,q){b=(b||"59")+"";d=Ae(d);a={context:c,anchor:a,enableSendFeedback:g?!1:!0,trackingParam:n,defaultHelpArticleId:q};m.sb(a,Ce());try{var t=Rd(b,d);if(f&&!Fe)try{t.j(a),Fe=!0}catch(z){}t.F(a);return!1}catch(G){return!0}};m.Ge=function(a,b,c,d){return m.Ee(void 0,d,b,c,void 0,void 0,void 0,a)};m.He=function(){var a=m.hd("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Ie[d]=c.toString())}};
var Je=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var Ke=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Le=function(a){a=void 0!==m.Ie[a]?m.Ie[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Me=function(a,b){return!!((m.Le("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Ne=function(a,b,c){if(b){a=m.ka(a)?m.Bb(a):a;c=m.bd(c);var d=m.rb(c.attrs);d.tabindex=0;var f=m.rb(c.params);f.flashvars=m.bc(c.args);if(m.Xd){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";f.movie=b;b=window.document.createElement("object");for(var g in d)b.setAttribute(g,d[g]);for(g in f)d=window.document.createElement("param"),d.setAttribute("name",g),d.setAttribute("value",f[g]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(g in d)b.setAttribute(g,d[g]);for(g in f)b.setAttribute(g,f[g])}f=window.document.createElement("div");f.appendChild(b);a.innerHTML=f.innerHTML}};m.Oe=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Pe();Yd(c,b.minVersion)?(c=Qe(b,c),Ne(a,c,b)):Re(a,b,c)};
var Se=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.bd(a);var d=!!b,f=m.C(a.attrs.id),g=f?f.parentNode:null;if(f&&g){if(window!=window.top){var n=null;if(window.document.referrer){var q=window.document.referrer.substring(0,128);zaa(q)||(n=q)}else n="unknown";n&&(d=!0,a.args.framer=n)}n=Pe();if(Yd(n,a.minVersion)){var q=Qe(a,n),t="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(t=f.getAttribute("src")||f.movie);(t!=q||d)&&Ne(g,q,a);Maa(n)&&Taa()}else Re(g,a,n);c&&c()}else m.s(function(){Se(a,
b,c)},50)}};var Re=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.bb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var Qe=function(a,b){var c;(c=Zd(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Yd(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Pe=function(){var a=Wd.getInstance(),b=m.He.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Taa=function(){var a=m.C("flash10-promo-div"),b=m.Me(m.He.getInstance(),107);a&&!b&&m.J(a)};m.Ue=function(a,b){var c=a.match(Uaa);window.spf.style.load(a,c?c[1]:"",b)};
var Vaa=function(){if(2.2==Ve)return!0;var a;a=m.k("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.h("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Waa=function(){};m.We=function(){};m.Xe=function(a){this.j=a};m.Ye=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};
var Ze=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};m.$e=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.af=function(a){return m.bf(new m.cf(void 0),a)};
m.cf=function(a){this.j=a};m.bf=function(a,b){var c=[];df(a,b,c);return c.join("")};
var df=function(a,b,c){switch(typeof b){case "string":ef(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var f="",g=0;g<d;g++)c.push(f),f=b[g],df(a,a.j?a.j.call(b,String(g),f):f,c),f=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=b[g],"function"!=typeof f&&
(c.push(d),ef(g,c),c.push(":"),df(a,a.j?a.j.call(b,g,f):f,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var ef=function(a,b){b.push('"',a.replace(Xaa,function(a){if(a in ff)return ff[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return ff[a]=f+b.toString(16)}),'"')};m.gf=function(a){this.j=a};var hf=function(a){this.j=a};var jf=function(a){this.data=a};var kf=function(a){return!m.ca(a)||a instanceof jf?a:new jf(a)};
var lf=function(a){this.j=a};m.mf=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.E)()||!!b&&b>(0,m.E)()};m.nf=function(a){this.j=a};m.of=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.E)()+1E3*d:0;if((d=d?m.pf:m.qf)&&window.JSON){m.ka(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(f){d.remove(a)}}};m.rf=function(a){if(!m.qf&&!m.pf||!window.JSON)return null;var b;try{b=m.qf.get(a)}catch(c){}if(!m.ka(b))try{b=m.pf.get(a)}catch(d){}if(!m.ka(b))return null;try{b=JSON.parse(b,void 0)}catch(f){}return b};
var sf=function(){var a={volume:100,muted:!1},b=m.rf("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.nb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var tf=function(a,b){m.La.call(this);this.B=this.vf=a;this.K=b;this.G=!1;this.j={};this.U=this.L=null;this.T=new m.Qa;m.Ma(this,this.T);this.C={};this.F=this.W=this.k=this.ma=this.da=null;this.P=!1;this.ea=this.H=null;this.Y={};this.Ka=["onReady"];this.Da=null;this.Ea=0;this.pa=!!m.r("PLAYER_PERSISTENCE_REFACTOR");uf(this);this.xe("onVolumeChange",(0,m.l)(this.Yp,this));this.xe("onError",(0,m.l)(this.Xp,this));this.xe("onTabOrderChange",(0,m.l)(this.Wp,this));this.xe("WATCH_LATER_VIDEO_ADDED",(0,m.l)(this.Zp,
this));this.xe("WATCH_LATER_VIDEO_REMOVED",(0,m.l)(this.$p,this))};
var vf=function(a,b){a.ma=b;a.da=b.clone();a.k=a.da.attrs.id||a.k;"video-player"==a.k&&(a.k=a.K,a.da.attrs.id=a.K);a.B.id==a.k&&(a.k=a.k+"-player",a.da.attrs.id=a.k);var c=a.da.args,d;if(!(d=a.da.args.eurl)){d=window.document.location.toString();var f=!!d&&-1!=d.search(Yaa),g=-1!=d.indexOf("/embed/");f!=g&&m.Ya(Error(d+" behavior is not consistent"));d=g?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d}c.eurl=d;a.da.args.enablejsapi="1";a.da.args.playerapiid=a.K;a.W||
(a.W=wf(a,a.da.args.jsapicallback||"onYouTubePlayerReady"));a.da.args.jsapicallback=null;if(c=a.da.attrs.width)a.B.style.width=m.je(Number(c)||c,!0);if(c=a.da.attrs.height)a.B.style.height=m.je(Number(c)||c,!0);a.B.style.overflow="hidden"};var xf=function(a){a.da.loaded||(a.da.loaded=!0,"0"!=a.da.args.autoplay?a.j.loadVideoByPlayerVars(a.da.args):a.j.cueVideoByPlayerVars(a.da.args))};var yf=function(a){if(!m.ca(a.da.disable.flash)){var b=a.da.disable,c;c=Yd(Pe(),a.da.minVersion);b.flash=!c}return!a.da.disable.flash};
var zf=function(a){var b=Af(a);b&&b.stopVideo&&b.stopVideo();if(yf(a)){var c=a.da;b&&b.getUpdatedConfigurationData&&(b=m.bd(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";vf(a,c);Bf(a,"flash")}};
var Bf=function(a,b){if(!a.ha()){if(!b){var c;if(!(c=!a.da.html5&&yf(a))){if(!m.ca(a.da.disable.html5)){if(c=Vaa())c=Cf(a)||a.da.assets.js;a.da.disable.html5=!c;c||(a.da.args.html5_unavailable="1")}c=!!a.da.disable.html5}b=c?yf(a)?"flash":"unsupported":"html5"}("flash"==b?a.py:"html5"==b?a.qy:a.ry).call(a)}};var Cf=function(a){var b=!0;if(a.pa){var c=Af(a);c&&a.da&&(a=a.da,b=m.F(c,"version")==a.assets.js)}return b&&!!m.k("yt.player.Application.create")};
var Af=function(a){var b=m.C(a.k);!b&&a.B&&a.B.querySelector&&(b=a.B.querySelector("#"+a.k));return b};var Df=function(a,b,c){var d=b[c];return function(){try{return a.Da=null,d.apply(b,arguments)}catch(f){"Bad NPObject as private data!"!=f.message&&(f.message+=" ("+c+")",a.Da=f,m.Ya(f,"WARNING"))}}};
var uf=function(a){a.G=!1;if(a.U)for(var b in a.C)a.U(b,a.C[b]);a.L=null;a.U=null;for(var c in a.j)a.j[c]=null;a.j.addEventListener=(0,m.l)(a.xe,a);a.j.removeEventListener=(0,m.l)(a.Mt,a);a.j.destroy=(0,m.l)(a.dispose,a);a.j.getLastError=(0,m.l)(a.Kt,a);a.j.getPlayerType=(0,m.l)(a.Lt,a);a.j.getCurrentVideoConfig=(0,m.l)(a.Jt,a);a.j.loadNewVideoConfig=(0,m.l)(a.uj,a);a.j.isReady=(0,m.l)(a.Nt,a)};
var wf=function(a,b){var c=b;if("string"==typeof b){if(a.Y[b])return a.Y[b];c=function(){var a=m.k(b);a&&a.apply(m.da,arguments)};a.Y[b]=c}return c?c:null};var Zaa=function(a,b){var c="ytPlayer"+b+a.K;a.C[b]=c;m.da[c]=function(c){m.s(function(){a.ha()||a.T.publish(b,c)},0)};return c};var Ef=function(a){return(a=Af(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Ff=function(a){m.fc("dcp");a.cancel();uf(a);a.F=null;a.da&&(a.da.loaded=!1);var b=Af(a);"html5"==Ef(a)?a.ea=b:b&&b.destroy&&b.destroy();m.Ib(a.vf)};m.Gf=function(a,b){a=m.ka(a)?m.Bb(a):a;b=m.bd(b);var c=Hf+"_"+m.oa(a),d=If[c];if(d)return d.uj(b),d.j;d=new tf(a,c);If[c]=d;m.w("player-added",d.j);m.Na(d,m.qa($aa,d));m.s(function(){d.uj(b)},0);return d.j};var Jf=function(){for(var a in If){var b=If[a];b&&b.cancel()}};m.Kf=function(a){if(a=m.C(a))a=Hf+"_"+m.oa(a),(a=If[a])&&a.dispose()};
var $aa=function(a){If[a.getId()]=null};m.Lf=function(a){a=m.C(a);if(!a)return null;var b=Hf+"_"+m.oa(a),c=If[b];c||(c=new tf(a,b),If[b]=c);return c.j};
var aba=function(){m.h("yt.abuse.botguardInitialized",id,void 0);m.h("yt.abuse.invokeBotguard",kd,void 0);m.h("yt.player.exports.navigate",m.xd,void 0);m.h("yt.player.embed",m.Gf,void 0);m.h("yt.player.destroy",m.Kf,void 0);m.h("yt.player.cancelAll",Jf,void 0);m.h("yt.player.getPlayerByElement",m.Lf,void 0);m.h("yt.player.exports.feedbackStart",m.De,void 0);m.h("yt.player.exports.feedbackShowArticle",m.Ge,void 0);m.h("yt.util.activity.init",m.qd,void 0);m.h("yt.util.activity.getTimeSinceActive",m.sd,
void 0);m.h("yt.util.activity.setTimestamp",rd,void 0);Mf=Mf||!!m.r("PLAYER_WATCH_WHILE")||!!m.hd("watch_while");var a=m.k("ytplayer.config");Nf(a);m.k("ytspf.enabled")&&(Of=m.Va(Pf,5E3),(a=m.Qf())?(a.addEventListener("onReady",Pf),a.addEventListener("onStateChange",Pf),Mf&&(a.addEventListener("onReady",Rf),a.addEventListener("onStateChange",Rf))):Sf("unable to init PP monitor"))};
var Nf=function(a){Jf();if(a=a||null){var b=m.Qf(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(Tf="",m.Gf("player-api",a)):b.playVideo();a=m.bd(a);a.loaded=!0}Rf();Pf();m.h("ytplayer.config",a,void 0)};m.Qf=function(){var a=m.k("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Pf=function(){var a=m.C("player"),b=m.Qf();if(a&&b){var a=a&&m.x(a,"off-screen"),b=1==(b&&b.isReady()?b.getPlayerState():void 0),c="watch"==m.r("PAGE_NAME");Uf&&!Mf&&b&&Sf("minimized PP playing");a&&c?Sf("PP off-screen on watch"):Mf||a||c||Sf("PP !off-screen off watch")}};var Rf=function(){if(Mf){var a="watch"==m.r("PAGE_NAME"),b=m.Qf();1==(b&&b.isReady()?b.getPlayerState():void 0)?Vf(!0):a&&Vf(!1);Wf()}};
var Wf=function(){var a=m.C("player"),b=m.C("player-mole-container");Uf=!a||m.x(a,"off-screen")||!b||m.x(b,"watch-mole");(a=m.Qf())&&a.isReady()&&a.setMinimized(Uf)};var Sf=function(a){var b=m.r("PAGE_NAME");b&&(b=[b,Tf,m.k("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.h("yt.www.persistentplayer.issue",a,void 0),m.Ya(Error(a),"WARNING"))};var Vf=function(a){m.mb(m.C("player-mole-container"),"video-mole",a);Wf()};
var Xf=function(){m.fc("ol");Yf("init");var a=m.r("PAGE_NAME");a&&Yf("init-"+a);wc()};var Yf=function(a){m.xc()?Zf.push(m.zc(m.qa(m.ib,a),0)):m.w(a)};var $f=function(){m.Cc(Zf);Zf.length=0;var a=m.r("PAGE_NAME");a&&m.ib("dispose-"+a);m.ib("dispose")};var bba=function(){Xf()};var cba=function(){m.r("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.r("EXP_DEFER_CSI_PING")&&sc("u");$f()};
var dba=function(a,b,c,d,f){for(var g=window.document.getElementsByTagName("script"),n=!1,q=0,t=g.length;q<t;q++)if(0<g[q].src.indexOf("/debug-")){n=!0;break}n&&(f||(f=Error(),f.message=a,f.fileName=b,f.lineNumber=c,(0,window.isNaN)(d)||(f.columnNumber=d)),m.Ya(f))};var ag=function(){bg=1;cg=0;m.r("TIMING_REPORT_ON_UNLOAD")&&vc(!0);m.r("EXP_DEFER_CSI_PING")&&sc("n");oc(void 0);pc();m.r("CSI_TRACK_ON_BEGIN")&&ic("nb");hc("mark_navigation_requested");dg(eba);m.ib("navigate")};
var eg=function(a){a=a.detail.part||a.detail.partial;m.fc("nc"+cg);++cg;var b=1==bg;bg=2;b?(dg(fba),fg()):dg(gba);(a=a.data&&a.data.swfcfg)&&gg(a)};var hg=function(){};var ig=function(a){a=a.detail.response;var b=1==bg;bg=3;b&&(dg(hba),fg());(a=a.data&&a.data.swfcfg)&&gg(a)};
var jg=function(a){m.fc("nd");a=a.detail.response.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;jc(void 0).yt_nav=b;ic("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);jc(void 0).srt=b;b=a.spfCached?"hot":"warm";jc(void 0).yt_lt=b;b=+!!a.spfPrefetched;jc(void 0).yt_pft=b;kc("req",a.responseStart-a.fetchStart);dg(kg);window.document.getElementById("content").style.height="";Xf();bg=0};
var lg=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.Ya(a)};var mg=function(a){a=m.bc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.$c(a)};var iba=function(){jba()};var kba=function(){};
var fg=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");$f();for(var b in m.Ta)delete m.Ta[b];m.h("ytplayer.config",null,void 0);if(!Mf)if((a=m.Qf())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Tf=a,(a=m.C("movie_player"))&&a.stopVideo?(a.stopVideo(),Tf="recovered"):Tf="missing2"}else Tf="missing";Pf()};var gg=function(a){"cfg"in gc(void 0)||m.fc("cfg");Nf(a)};
var dg=function(a){function b(){var b=a[0],f=a[1],g=a[2];c.className="";var n=c.style;n.transitionDuration=n.webkitTransitionDuration=b+"ms";n.width=f+"%";m.Wa(ng);ng=m.s(function(){c.className=g},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.yc()?(m.Bc(og),og=m.zc(b,0)):(m.Wa(ng),ng=m.s(b,0))};
var jba=function(){var a=kg[0]+50;m.Wa(ng);ng=m.s(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
var lba=function(){"watch"!=m.r("PAGE_NAME")&&m.h("yt.www.skywatch.lastBrowsePage",window.location.href,void 0);if(m.r("SKYWATCH_ENABLED")){var a=m.C("skywatch-close-button");a||(a=window.document.createElement("button"),m.kb(a,["yt-uix-button","yt-uix-button-default"]),a.id="skywatch-minimize-button",a.innerHTML="\u21f2",m.C("player-mole-container").appendChild(a));pg.push(m.H(a,"click",mba))}};var mba=function(){m.wd(m.k("yt.www.skywatch.lastBrowsePage")||"/")};
var qg=function(){m.Dc.call(this,"www/base");this.j=0};var rg=function(a){(a=a.detail.name)&&Hc(a)};m.ba=[];m.sg=m.sg||{};m.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;m.E=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.l.apply(null,c)}return(0,m.l)(this,a)};m.ra[" "]=m.ea;m.p(m.sa,Error);m.sa.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;m.ya=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;m.nba=2147483648*Math.random()|0;m.Ia=Array.prototype;m.Fa=m.Ia.indexOf?function(a,b,c){return m.Ia.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ka(a))return m.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.oba=m.Ia.lastIndexOf?function(a,b,c){return m.Ia.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ka(a))return m.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.v=m.Ia.forEach?function(a,b,c){m.Ia.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)};
m.lb=m.Ia.filter?function(a,b,c){return m.Ia.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,n=m.ka(a)?a.split(""):a,q=0;q<d;q++)if(q in n){var t=n[q];b.call(c,t,q,a)&&(f[g++]=t)}return f};m.tg=m.Ia.map?function(a,b,c){return m.Ia.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=m.ka(a)?a.split(""):a,n=0;n<d;n++)n in g&&(f[n]=b.call(c,g[n],n,a));return f};
m.ug=m.Ia.reduce?function(a,b,c,d){d&&(b=(0,m.l)(b,d));return m.Ia.reduce.call(a,b,c)}:function(a,b,c,d){var f=c;(0,m.v)(a,function(c,n){f=b.call(d,f,c,n,a)});return f};m.vg=m.Ia.some?function(a,b,c){return m.Ia.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1};
m.wg=m.Ia.every?function(a,b,c){return m.Ia.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=m.ka(a)?a.split(""):a,g=0;g<d;g++)if(g in f&&!b.call(c,f[g],g,a))return!1;return!0};m.La.prototype.Bb=!1;m.La.prototype.ha=function(){return this.Bb};m.La.prototype.dispose=function(){this.Bb||(this.Bb=!0,this.N())};m.La.prototype.N=function(){if(this.Ba)for(;this.Ba.length;)this.Ba.shift()()};m.p(m.Qa,m.La);m.e=m.Qa.prototype;m.e.To=1;m.e.Mh=0;m.e.subscribe=function(a,b,c){var d=this.Qb[a];d||(d=this.Qb[a]=[]);var f=this.To;this.Aa[f]=a;this.Aa[f+1]=b;this.Aa[f+2]=c;this.To=f+3;d.push(f);return f};m.e.unsubscribe=function(a,b,c){if(a=this.Qb[a]){var d=this.Aa;if(a=m.Ca(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Mb(a)}return!1};
m.e.Mb=function(a){if(0!=this.Mh)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.Aa[a];if(b){var c=this.Qb[b];c&&m.Ga(c,a);delete this.Aa[a];delete this.Aa[a+1];delete this.Aa[a+2]}return!!b};m.e.publish=function(a,b){var c=this.Qb[a];if(c){this.Mh++;for(var d=m.Ka(arguments,1),f=0,g=c.length;f<g;f++){var n=c[f];this.Aa[n+1].apply(this.Aa[n+2],d)}this.Mh--;if(this.j&&0==this.Mh)for(;c=this.j.pop();)this.Mb(c);return 0!=f}return!1};
m.e.clear=function(a){if(a){var b=this.Qb[a];b&&((0,m.v)(b,this.Mb,this),delete this.Qb[a])}else this.Aa.length=0,this.Qb={}};m.e.ta=m.aa(3);m.e.N=function(){m.Qa.J.N.call(this);delete this.Aa;delete this.Qb;delete this.j};m.Ta=window.yt&&window.yt.config_||{};m.h("yt.config_",m.Ta,void 0);m.h("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.$a=window.yt&&window.yt.msgs_||{};m.h("yt.msgs_",m.$a,void 0);m.Xd="Microsoft Internet Explorer"==window.navigator.appName;var pba=m.k("yt.pubsub.instance_")||new m.Qa;m.Qa.prototype.subscribe=m.Qa.prototype.subscribe;m.Qa.prototype.unsubscribeByKey=m.Qa.prototype.Mb;m.Qa.prototype.publish=m.Qa.prototype.publish;m.Qa.prototype.clear=m.Qa.prototype.clear;m.h("yt.pubsub.instance_",pba,void 0);var eb=m.k("yt.pubsub.subscribedKeys_")||{};m.h("yt.pubsub.subscribedKeys_",eb,void 0);var gb=m.k("yt.pubsub.topicToKeys_")||{};m.h("yt.pubsub.topicToKeys_",gb,void 0);var fb=m.k("yt.pubsub.isSynchronous_")||{};
m.h("yt.pubsub.isSynchronous_",fb,void 0);m.db=m.k("yt.pubsub.skipSubId_")||null;m.h("yt.pubsub.skipSubId_",m.db,void 0);var tb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");e:{var xg=m.da.navigator;if(xg){var yg=xg.userAgent;if(yg){m.zd=yg;break e}}m.zd=""};var Gg,yb,xb,Hg;m.ee=m.wa(m.zd,"Opera")||m.wa(m.zd,"OPR");m.B=m.wa(m.zd,"Trident")||m.wa(m.zd,"MSIE");m.de=m.wa(m.zd,"Gecko")&&!m.wa(m.zd.toLowerCase(),"webkit")&&!(m.wa(m.zd,"Trident")||m.wa(m.zd,"MSIE"));m.ce=m.wa(m.zd.toLowerCase(),"webkit");m.ce&&m.wa(m.zd,"Mobile");var Dg=m.da.navigator||null,Eg=Dg&&Dg.platform||"";m.ae=m.wa(Eg,"Mac");m.$d=m.wa(Eg,"Win");m.zg=m.wa(Eg,"Linux");var Fg=m.zd;m.Ag=!!Fg&&m.wa(Fg,"Android");m.Bg=!!Fg&&m.wa(Fg,"iPhone");m.Cg=!!Fg&&m.wa(Fg,"iPad");
Gg=m.da.navigator||null;m.qba=!!Gg&&m.wa(Gg.appVersion||"","X11");yb=function(){var a="",b;if(m.ee&&m.da.opera)return a=m.da.opera.version,m.ma(a)?a():a;m.de?b=/rv\:([^\);]+)(\)|;)/:m.B?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.ce&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.zd))?a[1]:"");return m.B&&(b=vb(),b>(0,window.parseFloat)(a))?String(b):a}();xb={};Hg=m.da.document;m.Ab=Hg&&m.B?vb()||("CSS1Compat"==Hg.compatMode?(0,window.parseInt)(yb,10):5):void 0;var kaa;kaa=!m.B||m.zb(9);m.rba=!m.de&&!m.B||m.B&&m.zb(9)||m.de&&m.wb("1.9.1");m.Jg=m.B&&!m.wb("9");m.sba=m.B||m.ee||m.ce;m.tba=m.B&&!m.zb(9);var Eb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Kg=m.Lb(!1);m.Lg=m.Lb(!0);m.Pb="StopIteration"in m.da?m.da.StopIteration:Error("StopIteration");m.Nb.prototype.next=function(){throw m.Pb;};m.Nb.prototype.gb=function(){return this};var oaa=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ub=m.ce;var Yaa=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/embed\//;var ec={},qaa=0,uba=m.k("yt.net.ping.workerUrl_")||null;m.h("yt.net.ping.workerUrl_",uba,void 0);var rc,tc,uc;var qc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},pc=(0,m.l)(qc.clearResourceTimings||qc.webkitClearResourceTimings||qc.mozClearResourceTimings||qc.msClearResourceTimings||qc.oClearResourceTimings||m.ea,qc),hc=qc.mark?function(a){qc.mark(a)}:m.ea;m.e=m.Dc.prototype;m.e.Rw=function(){2==this.k||this.init()};m.e.enable=function(){this.k=1;(0,m.v)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.Rw,this),this.subscribe("dispose-"+a,this.dispose,this),m.r("PAGE_NAME")==a&&m.Ec(this))},this)};m.e.init=function(){m.yc()&&m.Bc(this.B);this.k=2;this.F&&this.F()};m.e.dispose=function(){this.k=3;m.Bc(this.B);this.C&&this.C()};m.e.disable=function(){this.k=4;this.dispose();this.clear()};
m.e.subscribe=function(a,b,c){a=m.u(a,b,c);this.Aa.push(a);return a};m.e.clear=function(){m.hb(this.Aa);this.Aa=[]};var Gc=m.k("yt.modules.registry_")||{};m.h("yt.modules.registry_",Gc,void 0);m.Mg=null;"undefined"!=typeof window.XMLHttpRequest?m.Mg=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(m.Mg=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var Jc,Kc,Lc,Mc,Pc,Rc=0,Qc=0,Oc=[],vaa=/.+\.googlevideo\.com|c\.youtube\.com|\/videoplayback\?|spf\=navigate/g;var Uc={};var xaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,yaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.Zc=m.Vb;var Aaa={enablejsapi:1},Baa={},Caa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ad.prototype.clone=function(){var a=new ad,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.rb(c):a[b]=c}return a};m.ed=/\s*;\s*/;m.e=m.cd.prototype;m.e.isEnabled=m.aa(4);m.e.set=function(a,b,c,d,f,g){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.ca(c)||(c=-1);f=f?";domain="+f:"";d=d?";path="+d:"";g=g?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.E)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+f+d+c+g};
m.e.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.ed),f=0,g;g=d[f];f++){if(0==g.lastIndexOf(c,0))return g.substr(c.length);if(g==a)return""}return b};m.e.remove=function(a,b,c){var d=m.ca(this.get(a));this.set(a,"",0,b,c);return d};m.e.Va=m.aa(5);m.e.wa=m.aa(6);m.e.isEmpty=m.aa(7);m.e.ta=m.aa(2);m.e.uf=m.aa(8);m.e.clear=function(){for(var a=m.dd(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.gd=new m.cd(window.document);m.gd.k=3950;m.jd=null;m.vba=m.ce?"webkit":m.de?"moz":m.B?"ms":m.ee?"o":"";m.Ng=m.k("yt.dom.getNextId_");if(!m.Ng){m.Ng=function(){return++wba};m.h("yt.dom.getNextId_",m.Ng,void 0);var wba=0};m.e=m.md.prototype;m.e.xa=null;m.e.type="";m.e.target=null;m.e.relatedTarget=null;m.e.currentTarget=null;m.e.data=null;m.e.source=null;m.e.state=null;m.e.keyCode=0;m.e.charCode=0;m.e.altKey=!1;m.e.ctrlKey=!1;m.e.shiftKey=!1;m.e.clientX=0;m.e.clientY=0;m.e.wheelDeltaX=0;m.e.wheelDeltaY=0;m.e.rotation=0;m.e.scale=1;m.e.changedTouches=null;m.e.preventDefault=m.aa(9);m.e.stopPropagation=m.aa(10);m.e.stopImmediatePropagation=m.aa(11);
var Daa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.od=m.k("yt.events.listeners_")||{};m.h("yt.events.listeners_",m.od,void 0);var pd=m.k("yt.events.counter_")||{count:0};m.h("yt.events.counter_",pd,void 0);var Fd;var Bd,Cd=!1,Dd=[];m.Id.prototype.then=function(a,b,c){return m.Od(this,m.ma(a)?a:null,m.ma(b)?b:null,c)};m.Gd(m.Id);m.Id.prototype.cancel=function(a){0==this.k&&Ad(function(){var b=new Pd(a);Ld(this,b)},this)};m.Id.prototype.H=function(a){this.k=0;Jd(this,2,a)};m.Id.prototype.L=function(a){this.k=0;Jd(this,3,a)};m.Id.prototype.K=function(){for(;this.j&&this.j.length;){var a=this.j;this.j=[];for(var b=0;b<a.length;b++)Md(this,a[b],this.k,this.G)}this.F=!1};var Kaa=yd;m.p(Pd,m.sa);Pd.prototype.name="cancel";var Sd=null;Qd.prototype.C=function(a){Td(this,"startFeedback",arguments)};Qd.prototype.F=function(a){Td(this,"startHelp",arguments)};Qd.prototype.j=function(a){Td(this,"loadChatSupport",arguments)};var Og=!1,Pg="";
if(window.navigator.plugins&&window.navigator.plugins.length){var Qg=window.navigator.plugins["Shockwave Flash"];Qg&&(Og=!0,Qg.description&&(Pg=Ud(Qg.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(Og=!0,Pg="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var Rg=window.navigator.mimeTypes["application/x-shockwave-flash"];(Og=Rg&&Rg.enabledPlugin)&&(Pg=Ud(Rg.enabledPlugin.description))}else try{var Sg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),Og=
!0,Pg=Ud(Sg.GetVariable("$version"))}catch(xba){try{Sg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),Og=!0,Pg="6.0.21"}catch(yba){try{Sg=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Og=!0,Pg=Ud(Sg.GetVariable("$version"))}catch(zba){}}}m.Aba=Og;m.Tg=Pg;var Ug,Vg,Wg,Xg,Yg,Zg,$g,Bba,Cba;$g=Zg=Yg=Xg=Wg=Vg=Ug=!1;var ah=m.zd;ah&&(-1!=ah.indexOf("Firefox")?Ug=!0:-1!=ah.indexOf("Camino")?Vg=!0:-1!=ah.indexOf("iPad")?Xg=!0:-1!=ah.indexOf("iPhone")||-1!=ah.indexOf("iPod")?Wg=!0:-1!=ah.indexOf("Chrome")?Zg=!0:-1!=ah.indexOf("Android")?Yg=!0:-1!=ah.indexOf("Safari")&&($g=!0));m.bh=Ug;Bba=Vg;m.ch=Wg;m.dh=Xg;Cba=Yg;m.eh=Zg;m.fh=$g;m.Dba=function(){if(m.bh)return Vd(/Firefox\/([0-9.]+)/);if(m.B||m.ee)return yb;if(m.eh)return Vd(/Chrome\/([0-9.]+)/);if(m.fh)return Vd(/Version\/([0-9.]+)/);if(m.ch||m.dh){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.zd))return a[1]+"."+a[2]}else{if(Cba)return(a=Vd(/Android\s+([0-9.]+)/))?a:Vd(/Version\/([0-9.]+)/);if(Bba)return Vd(/Camino\/([0-9.]+)/)}return""}();m.ga(Wd);Wd.prototype.getVersion=function(){return[this.j,this.k,this.B]};m.e=m.ge.prototype;m.e.clone=function(){return new m.ge(this.top,this.right,this.bottom,this.left)};m.e.contains=function(a){return m.he(this,a)};m.e.ceil=m.aa(12);m.e.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.e.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.e.scale=function(a,b){var c=m.la(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Raa=m.ub("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Eba=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Fba=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.le.prototype.ri=!0;m.le.prototype.qi=function(){return this.j};m.le.prototype.toString=function(){return"Const{"+this.j+"}"};var me={};oe.prototype.ri=!0;var pe={};oe.prototype.qi=function(){return this.j};var Paa=qe(""),Oaa=/^[-.%_!# a-zA-Z0-9]+$/;re.prototype.ri=!0;re.prototype.qi=function(){return""};re.prototype.fp=!0;re.prototype.uh=function(){return 1};var se={};var xe,Qaa,Naa,ue;te.prototype.fp=!0;te.prototype.uh=function(){return this.k};te.prototype.ri=!0;te.prototype.qi=function(){return this.j};xe=/^[a-zA-Z0-9-]+$/;Qaa=m.ub("action","cite","data","formaction","href","manifest","poster","src");Naa=m.ub("link","script","style");ue={};m.gh=ye("",0);m.hh=m.Mb(function(){if(m.B)return m.wb("10.0");var a=window.document.createElement("div"),b=m.fe(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=m.we("div",{style:c});a.innerHTML=m.ve(b);a=a.firstChild;b=a.style[m.Aa("transition")];return""!=("undefined"!==typeof b?b:a.style[m.ie(a,"transition")]||"")});var Fe;m.Be={};Fe=!1;m.ga(m.He);m.Ie=m.k("yt.prefs.UserPrefs.prefs_")||{};m.h("yt.prefs.UserPrefs.prefs_",m.Ie,void 0);m.e=m.He.prototype;m.e.get=function(a,b){Ke(a);Je(a);var c=void 0!==m.Ie[a]?m.Ie[a].toString():null;return null!=c?c:b?b:""};m.e.set=function(a,b){Ke(a);Je(a);if(null==b)throw"ExpectedNotNull";m.Ie[a]=b.toString()};m.e.remove=function(a){Ke(a);Je(a);delete m.Ie[a]};m.e.save=function(){var a;a=[];for(var b in m.Ie)a.push(b+"="+(0,window.escape)(m.Ie[b]));a=a.join("&");m.fd("PREF",a,63072E3)};
m.e.clear=function(){m.Ie={}};var Uaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Ve;var ih=m.zd,ih=ih.toLowerCase();if(m.wa(ih,"android")){var jh=ih.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(jh)Ve=Number(jh[1]);else{var kh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},lh=ih.match("("+m.pb(kh).join("|")+")");Ve=lh?kh[lh[0]]:0}}else Ve=void 0;m.p(m.We,Waa);m.We.prototype.ta=m.aa(1);m.We.prototype.clear=function(){var a=m.Rb(this.gb(!0)),b=this;(0,m.v)(a,function(a){b.remove(a)})};m.p(m.Xe,m.We);m.e=m.Xe.prototype;m.e.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.e.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.e.get=function(a){a=this.j.getItem(a);if(!m.ka(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.e.remove=function(a){this.j.removeItem(a)};
m.e.ta=m.aa(0);m.e.gb=function(a){var b=0,c=this.j,d=new m.Nb;d.next=function(){if(b>=c.length)throw m.Pb;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ka(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.e.clear=function(){this.j.clear()};m.e.key=function(a){return this.j.key(a)};m.p(m.Ye,m.Xe);m.p(Ze,m.Xe);var ff={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Xaa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.gf.prototype.set=function(a,b){m.ca(b)?this.j.set(a,m.af(b)):this.j.remove(a)};m.gf.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.$e(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.gf.prototype.remove=function(a){this.j.remove(a)};m.p(hf,m.gf);hf.prototype.set=function(a,b){hf.J.set.call(this,a,kf(b))};hf.prototype.k=function(a){a=hf.J.get.call(this,a);if(!m.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};hf.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.p(lf,hf);lf.prototype.set=function(a,b,c){if(b=kf(b)){if(c){if(c<(0,m.E)()){lf.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.E)()}lf.J.set.call(this,a,b)};lf.prototype.k=function(a,b){var c=lf.J.k.call(this,a);if(c)if(!b&&m.mf(c))lf.prototype.remove.call(this,a);else return c};m.p(m.nf,lf);var mh,nh;mh=new m.Ye;m.pf=mh.isAvailable()?new m.nf(mh):null;nh=new Ze;m.qf=nh.isAvailable()?new m.nf(nh):null;m.p(tf,m.La);m.e=tf.prototype;m.e.getId=function(){return this.K};m.e.uj=function(a,b){this.ha()||(vf(this,a),Bf(this,b),this.G&&xf(this))};m.e.Jt=function(){return this.ma};
m.e.qy=function(){if(!this.P){var a=!0;this.pa&&(a=Cf(this));a&&"html5"==Ef(this)?(this.F="html5",this.G||this.Le()):(Ff(this),this.F="html5",a&&this.ea?(this.vf.appendChild(this.ea),this.Le()):(this.da.loaded=!0,this.H=(0,m.l)(function(){var a=this.vf,c=this.da.clone();m.k("yt.player.Application.create")(a,c);this.Le()},this),this.P=!0,Cf(this)?this.H():(m.Vc(this.da.assets.js,this.H),m.Ue(this.da.assets.css))))}};
m.e.py=function(){var a=this.da.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Ef(this)?(this.F="flash",this.G||Se(a,!1,(0,m.l)(this.Le,this))):(Ff(this),this.F="flash",this.da.loaded=!0,m.Oe(this.vf,a),this.Le())};
m.e.Le=function(){var a=Af(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.P=!1,a.isNotServable&&a.isNotServable())zf(this);else{uf(this);this.G=!0;a=Af(this);a.addEventListener&&(this.L=Df(this,a,"addEventListener"));a.removeEventListener&&(this.U=Df(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var f=b[d];this.j[f]||(this.j[f]=Df(this,a,f))}for(var g in this.C)this.L(g,this.C[g]);xf(this);
this.W&&this.W(this.j);this.T.publish("onReady",this.j)}else this.Ea=m.s((0,m.l)(this.Le,this),50)};m.e.Nt=function(){return this.G};m.e.xe=function(a,b){if(!this.ha()){var c=wf(this,b);if(c){if(!m.Ea(this.Ka,a)&&!this.C[a]){var d=Zaa(this,a);this.L&&this.L(a,d)}this.T.subscribe(a,c);"onReady"==a&&this.G&&m.s(m.qa(c,this.j),0)}}};m.e.Mt=function(a,b){if(!this.ha()){var c=wf(this,b);c&&this.T.unsubscribe(a,c)}};
m.e.Wp=function(a){a=a?naa:maa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.e.Yp=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?sf().volume:m.nb(a.volume,0,100);b.muted=void 0==a.muted?sf().muted:a.muted;m.of("yt-player-volume",b,2592E3)};m.e.Xp=function(a){5==a&&zf(this)};m.e.Zp=function(a){m.w("WATCH_LATER_VIDEO_ADDED",a)};m.e.$p=function(a){m.w("WATCH_LATER_VIDEO_REMOVED",a)};
m.e.ry=function(){Ff(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.da.messages.player_fallback||a;a=m.C("player-unavailable");m.C("unavailable-submessage")&&a&&(m.C("unavailable-submessage").innerHTML=b,(b=m.D("icon",a))&&m.Tc(b,"icon")&&(b.src=m.F(b,"icon")),m.A(a,"hid"),m.y(m.C("player"),"off-screen-trigger"))};m.e.Lt=function(){return this.F||Ef(this)};m.e.Kt=function(){return this.Da};m.e.cancel=function(){this.H&&m.Xc(this.da.assets.js,this.H);m.Wa(this.Ea);this.P=!1};
m.e.N=function(){Ff(this);this.Y=null;for(var a in this.C)m.da[this.C[a]]=null;this.j=null;delete this.vf;delete this.B;this.da&&(this.ma=this.da=this.da.fallback=null);tf.J.N.call(this)};var If={},Hf="player_uid_"+(1E9*Math.random()>>>0);var Gba=m.k("yt.abuse.botguardInitialized")||id;m.h("yt.abuse.botguardInitialized",Gba,void 0);var Hba=m.k("yt.abuse.invokeBotguard")||kd;m.h("yt.abuse.invokeBotguard",Hba,void 0);var Iba=m.k("yt.player.exports.navigate")||m.xd;m.h("yt.player.exports.navigate",Iba,void 0);var Jba=m.k("yt.player.embed")||m.Gf;m.h("yt.player.embed",Jba,void 0);var Kba=m.k("yt.player.destroy")||m.Kf;m.h("yt.player.destroy",Kba,void 0);var Lba=m.k("yt.player.cancelAll")||Jf;m.h("yt.player.cancelAll",Lba,void 0);
var Mba=m.k("yt.player.getPlayerByElement")||m.Lf;m.h("yt.player.getPlayerByElement",Mba,void 0);var Nba=m.k("yt.player.exports.feedbackStart")||m.De;m.h("yt.player.exports.feedbackStart",Nba,void 0);var Oba=m.k("yt.player.exports.feedbackShowArticle")||m.Ge;m.h("yt.player.exports.feedbackShowArticle",Oba,void 0);var Pba=m.k("yt.util.activity.init")||m.qd;m.h("yt.util.activity.init",Pba,void 0);var Qba=m.k("yt.util.activity.getTimeSinceActive")||m.sd;
m.h("yt.util.activity.getTimeSinceActive",Qba,void 0);var Rba=m.k("yt.util.activity.setTimestamp")||rd;m.h("yt.util.activity.setTimestamp",Rba,void 0);var Of,Uf=!1,Tf="",Mf=!1;var Zf=[];var bg,ng,og,cg=0,eba=[900,60,"waiting"],hba=[500,99,"waiting"],fba=[300,60,"waiting"],gba=[400,99,"waiting"],kg=[300,101,"done"];var pg=[];window.yt=window.yt||{};m.h("yt.setConfig",m.Ra,void 0);m.h("yt.getConfig",m.r,void 0);m.h("yt.hasMsg",m.ab,void 0);m.h("yt.pubsub.publish",m.w,void 0);m.h("yt.pubsub.subscribe",m.u,void 0);m.h("yt.setMsg",m.Za,void 0);m.h("yt.setGoogMsg",function(a){Sa(m.$a,arguments)},void 0);m.h("yt.setAjaxToken",function(){},void 0);m.h("reportTimingMaps",function(a,b,c,d){if(a)for(var f in a)m.fc(f,a[f],d);if(c)for(var g in c)kc(g,c[g],d);if(b)for(var n in b)a=n,c=b[n],jc(d)[a]=c;return wc(d)},void 0);
m.h("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],f;for(f in a)"_"!=f.charAt(0)&&d.push(f+"."+a[f]);c.rt=d.join(",");for(var g in b)"_"!=g.charAt(0)&&(c[g]=b[g]);a=m.r("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);nc(c)},void 0);m.p(qg,m.Dc);
qg.prototype.enable=function(){window.onload=bba;window.onunload=cba;window.onerror=dba;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",ag),window.addEventListener("spfpartprocess",eg),window.addEventListener("spfpartdone",hg),window.addEventListener("spfprocess",ig),window.addEventListener("spfdone",jg),window.addEventListener("spferror",lg),window.addEventListener("spfreload",mg),window.addEventListener("spfjsbeforeunload",rg)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",iba),this.subscribe("dispose",kba)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
qg.prototype.init=function(){qg.J.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();raa();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.r("PAGEFRAME_JS")?(b=m.r("PAGEFRAME_JS"),c=function(){m.k("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.k("yt.www.masthead.loadSearchbox"))&&a();var a=m.r("JS_COMMON_MODULE"),d=m.r("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.r("JS_DELAY_LOAD",void 0),0<a?(m.Wa(this.j),this.j=m.s(function(){b&&m.Vc(b,c);window.spf.script.require(d)},
a)):(b&&m.Vc(b,c),window.spf.script.require(d));else{var f={};f[a]=d;a=m.r("JS_DELAY_LOAD",void 0);0<a?(m.Wa(this.j),this.j=m.s(function(){b&&m.Vc(b,c);m.Yc(f)},a)):(b&&m.Vc(b,c),m.Yc(f))}lba();aba();var a=!!m.k("yt.reactLoaded"),g=m.r("REACT_JS");!a&&g&&m.Vc(g,function(){m.h("yt.reactLoaded",!0,void 0)})};
qg.prototype.dispose=function(){m.Wa(this.j);var a=m.k("ytbin.www.pageframe.cancelSetup");a&&a();m.I(pg);pg.length=0;m.Xa(Of);if(a=m.Qf())a.removeEventListener("onReady",Pf),a.removeEventListener("onStateChange",Pf),a.removeEventListener("onReady",Rf),a.removeEventListener("onStateChange",Rf);qg.J.dispose.call(this)};
qg.prototype.disable=function(){qg.J.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",ag),window.removeEventListener("spfpartprocess",eg),window.removeEventListener("spfpartdone",hg),window.removeEventListener("spfprocess",ig),window.removeEventListener("spfdone",jg),window.removeEventListener("spferror",lg),window.removeEventListener("spfreload",mg),window.removeEventListener("spfjsbeforeunload",rg));window.onload=null;window.onunload=null;window.onerror=null};
m.Fc(new qg);})(_yt_www);
