
all:
	cd basics/; make
	cd converter1/; make
	cd converter2/; make
	cd converter3/; make
	cd order-application/; make
	cd textedit/; make
	cd screen-capture/; make
	cd order-application/; make
	cd mouse-buttons/; make


clean:
	cd basics/; make clean
	cd converter1/; make clean
	cd converter2/; make clean
	cd converter3/; make clean
	cd order-application/; make clean
	cd textedit/; make clean
	cd screen-capture/; make clean
	cd order-application/; make clean
	cd mouse-buttons/; make clean
	
