use `company`;

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'employee.unl' 
INTO TABLE employee
FIELDS TERMINATED BY '|' ;

LOAD DATA LOCAL INFILE 'department.unl' 
INTO TABLE department
FIELDS TERMINATED BY ' ';

LOAD DATA LOCAL INFILE 'dept_locations.unl' 
INTO TABLE dept_locations
FIELDS TERMINATED BY ' ';

LOAD DATA LOCAL INFILE 'project.unl' 
INTO TABLE project
FIELDS TERMINATED BY ' ';


LOAD DATA LOCAL INFILE 'dependent.unl' 
INTO TABLE dependent
FIELDS TERMINATED BY ' ';


LOAD DATA LOCAL INFILE 'works_on.unl' 
INTO TABLE works_on
FIELDS TERMINATED BY ' ';

SET FOREIGN_KEY_CHECKS = 1;