#!/bin/bash -x

export PATH=/usr/local/bin:/usr/bin:/bin

export CLASSPATH=/usr/local/javas/rhino1_7R3/js.jar

# Doesn't work from script, but works from prompt (??)

echo java org.mozilla.javascript.tools.shell.Main -f hello-world.js
