(function ensightenInit(){var ensightenOptions = {client: "seagate", clientId: 927, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/seagate/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/seagate/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Fri Nov 21 20:07:06 GMT 2014", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+
encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=
0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=
a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=
function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};
b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};
b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,
50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};
var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=
log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",
b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=
-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(window.location.protocol=="http:")Bootstrapper.insertScript("//cdn.clicktale.net/www06/phc/966a3db5-b0ff-44b2-852b-f24817b7f756.js");else Bootstrapper.insertScript("https://clicktalecdn.sslcs.cdngc.net/www06/phc/966a3db5-b0ff-44b2-852b-f24817b7f756.js")},393876,245290);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("video-click",function(){var s=window.s;try{s.eVar36=Bootstrapper.clickedVideoUrl}catch(e){s.eVar36=""}s.eVar37="+1";s.events="event41";s.prop32="video_click";try{s.prop33="video_click\x3e"+s.pageName}catch(e){s.prop33=""}try{s.prop36=Bootstrapper.clickedVideoUrl}catch(e){s.prop36=""}s.linkTrackVars="eVar36,eVar37,events,prop32,prop33,prop36";
s.linkTrackEvents=""+"event41,";s.tl(this,"o",this.textContent||this.innerText||"Video Click")})},394321,[393475],244893,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("form-error",function(){var s=window.s;s.events="event30";try{s.eVar43=Bootstrapper.formName+"-error: "+Bootstrapper.formError}catch(e){s.eVar43=""}s.prop32="form-error";try{s.prop33=s.pageName+"\x3eform-error"}catch(e){s.prop33=""}s.prop18="D\x3dv43";s.linkTrackVars="events,eVar43,prop32,prop33,prop18";s.linkTrackEvents=""+"event30";
s.tl(this,"o","form-error")})},394331,[393475],244908,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("basic-link-click",function(){var s=window.s;try{s.prop32=Bootstrapper.link_name}catch(e){s.prop32=""}try{s.prop33=s.pageName+"\x3e"+Bootstrapper.link_name}catch(e){s.prop33=""}s.linkTrackVars="prop32,prop33";s.linkTrackEvents="";s.tl(this,"o",this.textContent||this.innerText||"basic-link-click")})},394343,[393475],244978,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("lead-initiated",function(){var s=window.s;s.events="event1";try{if(Bootstrapper.leadSource)s.prop32=Bootstrapper.leadSource}catch(e){if(Bootstrapper.leadSource)s.prop32=""}try{if(Bootstrapper.leadSource)s.prop33=s.pageName+"\x3e"+Bootstrapper.leadSource}catch(e){if(Bootstrapper.leadSource)s.prop33=""}try{if(Bootstrapper.partnerName)s.prop22=
Bootstrapper.partnerName}catch(e){if(Bootstrapper.partnerName)s.prop22=""}try{if(Bootstrapper.partnerName)s.eVar5=Bootstrapper.leadSource+":"+Bootstrapper.partnerName}catch(e){if(Bootstrapper.partnerName)s.eVar5=""}try{if(Bootstrapper.partnerName)s.prop1=Bootstrapper.leadSource+":"+Bootstrapper.partnerName}catch(e){if(Bootstrapper.partnerName)s.prop1=""}s.linkTrackVars="events,prop32,prop33,prop22,eVar5,prop1";s.linkTrackEvents=""+"event1,";s.tl(this,"o",this.textContent||this.innerText||"lead-initiated")})},
394323,[393475],244899,[244890]);Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("begin-return",function(){var s=window.s;s.prop32="begin a return";try{s.prop33=s.pageName+" \x3e begin a return"}catch(e){s.prop33=""}s.events="event34";s.linkTrackVars="prop32,prop33,events";s.linkTrackEvents=""+"event34";s.tl(this,"o","begin-a-return")})},394327,[393475],244905,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("email-click",function(){var s=window.s;s.prop32="email-click";try{s.prop33=s.pageName+"email-click"}catch(e){s.prop33=""}s.eVar35="Bootstrapper.emailType";s.events="event27";s.linkTrackVars="prop32,prop33,eVar35,events";s.linkTrackEvents=""+"event27";s.tl(this,"o",this.textContent||this.innerText||"email-click")})},394335,[393475],
244924,[244890]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.h=window.location.href;if(window.location.host=="www.seagate.com"||window.location.host=="m.seagate.com"||window.location.host=="seagate.com"){window.ebRand=Math.random()+"";ebRand=ebRand*1E6;if(window.location.protocol=="https:"){document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//seagate.magnify360.com/m360lib.js"+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}else{document.write("\x3cscr"+
'ipt type\x3d"text/javascript" src\x3d"'+"//cdn.magnify360.com/m360lib.js"+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//seagate.magnify360.com/uni/5071/360.js"+"?"+ebRand+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}},602293,245284);
Bootstrapper.bindDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var externalScript=document.createElement("script");var scrSrc=document.location.protocol=="https:"?"https://clicktalecdn.sslcs.cdngc.net/":"http://cdn.clicktale.net/";scrSrc+="www06/ptc/966a3db5-b0ff-44b2-852b-f24817b7f756.js";externalScript.src=scrSrc;externalScript.type="text/javascript";document.body.appendChild(externalScript)},393546,244961);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var h=window.location.host.toLowerCase();var ebRand=Math.random()+"";ebRand=ebRand*1E6;var url="//seagate.magnify360.com/uni/5071/360.js?"+ebRand;if(h=="www.shop.seagate.com"||h=="shop.seagate.com"){document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//seagate.magnify360.com/m360lib.js"+'"\x3e');document.write("\x3c/scr"+"ipt\x3e");document.write('\x3cscript src\x3d"'+
url+'"\x3e\x3c/scr'+"ipt\x3e")}},393547,244962);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("log-in",function(){var s=window.s;if(Bootstrapper.logInType=="direct")s.events="event31";if(Bootstrapper.logInType=="spp")s.events="event11";if(Bootstrapper.logInType=="direct")s.eVar44="direct log in";if(Bootstrapper.logInType=="spp")s.eVar44="spp log in";if(Bootstrapper.logInType=="consumer")s.eVar44="consumer log in";if(Bootstrapper.logInType==
"consumer")s.events="event10";s.linkTrackVars="events,events,eVar44,eVar44,eVar44,events";s.linkTrackEvents=""+"event31,"+"event11,"+"event10,";s.tl(this,"o","log-in")})},394342,[393475],244936,[244890]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var h=window.location.href;if(h.indexOf("wwwedit.okla.seagate.com/external-hard-drives/portable-hard-drives/wireless/wireless-plus-140213-a/")!=-1||h.indexOf("wwwedit.okla.seagate.com/external-hard-drives/portable-hard-drives/wireless/wireless-plus/")!=-1||h.indexOf("wwwreview.seagate.com/external-hard-drives/portable-hard-drives/wireless/wireless-plus/")!=-1||h.indexOf("wwwreview.seagate.com/external-hard-drives/portable-hard-drives/wireless/wireless-plus-140213-a/")!=
-1){var ebRand=Math.random()+"";ebRand=ebRand*1E6;if(window.location.protocol=="https:"){document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//seagate.magnify360.com/m360lib.js"+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}else{document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//cdn.magnify360.com/m360lib.js"+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}document.write("\x3cscr"+'ipt type\x3d"text/javascript" src\x3d"'+"//seagate.magnify360.com/uni/5071/360.js"+"?"+
ebRand+'"\x3e');document.write("\x3c/scr"+"ipt\x3e")}},393621,245037);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.trackerFramework=function(){cArray=function(){var funcs=[],hasRun=false;return{add:function(f){if(hasRun){try{f()}catch(e){Bootstrapper.reportException(e)}return}if(typeof f!=="function")return;funcs[funcs.length]=f},exec:function(){var toRun=funcs,i,len;for(i=0,len=toRun.length;i<len;i++)try{toRun[i].call(window)}catch(e){Bootstrapper.reportException(e)}},clear:function(){funcs=
[]},getFuncs:function(){return funcs}}};return{firstView:false,prePopulate:cArray(),postPopulate:cArray(),globalData:cArray(),localData:cArray(),globalEvents:cArray(),localEvents:cArray(),postPageView:cArray(),execute:function(){this.prePopulate.exec();this.events=this.getEvents();this.postPopulate.exec();this.sTarget.t();this.postPageView.exec()},getData:function(){var retObj={};var globalFuncs=this.globalData.getFuncs();for(var i=0,l=globalFuncs.length;i<l;i++){var tempObj=globalFuncs[i].call(window);
for(key in tempObj)if(tempObj[key])retObj[key]=tempObj[key]}var localFuncs=this.localData.getFuncs();for(var i=0,l=localFuncs.length;i<l;i++){var tempObj=localFuncs[i].call(window);for(key in tempObj)if(tempObj[key])retObj[key]=tempObj[key]}return retObj},getEvents:function(){var retEvents="";var globalFuncs=this.globalEvents.getFuncs();for(var i=0,l=globalFuncs.length;i<l;i++){var temp=globalFuncs[i].call(window);retEvents+=retEvents!=""?","+temp:temp}var localFuncs=this.localEvents.getFuncs();for(var i=
0,l=localFuncs.length;i<l;i++){var temp=localFuncs[i].call(window);retEvents+=retEvents!=""?","+temp:temp}return retEvents},autoLaunch:function(o){if(!this.firstView||o){this.sTarget=window.s;this.dataLayer=this.getData();this.execute()}this.firstView=this.firstView||true}}}()},393466,244880);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.detectBody=setInterval(function(){if(!document.getElementsByTagName("body").length)return;clearInterval(Bootstrapper.detectBody)},100)},393544,244959);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.s=window.s||{};Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==
detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.getCookie=function(c_name){var i,x,y,ARRcookies=document.cookie.split(";");
for(i=0;i<ARRcookies.length;i++){x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("\x3d"));y=ARRcookies[i].substr(ARRcookies[i].indexOf("\x3d")+1);x=x.replace(/^\s+|\s+$/g,"");if(x==c_name)return unescape(y)}};Bootstrapper.setCookie=function(name,value,days){var expires="";if(days){var date=new Date;date.setTime(date.getTime()+days*24*60*60*1E3);expires="; expires\x3d"+date.toGMTString()}document.cookie=name+"\x3d"+value+expires+"; path\x3d/"};Bootstrapper.clearLinkVars=function(){var linkVars=s.linkTrackVars.split(",");
for(var i=0;i<linkVars.length;i++)s[linkVars[i]]="";s.events=""};Bootstrapper.t_links=[];Bootstrapper.isTracked=function(lnk){for(var i=0;i<Bootstrapper.t_links.length;i++)if(Bootstrapper.t_links[i]===lnk)return true;Bootstrapper.t_links.push(lnk);return false};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};Bootstrapper.getElementXPath=function(e){var n=
e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p;n=n.parentNode}return"/HTML"+p};Bootstrapper.clearOmniVars=function(){s.events="";for(var i=0;i<75;i++){s["prop"+i]="";s["eVar"+i]="";if(i<=5)s["hier"+i]=""}};Bootstrapper.removeTag=function(input){input=input.replace(/&(lt|gt);/g,function(strMatch,p1){return p1=="lt"?"\x3c":"\x3e"});var strTagStrippedText=
input.replace(/<\/?[^>]+(>|$)/g,"");return strTagStrippedText};Bootstrapper.valid=function(input){var type=typeof input;if(type=="undefined")return false;else if(input===null)return false;else if(type=="string")if(input=="")return false;return true};Bootstrapper.getCleanUrl=function(){return window.location.href.split("?")[0]};document.oldWrite=document.write;document.write=function(x){if(!Bootstrapper.hasDOMParsed())document.oldWrite(x);else{var temp=document.createElement("div");temp.innerHTML=
x;var nodes=temp.childNodes;var approvedNodes=[];for(var i=0,l=nodes.length;i<l;i++)if(nodes[i].nodeType==1)approvedNodes.push(nodes[i]);if(approvedNodes.length){if(document.getElementById("_ensDocWrite")==null){var newDiv=document.createElement("div");newDiv.style.display="none";newDiv.id="_ensDocWrite";document.body.appendChild(newDiv)}var target=document.getElementById("_ensDocWrite");for(var i=0,l=approvedNodes.length;i<l;i++)if(approvedNodes[i].tagName=="SCRIPT")if(approvedNodes[i].src!="")if(approvedNodes[i].innerHTML!=
"")Bootstrapper.loadScriptCallback(approvedNodes[i].src,function(c){return function(){eval(c)}}(approvedNodes[i].innerHTML));else Bootstrapper.insertScript(approvedNodes[i].src);else eval(approvedNodes[i].innerHTML);else target.appendChild(approvedNodes[i])}}};Bootstrapper.adwordsConversion=function(id,language,format,color,label,value){if(typeof window.google_trackConversion!="function")Bootstrapper.loadScriptCallback("//www.googleadservices.com/pagead/conversion_async.js",function(){window.google_trackConversion({google_conversion_id:id,
google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,google_conversion_label:label,google_conversion_value:value||0})});else window.google_trackConversion({google_conversion_id:id,google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,google_conversion_label:label,google_conversion_value:value||0})};Bootstrapper.loadScriptCallbackId=function(src,callback,id){var scripts=document.getElementsByTagName("script"),
i,s=scripts[0];var newScript=document.createElement("script");newScript.type="text/javascript";newScript.async=true;newScript.src=src;newScript.id=id;newScript.onerror=function(){if(this.addEventListener)this.readyState="loaded"};newScript.onload=newScript.onreadystatechange=function(){if(!this.readyState||this.readyState==="complete"||this.readyState==="loaded"){this.onload=null;if(this.addEventListener)this.readyState="loaded";try{callback.call(this)}catch(e){window[ensightenOptions.ns].reportException(e)}}};
s.parentNode.insertBefore(newScript,s)};(function(){function n(a,c,m){if("_root"==c)return m;if(a!==m){var b;q||(a.matches&&(q=a.matches),a.webkitMatchesSelector&&(q=a.webkitMatchesSelector),a.mozMatchesSelector&&(q=a.mozMatchesSelector),a.msMatchesSelector&&(q=a.msMatchesSelector),a.oMatchesSelector&&(q=a.oMatchesSelector),q||(q=e.matchesSelector));b=q;if(b.call(a,c))return a;if(a.parentNode)return s++,n(a.parentNode,c,m)}}function t(a,c,m,b){d[a.id]||(d[a.id]={});d[a.id][c]||(d[a.id][c]={});d[a.id][c][m]||
(d[a.id][c][m]=[]);d[a.id][c][m].push(b)}function b(a,c,b,e){if(e||b)if(e)for(var l=0;l<d[a.id][c][b].length;l++){if(d[a.id][c][b][l]===e){d[a.id][c][b].pop(l,1);break}}else delete d[a.id][c][b];else d[a.id][c]={}}function g(a,c,b){if(d[a][b]){var g=c.target||c.srcElement,l,h,k={},f=h=0;s=0;for(l in d[a][b])d[a][b].hasOwnProperty(l)&&(h=n(g,l,p[a].element))&&e.matchesEvent(b,p[a].element,h,"_root"==l,c)&&(s++,d[a][b][l].match=h,k[s]=d[a][b][l]);c.stopPropagation=function(){c.cancelBubble=!0};for(h=
0;h<=s;h++)if(k[h])for(f=0;f<k[h].length;f++){if(!1===k[h][f].call(k[h].match,c)){e.cancel(c);return}if(c.cancelBubble)return}}}function f(a,c,m,f){function l(a){return function(c){g(h,c,a)}}a instanceof Array||(a=[a]);m||"function"!=typeof c||(m=c,c="_root");var h=this.id,k;for(k=0;k<a.length;k++)d[h]&&d[h][a[k]]||e.addEvent(this,a[k],l(a[k])),f?b(this,a[k],c,m):t(this,a[k],c,m);return this}function e(a,c,b){if("string"==typeof a&&"function"==typeof c||"string"==typeof c)e(document).on(a,c,b);if(!(this instanceof
e)){for(var d in p)if(p[d].element===a)return p[d];r++;p[r]=new e(a,r);p[r]._on=p[r].on;p[r].on=function(a,c,b,d){var e="function"==typeof c?c:b;if("function"==typeof c?b:d)a=[a],"string"==typeof c&&a.push(c),a.push(function(a){return function(c){c.defaultPrevented||Bootstrapper.Delegate.load(this);c.preventDefault();a.call(this)}}(e)),this._on.apply(this,a);else return this._on.call(this,a,c,b)};return p[r]}this.element=a;this.id=c}var q,s=0,r=0,d={},p={};e.prototype.on=function(a,c,b){return f.call(this,
a,c,b)};e.prototype.off=function(a,c,b){return f.call(this,a,c,b,!0)};e.matchesSelector=function(){};e.cancel=function(a){a.preventDefault();a.stopPropagation()};e.addEvent=function(a,c,b){a.element.addEventListener(c,b,"blur"==c||"focus"==c)};e.matchesEvent=function(){return!0};e.load=function(a){setTimeout(function(a){return function(){if(a&&/^javascript\s*\:/.test(a))return(new Function(a)).call(window);window.location.href=a}}(a.href||window.location.href),750)};window.Bootstrapper.Delegate=e})();
(function(n){var t=n.addEvent;n.addEvent=function(b,g,f){if(b.element.addEventListener)return t(b,g,f);"focus"==g&&(g="focusin");"blur"==g&&(g="focusout");b.element.attachEvent("on"+g,f)};n.simpleMatchesSelector=function(b){return"."===b.charAt(0)?-1<(" "+this.className+" ").indexOf(" "+b.slice(1)+" "):"#"===b.charAt(0)?this.id===b.slice(1):this.tagName.toUpperCase()===b.toUpperCase()};n.matchesSelector=function(b){if(~b.indexOf(" ")||~b.indexOf("\x3e")){var g=this;for(b=b.split(" ").reverse();b.length;){var f=
b.shift();if(~f.indexOf("\x3e")){for(f=f.split("\x3e").reverse();f.length;)if(tempSel=f.shift(),n.simpleMatchesSelector.call(g,tempSel))g=g.parentNode;else return!1;if(!b.length)return!0}else for(;g!=document;){var e=n.simpleMatchesSelector.call(g,f),g=g.parentNode;if(e){if(!b.length)return!0;break}}}return!1}return n.simpleMatchesSelector.call(this,b)};n.cancel=function(b){b.preventDefault&&b.preventDefault();b.stopPropagation&&b.stopPropagation();b.returnValue=!1;b.cancelBubble=!0}})(window.Bootstrapper.Delegate);
Bootstrapper.on=Bootstrapper.Delegate},393451,244866);Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("outlet-signup",function(){var s=window.s;s.events="event12";s.eVar21="outlet center signup";s.eVar44="outlet center signup";s.linkTrackVars="events,eVar21,eVar44";s.linkTrackEvents=""+"event12";s.tl(this,"o","outlet-signup")})},394336,[393475],244934,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("lead-complete",function(){var s=window.s;if(Bootstrapper.leadSource=="where-to-buy")s.events="event2,event55";if(Bootstrapper.leadSource!="where-to-buy")s.events="event2";try{s.eVar5=Bootstrapper.leadSource+":"+Bootstrapper.partnerName}catch(e){s.eVar5=""}try{s.prop1=Bootstrapper.leadSource+":"+Bootstrapper.partnerName}catch(e){s.prop1=
""}try{if(Bootstrapper.leadDollarValue)s.eVar1=Bootstrapper.leadDollarValue}catch(e){if(Bootstrapper.leadDollarValue)s.eVar1=""}s.linkTrackVars="events,events,eVar5,prop1,eVar1";s.linkTrackEvents=""+"event2,event55,"+"event2,";s.tl(this,"o",this.textContent||this.innerText||"")})},394324,[393475],244900,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("social-share-click",function(){var s=window.s;s.prop32="social-share-click";try{s.prop33=s.pageName+"\x3esocial-share-click"}catch(e){s.prop33=""}s.events="event15";try{s.eVar9=Bootstrapper.shareType}catch(e){s.eVar9=""}s.linkTrackVars="prop32,prop33,events,eVar9";s.linkTrackEvents=""+"event15";s.tl(this,"o",this.textContent||this.innerText||
"social-share-click")})},394333,[393475],244922,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("registration",function(){var s=window.s;try{s.eVar21=Bootstrapper.regType}catch(e){s.eVar21=""}if(Bootstrapper.regType=="consumer")s.events="event8";if(Bootstrapper.regType=="spp")s.events="event7,event8";s.linkTrackVars="eVar21,events,events";s.linkTrackEvents=""+"event8,"+"event7,event8,";s.tl(this,"o","Successful Registration")})},
394339,[393475],244955,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("coupon-used",function(){var s=window.s;s.prop32="coupon-used";try{s.prop33=s.pageName+"\x3ecoupon-used"}catch(e){s.prop33=""}try{s.eVar29=Bootstrapper.couponCode}catch(e){s.eVar29=""}s.prop25="D\x3dv29";s.events="event37";s.linkTrackVars="prop32,prop33,eVar29,prop25,events";s.linkTrackEvents=""+"event37";s.tl(this,"o","coupon used")})},
394337,[393475],244935,[244890]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),i.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));
if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")}},i={hidden:[],getTimeout:function(){return 5},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},init:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},traverse:function(b,a,c){if(1==
c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(var e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);try{f.oldStyle=f.style.display,f.style.display="none",b.style.display=b.oldStyle}catch(g){}b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);Bootstrapper.hasDOMParsed()||setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,
b,c)}}(b,a,c),50);return}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.MVT.addModule("mag360",{init:function(a){Bootstrapper.loadScriptCallback("//"+a.d+".magnify360.com/m360lib.js",function(a){return function(){Bootstrapper.loadScriptCallback("//"+a.d+".magnify360.com/j/"+a.a+"/"+a.c+"/360.js",function(){Bootstrapper.showBody=setInterval(function(){if(document.body==null)return;clearInterval(Bootstrapper.showBody);document.body.style.display=document.body.oldStyle||""},100)})}}(a))},
swap:function(a,b){}});Bootstrapper.getElementByXPath=function(xPath){window.currentNode="";var path=xPath.split("/");var node=Bootstrapper.getElementByXPathStep(document,path[1]);for(var i=2;i<path.length;i++){num=path[i].match(/\[/i)?path[i].match(/\[(\d)\]/i)[1]:0;path[i]=path[i].match(/\[/i)?path[i].match(/(\w+)/i)[1]:path[i];node=Bootstrapper.getElementByXPathStep(node,path[i],num)}return node};Bootstrapper.getElementByXPathStep=function(parent,eType,eNum){if(!parent)parent=document;if(eType.match(/\[/)){eNum=
eType.match(/\d+/)[0];eNum--;eType=eType.match(/\w+/)[0]}else if(!eNum)eNum=0;else eNum--;var child=parent.firstChild;if(!child)return null;var count=0;while(child){if(child.nodeType==1)if(child.tagName.toLowerCase()==eType.toLowerCase()&&count==eNum)return child;else if(child.tagName.toLowerCase()==eType.toLowerCase())count++;child=child.nextSibling}return null}},393538,244953);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("prod-registration",function(){var s=window.s;s.events="event9";s.eVar44="product registration";try{s.eVar22=Bootstrapper.prodRegistered}catch(e){s.eVar22=""}s.eVar21="product registration";s.linkTrackVars="events,eVar44,eVar22,eVar21";s.linkTrackEvents=""+"event9";s.tl(this,"o","product registration")})},394315,[393475],244863,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("print-click",function(){var s=window.s;s.prop32="print-click";try{s.prop33=s.pageName+"\x3eprint-click"}catch(e){s.prop33=""}s.events="event28";try{s.eVar33=Bootstrapper.printItem}catch(e){s.eVar33=""}s.eVar34="+1";s.linkTrackVars="prop32,prop33,events,eVar33,eVar34";s.linkTrackEvents=""+"event28";s.tl(this,"o",this.textContent||
this.innerText||"print-click")})},394334,[393475],244923,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("set-new-locale",function(){var s=window.s;s.prop32="set-new-locale";try{s.prop33=s.pageName+" \x3c set-new-locale"}catch(e){s.prop33=""}s.events="event18";s.linkTrackVars="prop32,prop33,events";s.linkTrackEvents=""+"event18";s.tl(this,"o","set-new-locale")})},394329,[393475],244904,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("top-nav-click",function(){var s=window.s;try{s.prop32=Bootstrapper.topNavLinkName}catch(e){s.prop32=""}try{s.prop33=Bootstrapper.topNavLinkName+"\x3e"+s.pageName}catch(e){s.prop33=""}s.linkTrackVars="prop32,prop33";s.linkTrackEvents="";s.tl(this,"o",this.textContent||this.innerText||"top-nav-click")})},394322,[393475],244896,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("outlet-center-click",function(){var s=window.s;s.events="event56";s.prop32="outlet-center-click";try{s.prop33=s.pageName+"\x3eoutlet-center-click"}catch(e){s.prop33=""}s.linkTrackVars="events,prop32,prop33";s.linkTrackEvents=""+"event56";s.tl(this,"o","outlet-center-click")})},394332,[393475],244920,[244890]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack=function(){var _private={clearSC:function(){var vars=s.linkTrackVars.split(",");for(var i=0;i<vars.length;i++){if(s[vars[i]])s[vars[i]]="";s.linkTrackVars=s.events=s.linkTrackEvents=""}return true},links:{},pushTrack:function(name,fn){if(typeof name!="string")return false;this.links[name]=this.links[name]||[];if(typeof fn=="function")this.links[name].push(fn);
return true},callTrack:function(name){if(typeof name!="string")return false;var l=_private.links[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)}},_public={addLink:function(name,fn){return _private.pushTrack(name,fn)},addTracking:function(name,fn){return _private.pushTrack(name,fn)},getLink:function(name){return _private.links[name]},track:function(name){var ret=_private.callTrack.call(this,name);_private.clearSC();return ret}};return _public}();Bootstrapper.attachLink=
function(node,name,event){if(node==undefined||node==null||typeof name!="string")return false;event=event||"onclick";Bootstrapper.unobtrusiveAddEvent(node,event,function(){Bootstrapper.linkTrack.track.call(this,name)})}},393475,244890);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.addDownloadTracking=function(){var fileTypes=[".exe",".pdf",".pkg",".dmg",".zip",".bin",".iso",".tar",".bz2",".img"];var links=window.document.getElementsByTagName("a");var exten="";for(var i=0;i<links.length;i++){var fn="";for(var k=0;k<fileTypes.length;k++)if(links[i].href.toLowerCase().indexOf(fileTypes[k])>-1){exten=fileTypes[k];fn=links[i].href.toString();
break}if(fn!="")if(Bootstrapper.isTracked(links[i])==false)Bootstrapper.unobtrusiveAddEvent(links[i],"onclick",function(filename,exten){return function(){filename=unescape(filename);Bootstrapper.fileType=exten||"Unknown";Bootstrapper.clickedFilename=filename||"Unknown";Bootstrapper.linkTrack.track.call(this,"download-click")}}(fn,exten))}};Bootstrapper.addTrackingAfterPageLoad=function(){setTimeout("Bootstrapper.addDownloadTracking()",1500)};Bootstrapper.addBasicTabTracking=function(){var links=window.document.getElementsByTagName("a");
for(var i=0;i<links.length;i++){var tab=links[i];if(tab.id){var append="";if(tab.id.indexOf("tab-")>-1){if(tab.children.length==0)append=tab.innerHTML.trim();else append=tab.id.substring(tab.id.lastIndexOf("-")+1);Bootstrapper.unobtrusiveAddEvent(tab,"onclick",function(append){return function(){Bootstrapper.pageView(append)}}(append))}}}};Bootstrapper.pageView=function(append){if(Bootstrapper.valid(append)&&Bootstrapper.valid(Bootstrapper.originalPageName)){if(Bootstrapper.originalPageName.lastIndexOf(":")==
Bootstrapper.originalPageName.length-1)s.pageName=s.prop45=s.eVar45=Bootstrapper.originalPageName+append;else s.pageName=s.prop45=s.eVar45=Bootstrapper.originalPageName+":"+append;s.events="event36"}s.t();Bootstrapper.addTrackingAfterPageLoad()};Bootstrapper.addLinkVars=function(name){if(s.linkTrackVars=="")s.linkTrackVars="prop32,prop33";else s.linkTrackVars+=",prop32,prop33";s.prop32=name;s.prop33=s.pageName+"\x3e"+name};Bootstrapper.trackLink=function(name,type){if(s.linkTrackVars=="")s.linkTrackVars=
"prop32,prop33";else s.linkTrackVars+=",prop32,prop33";s.prop32=name;s.prop33=window.s.pageName+"\x3e"+name;s.tl(this,type,name);Bootstrapper.clearLinkVars()};Bootstrapper.setPageName=function(pagename){Bootstrapper.pn=pagename};Bootstrapper.setMPageName=function(mPagename){Bootstrapper.mpn=mPagename}},393439,244857);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("customize-product-click",function(){var s=window.s;s.prop32="customize-product";try{s.prop33=s.pageName+"\x3ecustomize-product"}catch(e){s.prop33=""}s.events="event20";s.linkTrackVars="prop32,prop33,events";s.linkTrackEvents=""+"event20";s.tl(this,"o",this.textContent||this.innerText||"")})},394328,[393475],244907,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("download-click",function(){var s=window.s;try{s.prop7=Bootstrapper.clickedFilename}catch(e){s.prop7=""}try{s.eVar7=Bootstrapper.clickedFilename}catch(e){s.eVar7=""}s.events="event4";s.eVar54="+1";try{s.prop34=s.pageName+"\x3edownload\x3e"+Bootstrapper.fileType}catch(e){s.prop34=""}s.linkTrackVars="prop7,eVar7,events,eVar54,prop34";
s.linkTrackEvents=""+"event4";s.tl(this,"d",this.textContent||this.innerText||"download")})},394313,[393475],244864,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("support-request-click",function(){var s=window.s;s.events="event3";try{s.eVar2=Bootstrapper.requestClickType}catch(e){s.eVar2=""}s.linkTrackVars="events,eVar2";s.linkTrackEvents=""+"event3";s.tl(this,"o",this.textContent||this.innerText||"")})},394320,[393475],244894,[244890]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;try{var pathName=document.location.pathname.split("/");Bootstrapper.urlPath=new Array;for(var i=0;i<pathName.length;i++)if(pathName[i]!="")Bootstrapper.urlPath.push(pathName[i]);if(Bootstrapper.urlPath.length>=2)if(Bootstrapper.urlPath[0].length==2&&Bootstrapper.urlPath[1].length==2)Bootstrapper.urlPath.splice(0,2)}catch(e){}},393477,244892);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.adwordsConversion=function(id,language,format,color,label,value){if(typeof window.google_trackConversion!="function")Bootstrapper.loadScriptCallback("//www.googleadservices.com/pagead/conversion_async.js",function(){window.google_trackConversion({google_conversion_id:id,google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,
google_conversion_label:label,google_conversion_value:value||0})});else window.google_trackConversion({google_conversion_id:id,google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,google_conversion_label:label,google_conversion_value:value||0})};Bootstrapper.googleAdWords=function(id,language,format,color,label,value){if(typeof window.google_trackConversion!="function")Bootstrapper.loadScriptCallback("//www.googleadservices.com/pagead/conversion_async.js",
function(){window.google_trackConversion({google_conversion_id:id,google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,google_conversion_label:label,google_conversion_value:value||0})});else window.google_trackConversion({google_conversion_id:id,google_conversion_language:language,google_conversion_format:format,google_conversion_color:color,google_conversion_label:label,google_conversion_value:value||0})};Bootstrapper.loadScriptCallbackId=function(src,
callback,id){var scripts=document.getElementsByTagName("script"),i,s=scripts[0];var newScript=document.createElement("script");newScript.type="text/javascript";newScript.async=true;newScript.src=src;newScript.id=id;newScript.onerror=function(){if(this.addEventListener)this.readyState="loaded"};newScript.onload=newScript.onreadystatechange=function(){if(!this.readyState||this.readyState==="complete"||this.readyState==="loaded"){this.onload=null;if(this.addEventListener)this.readyState="loaded";try{callback.call(this)}catch(e){window[ensightenOptions.ns].reportException(e)}}};
s.parentNode.insertBefore(newScript,s)}},393499,244914);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("product-finder-click",function(){var s=window.s;try{s.eVar19=Bootstrapper.productFinderSpecs}catch(e){s.eVar19=""}s.events="event21";s.eVar23="+1";s.linkTrackVars="eVar19,events,eVar23";s.linkTrackEvents=""+"event21";s.tl(this,"o",this.textContent||this.innerText||"")})},394330,[393475],244903,[244890]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.linkTrack.addLink("log-in-srs-partner-link",function(){var s=window.s;if(Bootstrapper.logInType=="consumer")s.eVar44="srs consumer log in";if(Bootstrapper.logInType=="standard partner")s.eVar44="srs partner log in";if(Bootstrapper.logInType=="silver")s.eVar44="silver log in";if(Bootstrapper.logInType=="gold")s.eVar44="gold ";if(Bootstrapper.logInType==
"standard partner")s.events="event10";if(Bootstrapper.logInType=="consumer")s.events="event11";s.linkTrackVars="eVar44,eVar44,eVar44,eVar44,events,events";s.linkTrackEvents=""+"event10,"+"event11,";s.tl(this,"o","log-in-srs-partner-link")})},394348,[393475],245007,[244890]);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();