(function(){/*

SPF
(c) 2012-2014 Google, Inc.
License: MIT
*/
function m(a,b,c){var d=Array.prototype.slice.call(arguments,2);return function(){var c=d.slice();c.push.apply(c,arguments);return a.apply(b,c)}}function aa(a,b){if(a){var c=Array.prototype.slice.call(arguments,1);try{return a.apply(null,c)}catch(d){return d}}}function n(a,b){if(document.createEvent){var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!0,!0,b);return document.dispatchEvent(c)}return!0}function p(){return(new Date).getTime()}function ba(){};function ca(a){return a.classList?a.classList:a.className&&a.className.match(/\S+/g)||[]}function da(a,b){if(a.classList)return a.classList.contains(b);for(var c=ca(a),d=0,e=c.length;d<e;d++)if(c[d]==b)return!0;return!1}function ea(a,b){a.classList?a.classList.add(b):da(a,b)||(a.className+=" "+b)}function fa(a,b){if(a.classList)a.classList.remove(b);else{for(var c=ca(a),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ")}};function q(a,b){return r[a]=b}var r=window._spf_state||{};window._spf_state=r;function t(a,b){if(a.forEach)a.forEach(b,void 0);else for(var c=0,d=a.length;c<d;c++)c in a&&b.call(void 0,a[c],c,a)}function ga(a,b){if(a.every)return a.every(b,void 0);for(var c=0,d=a.length;c<d;c++)if(c in a&&!b.call(void 0,a[c],c,a))return!1;return!0}function ha(a,b){if(a.filter)return a.filter(b,void 0);var c=[];t(a,function(a,e,f){b.call(void 0,a,e,f)&&c.push(a)});return c}
function ia(a,b){if(a.map)return a.map(b,void 0);var c=[];c.length=a.length;t(a,function(a,e,f){c[e]=b.call(void 0,a,e,f)});return c}function u(a){return"[object Array]"==Object.prototype.toString.call(a)?a:[a]};var ja={"animation-class":"spf-animate","animation-duration":425,"cache-lifetime":6E5,"cache-max":50,"cache-unified":!1,"link-class":"spf-link","nolink-class":"spf-nolink","navigate-limit":20,"navigate-lifetime":864E5,"reload-identifier":null,"request-timeout":0,"url-identifier":"?spf=__type__"},v={};"config"in r||q("config",v);v=r.config;function ka(a,b){var c=b||document;return c.querySelectorAll?c.querySelectorAll(a):[]}function la(a){var b,c=a.parentNode;if(c&&11!=c.nodeType)if(a.removeNode)a.removeNode(!1);else{for(;b=a.firstChild;)c.insertBefore(b,a);c.removeChild(a)}}function ma(a,b,c){for(;a;){if(b(a))return a;if(c&&a==c)break;a=a.parentNode}return null}
function na(a,b,c){b=b||document;var d=b.createElement("iframe");d.id=a||"";d.src='javascript:""';d.style.display="none";c&&(d.onload=m(c,null,d));b.body.appendChild(d);return d};function oa(a,b,c,d){var e=d||{},f=!1,h=0,g,k=new XMLHttpRequest;k.open(a,b,!0);k.timing={};var l=k.abort;k.abort=function(){clearTimeout(g);k.onreadystatechange=null;l.call(k)};k.onreadystatechange=function(){var a=k.timing;if(2==k.readyState){a.responseStart=a.responseStart||p();f=-1<(k.getResponseHeader("Transfer-Encoding")||"").toLowerCase().indexOf("chunked");if(!f){var a=k.getResponseHeader("X-Firefox-Spdy"),c=window.chrome&&chrome.loadTimes&&chrome.loadTimes(),c=c&&c.wasFetchedViaSpdy;f=!(!a&&
!c)}e.A&&e.A(k)}else 3==k.readyState?f&&e.n&&(a=k.responseText.substring(h),h=k.responseText.length,e.n(k,a)):4==k.readyState&&(a.responseEnd=a.responseEnd||p(),window.performance&&window.performance.getEntriesByName&&(k.resourceTiming=window.performance.getEntriesByName(b).pop()),f&&e.n&&k.responseText.length>h&&(a=k.responseText.substring(h),h=k.responseText.length,e.n(k,a)),clearTimeout(g),e.w&&e.w(k))};a="POST"==a;if(e.headers)for(var E in e.headers)k.setRequestHeader(E,e.headers[E]),"content-type"==
E.toLowerCase()&&(a=!1);a&&k.setRequestHeader("Content-Type","application/x-www-form-urlencoded");0<e.F&&(g=setTimeout(function(){k.abort();e.B&&e.B(k)},e.F));k.timing.fetchStart=p();k.send(c);return k};function w(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}var pa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s+|\s+$/g,"")};function x(a,b){var c=a.split(b),d=1==c.length;return[c[0],d?"":b,d?"":c.slice(1).join(b)]};function qa(a){var b=y();a in b&&delete b[a]}function ra(){var a=y(),b;for(b in a)sa(a[b])||delete a[b];a=y();b=parseInt(v["cache-max"],10);b=isNaN(b)?Infinity:b;b=Object.keys(a).length-b;if(!(0>=b))for(var c=0;c<b;c++){var d=Infinity,e,f;for(f in a)a[f].count<d&&(e=f,d=a[f].count);delete a[e]}}function sa(a){if(!(a&&"data"in a))return!1;var b=a.life,b=isNaN(b)?Infinity:b;return p()-a.time<b}function ta(a){var b=parseInt(r["cache-counter"],10)||0;b++;q("cache-counter",b);a.count=b}
function y(a){return!a&&"cache-storage"in r?r["cache-storage"]:q("cache-storage",a||{})};function ua(a,b,c){var d=null,e=window.history.state;if(e){var d={},f;for(f in e)d[f]=e[f]}if(b)for(f in d=d||{},b)d[f]=b[f];va(!0,a,d,c)}function va(a,b,c,d){if(b||c){b=b||window.location.href;c=c||{};var e=p();q("history-timestamp",e);c["spf-timestamp"]=e;if(a)wa(c,b);else if(a=xa().contentWindow.history.pushState,"function"==typeof a)a.call(window.history,c,"",b);else throw Error("history.pushState is not a function.");q("history-url",b);d&&(d=r["history-callback"])&&d(b,c)}}
function ya(a){var b=window.location.href;if(r["history-ignore-pop"])q("history-ignore-pop",!1);else if(a.state){a=a.state;var c=a["spf-timestamp"];b==r["history-url"]?(q("history-timestamp",c),wa(a,b)):(a["spf-back"]=c<parseInt(r["history-timestamp"],10),a["spf-current"]=r["history-url"],q("history-timestamp",c),q("history-url",b),(c=r["history-callback"])&&c(b,a))}}
function wa(a,b){var c=xa().contentWindow.history.replaceState;if("function"==typeof c)c.call(window.history,a,"",b);else throw Error("history.replaceState is not a function");}function xa(){var a=document.getElementById("history-iframe");a||(a=na("history-iframe"));return a};function za(a,b){a&&b&&(a in z||(z[a]=[]),z[a].push(b))}function Aa(a,b){a in z&&b&&ga(z[a],function(a,d,e){return a==b?(e[d]=null,!1):!0})}function Ba(a){a in z&&t(z[a],function(a,c,d){d[c]=null;a&&a()})}var z={};"ps-s"in r||q("ps-s",z);z=r["ps-s"];function A(a,b,c){var d=B[a];return a&&b?(d||(d=B[a]={items:[],l:0,i:0,p:1}),d.items.push({u:b,q:c||0})):d&&d.items.length||0}function C(a,b){var c=B[a];if(c){var d=!!c.l||!!c.i;0<c.p&&(b||!d)&&Ca(a,b)}}function D(a){(a=B[a])&&a.p--}function F(a,b){var c=B[a];c&&(c.p++,C(a,b))}function Da(a){var b=B[a];b&&(Ea(b),delete B[a])}function Fa(a){var b=parseInt(r.uid,10)||0;b++;return a["spf-key"]||(a["spf-key"]=""+q("uid",b))}
function Ca(a,b){var c=B[a];if(c&&(Ea(c),0<c.p&&c.items.length)){var d=c.items[0];if(d){var e=m(function(a,b){b();a()},null,m(Ca,null,a,b));b?(c.items.shift(),e(d.u)):Ga(c,d,e)}}}function Ga(a,b,c){b.q?(c=m(c,null,ba),a.i=setTimeout(c,b.q),b.q=0):(a.items.shift(),c=m(c,null,b.u),(b=(b=v["advanced-task-scheduler"])&&b.addTask)?a.l=b(c):a.i=setTimeout(c,0))}function Ea(a){if(a.l){var b=v["advanced-task-scheduler"];(b=b&&b.cancelTask)&&b(a.l);a.l=0}a.i&&(clearTimeout(a.i),a.i=0)}var B={};function G(a){var b=document.createElement("a");b.href=a;b.href=b.href;a={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:b.port,pathname:b.pathname,search:b.search,hash:b.hash,J:b.J,H:b.H};a.origin=a.protocol+"//"+a.host;a.pathname&&"/"==a.pathname[0]||(a.pathname="/"+a.pathname);return a}function H(a,b){var c=G(a);return b?c.href:x(c.href,"#")[0]}
function Ha(a,b){var c=x(a,"#");a=c[0];for(var d=0;d<b.length;d++)a=a.replace(new RegExp("([?&])"+b[d]+"(?:=[^&]*)?(?:(?=[&])|$)","g"),function(a,b){return"?"==b?b:""});w(a,"?")&&(a=a.slice(0,-1));return a+c[1]+c[2]}function Ia(a){var b=v["advanced-persistent-parameters"]||"",c=x(a,"#");a=c[0];var d=-1!=a.indexOf("?")?"&":"?";return a+(b?d+b:"")+c[1]+c[2]};function Ja(a,b,c,d){var e="js"==a;b=I(a,b);var f=c||"^"+b,h=J(a,f),g;c&&(g=K(a,c))&&b!=g&&(n(e?"spfjsbeforeunload":"spfcssbeforeunload",{name:c,url:g}),e=g,Ka(a,c),e&&La(a,e),e=J(a,c),delete z[e],za(h,m(Ma,null,a,c,g)));e=J(a,b);if((e=L[e])&&f!=e){Ka(a,e);La(a,b);var k=J(a,e);k&&h&&k in z&&(z[h]=(z[h]||[]).concat(z[k]),delete z[k])}k=J(a,b);L[k]=f;Na(a,f,b);za(h,d);d=m(Oa,null,a);M(a,b)?(e&&f!=e&&(a=Pa(a,b))&&a.setAttribute("name",c||""),d()):(a=Qa(a,b,d,void 0,void 0,g))&&c&&a.setAttribute("name",
c)}function Ra(a,b){var c=K(a,b);Ka(a,b);c&&La(a,c);var d=J(a,b);delete z[d];Ma(a,b,c)}function Ma(a,b,c){c&&(n("js"==a?"spfjsunload":"spfcssunload",{name:b,url:c}),Sa(a,c))}function Oa(a){var b=J(a,""),c;for(c in z)0==c.indexOf(b)&&ga(c.substring(b.length).split("|"),m(Ta,null,a))&&Ba(c)}
function Qa(a,b,c,d,e,f){function h(){M(a,b,e)&&Ua(2,a,b,e);g&&l&&l.parentNode&&k==document&&l.parentNode.removeChild(l);c&&setTimeout(c,0);return null}var g="js"==a;b=I(a,b);Ua(1,a,b,e);var k=d||document,l=k.createElement(g?"script":"link");if(!b)return h();d=N(b);l.className=J(a,d);"onload"in l?l.onerror=l.onload=h:l.onreadystatechange=function(){/^c|loade/.test(l.readyState)&&h()};d=k.getElementsByTagName("head")[0]||k.body;g?(l.async=!0,l.src=b,d.insertBefore(l,d.firstChild)):(l.rel="stylesheet",
l.href=b,(f=f&&Pa(a,f,d))?d.insertBefore(l,f):d.appendChild(l));return l}function Sa(a,b){b=I(a,b);var c=Pa(a,b,void 0);c&&c.parentNode&&c.parentNode.removeChild(c);c=J(a,b);delete O[c]}function Pa(a,b,c){b=N(b);a="."+J(a,b);return ka(a,c)[0]}function Va(a){var b="js"==a,c=[];t(ka(b?"script[src]":'link[rel~="stylesheet"]'),function(d){var e=b?d.src:d.href,e=I(a,e);if(!M(a,e)){Ua(2,a,e);var f=N(e),f=J(a,f);ea(d,f);if(f=d.getAttribute("name")){var h=J(a,e);L[h]=f;Na(a,f,e)}c.push(d)}})}
function Wa(a,b){if(b&&(b=I(a,b),!M(a,b))){var c=N(b),d=J(a,c),e=J(a,"prefetch"),c=document.getElementById(e);if(!c)c=na(e,null,function(a){a.title=e;C(e,!0)});else if(c.contentWindow.document.getElementById(d))return;d=m(Xa,null,c,a,b,d,e);c.title?d():A(e,d)}}
function Xa(a,b,c,d,e){var f="css"==b;a=a.contentWindow.document;"js"==b?(b=a.createElement("object"),Ya?a.createElement("script").src=c:b.data=c,b.id=d,a.body.appendChild(b)):f?(b=Qa(b,c,null,a,e),b.id=d):(b=a.createElement("img"),b.src=c,b.id=d,a.body.appendChild(b))}
function Za(a,b,c){for(var d="js"==a,e=K(a,c),f=b.replace(/\s/g,""),f=f||"",h=0,g=0,k=f.length;g<k;++g)h=31*h+f.charCodeAt(g),h%=4294967296;f="hash-"+h;Na(a,c,f);!$a(a,f)&&(b=ab(a,b))&&(Ua(2,a,f),b&&!d&&(d=N(f),d=J(a,d),b.className=d,b.setAttribute("name",c)),(e=e&&e[0])&&Sa(a,e))}
function ab(a,b){b=pa(b);if(!b)return null;var c=document.getElementsByTagName("head")[0]||document.body,d;"js"==a?(d=document.createElement("script"),d.text=b,c.appendChild(d),c.removeChild(d)):(d=document.createElement("style"),c.appendChild(d),"styleSheet"in d?d.styleSheet.cssText=b:d.appendChild(document.createTextNode(b)));return d}
function I(a,b){var c="rsrc-p-"+a;if(b){var d=b.indexOf("//");if(0>d){if(0==b.lastIndexOf("hash-",0))return b;c=r[c]||"";if("[object String]"==Object.prototype.toString.call(c))b=c+b;else for(var e in c)b=b.replace(e,c[e]);b=0>b.indexOf("."+a)?b+"."+a:b;b=H(b)}else 0==d&&(b=H(b))}return b}function J(a,b,c){return a+"-"+b+(c?"-"+c:"")}function N(a){return a?String(a).replace(/[^\w]/g,""):""}function Ua(a,b,c,d){b=J(b,c,d);O[b]=a}function M(a,b,c){a=J(a,b,c);return O[a]}
function $a(a,b){var c=M(a,b);return""==b||2==c}function La(a,b){var c=J(a,b);delete L[c]}function Na(a,b,c){a=J(a,b);P[a]=c}function K(a,b){var c=J(a,b);return P[c]}function Ka(a,b){var c=J(a,b);delete P[c]}function Ta(a,b){var c=K(a,b);return void 0!=c&&$a(a,c)}var O={},L={},P={},Ya=-1!=navigator.userAgent.indexOf(" Trident/");"rsrc-s"in r||q("rsrc-s",O);O=r["rsrc-s"];"rsrc-n"in r||q("rsrc-n",L);L=r["rsrc-n"];"rsrc-u"in r||q("rsrc-u",P);P=r["rsrc-u"];function bb(a){a=u(a);t(a,function(a){Wa("img",a)})};function cb(a,b,c){Ja("js",a,b,c)}function db(a){Ra("js",a)}function eb(a,b){Qa("js",a,b)}function fb(a){a=u(a);t(a,function(a){Wa("js",a)})}function gb(a,b,c){a=u(a);a=ha(a,function(a){return!!a});var d=[];t(a,function(a){void 0==K("js",a)&&d.push(a)});var e=!d.length;if(b){var f=ga(a,m(Ta,null,"js"));e&&f?b():(a=J("js",a.sort().join("|")),za(a,b))}c&&!e&&c(d)}function hb(a,b){a=u(a);t(a,function(a){if(a){var b=Q[a]||a,b=I("js",b),e=K("js",a);e&&b!=e&&ib(a)}});gb(a,b,jb)}
function jb(a){t(a,function(a){function c(){cb(e,a)}var d=R[a],e=Q[a]||a;d?hb(d,c):c()})}function ib(a){a=u(a);t(a,function(a){var c=[],d;for(d in R){var e=R[d],e=u(e);t(e,function(e){e==a&&c.push(d)})}t(c,function(a){ib(a)});db(a)})}function kb(a,b){Za("js",a,b)}function lb(a){ab("js",a)}var R={};"js-d"in r||q("js-d",R);var R=r["js-d"],Q={};"js-u"in r||q("js-u",Q);Q=r["js-u"];function mb(a,b,c){Ja("css",a,b,c)}function nb(a,b){Qa("css",a,b)}function ob(a){a=u(a);t(a,function(a){Wa("css",a)})};function pb(a,b,c){if(b){var d=[],e;b=0;c&&(a+="\r\n");var f=a.indexOf("[\r\n",b);for(-1<f&&(b=f+3);-1<(f=a.indexOf(",\r\n",b));)e=pa(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e));f=a.indexOf("]\r\n",b);-1<f&&(e=pa(a.substring(b,f)),b=f+3,e&&d.push(JSON.parse(e)));e="";a.length>b&&(e=a.substring(b),c&&w(e,"\r\n")&&(e=e.substring(0,e.length-2)));return{k:d,b:e}}a=JSON.parse(a);"number"==typeof a.length?d=a:d=[a];return{k:d,b:""}}
function S(a,b,c,d,e){var f="process "+H(a),h=!v["experimental-process-async"],g;g=0;b.timing||(b.timing={});b.title&&(document.title=b.title);d&&b.url&&H(b.url)!=H(window.location.href)&&ua(b.url+window.location.hash);b.head&&(g=m(function(a,b){var c=T(a);qb(c);rb(c);D(f);sb(c,function(){b.spfProcessHead=p();F(f,h)})},null,b.head,b.timing),g=A(f,g));b.attr&&(g=m(function(a,b){for(var c in a){var d=document.getElementById(c);if(d){var e=a[c],f=void 0;for(f in e){var g=e[f];"class"==f?d.className=
g:"style"==f?d.style.cssText=g:d.setAttribute(f,g)}}}b.spfProcessAttr=p()},null,b.attr,b.timing),g=A(f,g));d=b.body||{};var k=g,l;for(l in d)g=m(function(a,b){var c=document.getElementById(a);if(c){var d=T(b),g=v["animation-class"];if(tb&&da(c,g)){D(f);var k=Fa(c);C(k,!0);g={r:d,reverse:!!e,e:null,h:null,g:c,G:g+"-old",I:g+"-new",D:e?g+"-reverse-start":g+"-forward-start",t:e?g+"-reverse-end":g+"-forward-end"};c=m(function(a){rb(a.r);ea(a.g,a.D);a.e=document.createElement("div");a.e.className=a.G;
var b=a.g,c=a.e;if(c){for(var d;d=b.firstChild;)c.appendChild(d);b.appendChild(c)}a.h=document.createElement("div");a.h.className=a.I;a.h.innerHTML=a.r.j;a.reverse?(b=a.e,b.parentNode.insertBefore(a.h,b)):(b=a.e,b.parentNode.insertBefore(a.h,b.nextSibling))},null,g);A(k,c,0);c=m(function(a){fa(a.g,a.D);ea(a.g,a.t)},null,g);A(k,c,0);c=m(function(a){a.g.removeChild(a.e);fa(a.g,a.t);la(a.h);D(k);sb(a.r,function(){F(k)})},null,g);A(k,c,parseInt(v["animation-duration"],10));c=m(function(a,b){F(b)},null,
g,f);A(k,c);C(k)}else{rb(d);var l=function(){D(f);sb(d,function(){F(f,h)})};(g=v["experimental-html-handler"])?(D(f),g(d.j,c,function(){l();F(f,h)})):(c.innerHTML=d.j,l())}}},null,l,d[l],b.timing),g=A(f,g);l=g-k;b.foot?(g=m(function(a,b,c){c&&(b.spfProcessBody=p());a=T(a);rb(a);D(f);sb(a,function(){b.spfProcessFoot=p();F(f,h)})},null,b.foot,b.timing,l),g=A(f,g)):l&&(g=m(function(a){a.spfProcessBody=p()},null,b.timing),g=A(f,g));c&&(g=A(f,m(c,null,a,b)));C(f,h)}
function ub(a,b,c){var d="preprocess "+H(a),e;b.head&&(e=m(function(a){a=T(a);qb(a);vb(a);wb(a)},null,b.head),A(d,e));var f=b.body||{},h;for(h in f)f[h]&&(e=m(function(a,b){var c=T(b);vb(c);wb(c)},null,h,f[h]),A(d,e));b.foot&&(e=m(function(a){a=T(a);vb(a);wb(a)},null,b.foot),A(d,e));c&&A(d,m(c,null,a,b));C(d)}
function T(a){var b=new xb;if(!a)return b;if("[object String]"!=Object.prototype.toString.call(a))return a.scripts&&t(a.scripts,function(a){b.d.push({url:a.url||"",text:a.text||"",name:a.name||"",async:a.async||!1})}),a.styles&&t(a.styles,function(a){b.a.push({url:a.url||"",text:a.text||"",name:a.name||""})}),a.links&&v["experimental-preconnect"]&&t(a.links,function(a){"spf-preconnect"==a.rel&&b.m.push({url:a.url||"",rel:a.rel||""})}),b.j=a.html||"",b;a=a.replace(yb,function(a,d,e,f){return"script"==
d?(a=(a=e.match(zb))?a[1]:"",d=(d=e.match(Ab))?d[1]:"",e=Bb.test(e),b.d.push({url:d,text:f,name:a,async:e}),""):"style"==d?(a=(a=e.match(zb))?a[1]:"",b.a.push({url:"",text:f,name:a}),""):a});a=a.replace(Cb,function(a,d){var e=d.match(Db),e=e?e[1]:"";if("stylesheet"==e){var e=(e=d.match(zb))?e[1]:"",f=d.match(Eb),f=f?f[1]:"";b.a.push({url:f,text:"",name:e});return""}return"spf-preconnect"==e&&v["experimental-preconnect"]?(f=(f=d.match(Eb))?f[1]:"",b.m.push({url:f,rel:e}),""):a});b.j=a;return b}
function sb(a,b){if(0>=a.d.length)b&&b();else{var c=-1,d=function(){c++;if(c<a.d.length){var e=a.d[c],f=function(){};e.url?f=e.name?m(cb,null,e.url,e.name):m(eb,null,e.url):e.text&&(f=e.name?m(kb,null,e.text,e.name):m(lb,null,e.text));e.url&&!e.async?f(d):(f(),d())}else b&&b()};d()}}function wb(a){0>=a.d.length||(a=ia(a.d,function(a){return a.url}),fb(a))}
function rb(a){if(!(0>=a.a.length))for(var b=0,c=a.a.length;b<c;b++){var d=a.a[b];d.url?d.name?mb(d.url,d.name):nb(d.url):d.text&&(d.name?Za("css",d.text,d.name):ab("css",d.text))}}function vb(a){0>=a.a.length||(a=ia(a.a,function(a){return a.url}),ob(a))}function qb(a){0>=a.m.length||(a=ia(a.m,function(a){return"spf-preconnect"==a.rel?a.url:""}),bb(a))}function xb(){this.j="";this.d=[];this.a=[];this.m=[]}
var tb=function(){var a=document.createElement("div");if("transition"in a.style)return!0;for(var b=["webkit","Moz","Ms","O","Khtml"],c=0,d=b.length;c<d;c++)if(b[c]+"Transition"in a.style)return!0;return!1}(),Cb=/\x3clink([\s\S]*?)\x3e/ig,yb=/\x3c(script|style)([\s\S]*?)\x3e([\s\S]*?)\x3c\/\1\x3e/ig,Bb=/(?:\s|^)async(?:\s|=|$)/i,Eb=/(?:\s|^)href\s*=\s*["']?([^\s"']+)/i,zb=/(?:\s|^)name\s*=\s*["']?([^\s"']+)/i,Db=/(?:\s|^)rel\s*=\s*["']?([^\s"']+)/i,Ab=/(?:\s|^)src\s*=\s*["']?([^\s"']+)/i;function Fb(a,b){var c=b||{};c.method=((c.method||"GET")+"").toUpperCase();c.type=c.type||"request";var d=a,e=v["url-identifier"]||"";if(e){var e=e.replace("__type__",c.type||""),f=x(d,"#"),h=x(f[0],"?"),d=h[0],g=h[1],h=h[2],k=f[1],f=f[2];if(0==e.lastIndexOf("?",0))g&&(e=e.replace("?","&")),h+=e;else{if(0==e.lastIndexOf(".",0))if(w(d,"/"))e="index"+e;else{var l=d.lastIndexOf(".");-1<l&&(d=d.substring(0,l))}else w(d,"/")&&0==e.lastIndexOf("/",0)&&(e=e.substring(1));d+=e}d=d+g+h+k+f}e=H(d);d={};d.spfUrl=
e;d.startTime=p();d.fetchStart=d.startTime;n:{h=Gb(a,c.current,null,c.type,!1);k=c.current;g=[];k&&(g.push(h+" previous "+k),g.push(h+" previous "+G(k).pathname));g.push(h);h=0;for(k=g.length;h<k;h++){r:{f=g[h];l=y();if(f in l){l=l[f];if(sa(l)){ta(l);f=l.data;break r}qa(f)}f=void 0}if(f){g={key:g[h],response:f.response,type:f.type};break n}}g=null}d.spfPrefetched=!!g&&"prefetch"==g.type;d.spfCached=!!g;if(g)return setTimeout(m(Hb,null,a,c,d,g.key,g.response),0),null;g={};void 0!=c.C&&(g["X-SPF-Referer"]=
c.C);c.current&&(g["X-SPF-Previous"]=c.current);if(h=v["advanced-header-identifier"])g["X-SPF-Request"]=h.replace("__type__",c.type),g.Accept="application/json";h={v:!1,b:"",complete:[]};d=m(Ib,null,a,c,d,h);d={headers:g,F:v["request-timeout"],A:m(Jb,null,a,h),n:m(Kb,null,a,c,h),w:d,B:d};return"POST"==c.method?oa("POST",e,c.s,d):oa("GET",e,null,d)}
function Hb(a,b,c,d,e){var f=!1;c.responseStart=c.responseEnd=p();b.type&&0==b.type.lastIndexOf("navigate",0)&&(c.navigationStart=c.startTime,v["cache-unified"]||(qa(d),f=!0));if(b.c&&"multipart"==e.type){d=e.parts;for(var h=0;h<d.length;h++)b.c(a,d[h])}Lb(a,b,c,e,f)}function Jb(a,b,c){a=c.getResponseHeader("X-SPF-Response-Type")||"";b.v=-1!=a.toLowerCase().indexOf("multipart")}
function Kb(a,b,c,d,e,f){if(c.v){e=c.b+e;var h;try{h=pb(e,!0,f)}catch(g){d.abort();b.f&&b.f(a,g);return}if(b.c)for(d=0;d<h.k.length;d++)b.c(a,h.k[d]);c.complete=c.complete.concat(h.k);c.b=h.b}}
function Ib(a,b,c,d,e){if(e.timing)for(var f in e.timing)c[f]=e.timing[f];if(e.resourceTiming)if("load"==b.type)for(var h in e.resourceTiming)c[h]=e.resourceTiming[h];else if(window.performance&&window.performance.timing&&(f=window.performance.timing.navigationStart,f+e.resourceTiming.startTime>=c.startTime))for(var g in e.resourceTiming)h=e.resourceTiming[g],void 0!==h&&(w(g,"Start")||w(g,"End")||"startTime"==g)&&(c[g]=f+Math.round(h));"load"!=b.type&&(c.navigationStart=c.startTime);d.complete.length&&
(d.b=pa(d.b),d.b&&Kb(a,b,d,e,"",!0));var k;try{k=pb(e.responseText).k}catch(l){b.f&&b.f(a,l);return}if(b.c&&1<k.length)for(d=d.complete.length;d<k.length;d++)b.c(a,k[d]);if(1<k.length){var E;d=0;for(e=k.length;d<e;d++)g=k[d],g.cacheType&&(E=g.cacheType);k={parts:k,type:"multipart"};E&&(k.cacheType=E)}else k=1==k.length?k[0]:{};Lb(a,b,c,k,!0)}
function Lb(a,b,c,d,e){if(e&&"POST"!=b.method&&(e=Gb(a,b.current,d.cacheType,b.type,!0))){d.cacheKey=e;var f={response:d,type:b.type||""},h=parseInt(v["cache-lifetime"],10),g=parseInt(v["cache-max"],10);0>=h||0>=g||(g=y(),f={data:f,life:h,time:p(),count:0},ta(f),g[e]=f,setTimeout(ra,1E3))}d.timing=c;b.o&&b.o(a,d)}
function Gb(a,b,c,d,e){a=H(a);var f;v["cache-unified"]?f=a:"navigate-back"==d||"navigate-forward"==d?f="history "+a:"navigate"==d?f=(e?"history ":"prefetch ")+a:"prefetch"==d&&(f=e?"prefetch "+a:"");b&&"url"==c?f+=" previous "+b:b&&"path"==c&&(f+=" previous "+G(b).pathname);return f||""};function Mb(a){return ma(a,function(a){return da(a,v["link-class"])})}function Nb(a){return ma(a,function(a){return da(a,v["nolink-class"])})}function Ob(a,b){return ma(a,function(a){return a.href&&"img"!=a.tagName.toLowerCase()},b)}function Pb(a){if(a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||0<a.button)return null;var b=Mb(a.target);return!b||v["nolink-class"]&&Nb(a.target)?null:(a=Ob(a.target,b))?a.href:null}function Qb(a){return G(a).origin!=G(window.location.href).origin?!1:!0}
function Rb(){if(!r["nav-init"])return!1;var a=parseInt(r["nav-counter"],10)||0;a++;var b=parseInt(v["navigate-limit"],10),b=isNaN(b)?Infinity:b;if(a>b)return!1;a=parseInt(r["nav-init-time"],10);a--;a=p()-a;b=parseInt(v["navigate-lifetime"],10);b=isNaN(b)?Infinity:b;return a>b?!1:!0}function Sb(a){if(!a.defaultPrevented){var b=Pb(a);b&&(b=Ia(b),Qb(b)&&Rb()&&n("spfclick",{url:b,target:a.target})&&(Tb(b),a.preventDefault()))}}function Ub(a){var b=Pb(a);b&&setTimeout(function(){Vb(b)},0)}
function Wb(a,b){var c=!(!b||!b["spf-back"]),d=b&&b["spf-referer"],e=b&&b["spf-current"],f=b&&b["spf-position"],h=v["reload-identifier"];h&&(a=Ha(a,[h]));Qb(a)?Rb()?n("spfhistory",{url:a,referer:d,previous:e})&&Tb(a,null,e,d,!0,c,f):U(a,"1"):U(a,"9")}
function Tb(a,b,c,d,e,f,h){V();b=b||{};d=void 0==d?window.location.href:d;c=e?c:window.location.href;e=!!e;f=!!f;h=h||null;var g;n:{if(-1!=a.indexOf("#")&&(g=H(a),x(c||window.location.href,"#")[0]==g)){g=!1;break n}g=!0}if(g)if(Xb(a,d,c,b)){q("nav-counter",(parseInt(r["nav-counter"],10)||0)+1);Yb(a);g=H(a);var k="preprocess "+H(g),l;for(l in B)k!=l&&0==l.lastIndexOf("preprocess",0)&&Da(l);l=Zb()[g];q("nav-request",l);q("nav-promote",null);q("nav-promote-time",null);l&&4!=l.readyState?(c="preprocess "+
H(a),l="promote "+H(a),q("nav-promote",a),q("nav-promote-time",p()),Da(c),C(l,!0),e||$b(a,d,m(W,null,b))):(l=m(W,null,b),g=m(ac,null,b,f),h=m(bc,null,b,f,h,""),v["advanced-navigate-persist-timing"]||cc(),b=Fb(a,{method:b.method,c:g,f:l,o:h,s:b.postData,type:"navigate"+(e?f?"-back":"-forward":""),current:c,C:d}),q("nav-request",b),e||$b(a,d,l))}else U(a,"2");else e||$b(a,d,m(W,null,b)),dc(a,h)}
function dc(a,b){if(b)window.scroll.apply(null,b);else{var c=x(a,"#");c[2]?(c=document.getElementById(c[2]))&&c.scrollIntoView():window.scroll(0,0)}}function $b(a,b,c){try{ua(null,{"spf-position":[window.pageXOffset,window.pageYOffset]}),H(a,!0)!=window.location.href&&va(!1,a,{"spf-referer":b},void 0)}catch(d){V(),c(a,d)}}function W(a,b,c){q("nav-request",null);ec(b,c,a)&&U(b,"10",c)}
function ac(a,b,c,d){if(fc(c,d,a))if(d.reload)U(c,"5");else if(d.redirect)gc(a,d.redirect);else try{S(c,d,function(){hc(c,d,a)},!0,b)}catch(e){W(a,c,e)}else U(c,"3")}
function bc(a,b,c,d,e,f){q("nav-request",null);r["nav-promote"]==d&&(d=f.timing||{},d.navigationStart=r["nav-promote-time"],d.spfPrefetched=!0);d="multipart"==f.type;if(!d){if(!ic(e,f,a)){U(e,"4");return}if(f.reload){U(e,"5");return}if(f.redirect){gc(a,f.redirect);return}}try{S(e,d?{}:f,function(){dc(e,c);jc(e,f,a)},!0,b)}catch(h){W(a,e,h)}}function gc(a,b){try{b+=window.location.hash,ua(b,null,!0)}catch(c){V(),W(a,b,c)}}function V(){var a=r["nav-request"];a&&(a.abort(),q("nav-request",null))}
function X(a,b){var c;a&&(c=Array.prototype.slice.call(arguments),c[0]=a,c=aa.apply(null,c));return!1!==c}
function U(a,b,c){c=c?c.message:"";V();Yb();var d=b;c&&(d+=" Message: "+c);n("spfreload",{url:a,reason:d});v["experimental-remove-history"]&&window.location.href==a&&(q("history-ignore-pop",!0),window.history.back());setTimeout(function(){var c=v["reload-identifier"];if(c){var d={};d[c]=encodeURIComponent(b);var c=a,h=x(c,"#"),c=h[0],g=-1!=c.indexOf("?")?"&":"?",k;for(k in d)c+=g+k,d[k]&&(c+="="+d[k]),g="&";a=c+h[1]+h[2]}window.location.href=a},0)}
function kc(a,b,c){b=b||{};c=c||a;Xb(a,void 0,void 0,b,!0)&&Fb(a,{method:b.method,c:m(lc,null,!1,b,c),f:m(mc,null,!1,b,c),o:m(nc,null,!1,b,c),s:b.postData,type:"load"})}function Vb(a,b){a=Ia(a);oc(a,b)}function oc(a,b,c){b=b||{};c=c||a;var d=window.location.href;Xb(a,void 0,void 0,b,!0)&&(b=Fb(a,{method:b.method,c:m(lc,null,!0,b,c),f:m(mc,null,!0,b,c),o:m(nc,null,!0,b,c),s:b.postData,type:"prefetch",current:d}),a=H(a),Zb()[a]=b)}
function mc(a,b,c,d,e){a&&pc(d);a&&r["nav-promote"]==c?W(b,d,e):ec(d,e,b,!0)}function lc(a,b,c,d,e){if(fc(d,e,b,!0)){if(e.reload){if(!a)return;if(r["nav-promote"]==c){U(d,"5");return}}if(e.redirect)qc(a,b,c,e.redirect);else{if(a){var f=m(ac,null,b,!1,d,e),h="promote "+H(c);A(h,f);if(r["nav-promote"]==c){C(h,!0);return}}(a?ub:S)(d,e,function(){hc(d,e,b,!0)})}}}
function nc(a,b,c,d,e){var f="multipart"==e.type;if(!f){if(!ic(d,e,b,!0)){U(d,"4");return}if(e.reload){if(!a)return;if(r["nav-promote"]==c){U(d,"5");return}}if(e.redirect){qc(a,b,c,e.redirect);return}}var h="promote "+H(c);if(a){pc(d);if(r["nav-promote"]==c){A(h,m(bc,null,b,!1,null,c,d,e));C(h,!0);return}Da(h)}h=a?ub:S;try{h(d,f?{}:e,function(){jc(d,e,b,!0)})}catch(g){mc(a,b,c,d,g)}}
function qc(a,b,c,d){a=a?oc:kc;var e={};t("onError onRequest onPartProcess onPartDone onProcess onDone".split(" "),function(a){e[a]=b[a]});a(d,e,c)}function ec(a,b,c,d){a={url:a,err:b};(c=X((c||{}).onError,a))&&!d&&(c=n("spferror",a));return c}function Xb(a,b,c,d,e){a={url:a,referer:b,previous:c};(d=X((d||{}).onRequest,a))&&!e&&(d=n("spfrequest",a));return d}function fc(a,b,c,d){a={url:a,part:b};(c=X((c||{}).onPartProcess,a))&&!d&&(c=n("spfpartprocess",a));return c}
function hc(a,b,c,d){a={url:a,part:b};X((c||{}).onPartDone,a)&&!d&&n("spfpartdone",a)}function ic(a,b,c,d){a={url:a,response:b};(c=X((c||{}).onProcess,a))&&!d&&(c=n("spfprocess",a));return c}function jc(a,b,c,d){a={url:a,response:b};X((c||{}).onDone,a)&&!d&&n("spfdone",a)}function pc(a){a=H(a);var b=Zb(),c=b[a];c&&c.abort();delete b[a]}function Yb(a){var b=Zb();a=a&&H(a);for(var c in b)a!=c&&pc(c)}
var cc,rc=window.performance&&(window.performance.clearResourceTimings||window.performance.webkitClearResourceTimings||window.performance.mozClearResourceTimings||window.performance.msClearResourceTimings||window.performance.oClearResourceTimings);cc=rc?m(rc,window.performance):ba;function Zb(){return"nav-prefetches"in r?r["nav-prefetches"]:q("nav-prefetches",{})};function Y(){Va("js");Va("css");"complete"==document.readyState&&(document.removeEventListener?document.removeEventListener("DOMContentLoaded",Y,!1):document.detachEvent&&document.detachEvent("onreadystatechange",Y))}document.addEventListener?document.addEventListener("DOMContentLoaded",Y,!1):document.attachEvent&&document.attachEvent("onreadystatechange",Y);Y();
var sc={init:function(a){var b=!("function"!=typeof window.history.pushState&&!xa().contentWindow.history.pushState);a=a||{};for(var c in ja)v[c]=c in a?a[c]:ja[c];for(c in a)c in ja||(v[c]=a[c]);if(b){c=ec;if(!r["history-init"]&&window.addEventListener){a=window.location.href;window.addEventListener("popstate",ya,!1);q("history-init",!0);q("history-callback",Wb);q("history-error-callback",c);q("history-listener",ya);q("history-url",a);q("history-timestamp",p());var d={"spf-referer":document.referrer};
try{ua(a,d)}catch(e){c&&c(a,e)}}!r["nav-init"]&&document.addEventListener&&(document.addEventListener("click",Sb,!1),!v["experimental-prefetch-mousedown"]||"ontouchstart"in window||0<window.navigator.maxTouchPoints||0<window.navigator.msMaxTouchPoints||(document.addEventListener("mousedown",Ub,!1),q("prefetch-listener",Ub)),q("nav-init",!0),q("nav-init-time",p()),q("nav-counter",0),q("nav-listener",Sb))}return b},dispose:function(){"undefined"!=typeof History&&History.prototype.pushState&&(V(),r["nav-init"]&&
(document.removeEventListener&&(document.removeEventListener("click",r["nav-listener"],!1),v["experimental-prefetch-mousedown"]&&document.removeEventListener("mousedown",r["prefetch-listener"],!1)),q("nav-init",!1),q("nav-init-time",null),q("nav-counter",null),q("nav-listener",null)),r["history-init"]&&(window.removeEventListener&&window.removeEventListener("popstate",r["history-listener"],!1),q("history-init",!1),q("history-callback",null),q("history-error-callback",null),q("history-listener",null),
q("history-url",null),q("history-timestamp",0)));for(var a in v)delete v[a]},navigate:function(a,b){a&&(a=Ia(a),Qb(a)?Rb()?Tb(a,b):U(a,"1"):U(a,"9"))},load:function(a,b){a=Ia(a);kc(a,b)},prefetch:Vb,process:function(a,b){function c(a,c,d,e){a==c&&b&&b(e)}var d=window.location.href;if("multipart"==a.type)for(var e=a.parts,f=0;f<e.length;f++){var h=m(c,null,f,e.length-1);S(d,e[f],h)}else h=m(c,null,0,0),S(d,a,h)}},tc={cache:{remove:qa,clear:function(){y({})}},script:{load:cb,get:eb,ready:gb,done:function(a){Na("js",
a,"");Oa("js")},require:hb,declare:function(a,b){if(a){for(var c in a)R[c]=a[c];if(b)for(c in b)Q[c]=b[c]}},path:function(a){q("rsrc-p-js",a)},unload:db,ignore:function(a,b){a=u(a);var c=J("js",a.sort().join("|"));Aa(c,b)},unrequire:ib,prefetch:fb},style:{load:mb,get:nb,unload:function(a){Ra("css",a)},path:function(a){q("rsrc-p-css",a)},prefetch:ob}},uc=this.spf=this.spf||{},vc;for(vc in sc)uc[vc]=sc[vc];for(var Z in tc)for(var wc in tc[Z])uc[Z]=uc[Z]||{},uc[Z][wc]=tc[Z][wc];n("spfready");})();
