// Copyright (c) 2014 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(l){var f,b={_breaker:{},each:function(a,c){var e,d;if("object"===b.type(a)&&a.hasOwnProperty)for(e in a){if(a.hasOwnProperty(e)&&c(a[e],e)===b._breaker)break}else if(a){e=0;for(d=a.length;e<d&&c(a[e],e)!==b._breaker;e++);}},extend:function(a){var c,b,d,g,k=arguments.length;a=a||{};for(b=1;b<k;b++)if(g=arguments[b],void 0!==g&&null!==g)for(d in g)c=g[d],a!==c&&void 0!==c&&(a[d]=c);return a},noop:function(){},type:function(){var a=function(a,b){try{return("function"===typeof window[b]||"object"===
typeof window[b])&&a instanceof window[b]}catch(d){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},
all:function(a,c){var e="array"===b.type(a)?[]:{};b.each(a,function(a,g){c(a,g)&&("array"===b.type(e)?e.push(a):e[g]=a)});return e},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,b){return(c=a[c])?c.split(b||" "):[]},batchable:function(a,c){c=c||b.noop;var e=function(){return b.extend({batch:!0,timeout:100},c())},d=b.traits.cors&&b.traits.json,g=[],k=null,q=function(){null!==k&&(clearTimeout(k),k=null);1===g.length?a.apply(null,g[0].arguments):
1<g.length&&a.apply(null,g);g=[]},f=function(){g.push({arguments:b.toArray(arguments),batch:!0});!d||!e().batch?q():null===k&&(k=setTimeout(b.bind(function(){q()},this),e().timeout))};b.extend(f,{flush:q,now:a});return f},batchArgs:function(a,c){return b.map(a,function(a){return void 0===c?a.arguments:a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(a){return"object"===b.type(a)&&a.batch&&"array"===b.type(a.arguments)}).length===a.length},bind:function(a,
c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(d,g,k){if(d){var f=d[c];if(f||void 0!==k)return f||(f=++b),a[f]||(d[c]=f,a[f]={}),void 0!==k&&(a[f][g]=k),"string"===typeof g?a[f][g]:a[f]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""},clone:function(a){return b.extend({},a)},contains:function(a,
c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===c)return!0;return!1},cors:function(a,c,b){var d,g=function(){b?b(d.responseText):eval(d.responseText)};
d=new window.XMLHttpRequest;d.onreadystatechange=function(){4===d.readyState&&200===d.status&&g()};try{return d.open("POST",a),d.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),d.withCredentials=!0,d.send(c),!0}catch(k){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,e,d){var g;a=(d||document).createElement(a);c=c||{};e=e||{};for(g in c)void 0!==c[g]&&(a[g]=c[g]);b.css(a,e);b.cache(a,"origin","viglink");return a},css:function(a,
b){for(var e in b)try{a.style[e]=b[e]}catch(d){}return a},destructing:function(a){return function(a){var b=!1,d;return function(){b||(d=a.apply(null,arguments),b=!0);return d}}(a)},escapeRegExp:function(){var a;return function(b){a=a||/([.*+?^${}()|[\]\\])/g;return b.replace(a,"\\$1")}}(),eventLink:function(a){var b,e=a.target||a.srcElement;do{try{b=e.nodeType}catch(d){break}if(1===b&&(a=e.tagName.toUpperCase(),"A"===a||"AREA"===a))return e;e=e.parentNode}while(e)},exceptionLogger:function(){var a=
!1,c=b.noop;return function(b,d){if(void 0!==d)a=d,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(d){c(d)}else return b.apply(this,arguments)}}}(),find:function(a,c){var e;b.each(a,function(a,g){if(c(a,g))return e=a,b._breaker});return e},generateNodeFilter:function(){var a=function(a,b){var g,k;b=","+b.join(",")+",";g=0;for(k=a.length;g<k;g++)if(c(a[g],b))return!0;return!1},c=function(a,b){return-1!==b.indexOf(","+a+",")};return function(e){e=b.extend({custom:null,classes:[],
rels:[],tags:[]},e);e.tags.length&&(e.tags=","+e.tags.join(",").toLowerCase()+",");return function(d,g){g=b.extend({ancestors:!0,self:!0},g);var k=!0,f=!0,h=function(d,g){var k;if(k=!(e.tags.length&&c(d.nodeName.toLowerCase(),e.tags))){if(k=e.classes.length){k=e.classes;var f=b.attrValues(d,"className");k=a(k,f)}if(k=!k){if(k=e.rels.length)k=e.rels,f=b.attrValues(d,"rel"),k=c(d.nodeName.toLowerCase(),",a,")&&a(k,f);k=!k&&!("function"===b.type(e.custom)&&e.custom(d,g))}}return k},f=!g.self||h(d,!0);
if(g.ancestors)for(;d.parentNode;)if(d=d.parentNode,1===d.nodeType&&!h(d,!1)){k=!1;break}return f&&k}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,e=Infinity,d=Infinity,g=-Infinity,k=-Infinity,f;for(a=0;a<c;a++)f=b.position(arguments[a]),
e=Math.min(e,f.x),d=Math.min(d,f.y),g=Math.max(g,f.x+arguments[a].offsetWidth),k=Math.max(k,f.y+arguments[a].offsetHeight);return{x:e,y:d,w:g-e,h:k-d,x1:e,y1:d,x2:g,y2:k}},getActualHref:function(a){return b.cache(a,"href")||a.href},hasAttrValue:function(a,c,e,d){return c?b.contains(b.attrValues(a,c,d),e):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&
a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var e=[];b.each(a,function(a,b){void 0!==a&&(e[b]=c(a))});return e},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(e){return!0}},on:function(){var a;return function(c,e,d){var g,k,f;if(1===arguments.length)a=
c;else{if(2===arguments.length){if(!a)return;d=e;e=c;c=a}else g=b.toArray(arguments).slice(3,arguments.length);try{k=c["on"+e]}catch(h){}"function"===typeof k&&(c["on"+e]=b.bind(function(a){a=a||window.event;var d=k.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));f=b.exceptionLogger(function(){if(a.enabled())return d.apply(null,
b.toArray(arguments).concat(g||[]))});c.addEventListener?c.addEventListener(e,f,!1):c.attachEvent&&c.attachEvent("on"+e,f)}}}(),position:function(a,b){var e,d=0,g=0,k=0,f=0;b=b||document;if(!a.offsetParent)return!1;e=a;do d+=e.offsetLeft,g+=e.offsetTop,e=e.offsetParent;while(e);e=a;do k+=e.scrollLeft,f+=e.scrollTop,e=e.parentNode;while(e&&e!==b.body);return{x:d-k,y:g-f}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(b,
e){(null===b||void 0===b)&&delete a[e]});return a},ready:function(){var a=!1,c=[],e=!1,d,g,k,f,h;document.addEventListener?k=function(){document.removeEventListener("DOMContentLoaded",k,!1);h()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),h())});d=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return h();if(document.addEventListener)document.addEventListener("DOMContentLoaded",
k,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&g()}b.on(window,"load",h)}};g=function(){if(!e){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.exceptionLogger(g),1);return}h()}};h=function(){if(!e){if(!document.body)return setTimeout(b.exceptionLogger(h),13);e=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){d();e?a():c.push(a)}}(),reduce:function(a,
c,e){b.each(c,function(b,c){a=e(a,b,c)});return a},reformatKeys:function(a){var c,e,d=function(a){return"_"+a.toLowerCase()};for(c in a)e=c.replace(/([A-Z])/g,d),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),e!==c&&(a[e]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var e,d,g=b.attrValues(a,"className");e=0;for(d=g.length;e<d;e++)g[e]===c&&delete g[e];a.className=g.join(" ")}},request:function(a,c,e){var d,g,k,f=b.uniqid("vglnk_"),h=b.toArray(arguments).slice(3,
arguments.length);e=b.extend({fn:b.noop,jsonp:!0,"return":!1,timeout:null},e);"string"===typeof e.fn?(d=window[e.fn],f=e.fn):"function"===typeof e.fn&&(d=e.fn);"function"===b.type(d)&&(k=b.exceptionLogger(b.destructing(function(){d.apply(this,b.toArray(arguments).concat(h));window[f]&&(window[f]=void 0)})),null!==e.timeout&&setTimeout(k,e.timeout));!0===e.jsonp&&(window[f]=k,c=b.extend({format:"jsonp",jsonp:f},c));g=b.toQuery(c);return e["return"]?a+(g.length?"?":"")+g:b.traits.cors&&b.cors(a,g,e.jsonp?
null:k)?!0:b.jsonp(a+(g.length?"?":"")+g)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var e,d,g=[];e=0;for(d=a.length;e<d;e++)g[e]=a[e];return g}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},
transmitsPII:function(a){return b.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}(),withScope:function(){var a=function(a,e,d){if(d.self&&b.contains(e,a))return a;if(d.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(e,a)})};return function(c,e,d){var g=b.select(e);d=b.extend({ancestors:!0,descendants:!0,self:!0});return b.all(b.map(c,
function(c){var e,f=[];(e=a(c,g,d))?f.push(e):1===c.nodeType&&d.descendants&&b.each(g,function(a){b.contains(b.ancestors(a),c)&&f.push(a)});return[c,f]}),function(a){return 0<a[1].length})}}()});var y=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};y.amd=!0;(function(a){function b(a,c,d,e){var g,f,k,n,h;(c?c.ownerDocument||c:D)!==A&&J(c);c=c||A;d=d||[];if(!a||"string"!==typeof a)return d;if(1!==(n=c.nodeType)&&9!==n)return[];if(F&&!e){if(g=
qa.exec(a))if(k=g[1])if(9===n)if((f=c.getElementById(k))&&f.parentNode){if(f.id===k)return d.push(f),d}else return d;else{if(c.ownerDocument&&(f=c.ownerDocument.getElementById(k))&&T(c,f)&&f.id===k)return d.push(f),d}else{if(g[2])return K.apply(d,c.getElementsByTagName(a)),d;if((k=g[3])&&w.getElementsByClassName&&c.getElementsByClassName)return K.apply(d,c.getElementsByClassName(k)),d}if(w.qsa&&(!B||!B.test(a))){f=g=z;k=c;h=9===n&&a;if(1===n&&"object"!==c.nodeName.toLowerCase()){n=U(a);(g=c.getAttribute("id"))?
f=g.replace(ra,"\\$&"):c.setAttribute("id",f);f="[id='"+f+"'] ";for(k=n.length;k--;)n[k]=f+m(n[k]);k=ea.test(a)&&r(c.parentNode)||c;h=n.join(",")}if(h)try{return K.apply(d,k.querySelectorAll(h)),d}catch(p){}finally{g||c.removeAttribute("id")}}}return ja(a.replace(Z,"$1"),c,d,e)}function e(){function a(c,d){b.push(c+" ")>t.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function d(a){a[z]=!0;return a}function g(a){var b=A.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&
b.parentNode.removeChild(b)}}function f(a,b){for(var c=a.split("|"),d=a.length;d--;)t.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||ka)-(~a.sourceIndex||ka);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function x(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function n(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function p(a){return d(function(b){b=
+b;return d(function(c,d){for(var e,g=a([],c.length,b),f=g.length;f--;)if(c[e=g[f]])c[e]=!(d[e]=c[e])})})}function r(a){return a&&typeof a.getElementsByTagName!==P&&a}function l(){}function m(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function u(a,b,c){var d=b.dir,e=c&&"parentNode"===d,g=sa++;return b.first?function(b,c,S){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,S)}:function(b,c,S){var f,da,k=[E,g];if(S)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,S))return!0}else for(;b=
b[d];)if(1===b.nodeType||e){da=b[z]||(b[z]={});if((f=da[d])&&f[0]===E&&f[1]===g)return k[2]=f[2];da[d]=k;if(k[2]=a(b,c,S))return!0}}}function v(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function C(a,b,c,d,e){for(var g,f=[],k=0,n=a.length,h=null!=b;k<n;k++)if(g=a[k])if(!c||c(g,d,e))f.push(g),h&&b.push(k);return f}function V(a,e,g,f,k,n){f&&!f[z]&&(f=V(f));k&&!k[z]&&(k=V(k,n));return d(function(d,n,h,p){var r,q,x=[],l=[],ia=n.length,m;if(!(m=
d)){m=e||"*";for(var s=h.nodeType?[h]:h,u=[],t=0,v=s.length;t<v;t++)b(m,s[t],u);m=u}m=a&&(d||!e)?C(m,x,a,h,p):m;s=g?k||(d?a:ia||f)?[]:n:m;g&&g(m,s,h,p);if(f){r=C(s,l);f(r,[],h,p);for(h=r.length;h--;)if(q=r[h])s[l[h]]=!(m[l[h]]=q)}if(d){if(k||a){if(k){r=[];for(h=s.length;h--;)if(q=s[h])r.push(m[h]=q);k(null,s=[],r,p)}for(h=s.length;h--;)if((q=s[h])&&-1<(r=k?N.call(d,q):x[h]))d[r]=!(n[r]=q)}}else s=C(s===n?s.splice(ia,s.length):s),k?k(null,n,s,p):K.apply(n,s)})}function fa(a){var b,c,d,e=a.length,g=
t.relative[a[0].type];c=g||t.relative[" "];for(var f=g?1:0,k=u(function(a){return a===b},c,!0),n=u(function(a){return-1<N.call(b,a)},c,!0),h=[function(a,c,d){return!g&&(d||c!==$)||((b=c).nodeType?k(a,c,d):n(a,c,d))}];f<e;f++)if(c=t.relative[a[f].type])h=[u(v(h),c)];else{c=t.filter[a[f].type].apply(null,a[f].matches);if(c[z]){for(d=++f;d<e&&!t.relative[a[d].type];d++);return V(1<f&&v(h),1<f&&m(a.slice(0,f-1).concat({value:" "===a[f-2].type?"*":""})).replace(Z,"$1"),c,f<d&&fa(a.slice(f,d)),d<e&&fa(a=
a.slice(d)),d<e&&m(a))}h.push(c)}return v(h)}function ta(a,e){var g=0<e.length,f=0<a.length,k=function(d,k,h,n,p){var r,q,s,x=0,m="0",Y=d&&[],l=[],u=$,v=d||f&&t.find.TAG("*",p),w=E+=null==u?1:Math.random()||0.1,y=v.length;for(p&&($=k!==A&&k);m!==y&&null!=(r=v[m]);m++){if(f&&r){for(q=0;s=a[q++];)if(s(r,k,h)){n.push(r);break}p&&(E=w)}g&&((r=!s&&r)&&x--,d&&Y.push(r))}x+=m;if(g&&m!==x){for(q=0;s=e[q++];)s(Y,l,k,h);if(d){if(0<x)for(;m--;)!Y[m]&&!l[m]&&(l[m]=ua.call(n));l=C(l)}K.apply(n,l);p&&(!d&&0<l.length&&
1<x+e.length)&&b.uniqueSort(n)}p&&(E=w,$=u);return Y};return g?d(k):k}var Q,w,t,aa,la,U,ga,ja,$,L,R,J,A,G,F,B,O,ba,T,z="sizzle"+-new Date,D=a.document,E=0,sa=0,ma=e(),na=e(),oa=e(),ha=function(a,b){a===b&&(R=!0);return 0},P="undefined",ka=-2147483648,va={}.hasOwnProperty,M=[],ua=M.pop,wa=M.push,K=M.push,pa=M.slice,N=M.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},Z=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,xa=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,
ya=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,za=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Aa=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),Ba=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,
ca={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ca=/^(?:input|select|textarea|button)$/i,Da=/^h\d$/i,W=/^[^{]+\{\s*\[native \w/,qa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,ra=/'|\\/g,H=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,I=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{K.apply(M=pa.call(D.childNodes),D.childNodes),M[D.childNodes.length].nodeType}catch(Ea){K={apply:M.length?function(a,b){wa.apply(a,pa.call(b))}:function(a,b){for(var c=
a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}w=b.support={};la=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};J=b.setDocument=function(a){var b=a?a.ownerDocument||a:D;a=b.defaultView;if(b===A||9!==b.nodeType||!b.documentElement)return A;A=b;G=b.documentElement;F=!la(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){J()},!1):a.attachEvent&&a.attachEvent("onunload",function(){J()}));w.attributes=g(function(a){a.className="i";return!a.getAttribute("className")});
w.getElementsByTagName=g(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});w.getElementsByClassName=W.test(b.getElementsByClassName)&&g(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});w.getById=g(function(a){G.appendChild(a).id=z;return!b.getElementsByName||!b.getElementsByName(z).length});w.getById?(t.find.ID=function(a,b){if(typeof b.getElementById!==P&&F){var c=
b.getElementById(a);return c&&c.parentNode?[c]:[]}},t.filter.ID=function(a){var b=a.replace(H,I);return function(a){return a.getAttribute("id")===b}}):(delete t.find.ID,t.filter.ID=function(a){var b=a.replace(H,I);return function(a){return(a=typeof a.getAttributeNode!==P&&a.getAttributeNode("id"))&&a.value===b}});t.find.TAG=w.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==P)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,g=b.getElementsByTagName(a);if("*"===a){for(;c=
g[e++];)1===c.nodeType&&d.push(c);return d}return g};t.find.CLASS=w.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==P&&F)return b.getElementsByClassName(a)};O=[];B=[];if(w.qsa=W.test(b.querySelectorAll))g(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&B.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||B.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||B.push(":checked")}),g(function(a){var c=b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&B.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||B.push(":enabled",":disabled");a.querySelectorAll("*,:x");B.push(",.*:")});(w.matchesSelector=W.test(ba=G.matches||G.webkitMatchesSelector||G.mozMatchesSelector||G.oMatchesSelector||G.msMatchesSelector))&&
g(function(a){w.disconnectedMatch=ba.call(a,"div");ba.call(a,"[s!='']:x");O.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});B=B.length&&RegExp(B.join("|"));O=O.length&&RegExp(O.join("|"));
T=(a=W.test(G.compareDocumentPosition))||W.test(G.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ha=a?function(a,c){if(a===c)return R=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):
1;return d&1||!w.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===D&&T(D,a)?-1:c===b||c.ownerDocument===D&&T(D,c)?1:L?N.call(L,a)-N.call(L,c):0:d&4?-1:1}:function(a,c){if(a===c)return R=!0,0;var d,e=0;d=a.parentNode;var g=c.parentNode,f=[a],X=[c];if(!d||!g)return a===b?-1:c===b?1:d?-1:g?1:L?N.call(L,a)-N.call(L,c):0;if(d===g)return h(a,c);for(d=a;d=d.parentNode;)f.unshift(d);for(d=c;d=d.parentNode;)X.unshift(d);for(;f[e]===X[e];)e++;return e?h(f[e],X[e]):f[e]===D?-1:X[e]===
D?1:0};return b};b.matches=function(a,d){return b(a,null,null,d)};b.matchesSelector=function(a,d){(a.ownerDocument||a)!==A&&J(a);d=d.replace(za,"='$1']");if(w.matchesSelector&&F&&(!O||!O.test(d))&&(!B||!B.test(d)))try{var e=ba.call(a,d);if(e||w.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(g){}return 0<b(d,A,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==A&&J(a);return T(a,b)};b.attr=function(a,b){(a.ownerDocument||a)!==A&&J(a);var c=t.attrHandle[b.toLowerCase()],
c=c&&va.call(t.attrHandle,b.toLowerCase())?c(a,b,!F):void 0;return void 0!==c?c:w.attributes||!F?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;R=!w.detectDuplicates;L=!w.sortStable&&a.slice(0);a.sort(ha);if(R){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}L=null;return a};aa=b.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===
b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=aa(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=aa(b);return c};t=b.selectors={cacheLength:50,createPseudo:d,match:ca,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(H,I);a[3]=(a[3]||a[4]||a[5]||"").replace(H,I);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(ca.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(c&&Aa.test(c)&&(b=U(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=
a.replace(H,I).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=ma[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&ma(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==P&&a.getAttribute("class")||"")})},ATTR:function(a,d,e){return function(g){g=b.attr(g,a);if(null==g)return"!="===d;if(!d)return!0;g+="";return"="===d?g===e:"!="===d?
g!==e:"^="===d?e&&0===g.indexOf(e):"*="===d?e&&-1<g.indexOf(e):"$="===d?e&&g.slice(-e.length)===e:"~="===d?-1<(" "+g+" ").indexOf(e):"|="===d?g===e||g.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,b,c,d,e){var g="nth"!==a.slice(0,3),f="last"!==a.slice(-4),k="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,n){var h,p,r,q,s;c=g!==f?"nextSibling":"previousSibling";var x=b.parentNode,m=k&&b.nodeName.toLowerCase();n=!n&&!k;if(x){if(g){for(;c;){for(p=b;p=p[c];)if(k?p.nodeName.toLowerCase()===
m:1===p.nodeType)return!1;s=c="only"===a&&!s&&"nextSibling"}return!0}s=[f?x.firstChild:x.lastChild];if(f&&n){n=x[z]||(x[z]={});h=n[a]||[];q=h[0]===E&&h[1];r=h[0]===E&&h[2];for(p=q&&x.childNodes[q];p=++q&&p&&p[c]||(r=q=0)||s.pop();)if(1===p.nodeType&&++r&&p===b){n[a]=[E,q,r];break}}else if(n&&(h=(b[z]||(b[z]={}))[a])&&h[0]===E)r=h[1];else for(;p=++q&&p&&p[c]||(r=q=0)||s.pop();)if((k?p.nodeName.toLowerCase()===m:1===p.nodeType)&&++r)if(n&&((p[z]||(p[z]={}))[a]=[E,r]),p===b)break;r-=e;return r===d||
0===r%d&&0<=r/d}}},PSEUDO:function(a,e){var g,f=t.pseudos[a]||t.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return f[z]?f(e):1<f.length?(g=[a,a,"",e],t.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var c,d=f(a,e),g=d.length;g--;)c=N.call(a,d[g]),a[c]=!(b[c]=d[g])}):function(a){return f(a,0,g)}):f}},pseudos:{not:d(function(a){var b=[],c=[],e=ga(a.replace(Z,"$1"));return e[z]?d(function(a,b,c,d){d=e(a,null,d,[]);for(var g=a.length;g--;)if(c=d[g])a[g]=!(b[g]=c)}):
function(a,d,g){b[0]=a;e(b,null,g,c);return!c.pop()}}),has:d(function(a){return function(d){return 0<b(a,d).length}}),contains:d(function(a){a=a.replace(H,I);return function(b){return-1<(b.textContent||b.innerText||aa(b)).indexOf(a)}}),lang:d(function(a){Ba.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(H,I).toLowerCase();return function(b){var c;do if(c=F?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&
1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===G},focus:function(a){return a===A.activeElement&&(!A.hasFocus||A.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Da.test(a.nodeName)},input:function(a){return Ca.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:p(function(){return[0]}),
last:p(function(a,b){return[b-1]}),eq:p(function(a,b,c){return[0>c?c+b:c]}),even:p(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:p(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:p(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:p(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};t.pseudos.nth=t.pseudos.eq;for(Q in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[Q]=x(Q);for(Q in{submit:!0,reset:!0})t.pseudos[Q]=n(Q);l.prototype=t.filters=
t.pseudos;t.setFilters=new l;U=b.tokenize=function(a,d){var e,g,f,k,n,h,p;if(n=na[a+" "])return d?0:n.slice(0);n=a;h=[];for(p=t.preFilter;n;){if(!e||(g=xa.exec(n)))g&&(n=n.slice(g[0].length)||n),h.push(f=[]);e=!1;if(g=ya.exec(n))e=g.shift(),f.push({value:e,type:g[0].replace(Z," ")}),n=n.slice(e.length);for(k in t.filter)if((g=ca[k].exec(n))&&(!p[k]||(g=p[k](g))))e=g.shift(),f.push({value:e,type:k,matches:g}),n=n.slice(e.length);if(!e)break}return d?n.length:n?b.error(a):na(a,h).slice(0)};ga=b.compile=
function(a,b){var c,d=[],e=[],g=oa[a+" "];if(!g){b||(b=U(a));for(c=b.length;c--;)g=fa(b[c]),g[z]?d.push(g):e.push(g);g=oa(a,ta(e,d));g.selector=a}return g};ja=b.select=function(a,b,c,d){var e,g,f,k,n="function"===typeof a&&a,h=!d&&U(a=n.selector||a);c=c||[];if(1===h.length){g=h[0]=h[0].slice(0);if(2<g.length&&"ID"===(f=g[0]).type&&w.getById&&9===b.nodeType&&F&&t.relative[g[1].type]){if(b=(t.find.ID(f.matches[0].replace(H,I),b)||[])[0])n&&(b=b.parentNode);else return c;a=a.slice(g.shift().value.length)}for(e=
ca.needsContext.test(a)?0:g.length;e--;){f=g[e];if(t.relative[k=f.type])break;if(k=t.find[k])if(d=k(f.matches[0].replace(H,I),ea.test(g[0].type)&&r(b.parentNode)||b)){g.splice(e,1);a=d.length&&m(g);if(!a)return K.apply(c,d),c;break}}}(n||ga(a,h))(d,b,!F,c,ea.test(a)&&r(b.parentNode)||b);return c};w.sortStable=z.split("").sort(ha).join("")===z;w.detectDuplicates=!!R;J();w.sortDetached=g(function(a){return a.compareDocumentPosition(A.createElement("div"))&1});g(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||f("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!w.attributes||!g(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&f("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});g(function(a){return null==a.getAttribute("disabled")})||f("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof y&&y.amd?y(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);b.browser=function(){var a,c={},e=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(e,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.platforms=function(){var a={bbp:{id_spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{id_spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{id_spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},
phpb:{id_spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{id_spec:{ancestor:!1,attribute:"name",parser:/^Post(\d+)$/,selector:"a[name^='Post']"},scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{id_spec:{parser:/^post_(\d+)$/,
selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:null}};return function(c){return b.extend(a[c]||{},{getPostIDs:function(a){var c=[],g=this.id_spec;!a&&(document&&document.body)&&(a=[document.body]);a&&g&&(a=!1===g.ancestor?b.select(g.selector):b.reduce([],b.withScope(a,g.selector),function(a,b){return a.concat(b[1])}),b.each(a,function(a){var e=g.attribute||
"id";(a=a[e]?a[e].match(g.parser):null)&&!b.contains(c,a[1])&&c.push(a[1])}));return c.length?c:null}})}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),quirksMode:!Boolean(window.addEventListener),
windowLevelHandlers:Boolean(window.addEventListener)};var h,m,v,u;f={PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],rels:["norewrite"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return"viglink"===b.cache(a,"origin")}}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var e=c[d],g;if(e&&e.callback&&a){if("string"===
b.type(a)&&(g=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(g[1]);"domains"===d&&"array"===b.type(a)&&(a={results:a});e.callback.apply(window,[a].concat(e.data||[]))}})};return function(g){var k={},h={};b.each(g,function(a){a=c.apply(this,a);var d=a.method;k[d]=b.prune(a.params);h[d]={callback:a.opts.fn||b.noop,data:a.data}});e({data:h,method:"batch",params:b.extend(f.commonParams(),{batch:window.JSON.stringify(k)}),opts:{jsonp:!1,fn:function(b,c){a(b,c)}}})}}(),c=function(a,c,e){var m=b.toArray(arguments).slice(3,
arguments.length),x=a,n=e||{},p;p=b.extend(f.commonParams(a),c);p.subId&&p.key!==h.key&&(p.subId=null);return{data:m,method:x,opts:n,params:p}},e=function(a){return b.request.apply(b,[h.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,b.batchArgs(arguments)):e(c.apply(this,arguments))},function(){return{batch:h.batch_calls,timeout:h.batch_call_timeout}})}(),addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=
function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var g=a.open("",c);g.focus();return g}},c=function(a){var c=a.previousSibling,g=a.nextSibling,k=["",a.textContent,""],h=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},m=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?
" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==k[1]&&(k[0]=c&&3===c.nodeType?h(c,"previous"):"",k[2]=g&&3===g.nodeType?h(g,"next"):"",k=m.apply(this,k),""!==k[0]&&""!==k[2]&&(k[0]=k[0].split(" ").reverse().slice(0,10+(" "===k[0].substr(k[0].length-1,1)?1:0)).reverse().join(" "),k[2]=k[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:k[0],after:k[2],txt:k[1],
loc:location.href,out:b.getActualHref(a),v:2},f.log("info",b.toQuery(a))))};return function(e,d){var g,f,m,l,n=b.context(e)||window;d=e.target||d;d=!d||d===n.name||"_top"===d&&n.top===n||"_parent"===d&&n.parent===n?"_self":d;m=a(n,d);if("_self"!==d&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===m.document)throw!0;l="jsonp"}catch(p){l="go"}g=b.destructing(b.bind(function(){h.time_click&&arguments.length&&this.logTime("clk");var a=b.toArray(arguments);
a.unshift(e,m,d);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof e?e:b.getActualHref(e));if("string"===typeof e&&(e=b.createA(e,d),!this.processLink(e))||!h.enabled)return g();f=this.clickParams(e,l);this.logTime();h.log_context&&c(e);if("go"===l)this.redirect(this.api.now("click",f,{"return":!0}),n,m,d);else if(m===n)this.api.now("click",f,{fn:g,timeout:h.click_timeout});else{if(b.contextIsAncestor(n,m))return this.redirect(b.getActualHref(e),n,m,d);g=b.exceptionLogger(g);
setTimeout(function(){g()},h.click_timeout);m.document.open();m.callback=g;m.document.write("<html><head><title>"+b.getActualHref(e)+'</title><script type="text/javascript" src="'+this.api.now("click",f,{fn:"callback","return":!0})+'">\x3c/script></head></html>');m.document.close()}}}(),clickParams:function(a,c){var e=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:h.reaffiliate||null,title:window.document.title,txt:a.innerHTML});128<e.txt.length&&
(e.txt=e.txt.replace(/<[^>]+>/g,""),e.txt=128<e.txt.length?e.txt.substr(0,125)+"...":e.txt);return e},commonParams:function(a){var c={drKey:h.key?null:h.dr_key,key:h.key,libId:h.library_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:h.cuid,loc:location.href,subId:h.sub_id,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,b){function c(a,b){0==m||1E3<b?a(0==m&&h):setTimeout(function(){c(a,2*b)},2*b)}function f(){--m||(h=!n&&p)}var h=!1,m=2,n=!1,p=
!1;if("function"==typeof b){a+="?ch=*&rn=*";var r=11*Math.random(),s=new Image;s.onload=f;s.onerror=function(){n=!0;f()};s.src=a.replace(/\*/,1).replace(/\*/,r);s=new Image;s.onload=f;s.onerror=function(){p=!0;f()};s.src=a.replace(/\*/,2).replace(/\*/,r);c(b,250)}}}}catch(c){a={detect:function(a,b){b(!0)}}}return function(c){var d=b.updateUrl(h.asset_url,{pathname:"/images/pixel.gif"});a.detect(d,c)}}(),enabled:function(){if(h.enabled&&v!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))h.enabled=
!1;return h.enabled},expose:function(a,c){if(c=c||this[a])"function"===typeof c?c=b.exceptionLogger(b.bind(c,this)):"object"===typeof c&&(c=b.clone(c)),u[a]||(u[a]=c)},fire:function(){var a={};return function(c,e){c=c.toLowerCase();var d=a[c]||{fired:!1,listeners:[]};"function"===typeof e?d.fired?setTimeout(function(){e({type:c})},0):d.listeners.push(e):(d.fired=!0,b.each(d.listeners,function(a){"function"===typeof a&&a({type:c})}),d.listeners=[]);a[c]=d}}(),handleRightClick:function(a,c){if(h.rewrite_modified&&
a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return h.harmony_level<=a}}(),init:function(){var a=function(){var a=!0===window.document.__v5k;
window.document.__v5k=!0;return!a};return function(){var c=this;m={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(e){}b.exceptionLogger(b.bind(c.logException,c),!h.dev);return b.exceptionLogger(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);u=v[l]=b.noop;this.expose("click");this.expose("link",
b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return f.registerProcessor.apply(f,arguments)});b.extend(u,u===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),
initDRApi:function(){var a=!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){a=!0;h.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:f.onClick,right:f.onContextmenu},e={left:b.noop,right:b.noop},d=b.traits.windowLevelHandlers?a:a.document,g=function(d){d=d||a.event;if((d=b.eventLink(d))&&!b.cache(d,"evented"))l(d,f.harmony(b.harmony.LINK_LEVEL_EVENTS)?
c:e),b.cache(d,"evented",!0)},k=function(a){a.document&&a.MutationObserver&&(new MutationObserver(b.exceptionLogger(b.batchable(function(a){var c=[];b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,b){return a.concat(b)}));b.each(a,function(a){var d;"characterData"===a.type?d=[a.target]:a.addedNodes.length&&(d=b.toArray(a.addedNodes));d=b.all(d,function(a){return f.allowed(a)&&Boolean(a.parentNode)});d.length&&(c=c.concat(d))});c.length&&b.each(m,function(a,b){f.runPlugin(b,
c)})},function(){return{batch:h.batch_mutation,timeout:h.batch_mutation_timeout}})))).observe(a.document,{characterData:!0,childList:!0,subtree:!0})},l=function(a,c){b.on(a,"click",b.bind(c.left,f));b.on(a,"contextmenu",b.bind(c.right,f))};h.dynamic&&k(a);b.on(d,"copy",b.bind(f.onCopy,f));b.on(d,"mousedown",g);if(f.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",g)})});(!b.traits.quirksMode||f.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&
l(d,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(u[b[a]]=window[a],"vglnk_domain"===a&&(u[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){h.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(f);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=
b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,b=l.split("."),e;for(l=b.pop();0<b.length;)e=b.shift(),a[e]=a[e]||{},a=a[e];v=a;u=v[l]=v[l]||{}},initOptions:function(){var a;this.initLegacyOptions();h=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,
key:null,link_urls:!0,partner:null,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),h,u,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},time_click:!1,time_ping:!1,testing_js:[],plugins:{link_affiliation:{},modified_clicks:{}}});for(a in h)"_plugin"===a.substr(-7)&&delete h[a]},initPlugins:function(){var a,
c=1,e={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},d=["spotlight"],g=function(b){return function(b){return function(){delete m[b].opts.mode;c=1;clearTimeout(a);l()}}(b)},k=function(a){var c;b.find(e,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:h.key,link_phrases:!1});a[c].link_urls=h.link_urls;return a},l=function(){var d={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop},
e=function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);f.log.apply(this,c)}}},g=function(a){return!Boolean(a._ran)};a=null;b.each(b.all(m,g),function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,d,a.setup(a.opts,b.clone(b),u,e(a.opts.key||h.key)))),a.opts.mode!==f.PLUGIN_MANUAL&&f.runPlugin(c))});b.find(m,g)&&(a=setTimeout(b.exceptionLogger(l),Math.min(Math.max(Math.pow(2,
++c),100),5E3)))},x=function(){setTimeout(function(){f.api.flush()},100);l();b.on("DOMReady",function(){setTimeout(f.api.flush,0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=e[c]||c;"object"===typeof a&&!1!==a.enabled&&(m[c]={opts:a},b.contains(d,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,g(c)))},this));x()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(h.api_url);if("/api/click"===
a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){h.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target=
"_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["norewrite","noskim"],custom:function(c){var d,g="",f=!1;try{d=c.hostname,g=c.protocol,d.charAt(0)}catch(m){return!0}""!==d&&(d=b.canonicalizeHostname(c));f=Boolean(""===d||a===d||!g.match(/^https?:$/i)||h.norewrite[d]);g=b.cache(c,"type");c=b.cache(c,"params")||{};if(!Boolean(g||c.type)&&!f)f=Boolean(!h.rewrite_original||"object"===b.type(h.commercial)&&!h.commercial[d]);return f}});
return function(a){return c(a,{ancestors:!1})}}(),log:function(a,c,e,d){var g,f=b.toQuery({libId:h.library_id,nocache:b.uniqid()});g="pixel.gif";if("custom"===a)f+="&"+b.toQuery({key:c,type:e}),b.each("array"===b.type(d)?d:[d],function(a){b.each(["e","i","o"],function(b){delete a[b]});f+="&"+b.toQuery(a)});else{f+="&"+b.toQuery({key:h.key,drKey:h.key?null:h.dr_key});if("time"===a)g="time.gif",a={time:e,type:c};else if("exception"===a)a={e:c,o:e};else if("info"===a)a={i:c};else return;f+="&"+b.toQuery(a)}g=
h.api_url+"/"+g+"?"+f;b.transmitsPII(g)||(b.createEl("img").src=g)},logException:function(a){if(h.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,e,d,g){var f=d||b.getActualHref(a),m=b.bind(function(){this.redirect(f,
b.context(a),c,e)},this);"object"===typeof g&&(g.tracking||g.image)?(d=b.createEl(g.tracking?"iframe":"img",{src:g.tracking||g.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(d),setTimeout(b.exceptionLogger(m),g.timeout||h.hop_timeout)):m()},onApiPing:function(a,c,e,d,g,k){h.rewrite_original=!1;g=b.reformatKeys(g||{});var m,l;d=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};l=b.extend(h.plugins,g.plugins);h=b.extend(h,
g);delete h.plugins;h.library_id=a;h.click_timeout=c;h.time_ping&&this.logTime("png");"array"===b.type(h.testing_js)&&0<h.testing_js.length&&b.each(h.testing_js,function(a){b.jsonp(a)});b.extend(h.norewrite,d(e));b.extend(h.nofollow,d(k));for(m in h)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===b.type(h[m]))&&(b.on(f,m.toLowerCase().substr(2),b.bind(h[m],window)),delete h[m]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;
var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,e=a.which&&1===a.which||0===a.button,d=b.eventLink(a);if(d&&this.isRewritable(d)&&!c&&e&&!b.isDefaultPrevented(a))return this.click(d),b.preventDefault(a)},onContextmenu:function(a){(a=b.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var c,e,d,g=[];if(window.getSelection){e=window.getSelection();a=0;for(c=e.rangeCount;a<c;a++){try{d=e.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,
"\n")}catch(h){}0<d.length&&128>=d.length&&g.push(d)}}b.each(g,function(a){f.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(h[a]=b);return h[a]},ping:function(){var a=!1;return function(){if(!a&&(h.key||h.dr_key)){var c={ref:document.referrer||null};a=!0;b.transmitsPII(this.api.now("ping",c,{"return":!0}))||(this.logTime(),this.detectFiltering(b.bind(function(a){a&&(h.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);
this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a}},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,e,d){c=c||window.top;!b.traits.crossWindowCommunication&&!e?(d=c.open(a,d),d.focus()):b.traits.jsRedirectSetsReferrer?
setTimeout(b.exceptionLogger(function(){!e||e===c?c.location=a:b.contextIsAncestor(c,e)?e.location=a:e.location.replace(a)}),0):("_blank"===d&&(d=b.uniqid("win_")),d=b.createA(a,d),d.rel="norewrite",c.document.body.appendChild(d),d.click(),d.parentNode.removeChild(d))},runPlugin:function(a,c){var e=window.document,d=m[a];if(d&&d.initDocuments){if(c)d.initNodes(c);else if(d.init(),"function"===b.type(d.initDocuments)&&"document"===b.type(e)&&d.initDocuments([e]),"function"===b.type(d.initNodes)&&"element"===
b.type(e.body))b.on("DOMReady",function(){d.initNodes([e.body])});d._ran=!0}},registerProcessor:function(){var a=!1,c=[],e=function(d){if(void 0===d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),fn:d}),a&&this.initLinks())};e(function(){a=!0});return e}()};f.init();try{delete window.vglnk_self}catch(C){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,f,b){var y={},h;l=f.extend({any:!0},l);h={getDomains:function(){var m=[];f.each(y,function(b,f){m.push(f)});0<m.length&&b.api("domains",{domains:m.join("|")},{fn:f.bind(h.onDomainApi,h)})},init:function(){b.opt("rewrite_original",!0);l.any||b.registerProcessor(f.bind(function(b){this.initDomainLookup();this.saveDomain(b)},this))},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,f.on("DOMReady",f.bind(this.getDomains,this)))}}(),onDomainApi:function(h){var l;
"object"===f.type(h)&&"array"===f.type(h.results)&&(l={},f.each(h.results,function(b){l[b]=!0}),b.opt("commercial",l))},saveDomain:function(b){b=f.canonicalizeHostname(b);y[b]=!0}};return{init:f.bind(h.init,h)}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,f,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,f,b){l=f.extend({key:null},l);var y={init:function(b){f.each(this.getDRSearchForms(b),function(b){if(!f.cache(b,"evented")){var h=y.getInput(b),l=function(){h.value||f.css(h,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(b,"evented",!0);b.onsubmit=null;h.onfocus=null;h.onblur=null;f.on(h,"focus",function(){f.css(h,{"background-image":"none"})});f.on(h,"blur",l);l();f.on(b,"submit",function(f){y.onSubmit(f,b)})}})},
getDRSearchForms:function(b){var l=[];f.each(b,function(b){"element"===f.type(b)&&f.each(b.getElementsByTagName("form"),function(b){y.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&l.push(b)})});return l},getInput:function(b){return b.p||b.q2},onSubmit:function(h,m){h=h||window.event;var v="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:y.getInput(m).value}),v=f.createA(v,"_blank");f.cache(v,"params",{key:l.key});b.click(v);return f.preventDefault(h)}};if(l.key)return{init:f.bind(y.init,y),
initNodes:function(b){y.init(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,f,b,y){var h,m={},v=0;l=f.extend({platform:null},l);h={getLinks:function(){var m=f.platforms(l.platform).getPostIDs();b.api("optimize",{pt:l.platform,i:m?m.join("|"):null,u:location.href},{fn:f.bind(h.onOptimizeApi,h)})},log:function(){y("optimize",{ct:v})},onOptimizeApi:function(b){"object"===f.type(b)&&"object"===f.type(b.optLinks)&&(m=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var b=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],
custom:function(a,b){if(b)return Boolean(f.cache(a,"type"))}}),h=function(a){var b=a.href,e=a.textContent||a.innerText,d=function(){var b=f.canonicalizeHostname(a);return f.canonicalizeHostname(f.createEl("a",{href:e}))===b},g=function(){var b;return d()?(b=f.fromQuery(a.search),f.find(b,function(a){return a===e})):!1};return{exact:b===e||function(){var a=e.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+f.map(a,f.escapeRegExp).join(".+")+"$").test(b)}()||g(),partial:function(){var b=f.canonicalizeHostname(a);
return RegExp("\\b"+f.escapeRegExp(b)+"\\b","i").test(e)}()||-1!==e.indexOf(b)}};return function(a){var c,e=m[a.href];if(e&&b(a)){c=h(a);if(c.exact){c=e.frdLink||e.optLink;for(var d;d=a.firstChild;)a.removeChild(d);a.appendChild(document.createTextNode(c))}else if(c.partial)return;f.cache(a,"params",{type:"LO",origOutId:e.pcid+":"+e.linkId});a.href=e.optLink;v++}}}(),optimizeLinks:function(){var l={data:!1,timing:!1};return function(v){l=f.extend(l,v);l.timing&&(l.data&&m)&&(b.registerProcessor(f.bind(this.optimizeLink,
h)),setTimeout(function(){h.log()},0))}}(),setup:function(){if(!l.platform||"full"===l.platform)this.getLinks();else f.on("DOMReady",f.bind(this.getLinks,this))}};h.setup();return{init:function(){f.on("DOMReady",function(){h.optimizeLinks({timing:!0})})}}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(l,f,b){l=f.extend({level:null},l);return{init:function(){var f=parseInt(l.level,10);isFinite(f)&&b.opt("harmony_level",f)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,f,b,y){var h,m,v=null,u={},C,a=0,c=0,e=0;l=f.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},l);if(l.key)return h=f.platforms(l.platform),m={addPhrasesToMatcher:function(a){var b="";"regexp"===f.type(a)?b=a.source:"array"===f.type(a)&&(b="(?:^|[\\s\"'\\(])("+f.map(a,function(a){return f.escapeRegExp(a).split(" ").join("\\s+")}).join("|")+
")(?=\\s|\\W*$|\\W{2})");""!==b&&(C=RegExp(C?"(?:"+b+"|"+C.source+")":b,"i"))},focusLink:function(a){a.id||(a.id=f.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,c,e=b.opt("partner"),f={};for(a in e)break;if(a)for(c in e[a])f[a+"_"+c]=e[a][c];return f},getPhrases:function(a){var c=h.getPostIDs(a);b.api("insert",f.extend(m.getPartnerParams(),{cat:l.cat,i:c?c.join("|"):null,mode:l.mode,pt:l.platform,ps:l.product_source,u:location.href,type:l.type}),
{fn:f.bind(m.onInsertApi,m)},a)},init:function(){l.scope=l.scope||h.scope||"body";l.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"))},initLink:function(a,c,e){if(e=l.link_target||e)a.target=e;a.rel=
"nofollow";a.href||(a.href=c.url);f.cache(a,"params",{exp:v,key:l.key,mid:c.mid,type:c.type||null});f.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var b=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a")&&Boolean(a.href)}}),g=function(a){var c;if(b(a,{ancestors:!1,self:!0}))if(3===a.nodeType)h(a);
else if(1===a.nodeType)for(a=a.firstChild;a;)c=a.nextSibling,g(a),a=c},b=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a")&&Boolean(a.href)}}),g=function(a){var c;if(a){if(b(a,{ancestors:!1,self:!0}))for(c=a.firstChild;c;)a=c.nextSibling,1===c.nodeType?g(c):3===c.nodeType&&h(c),c=a}else f.each(f.select(l.scope),
function(a){b(a,{ancestors:!0,self:!1})&&g(a)})},b=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a")&&Boolean(a.href)}}),g=function(a){var c;if(a){if(b(a,{ancestors:!1,self:!0}))for(c=a.firstChild;c;)a=c.nextSibling,1===c.nodeType?g(c):3===c.nodeType&&h(c),c=a}else f.each(f.select(l.scope),function(a){b(a,
{ancestors:!0,self:!1})&&g(a)})},h=function(a){var b=!1,c=a.parentNode,d=function(a,b){c.insertBefore(a,b);c.removeChild(b)};a.data&&(b=C.test(a.data.replace(/\s+/," ")));b&&q(a,d)},q=function(b,d){for(var g,h,k,q,v=function(b){var c;b=!b||!l.per_phrase||!b.count||b.count<l.per_phrase;c=!l.per_page||a<l.per_page;return b&&c},y=function(a,b){var c,d,e,g,h,k,m,n,p,q,r=function(b){p.parentNode.insertBefore(a,p);p.parentNode.removeChild(p);return b},x=function(a,b,c){a=f.extend({},a);a.x1-=c;a.y1-=c;
a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};p=f.createEl("span");a.parentNode.insertBefore(p,a);p.appendChild(a);q=f.geometry(p);if(l.proximity||l.same_proximity)for(k in u)if((m=u[k].links)&&!(u[k]===b&&!l.same_proximity||u[k]!==b&&!l.proximity)){n=u[k]===b?Math.max(l.same_proximity,l.proximity):l.proximity;c=0;for(d=m.length;c<d;c++){h=m[c].segments;e=0;for(g=h.length;e<g;e++)if(x(h[e].geometry,q,n))return r(!1)}}return r(!0)},V=function(a,b){var c,d,e,g,h={el:a,segments:[]},
k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===g||e.offsetTop===g.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),g=e;l.geometry=f.geometry.apply(f,l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};b&&b.data&&(Boolean(k=b.data.match(/^\s+/))||Boolean(k=b.data.match(C)));)h=k[0],q=k.slice(1).join(""),g=u[m.normalizePhrase(q)],h=b.data.indexOf(h)+h.length-q.length,0<h&&(b=b.splitText(h)),h=b.length<=q.length?null:b.splitText(q.length),
q&&!g&&(g={url:q.match(/^https?:\/\//i)?q:"http://"+q,type:"U"}),g&&(g.url.match(/https?:\/\//i)&&q&&v(g)&&y(b,g))&&(q=x(q,g),f.cache(q,"unlinked")||("L"===g.type.toUpperCase()?c++:e++,d(q,b),V(q,g),g.count++,a++)),b=h},x=function(a,b){var c;c=f.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";f.cache(c,"type","inserted");f.cache(c,"phrase",a);l.ui&&(c.title="Link added by VigLink");m.initLink(c,b);return c};return function(a){C&&(a=f.all(a,b),
f.each(a,g),l.link_phrases&&m.log())}}(),loadPhrases:function(a,b){var c,e,f,h=[];c=0;for(e=a.length;c<e;c++)f=a[c],f.phrase&&f.url&&(f.phrase=this.normalizePhrase(f.phrase),u[f.phrase]||(h.push(f.phrase),u[f.phrase]={count:u[f.phrase]?u[f.phrase].count:0,phrase:f.phrase,mid:f.mid,url:f.url,type:f.type||""}));0<h.length&&this.addPhrasesToMatcher(h);this.insertLinks(b)},log:function(){var b,f,h={heavy:[],lite:[]},l=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(b in u)f=parseInt(u[b].count,
10),0<f&&(f=[f,b.replace(/\|/g,"%7C")].join(),h["L"===u[b].type.toUpperCase()?"lite":"heavy"].push(f));h.lite.sort(l);h.heavy.sort(l);y("insert",[{ct:a,cl:c,ch:e,cu:0,exp:v},{pl:h.lite.join("|")},{ph:h.heavy.join("|")}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},onInsertApi:function(a,b){"object"===f.type(a)&&(v=a.exp,a.results&&this.loadPhrases(a.results,b))}},{init:f.bind(m.init,m),initNodes:function(a){a=f.reduce([],f.withScope(a,l.scope),
function(a,b){return a.concat(b[1])});a.length&&(l.link_phrases?m.getPhrases(a):m.insertLinks(a))}}};
