//<script>

bouncex.state = {"iol":true,"tn":1426280174,"rc":false,"mobile":false,"RECORD_CAMPAIGN_EVENT_ENABLED":1,"EV":""};
bouncex.cookie = {"v":{"ever_logged_in":false,"new_ever_logged_in":false},"fvt":1426280174,"vid":1426280174134884,"ao":0,"as":0,"vpv":1,"d":"d","lp":"http%3A%2F%2Fwww.techrepublic.com%2Farticle%2Fintel-looks-to-teen-scientists-to-improve-solar-power-cybersecurity-and-cancer-research%2F","r":"www.facebook.com","cvt":1426280174,"gcr":47,"m":0,"campaigns":{"65535":{"vv":0,"lvt":1426280174}},"lvt":1426280174};
bouncex.campaigns = {"65535":{"ad_shown":false,"pid":"21873","ctype":"other","activations":[{"activation":"scroll","prop":"","val":"30"},{"activation":"inactivity","prop":"","val":"300"}],"overlay":"none","coverlay":"none","bottom":"none","callout":"none","callout_t":"","callout_pos":"rm","callout_anchor_pos":"lm","callout_voffset":"0","callout_hoffset":"0","top":"none","overlay_teleport_html":"","overlay_teleport_type":"_blank","opacity":0.9,"color":"#000000","close_button_delay":0,"show_close":1,"show_close_step":0,"close_redirect_url":"","close_redirect_type":"_self","activation_delay":5,"closed_no_show":0,"mas":4,"mao":12,"map":1,"iao":"0","rao":"0","tvao":"0","is_ec":false,"is_api":false,"is_man":0,"ad_auto_close":0,"activation_offset":0,"header_top_nano":0,"header_bottom_nano":1,"hbna":"anypage","hbnbg":"1","htna":"0","htnbg":"1","ad_visible":false,"osfn":"","tes":"1","te":"no_effect","t_valign":"top","b_valign":"bottom","qbxtest":false,"submission_redirect":"","submission_redirect_delay":2,"osfn_website":"","supress_overlay":0,"repress_overlay":0,"supress_top":0,"repress_top":0,"supress_bottom":0,"repress_bottom":0,"event_js":"{\"activation\":\"var x = setInterval(function(){\\n  if(jQuery('.modal.modal-register.show.modal-register-success').length>0){\\n    bouncex.report_conversion({goal:'Registeration'});\\n    clearInterval(x);\\n  }\\n},1000);\",\"impression\":\"bouncex.report_ga('impression','tShape  Control 2');\\n\",\"click\":\"bouncex.report_ga('click','tShape  Control 2');\\n\",\"submission\":\"bouncex.report_ga('submission','tShape  Control 2');\\n\",\"close\":\"\"}","html":""}};
bouncex.debug = false;
//bouncex.website.bau = 'http://bounceexchange.com/';

bouncex.init();
