(function(z){
var JK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.hp),b?-1:-a):a.Vm+(b?-1:1)};var KK=function(a){z.yv.call(this,a);this.Vm=0;this.jd="new"};var LK=function(a,b){a.NV=b};var MK=function(a){return a.get(a.k.op)};
var NK=function(a){return(0,z.P)('\x3cdiv class\x3d"fyre '+(a.fe?"fyre-liveblog ":"")+(a.Xg?"fyre-livechat ":"")+(a.tS?"fyre-bootstrap ":"")+(a.Ke?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ua?"fyre-avatar-disabled":"")+'"\x3e'+(a.Wu?z.im(z.Es(a)):"")+(0,z.P)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Ua?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Un?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var OK=function(a){return(0,z.P)('\x3ca href\x3d"'+z.Q(z.R(a.Ca))+'" title\x3d"'+z.Q(a.Y)+'" data-id\x3d"'+z.Q(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.Q(a.cS)+'"\x3e\x3cimg src\x3d"'+z.Q(z.R(a.ud))+'" alt\x3d"'+z.Q(a.Y)+'" onerror\x3d"javascript:this.src\x3d\''+z.Q(z.Cm(a.Yb))+"';\" /\x3e\x3c/a\x3e")};
var PK=function(a){return(0,z.P)(z.Pq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.O(a.j.KM)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(a.j.tx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(a.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(a.j.ux)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var QK=function(a){return(0,z.P)('\x3cdiv class\x3d"tooltip"\x3e'+z.O(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var RK=function(){};var SK=function(a,b){z.Ej.call(this,b,a)};var TK=function(a,b){z.AF.call(this,a,b)};var UK=function(a,b){var c=a.d.Fb;c.jh[4]&&(z.Oy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.mr)},a)),z.Qy(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.mr)})))};
var VK=function(a,b){var c=[a.Vl,a.Iy];a.sg&&c.push(a.sg);a.Os&&c.push(a.Os);a.Jy&&c.push(a.Jy);z.x(c,function(a){z.Io(a,"fyre-stream-sort-selected")});z.Go(b,"fyre-stream-sort-selected")};var WK=function(a,b){z.AF.call(this,a,b)};var XK=function(a,b){z.rx.call(this,a,b);this.nl=!1;this.Ea=new z.zx;this.Ea.oc(this);this.Jt="archiveShowMore"};var YK=function(a,b){z.yF.call(this,a,b)};var ZK=function(a,b,c){z.St.call(this,a,b,c);this.cz=b||"";this.pg(QK(this.s()))};
var $K=function(a,b,c){z.Mt.call(this,a,b||3,c)};var aL=function(a,b){z.T.call(this,b);this.m=a};var bL=function(a,b){z.T.call(this,b);this.bc=a};var cL=function(a,b){bL.call(this,a,b)};var dL=function(a,b,c,d,f){z.zF.call(this,a,b,c,d,f)};
var eL=function(){var a=z.u.window,b=z.u.document;function c(){var a=C.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){C.uV||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(C,g)}function f(a){var b;if(a.PN)return a;if(C.tV&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.PN=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.nS&&a.nS("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var C={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.tV,shivMethods:!1!==g.uV,type:"default",shivDocument:f};f(b)};var fL=function(a,b){z.IF.call(this,a,b);a.N.IN||eL();var c=a.u.Lb(),d=a.u.v();this.gg=new dL(a,c,a.yl.Ia,d.Xg()||z.cg);this.D(this.gg);a.N.Ua||(this.nn=new cL(c),this.D(this.nn));this.tr=new z.xF;this.D(this.tr)};var gL=function(a){var b=z.E.eb();return!a.B.fe()||b};var hL=function(a){z.Uy.call(this,a);this.Dm=1};var iL=function(a){z.Hs.call(this,a);z.av(a.u);this.Pb=new fL(a);this.Aq.start();this.ll(this.Pb);z.Ls(this)};
var jL=function(a,b){this.oC=SK;this.BI=iL;z.X.Do(b.strings||{});z.tl.call(this,a,b)};var kL=function(a){a.bk&&(a.bk.p(),delete a.bk)};z.v(KK,z.yv);z.e=KK.prototype;z.e.Xk=z.l(58);z.e.HE=z.l(60);z.e.IE=z.l(59);z.e.HE=z.K(60,function(a){this.Ha||(this.jo[a]=!1,z.zv(this,a,function(a){a.M(a.xa.Am)}))});
z.e.IE=z.K(59,function(a,b){if(!this.Ha){var c=this.d.u.v(),d=z.xu(a,b),f=c.get(z.U.ht);c.set(z.U.hp,d.DT);z.y(d.bb,(0,z.t)(this.d.R.M,this.d.R,"bootstrap_author_received"));d.content=z.hj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.kb(d.content,z.Bv(this,a))},this);z.kb(this.Bc,z.gj(d.content,z.Cb(a)));this.Td(a,d.content);z.zv(this,a,function(b){b.M(b.xa.pk,{Ed:a});b.set(b.k.af,!0)})}});
z.e.Xk=z.K(58,function(a,b){this.Vm=a;this.jd=b||this.jd;var c=this.Fd[a]=new z.uv;z.Ru.C();var d=this.d.u.v(),f=(0,z.t)(this.IE,this,a),g=(0,z.t)(this.HE,this,a),h=this.d.N.Hm,d=d.get(z.U.Rc),h=z.w.mu(d,h)+String(a)+".json";z.Su(0,h,f,g);return c});z.dG.prototype.Xk=z.K(57,function(a,b){this.Ak||(this.Ak=new KK(this.J));var c=this.Ak,d=JK(c,a,b);return c.Xk(d,a)});z.Ru.prototype.Nh=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.L.vd,z.w.Ye,a.na);(new z.Pe({url:a,wa:b,ra:c})).send()});
z.Pv.prototype.Nh=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.Ru.C().Nh;z.Qv(this,c,b,a);return a});z.dG.prototype.Nh=z.K(47,function(){z.Vv(this);this.zi=new z.Pv(this.J,void 0);var a=new z.uv;this.zi.Nh(a);return a});z.Ru.prototype.Jh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.L.vd,z.w.Ye,a.na,a.EM);(new z.Pe({url:a,wa:b,ra:c})).send({format:"stream"})});z.Pv.prototype.Jh=z.K(45,function(a,b){var c={na:this.d.u.v().id,EM:a},d=z.Ru.C().Jh;z.Qv(this,d,c,b);return b});
z.dG.prototype.Jh=z.K(44,function(a){z.Vv(this);this.zi=new z.Pv(this.J,void 0);var b=new z.uv;this.zi.Jh(a,b);return b});z.T.prototype.SF=z.K(43,function(){return this.aa});z.Bj.prototype.Un=z.K(42,function(){return this.get(this.k.gp)});z.v(RK,z.zl);z.da(RK);var lL={LW:"attachmentDelegate"};z.kb(lL,z.rG);RK.prototype.Qn=function(a){var b=RK.b.Qn.call(this,a),c=a.attachmentDelegate;c&&(b.MM=c);b.mx=a[lL.EK]||null;return b};z.v(SK,z.Ej);SK.prototype.ty=function(a){this.ui=new z.Nu(this);this.Vt=new z.Gq(this,a);this.Hc=new z.yi(this);this.cb=new z.jv(this,a);this.yl=new z.qv(this);this.u=new z.Zu(this,a);this.Jb=new z.dG(this,a);new z.rf;this.Go=new z.fw(this,a);this.Fb=new z.Ey(this)};z.v(TK,z.AF);z.e=TK.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.hx=b.v().fe();a.AT=!z.E.get(z.E.k.Pd);a.ql=b.ql(z.E.id);a.LN=2===c.get(z.U.tk);a.KN=3===c.get(z.U.tk);a.j={JS:z.X.get(z.X.g.xt),MS:z.X.get(z.X.g.yt),aS:z.X.get(z.X.g.tA),tx:z.X.get(z.X.g.Cp),ux:z.X.get(z.X.g.Dp),zo:z.X.get(z.X.g.vB),Qo:z.X.get(z.X.g.Gp),aW:z.X.get(z.X.g.NB)};return a};
z.e.G=function(a){TK.b.G.call(this,a);a=this.c;var b;b=this.s();var c=z.P,d=z.Pq(b),f;f=b.hx?(0,z.P)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.AT?b.ql?z.O(b.j.MS):z.O(b.j.JS):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.O(b.j.tx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.O(b.j.ux)+"\x3c/a\x3e"+(b.LN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.O(b.j.aW)+"\x3c/a\x3e":"")+(b.KN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.O(b.j.zo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.O(b.j.aS)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.Wk=this.n("fyre-follow-conversation");this.Os=this.n("fyre-stream-sort-hot-threads")||
null;this.Jy=this.n("fyre-stream-sort-top-comments")||null;this.sg=this.n("fyre-stream-sort-back");this.Vl=this.n("fyre-stream-sort-newest");this.Iy=this.n("fyre-stream-sort-oldest");this.IH=this.n("fyre-stream-sort-options");this.ad=this.n("fyre-content-loading");this.Ad()};z.e.l=function(){TK.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Mf,this.Kn,this);a.e(this.c,"click",this.ab);z.x([3,4,5],function(b){z.BF(this,a,b)},this);UK(this,a)};
z.e.ab=function(a){a.preventDefault();a=a.target;if(!z.Mo(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.sg)if(a===this.Wk)this.GE();else switch(VK(this,a),this.Ul(),a){case this.Os:this.AD();break;case this.Jy:this.dispatchEvent({type:"sortTopComments",Tb:(0,z.t)(this.Ad,this)});break;case this.Vl:this.bn("new");break;case this.Iy:this.bn("old")}};z.e.ri=function(a,b){a&&this.uy(b);z.Hn(this.IH,"display",a?"none":"block");z.Hn(this.sg,"display",a?"block":"none")};
z.e.uy=function(a){var b=this.Vl,c=this.bn,d=z.X.get(z.X.g.it);4===a&&(b=this.Os,c=this.AD,d=z.X.get(z.X.g.OI));this.sg.innerHTML=d;this.q().vf(this.sg,"click",(0,z.t)(function(a){a.stopPropagation();this.ri(!1);VK(this,b);c.apply(this)},this))};z.e.Hn=function(a){a.stopPropagation();this.ri(!1);VK(this,this.Vl);this.bn()};z.e.mr=function(a){var b=a.Tb;z.kb(a,{Tb:(0,z.t)(function(){b();this.ri(!0,4)},this)})};
z.e.bn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Tb:(0,z.t)(this.Ad,this)})};z.e.AD=function(){this.dispatchEvent({type:"sortHotThreads",Tb:(0,z.t)(this.Ad,this)})};z.e.GE=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.ql(z.E.get(b.X)),a.jj(!b),a=b?z.X.get(z.X.g.xt):z.X.get(z.X.g.yt),this.Wk.innerHTML=a):z.Qh(this.d.Hc,(0,z.t)(this.GE,this))};
z.e.Kn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.fe()||z.E.get(c.Pd);this.Wk&&(b?z.S(this.Wk,!1):(a=a.ql(z.E.id)?z.X.get(z.X.g.yt):z.X.get(z.X.g.xt),this.Wk.innerHTML=a,z.S(this.Wk,!0)))};z.e.h=function(){TK.b.h.call(this);z.E.off(null,null,this)};z.v(WK,TK);WK.prototype.G=function(a){this.c=a;z.Vl(a,PK,this.s());this.Vl=this.n("fyre-stream-sort-newest");this.Iy=this.n("fyre-stream-sort-oldest");this.IH=this.n("fyre-stream-sort-options");this.ad=this.n("fyre-content-loading");this.Ad()};WK.prototype.bn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.NV.stream,direction:a,Tb:(0,z.t)(this.Ad,this)})};
WK.prototype.s=function(){return{j:{KM:z.X.get(z.X.g.JI),tx:z.X.get(z.X.g.Cp),ux:z.X.get(z.X.g.Dp),zo:z.X.get(z.X.g.vB),Qo:z.X.get(z.X.g.Gp)}}};z.v(XK,z.rx);z.e=XK.prototype;z.e.Pm=function(a){this.clear();z.S(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Hd();this.sb={};this.qj=[];for(this.kh=this.Dk=null;this.ma&&0!=this.ma.length;)this.qo(0).p()};z.e.G=function(a){XK.b.G.call(this,a);z.Vl(this.c,z.Qq,this.s());this.Vj=this.n("fyre-stream-content");this.si=this.n("fyre-stream-more");this.Ea.S(this.si);z.S(this.si,!1)};z.e.h=function(){this.Ea&&this.Ea.p();this.Ea=null;XK.b.h.call(this)};
z.e.l=function(){XK.b.l.call(this);this.q().e(this.Ea,"showMore",this.sw)};z.e.s=function(){return{Sc:z.w.L.kb,Pu:!!this.Ea,j:{Ay:z.X.get(z.X.g.KI)}}};z.e.uw=function(){this.Ea.Ks()};z.e.Mx=function(){this.dispatchEvent({type:this.Jt,direction:this.jd,target:this,Tb:(0,z.t)(this.uw,this),ij:(0,z.t)(this.eF,this)})};z.e.Fo=function(){var a=this.J.Jb.Ak,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.hp),c=!b&&a.Vm>-c;b&&-1>a.Vm||c?this.Ea.show():this.Ea.nb()};
z.e.start=function(){this.nl||(this.Mx(),this.nl=!0)};z.v(YK,z.yF);YK.prototype.s=function(){var a=this.m.get(z.U.Qc),b,c;this.m.fe()?(b=z.X.get(z.X.g.sK),c=z.X.get(z.X.g.yA)):(b=z.X.get(z.X.g.Nf),c=z.X.get(z.X.g.jm));z.Ga(b,"%s")||(b="%s "+b);z.Ga(c,"%s")||(c="%s "+c);switch(a){case 1:b=z.wa(b,a);break;default:b=z.wa(c,a)}return{j:{Bu:b}}};YK.prototype.kz=function(){var a=this.c,b;b=this.s();b=(0,z.P)("\x3cspan\x3e"+z.O(b.j.Bu)+"\x3c/span\x3e");a.innerHTML=b};z.v(ZK,z.St);ZK.prototype.Io=200;ZK.prototype.Ph=function(){return new $K(this.Gc)};ZK.prototype.s=function(){var a={};a.message=this.cz;return a};z.v($K,z.Mt);$K.prototype.Lc=function(a,b,c){var d=z.go(this.element),d=new z.Ah(d.width,d.height+25);b=z.Ht(this.element,this.Ah,a,b,d,c,9);z.Nn(a.lastChild,0);b&&(d=new z.Ah(0,-5),z.Ht(this.element,2,a,1,d,c,5),z.Nn(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(aL,z.T);z.e=aL.prototype;z.e.r=function(){this.c=z.Yl(OK,this.s())};z.e.l=function(){aL.b.l.call(this);this.Sa=new ZK(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.ab)};z.e.h=function(){aL.b.h.call(this);this.Sa&&this.Sa.p()};z.e.s=function(){var a=z.Wd,b={};b.ud=this.m.get(a.ub);b.Yb=this.m.get(a.hk);b.Y=this.m.get(a.ua);b.id=this.m.id;b.cS=this.m.id.replace(/[@.]/g,"-");b.Ca=this.m.get(a.Vb);return b};
z.e.ab=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(bL,z.T);z.e=bL.prototype;z.e.CA=10;z.e.h=function(){bL.b.h.call(this);delete this.bc};z.e.Q=function(){bL.b.Q.call(this);this.bc.off(null,null,this)};z.e.qE=function(a){a=new aL(a);var b=this.Kc();if(b===this.CA){var c=this.qo(b-1);c&&(c.p(),b--)}0<b?this.ve(a,0,!0):this.D(a,!0)};z.e.hR=function(a){var b;this.Uc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Vh=function(){this.bc.on(this.bc.xa.gt,this.qE,this);this.bc.on(this.bc.xa.Gt,this.hR,this);var a=this.bc.ob.reverse().slice(0,this.CA);z.x(a,this.qE,this)};z.v(cL,bL);z.v(dL,z.zF);dL.prototype.G=function(a){dL.b.G.call(this,a);this.Mj()};dL.prototype.Mj=function(){this.c.innerHTML=z.Tq(this.s())};z.v(fL,z.IF);
fL.prototype.bH=function(a,b){if(!this.Ha){this.B=b;var c=b.get(z.U.th),d=b.get(z.U.Qd);this.at=new z.FF(c,d,a.N.Ua);this.D(this.at);this.kq=new YK(a.u.v());this.D(this.kq);this.Yr=null;b.Un()&&(this.fu=new WK(a),this.D(this.fu),this.Bk=new XK(a),this.D(this.Bk),LK(this.fu,{stream:this.Bk}));this.hh=new TK(a);this.D(this.hh);this.Qr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.S(this.Ae,!0)},this));b.get(z.U.pm)&&!z.cg&&MK(this.B)&&(this.B.Xg()||this.B.fe()||this.Xv())}};
fL.prototype.s=function(){var a=!this.d.N.aq&&!z.w.Nu&&!this.d.N.wD;return{cI:z.w.L.dz,dI:(0,window.encodeURIComponent)(String(window.location.href)),Ua:this.d.N.Ua,Xg:this.B.Xg(),fe:this.B.fe(),Ke:z.cg,Wu:a,tS:this.d.N.aq,Un:this.B.Un()}};z.Fx={HW:"fyre-archive-stream",IW:"fyre-archive-stream-header",t_:"fyre-top-content-stream",M_:"fyre-widget",pm:"fyre-featured-content-wrapper"};z.kb(z.Fx,z.tJ);z.e=fL.prototype;
z.e.r=function(){this.c=z.Yl(NK,this.s());var a=this.B.get(z.U.tk);if(1!==a){var b=this.d.Fb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Fy(b,a,c,this)}this.tr.S(this.n(z.Fx.dK));this.Bk&&(b=this.n("fyre-archive-stream-header"),this.fu.S(b),this.Bk.S(this.n("fyre-archive-stream")));this.Bh(1);this.Ae=this.n(z.Fx.rh);b=gL(this);z.S(this.Ae,b)};
z.e.l=function(){fL.b.l.call(this);var a=this.Zb;this.aa&&a&&a.S(this.Ae,!0);this.d.R.So("stream_data_received",this.fQ,this);this.q().e(this,"request_content_context",this.GP).e(this,"request_content_reply",this.jR);this.Bk&&this.Bk.start()};z.e.Vh=function(){this.nn&&this.nn.Vh();this.gg.Vh()};z.e.fQ=function(){var a=this.B,b=a.get(z.U.kk);z.rh||b||(b=(0,z.t)(function(){this.Yr=new z.mL(this.d,a.get(z.U.Qd));this.D(this.Yr,!0)},this),z.uc(z.w.L.kb+z.w.yf.Yr,null,null,b))};
z.e.Xv=function(){var a=new z.qE(this.SF,this);a.EG=(0,z.t)(this.PU,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.uc(z.w.L.kb+z.w.yf.rO,null,null,b)};z.e.PU=function(){var a=this.n("fyre-featured-content-wrapper");this.iv=new z.JJ(this.d);this.D(this.iv);this.iv.S(a);this.iv.Wg()};z.e.Qr=function(a){if(!this.d.N.readOnly){var b=this.d.u.v();z.Aw(z.xw.C(),"main",a,{J:this.d,ji:"new"},b);z.E.on(z.E.hc(z.E.k.X),this.Wc,this)}};z.e.Wc=function(){var a=gL(this);z.S(this.Ae,a)};
z.e.Uh=function(){0<z.xo(this,this.Zb)&&(this.removeChild(this.Zb),this.Zb.p());this.Qr((0,z.t)(function(a){this.Zb=a;this.D(this.Zb);a=this.Zb;this.aa&&a&&a.S(this.Ae,!0);z.S(this.Ae,!0)},this))};z.e.Ug=function(a){null!=a&&(this.d.Fb.bl(1),(0,window.setTimeout)((0,z.t)(function(){this.Ha||z.JF(this,a)},this),3E3))};z.e.GP=function(a){z.JF(this,a.Gk)};z.e.jR=function(a){z.JF(this,a.Gk,function(a){z.ww(a.Ib)})};
z.e.h=function(){fL.b.h.call(this);z.E.off(z.E.hc(z.E.k.X),this.Wc,this);this.B&&(this.B.off(null,null,this),this.B=null)};z.v(hL,z.Uy);z.e=hL.prototype;z.e.ce=function(a,b){hL.b.ce.call(this,a,b);a.e(b,"repliesExpanded",this.DE);a.e(b,"sortHotThreads",this.sR);a.e(b,"sortOrderChanged",this.hF);a.e(b,"sortTopComments",this.tR);a.e(b,"archiveShowMore",this.rP);a.e(b,"archiveSortOrderChanged",this.sP)};
z.e.rP=function(a){var b=a.Tb||z.n;a=(0,z.t)(this.Fe,this,a.target);var c=this.d.Jb;c.Ak||(c.Ak=new KK(c.J));var c=c.Ak,d=JK(c),f=c.le[d];f&&(c.Vm=d);if(f)b(),a(f);else{c=this.d.Jb.Xk();d=c.k.af;if(c.get(d))b();else c.on(c.hc(d),b,this);z.Vy(this,c,a)}};z.e.Sv=function(a,b){var c=2===b.bd,d=1!==b.bd;switch(b.type){case 0:var f=this.d.u.v(),f=z.tk(b,f),g=f.get(z.Hk),g=this.d.u.bb().get(g);f.set(z.uk,g);a.jw(f,c,d)}};
z.e.$E=function(a){if(1!==this.Dm){var b=this.HV.hh;b.ri(!1);VK(b,b.Vl);z.kb(a,{direction:"new",Tb:z.n});this.hF(a)}};z.e.sP=function(a){z.Wy(this);a.stream.Pm(a.direction);var b=this.d.Jb.Xk(a.direction,!0),c=(0,z.t)(function(b){a.Tb();this.Fe(a.stream,b)},this);z.Vy(this,b,c,a.ij)};z.e.hF=function(a){this.d.N.Rn=null;var b=z.Yy(this,1);z.Vv(this.d.Jb);b.Pm(a.direction);var c=z.Uv(this.d.Jb,a.direction),d=(0,z.t)(function(c){a.Tb();this.Fe(b,c)},this);z.Vy(this,c,d,a.ij)};
z.e.tR=function(a){var b=z.Yy(this,3),c=this.d.Jb.Jh("likes");z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.Fe(b,c)},this))};z.e.sR=function(a){var b=z.Yy(this,4),c=this.d.Jb.Nh();z.Vy(this,c,(0,z.t)(function(c){a.Tb();z.hb(c)?z.qx(b):this.Fe(b,c)},this))};z.v(iL,z.Hs);z.e=iL.prototype;z.e.c=null;z.e.h=function(){iL.b.h.call(this);this.Qs.p();this.RC.p();this.Pb.aa&&this.Pb.p();this.Lf&&this.Lf.p();delete this.Lf};z.e.ll=function(a){iL.b.ll.call(this,a);this.Qs=new hL(this.d);this.Qs.handle(a);this.RC=new z.Ty(this.d);this.RC.handle(a)};z.e.Qy=function(){this.d.ui.stop()};z.e.MV=function(){this.d.yl.stop()};z.e.Sj=function(){this.d.ui.start()};z.e.KV=function(){this.d.yl.start()};
z.e.oa=function(){this.Lf&&this.Lf.p();this.Pb.oa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.xM)z.Ms(this);else{var a=z.Js(this);this.Pb.Ug(a)}this.d.R.M("render_complete")};z.v(jL,z.tl);jL.prototype.hC=RK.C();jL.prototype.h=function(){jL.b.h.call(this);this.stop();delete this.N;delete this.ha;kL(this);z.yl(this);this.hj&&(this.hj.p(),delete this.hj)};jL.prototype.Yy=function(){this.stop();kL(this);jL.b.Yy.call(this)};z.lg.main.Dh.ia(jL);})(fyre.conv);
