
all: subdirs

subdirs:
	cd example1; make
	cd example2; make
	cd example3; make
	cd example4; make


clean:
	cd example1; make clean
	cd example2; make clean
	cd example3; make clean
	cd example4; make clean

