

(function($,win,undef){var $win=$(win),doc=win.document;$.plugin2=function(name,methods){var CLASS_NAME='plugin-'+name,OPTIONS_DATA_KEY=name+'-options';methods._mergeOptions=function(options){return $.extend(true,{},this._defaultOptions,options);};methods.closestInit=function(){var $init=this.$caller.closest('.'+CLASS_NAME);return $init.length>0?$init:$(doc);};methods.option=function(key,value){var $init=this.closestInit(),first;if(typeof key==='undefined'){first=$init[0];return first?$.data(first,OPTIONS_DATA_KEY):null;}else if(typeof value==='undefined'){first=$init[0];return first?$.data(first,OPTIONS_DATA_KEY)[key]:null;}else{$init.each(function(){$.data(this,OPTIONS_DATA_KEY)[key]=value;});return this.$caller;}};methods.live=function(selector,options){var plugin=this,$caller=plugin.$caller;options=plugin._mergeOptions(options);if(plugin._init){plugin._init(selector,options);}
$caller.onCreate(selector,function(){var $element,elementPlugin;if(!$.data(this,OPTIONS_DATA_KEY)){$element=$(this);elementPlugin=$.extend({},plugin,{'$caller':$element});$.data(this,OPTIONS_DATA_KEY,options);$element.addClass(CLASS_NAME);if(elementPlugin._create){elementPlugin._create(this,options);}}});if(plugin._createAll){$caller.bind('create',function(event){plugin._createAll(event.target,selector,options);});}
return $caller;};methods.init=function(options){return this.live(null,options);};$.fn[name]=function(method){var plugin=$.extend({},methods,{'$caller':this});if(!method||typeof method==='object'){return plugin.init(method);}
method=''+method;if(method.substr(0,1)!=='_'&&plugin[method]){return plugin[method].apply(plugin,Array.prototype.slice.call(arguments,1));}else{return $.error('['+method+'] method doesn\'t exist on ['+name+'] plugin!');}};};$.run=function(runFunction){runFunction();return runFunction;};$.throttle=function(interval,throttledFunction){var lastTrigger=0,timeout,lastArguments;if(interval<=0){return throttledFunction;}
return function(){var context,now,delay;lastArguments=arguments;if(timeout){return;}
context=this;now=+new Date();delay=interval-now+lastTrigger;if(delay<=0){lastTrigger=now;throttledFunction.apply(context,lastArguments);}else{timeout=setTimeout(function(){lastTrigger=now;timeout=null;throttledFunction.apply(context,lastArguments);},delay);}};};(function(){var $dragCover,endDrag,$dragElement,startDrag,dragStartTimeout,startPageX,startPageY,lastPageX,lastPageY,dragMoveCallback,dragEndCallback;$dragCover=$('<div/>',{'css':{'height':'100%','left':0,'position':'fixed','top':0,'user-select':'none','width':'100%','z-index':1000000}});endDrag=function(event){if(dragStartTimeout){clearTimeout(dragStartTimeout);dragStartTimeout=null;}
dragMoveCallback=null;$(doc.body).css('user-select','');if($dragElement){$dragElement.unbind('.drag');$dragElement=null;}
if(dragEndCallback){dragEndCallback(event);dragEndCallback=null;}};$.drag=function(element,event,startCallback,moveCallback,endCallback){var data;if(event.which!==1||event.altKey||event.ctrlKey||event.metaKey||event.shiftKey){return;}
data={'$dragCover':$dragCover};endDrag(event);$(doc.body).css('user-select','none');$dragElement=$(element);$dragElement.bind('dragstart.drag',function(){return false;});startPageX=lastPageX=event.pageX;startPageY=lastPageY=event.pageY;startDrag=function(){var drag=function(){dragMoveCallback=function(event){return moveCallback.call(element,event,data);};dragEndCallback=function(event){return endCallback.call(element,event,data);};$(doc.body).append($dragCover);startCallback.call(element,event,data);};if(event.dragImmediately){drag();}else{dragStartTimeout=setTimeout(function(){var deltaX=lastPageX-startPageX,deltaY=lastPageY-startPageY;if(Math.sqrt(deltaX*deltaX+deltaY*deltaY)<(event.dragDistance||5)){startDrag();return;}
drag();},(event.dragDelay||100));}};startDrag();};$win.mousemove($.throttle(50,function(event){if(dragStartTimeout){lastPageX=event.pageX;lastPageY=event.pageY;}
if(dragMoveCallback){dragMoveCallback(event);}}));$win.mouseup(function(event){endDrag(event);$dragCover.remove();});}());$.fn.isFixedPosition=function(){var $parent=this,$newParent;while(true){if($parent.css('position')==='fixed'){return true;}
$newParent=$parent.offsetParent();if($parent.length===0||$parent[0]===$newParent[0]){break;}else{$parent=$newParent;}}
return false;};$.fn.zIndex=function(){var zIndex;for(var $parent=this;$parent.length>0;$parent=$parent.parent()){try{zIndex=parseInt($parent.css('z-index'),10);}catch(error){break;}
if(!isNaN(zIndex)&&zIndex!==0){break;}}
return zIndex;};(function(){var oldDelegate=$.fn.delegate;$.fn.delegate=function(){if(arguments[0]){return oldDelegate.apply(this,arguments);}else{return $.fn.bind.apply(this,Array.prototype.slice.call(arguments,1));}};}());(function(){var CHECK_INTERVAL_DATA='input-checkInterval';if(!('oninput'in doc.createElement('input'))){$.event.special.input={'add':function(handleObject){var $root=$(this),selector=handleObject.selector,handler,clearCheckInterval;handler=$.throttle(50,function(){$(this).trigger('input');});$root.delegate(selector,'keyup',function(){setTimeout(handler,0);});clearCheckInterval=function(){var interval=$.data(this,CHECK_INTERVAL_DATA);if(interval){clearInterval(interval);$.removeData(this,CHECK_INTERVAL_DATA);}};$root.delegate(selector,'focus',function(){clearCheckInterval.call(this);$.data(this,CHECK_INTERVAL_DATA,setInterval(handler,50));});$root.delegate(selector,'blur',clearCheckInterval);}};}}());$.elementFromPoint=function(x,y){var element=doc.elementFromPoint(x,y);if(element){if(element.nodeType===3){element=element.parentNode;}
if(element){return $(element);}}
return $();};$.fn.onCreate=function(selector,handler){if(selector){this.bind('create',function(event){$(event.target).find(selector).each(handler);});}else{this.each(handler);}};$.easing.easeOutBack=function(x,t,b,c,d,s){if(s===undefined){s=1.70158;}
return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;};$.addQueryParameters=function(){var uri=arguments[0],questionAt=uri.indexOf('?'),queryString,argIndex,argLength=arguments.length,paramName,paramValue;if(questionAt>-1){queryString='&'+uri.substring(questionAt+1);uri=uri.substring(0,questionAt);}else{queryString='';}
for(argIndex=1;argIndex<argLength;argIndex+=2){paramName=arguments[argIndex];paramValue=arguments[argIndex+1];queryString=queryString.replace(new RegExp('&'+paramName+'=[^&]*','g'),'');if(paramValue!==undefined&&paramValue!==null){$.each($.isArray(paramValue)?paramValue:[paramValue],function(i,v){queryString+='&';queryString+=encodeURIComponent(paramName);queryString+='=';queryString+=encodeURIComponent(v);});}}
return queryString.length>1?uri+'?'+queryString.substring(1):uri;};}(jQuery,window));

(function($,win,undef){var $win=$(win),doc=win.document;$.plugin2('popup',{'_defaultOptions':{'padding':{'left':35,'right':35,'top':20}},'_create':function(element){var $inner=$(element);var options=this.option();var $container=$('<div/>',{'class':'popup'});var $content=$('<div/>',{'class':'content'});var $closeButton=$('<div/>',{'class':'closeButton'});var name=$inner.attr('name');if(name){$container.attr('name',name);}
$container.bind('open.popup',function(){var $original=$(this);var scrollLeft=$original.data('popup-scrollLeft');var scrollTop=$original.data('popup-scrollTop');if(typeof scrollLeft!=='number'&&typeof scrollTop!=='number'){$original.data('popup-scrollLeft',$win.scrollLeft());$original.data('popup-scrollTop',$win.scrollTop());}
$original.show();});$container.bind('restoreOriginalPosition.popup',function(){var $original=$(this);var scrollLeft=$original.data('popup-scrollLeft');var scrollTop=$original.data('popup-scrollTop');$original.removeData('popup-scrollLeft');$original.removeData('popup-scrollTop');if(typeof scrollLeft==='number'&&typeof scrollTop==='number'){$win.scrollLeft(scrollLeft);$win.scrollTop(scrollTop);}});$container.bind('close.popup',function(){var $original=$(this);$original.hide();$('.popup').each(function(){var $popup=$(this);var $source=$popup.popup('source');if($source&&$.contains($original[0],$source[0])){$popup.popup('close');}});});$closeButton.bind('click.popup',function(){$(this).popup('close');});var $body=$(doc.body);$content.append($inner);$content.append($closeButton);$container.append($content);$body.append($container);},'open':function(){this.$caller.popup('container').trigger('open');return this.$caller;},'restoreOriginalPosition':function(){this.$caller.popup('container').trigger('restoreOriginalPosition');return this.$caller;},'close':function(){this.container().trigger('close');return this.$caller;},'container':function(){return this.$caller.closest('.popup');},'content':function(){return this.$caller.popup('container').find('> .content');},'source':function($newSource,event){var options=this.option();if(event&&($newSource.height()<30||typeof event.pageX!=='number'||typeof event.pageY!=='number')){event=undef;}
if(typeof $newSource==='undefined'){var container=this.$caller.popup('container')[0];return container?$.data(container,'popup-$source'):null;}else{var $container=this.$caller.popup('container');$container.attr('data-popup-source-class',$newSource.prop('class'));$container.each(function(){$.data(this,'popup-$source',$newSource);});var sourceOffset=$newSource.offset();var popupWidth=$container.outerWidth();var markerDelta=0;var left=event?event.pageX-popupWidth/2:sourceOffset.left+($newSource.outerWidth()-popupWidth)/2;if(left<options.padding.left){markerDelta=left-options.padding.left;left=options.padding.left;}else{var leftDelta=left+popupWidth-$(doc).width()+options.padding.right;if(leftDelta>0){markerDelta=leftDelta;left-=leftDelta;}}
var $content=$container.popup('content');var $marker=$content.find('> .marker');if($marker.length===0){$marker=$('<div/>',{'class':'marker'});$content.append($marker);}
var markerLeft=(popupWidth-$marker.outerWidth())/2+markerDelta;$marker.css('left',markerLeft<5?5:markerLeft);var top=event?event.pageY:sourceOffset.top+$newSource.outerHeight();if(top<30){top=30;}
var isFixedPosition=$newSource.isFixedPosition();if(isFixedPosition){left-=$(window).scrollLeft();top-=$(window).scrollTop();}
var $newSourceParent=$newSource.closest('.popup');if($newSourceParent.length===0){$newSourceParent=$newSource.parent();}
$container.css({'left':left,'margin':0,'position':isFixedPosition?'fixed':'absolute','top':top,'z-index':$newSource.parent().zIndex()+1});return this.$caller;}}});$win.click(function(event){var target=event.target,$target=$(target);if($target.closest('#context-menu-layer, .context-menu-root').length>0){return;}
if($target.popup('container').length===0){$('.popup').each(function(){var $container=$(this);var $source=$container.popup('source');if($source&&$source.length>0){var source=$source[0];if(!(source==target||$.contains(source,target))){$container.popup('close');}}});}});$win.keydown(function(event){if(event.which===27){var $containers=$('.popup');if($containers.length>0){$containers.popup('close');return false;}else{return true;}}});}(jQuery,window));

(function($,win,undef){var $win=$(win),doc=win.document,formTargetIndex=0;$.plugin2('frame',{'_defaultOptions':{'frameClassName':'dari-frame','loadingClassName':'dari-frame-loading','loadedClassName':'dari-frame-loaded','bodyClassName':'dari-frame-body','setBody':function(body){$(this).html(body);}},'_init':function(selector,options){var plugin=this,$caller=plugin.$caller,frameClassName=options.frameClassName,loadingClassName=options.loadingClassName,loadedClassName=options.loadedClassName,bodyClassName=options.bodyClassName,findTargetFrame,beginLoad,endLoad,loadPage;findTargetFrame=function(element,callback){var $element=$(element),target=$element.attr('target'),$frame;if(target&&$('frame[name="'+target+'"], iframe[name="'+target+'"]').length>0){return true;}
if(target!=='_top'&&target!=='_blank'){if(target==='_parent'){$frame=$element.frame('container').parent().frame('container');}else if(target){$frame=$('.'+frameClassName+'[name="'+target+'"]');if($frame.length===0){$frame=$('<div/>',{'class':frameClassName,'name':target});$(doc.body).append($frame);$frame.popup();}}else{$frame=$element.frame('container');}
if($frame.length>0&&$frame[0]!==doc){return callback($element,$frame);}}
return true;};beginLoad=function($frame,$source,event){var version=($frame.data('frame-loadVersion')||0)+1,$popup=$frame.popup('container');$frame.add($popup).removeClass(loadedClassName).addClass(loadingClassName);$frame.data('frame-loadVersion',version);$frame.data('frame-$source',$source);if($popup[0]&&$source[0]&&!$.contains($popup[0],$source[0])){$frame.popup('source',$source,event);$frame.empty();}
$frame.popup('open');return version;};endLoad=function($frame,version,data){var $popup,$wrapper,$bodyContainer,body;if(version>=$frame.data('frame-loadVersion')){$popup=$frame.popup('container');body=data;body=body.replace(/^[\s\S]*?<body[^>]*>/ig,'');body=body.replace(/<\/body>[\s\S]*?$/ig,'');$frame.add($popup).removeClass(loadingClassName).addClass(loadedClassName);options.setBody.call($frame[0],body);$frame.trigger('create');$frame.trigger('load');$win.resize();}};loadPage=function($frame,$source,method,url,data,event){var plugin=this,version=beginLoad($frame,$source,event),extraFormData=$frame.attr('data-extra-form-data');$frame.trigger('beforeLoad',{url:url,data:data});if(extraFormData){url+=(url.indexOf('?')<0?'?':'&')+extraFormData;}
return $.ajax({'cache':false,'type':method,'url':url,'data':data,'complete':function(response){endLoad($frame,version,response.responseText);}});};$caller.delegate('a','click.frame',function(event){return findTargetFrame(this,function($anchor,$frame){loadPage($frame,$anchor,'get',$anchor.attr('href'),null,event).done(function(){if($anchor.data('hide-parent')){$anchor.parent().hide();}else{$anchor.hide();}});return false;});});$caller.delegate('form','click.frame',function(event){if(!$(event.target).is('button, input[type="submit"]')){return;}
$.data(this,'frame-clicked',event.target);});$caller.delegate('form','submit.frame',function(){return findTargetFrame(this,function($form,$frame){var action=$form.attr('action'),extraFormData=$frame.attr('data-extra-form-data'),clicked=$.data($form[0],'frame-clicked'),clickedName,clickedValue;if(clicked){clickedName=$(clicked).prop('name');clickedValue=$(clicked).prop('value');if(clickedName&&clickedValue){action+=(action.indexOf('?')>-1?'&':'?')+encodeURIComponent(clickedName)+'='+encodeURIComponent(clickedValue);}}
if($form.attr('enctype')!=='multipart/form-data'){loadPage($frame,$form,$form.attr('method'),action,$form.serialize());return false;}
$form.attr('action',action+(action.indexOf('?')<0?'?':'&')+extraFormData);if($form.find(':hidden[name="_frame"]').length===0){$form.prepend($('<input/>',{'name':'_frame','type':'hidden','value':'true'}));}
var target=$form.attr('target');var hasTarget=true;if(!target){formTargetIndex+=1;target='frameTarget'+formTargetIndex+(+new Date());$form.attr('target',target);hasTarget=false;}
var $submitFrame=$('iframe[name='+target+']');if($submitFrame.length===0){$submitFrame=$('<iframe/>',{'name':target});$submitFrame.hide();$(doc.body).append($submitFrame);}
var version=beginLoad($frame,$form);$submitFrame.unbind('.frame');$submitFrame.bind('load.frame',function(){$form.attr('action',action);endLoad($frame,version,$submitFrame.contents().find('textarea#frameBody').val()||$submitFrame.contents().find('body').html());if(!hasTarget){$form.removeAttr('target');setTimeout(function(){$submitFrame.remove();},0);}});return true;});});$caller.onCreate('.'+frameClassName,function(){var $frame=$(this),$anchor;if($frame.is(':not(.'+loadingClassName+'):not(.'+loadedClassName+')')){$anchor=$frame.find('a:only-child:not([target])');if($anchor.length>0){$anchor.click();}else{$frame.find('form:only-child:not([target])').submit();}}});return $caller;},'container':function(){return this.$caller.closest('.'+this.option('frameClassName'));},'source':function(){return this.container().data('frame-$source');}});}(jQuery,window));