(function(){var g=void 0,h=true,i=null,k=false,m,o=this;function aa(a){var b=ba;function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ca(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function da(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function p(a,b){var c="",d=ea(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ea(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,l=3285377520,j=[],n,w,x,E,y,H=Math.ceil((a.length/4+2)/16),R=[H],A=0,v;A<H;A++){R[A]=[];for(n=0;n<16;n++)R[A][n]=a.charCodeAt(A*64+n*4)<<24|a.charCodeAt(A*64+n*4+1)<<16|a.charCodeAt(A*64+n*4+2)<<8|a.charCodeAt(A*64+n*4+3)}A=(a.length-1)*8;a=H-1;R[a][14]=Math.floor(A/Math.pow(2,32));R[a][15]=A&4294967295;for(A=0;A<H;A++){for(v=0;v<16;v++)j[v]=R[A][v];
for(v=16;v<80;v++)j[v]=(j[v-3]^j[v-8]^j[v-14]^j[v-16])<<1|(j[v-3]^j[v-8]^j[v-14]^j[v-16])>>>31;a=c;n=d;w=e;x=f;E=l;for(v=0;v<80;v++)y=Math.floor(v/20),y=(a<<5|a>>>27)+(y==0?n&w^~n&x:y==1?n^w^x:y==2?n&w^n&x^w&x:n^w^x)+E+b[y]+j[v]&4294967295,E=x,x=w,w=n<<30|n>>>2,n=a,a=y;c=c+a&4294967295;d=d+n&4294967295;e=e+w&4294967295;f=f+x&4294967295;l=l+E&4294967295}return[c,d,e,f,l]}function r(a,b){return function(){a.apply(b,arguments)}}function fa(a){return a.replace(/^www\./,"")}
function s(a,b,c){a.addEventListener?a.addEventListener(b,c,k):a.attachEvent&&a.attachEvent("on"+b,c)}function ga(a,b){var c=o;c.removeEventListener?c.removeEventListener(a,b,k):c.detachEvent&&c.detachEvent("on"+a,b)}function t(a){return typeof a==="number"}function u(a){return typeof a==="string"}function ha(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function z(){return(new Date).getTime()}function ia(a){return encodeURIComponent(a)}
function ja(a,b){if(!(a&&a.constructor===Object)||!(b&&b.constructor===Object))return a===b;var c=0,d=h;q(a,function(a,e){c++;return d=a===b[e]});if(!d)return k;var e=0;q(b,function(){e++});return c===e}function q(a,b){if((!!a&&a.constructor===Object)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===k)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===k)break}}function ka(a,b){var c=[];q(a,function(a){b(a)&&c.push(a)});return c}
function la(a){(!!a&&a.constructor===Object)===h&&(a="");var b={};q(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ma(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,l=a.length;f<=l;f++)c[0][f]=f;for(var j,n,w,d=1;d<=e;d++)for(f=1;f<=l;f++)j=d-1,n=f-1,w=c[j][n],b.charAt(j)==a.charAt(n)?c[d][f]=w:(n=c[d][n]+1,j=c[j][f]+1,w+=2,c[d][f]=Math.min(n,j,w));return c[b.length][a.length]};var B={},na=1;function C(a,b,c){na++;B[a]=B[a]||{};B[a][na]=[b,c];return na}function D(a){if(u(a))B[a]=g,delete B[a];else if(t(a)){var b=h;q(B,function(c){q(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=k});return b})}}function F(a,b){if(B[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(B[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};var G={};
G.d=function(){G.G?G.T("pageload"):(G.Sa=[{target:o,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:o,event:"resize"},{target:document.body,event:"mousedown"}],G.Z=i,G.ta=k,G.F=i,G.Ja={},q(G.Sa,function(a){var b=a.event;s(a.target,b,function(a){G.T.call(G,b,a)})}),C("focus",function(){G.T("focus")}),G.T("pageload"),s(document.body,"click",function(a){a:if(a=a||window.event){if(a=a.target||a.srcElement,a.tagName!=="A")if(a.parentNode)if(a.parentNode.tagName==="A")a=
a.parentNode;else if(a.parentNode.parentNode&&a.parentNode.parentNode.tagName==="A")a=a.parentNode.parentNode;else{a=g;break a}else{a=g;break a}}else a=g;a&&F("anchor",a)}),G.G=h)};G.Va=function(){var a,b=G.Ja.keydown;if(b===g)return k;b=z()-b;return b<=(a||15E3)&&b>=0};G.ya=100;G.T=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.vb(a);G.Z===i?G.Qa():G.ta=h};G.vb=function(a){G.Ja[a]=z()};
G.Qa=function(){G.Z=o.setTimeout(G.Xa,G.ya);F("activity");G.F!==i&&o.clearTimeout(G.F);G.F=o.setTimeout(function(){F("inactive");o.clearTimeout(G.F);G.F=i},5E3+G.ya)};G.Xa=function(){o.clearTimeout(G.Z);G.Z=i;if(G.ta)G.ta=k,G.Qa()};function oa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function pa(a,b,c){var d="",e=o.location.href.split("?");e.length&&(e=oa(e[1]),b=c||b,e[b]&&(d="&"+a+"="+e[b]));return d}function qa(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function ra(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=o.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=qa(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(qa(b.protocol,b.port)||b.port==="0")b.port="";return b}
function sa(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function I(a,b,c){a[b]=a[b]||c}function ta(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=oa(b.src.split("?")[1]),I(a,"uid",b.uid),I(a,"domain",b.domain),k})}function J(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""}function ua(a){var b=[];q(a,function(a,d){d.charAt(0)=="_"&&b.push(d+"="+a)});return b.length?"&"+b.join("&"):""};var va=/[?&]__cb_debug=/i;function wa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function K(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=wa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function xa(a,b,c){return a===g?k:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?k:xa(a.parentNode,b,c)}
function L(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=wa("data-cb-scroll-element"))&&c.length)return c[0][b];if(t(o[a]))return o[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function ya(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function M(){return ya("Height")}
function za(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function N(){return za("Height")}function Aa(a,b){var c;u(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==document.documentElement;){if(c(a))return a;a=a.parentNode}return i};function O(a){var b=a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=P(a,"overflow"),e=P(a,"overflow-x"),f=P(a,"overflow-y");d==="hidden"||e==="hidden"||f==="hidden"||q(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,k})}return{height:b,width:c}}function Ba(a){a=O(a);return a.height*a.width}
function Ca(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=k:(b=O(a),b=b.height>1&&b.width>1);if(!b)return k;if(P(a,"visibility")==="hidden")return k;if(P(a,"overflow")==="hidden"&&(a.offsetHeight===0||a.offsetWidth===0))return k;b=h;for(var c=a.parentElement;c&&b;){var d;var e=c;if(e.scrollHeight===e.clientHeight&&e.scrollWidth===e.clientWidth)d=k;else{d=P(e,"overflow");var f=P(e,"overflow-x"),e=P(e,"overflow-y");d=d==="auto"||d==="scroll"||f==="auto"||f===
"scroll"||e==="auto"||e==="scroll"}d&&(b=Da(a,c));c=c.parentElement}return b&&Da(a,i)}function Da(a,b){var c,d;if(b){var e=O(b);c=e.width;d=e.height}else c=ya("Width"),d=M();var f=O(a),e=f.height,f=f.width,l=Q(a,b),j=l.y,l=l.x;c=Math.min(l+f,f,c,c-l);d=Math.min(j+e,e,d,d-j);if(c<0||d<0)return k;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function Q(a,b,c){for(var d=a.offsetLeft,e=a.offsetTop,f=k,l=c?0:L("X","Left",g),j=c?0:L("Y","Top",g),n=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===n)d+=a.offsetLeft,e+=a.offsetTop,n=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(P(a,"position")==="fixed"){f=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:l,e-=b?b.scrollTop:j);f&&(d+=l,e+=j);return{x:d,y:e}}
function P(a,b){var c;c=o.getComputedStyle?(c=o.getComputedStyle(a,i))&&(c[b]||c.getPropertyValue(b)):a.currentStyle?a.currentStyle[b]:a.style&&a.style[b];return c||""};var S={Aa:{IDLE:0,Bb:1,Ab:2,za:3},j:0};S.d=function(){if(!S.G)C("activity",S.eb,S),C("inactive",S.hb,S),C("focus",S.gb,S),C("blur",S.fb,S),S.G=h};S.Ea=function(){return S.j};S.eb=function(){S.j===1?S.p(3):S.j===0&&S.p(2)};S.hb=function(){S.j===3?S.p(1):S.j===2&&S.p(0)};S.gb=function(){(S.j===0||S.j===2)&&S.p(3)};S.fb=function(){S.j===3?S.p(2):S.j===1&&S.p(0)};S.p=function(a){S.j=a;F("state",a)};function Ea(a,b){this.ha=a||g;this.H=b||g;this.v=this.ua=0}m=Ea.prototype;m.d=function(){this.v=this.ua=0;this.M=i;this.tb=C("state",this.D,this);this.D(S.Ea())};m.total=function(){this.ua+=this.v;this.v=0;return this.ua};m.D=function(a){o.clearInterval(this.M);this.M=i;if(a===S.Aa.za)this.M=o.setInterval(r(this.lb,this),1E3)};m.lb=function(){if(this.ha===g||this.ha())this.v++,this.H&&this.H()};m.terminate=function(){o.clearInterval(this.M);this.M=i;D(this.tb)};
m.C=function(){this.terminate();this.H=this.ha=g};function T(a,b){this.h=a;this.R=b;this.q=a.getAttribute("data-cb-ad-id")||a.id||"";this.r=i;this.Ba=0;var c=this;this.A=new Ea(function(){Fa(c);return Ca(c.g)},r(this.H,this));Ga(this);if(this.R)this.Za=C("activity",this.va,this)}function Ga(a){a.Ba++;a.b={};a.b.campaignId="";a.b.creativeId="";a.b.placementId="";a.b.siteId="";a.b.server_height="";a.b.server_width="";a.g=a.h;a.B={Ga:k,frame:k};a.ga=k;a.ja=k;Fa(a);a.A.d();a.Ra=k;a.N=0;a.z=i;a.xb=C("state",a.D,a);a.D(S.Ea())}
T.prototype.D=function(a){if(this.z!==i)clearInterval(this.z),this.z=i;this.N=0;if(a===S.Aa.za)this.z=o.setInterval(r(this.wb,this),100);this.R&&this.va()};T.prototype.wb=function(){if(Ca(this.g)){if(this.N++,this.N>=10)this.Ra=h,Ha(this),F("forcePing")}else this.N=0};function Ha(a){D(a.xb);o.clearInterval(a.z);a.z=i}T.prototype.H=function(){F("adEngaged",this.u(h),this.h);this.R&&this.va()};
var Ia={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function Fa(a){var b=o._sf_async_config;if(b&&(b=b.creativeDetection,b===k||u(b)&&b!=="iab"))return;var c=Ba(a.h);if(a.g!==a.h)if(Ba(a.g)>c)a.g=a.h;else return;q(["iframe","embed","object","img","div"],function(b){q(a.h.getElementsByTagName(b),function(b){var d=O(b);if(!(d.height*d.width>c)&&Ia[d.width]&&Ia[d.width][d.height])return a.g=b,a.B.Ga=h,k});return a.g===a.h})}
function Ja(a,b,c){a.b=b;a.ja=!!c;if(a.ja){var b=h,d=o._sf_async_config;if(d&&(d=d.creativeDetection,d===k||u(d)&&d!=="iframe"))b=k;if(b&&Ba(c)>0)a.g=c,a.B.frame=h}F("forcePing")}m=T.prototype;
m.u=function(a){var b={id:this.q,engagedSeconds:this.A.total()};b.campaignId=this.b?this.b.campaignId:"";b.creativeId=this.b?this.b.creativeId:"";if(a)return b;var a=O(this.g),c=Q(this.g,g,h);b.positionLeft=c.x;b.positionTop=c.y;b.width=a.width;b.height=a.height;b.viewable=this.Ra;b.order=this.Ba;b.placementId=this.b?this.b.placementId:"";b.siteId=this.b?this.b.siteId:"";b.server_height=this.b?this.b.server_height:"";b.server_width=this.b?this.b.server_width:"";b.lineId=this.b?this.b.lineId:"";b.exclude=
this.ga;return b};m.$=function(){if(!this.ja){var a=this.h,b={};b.campaignId=K("data-cb-campaign-id",a)||"";b.creativeId=K("data-cb-creative-id",a)||"";b.placementId=K("data-cb-placement-id",a)||"";b.siteId=K("data-cb-site-id",a)||"";b.server_height=K("data-cb-creative-height",a)||"";b.server_width=K("data-cb-creative-width",a)||"";b.lineId=K("data-cb-line-id",a)||"";if(K("data-cb-exclude",a))this.ga=h;ja(b,this.b)||Ja(this,b)}};
m.va=function(){function a(a,b,c){var d=document.createElement("div"),e=document.createElement("span");e.setAttribute("style","font-weight: bold;");e.textContent=a;d.textContent=b;d.insertBefore(e,d.firstChild);c.appendChild(d)}var b=this.h;if(b){var c,d=this;if(this.r)c=document.getElementById(this.r);else{this.r="engagementLog-"+this.q+"-"+p(da());c=document.createElement("div");c.setAttribute("id",this.r);document.body.appendChild(c);var e=b.getAttribute("style")||"",f=P(b,"position"),f=f==="fixed"||
f==="absolute"||f==="relative"?"":"position: relative;";e+="box-shadow: 0px 0px 0px 3px #49A2DC; z-index: 2000;"+f;b.setAttribute("style",e);var l="box-shadow: 0px 0px 0px 3px #5BC3BD, 10px 5px 5px #C8DAE8; z-index: 2000;"+f;c.onmouseover=function(){b.setAttribute("style",l)};c.onmouseout=function(){e?b.setAttribute("style",e):b.removeAttribute("style")};s(c,"click",function(){d.kb=h})}c.innerHTML="";if(this.kb)c.setAttribute("style","display: none;");else{var j=Q(b),f=j.y,j=j.x;f+=L("Y","Top",g);
j+=L("X","Left",g);c.setAttribute("style","background-color: #F1F7FB; z-index: 9000000; position: absolute; padding: 10px; border-radius: 5px; font-size: 12px; color: #658BA1; border: 1px solid #C8DAE8; margin: 3px; font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif; top: "+f+"px; left: "+j+"px;");f=this.u();a("Ad Name: ",f.id+" ["+f.width+"x"+f.height+"]",c);(j=f.campaignId)&&a("Campaign: ",j,c);(j=f.creativeId)&&a("Creative: ",j,c);a("Viewable: ",f.viewable+"",c);c.appendChild(document.createElement("br"));
j=Ca(this.g);a((j?"In ":"Out Of ")+" View","",c);j&&a("in view intervals: ",this.N+"",c);a("Engaged Time: ",f.engagedSeconds+" seconds",c);if(this.g!==b)this.ea?b.removeChild(document.getElementById(this.ea)):this.ea="creativeContainer-"+this.q+"-"+p(da()),c=document.createElement("div"),c.setAttribute("id",this.ea),f=Q(this.g,b),j=O(this.g),c.setAttribute("style","position: absolute; border-radius: 5px; border: 2px solid #00FFAD; background: transparent; top: "+f.y+"px; left: "+f.x+"px; height: "+
j.height+"px; width: "+j.width+"px; margin: 0px; padding: 0px; z-index: 1000000;"),f=document.createElement("div"),f.setAttribute("style","position: absolute; right: 0px; bottom: 0px; font-size: 20px; background-color: white; padding: 10px;"),f.textContent=""+(this.B.Ga?"IAB ":"")+(this.B.frame?"iframe ":""),c.appendChild(f),b.appendChild(c)}}};m.reset=function(){Ha(this);this.A.terminate();Ga(this)};
m.C=function(){Ha(this);this.A.C();this.B=this.b=this.g=this.h=this.A=i;if(this.r){var a=document.getElementById(this.r);(a.parentElement?a.parentElement:a.parentNode).removeChild(a)}this.R&&D(this.Za)};var U={};U.Wa=function(){try{U.create("_cb_test","1",1);var a=U.c("_cb_test");U.remove("_cb_test");return a==="1"}catch(b){return k}};U.c=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),k});return b};U.create=function(a,b,c){var d=o._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(z()+c*1E3),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"};
U.remove=function(a){U.c(a)&&U.create(a,"",-86400)};var V={};V.f=function(a){var b=o._sf_async_config;if(!a&&b&&b.noCookies)return i;if(V.f.da!==g)return V.f.da;var a=z()+"",c,d;try{if((d=o.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return V.f.da=d}catch(e){}return V.f.da=i};V.c=function(a){var b=V.f();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&z()>c)?(V.remove(a),""):b.getItem(a)||""};
V.create=function(a,b,c){var d=V.f();if(d){var e=new Date;e.setTime(z()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};V.remove=function(a){var b=V.f();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ka(a){this.X=a||"";this.Ya=V.f()!==i||U.Wa();this.sa=k;La(this)}m=Ka.prototype;m.isSupported=function(){return this.Ya};
function La(a){if(!U.c("_cb_ls")){var b=V.f()!==i,c=U.c("_SUPERFLY_nosample");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=U.c("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),U.remove("_chartbeat3"));b&&((b=U.c("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=U.c("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=U.c("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));U.create("_cb_ls","1",2592E3)}}
function Ma(a){var b=a.sa;a.sa=k;return b}m.create=function(a,b,c,d){a=d?a:this.X+a;(V.f()?V:U).create(a,b,c);V.f()&&U.create(a,b,c)};m.update=function(a,b,c,d,e,f){a=d?a:this.X+a;e=u(e)?e:"::";d=(d=this.c(a,h))?d.split(e):[];t(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
m.c=function(a,b){var a=b?a:this.X+a,c=(V.f()?V:U).c(a);if(!c&&V.f()&&(c=U.c(a))&&U.c("_cb_ls")){this.sa=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}V.create(a,c,d)}return c};m.remove=function(a,b){a=b?a:this.X+a;(V.f()?V:U).remove(a);V.f()&&U.remove(a)};var W=function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof document[a]==="boolean")return b=c,k});var c={};if(b!==g)c.Fa=a,c.xa=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),c.ba=b+"visibilitychange";return c}();
W.d=function(){if(!W.G)W.S=W.Oa(),W.ba&&document.addEventListener&&document.addEventListener(W.ba,W.rb,k),W.Ca("focus","onfocusin",W.na),W.Ca("blur","onfocusout",W.Na),W.S&&W.na(),W.G=h};W.Cb=function(){return W.S};W.na=function(){W.S=h;F("focus")};W.Na=function(){W.S=k;F("blur")};W.Ca=function(a,b,c){o.addEventListener?o.addEventListener(a,c,k):document.attachEvent&&document.attachEvent(b,c)};
W.Oa=function(){var a=h;document.hasFocus&&(a=document.hasFocus());var b=k;W.Fa&&(b=document[W.Fa]);return a&&!b};W.rb=function(){W.Oa()?W.na():W.Na()};function Na(a){var b=i;if(a&&(b=Oa()))return b;var c=o.location,b=X(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Oa(){var a=i;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=ra(b.href),a=X(b.pathname)+b.search+b.hash,k});return a}
for(var Pa={},Qa=0;Qa<81;Qa++)Pa["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Qa)]=h;function Ra(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Pa[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function X(a){if(!u(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Ra);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function ba(){this.a=o._sf_async_config||{};this.fa=r(this.qb,this);this.s=[];this.e=new Ka(this.ub);this.o=k;this.i=new Ea;this.oa=r(this.I,this);s(o,"unload",this.oa);Sa(this)||this.d()}m=ba.prototype;m.qa=h;function Sa(a){if(W.xa&&document[W.xa]==="prerender"){a.o=h;var b=r(function(){if(this.o&&document[W.xa]!=="prerender")this.o=k,this.d(),Ta(this),window.setTimeout(function(){document.removeEventListener(W.ba,b,k)},100)},a);document.addEventListener(W.ba,b,k);return h}return k}
m.d=function(){this.ka=this.n=0;this.L=z();this.K=p(Ua(this));this.w=h;this.Ka=72E5;this.W=0;if(this.qa){var a=+this.a.sessionLength;if(!isNaN(a))this.Ka=a*6E4}this.i.d();S.d();G.d();W.d();this.m=0;this.Ua=C("activity",this.ma,this)};function Ta(a){if(!a.e.c("_SUPERFLY_nosample")&&!a.o)a.nb?a.ra():(a.nb=h,!o._sf_async_config&&!o._cbq?(a.U=r(a.ra,a),s(o,"load",a.U)):a.ra())}
m.ra=function(){var a=o._sf_startpt,b=o._sf_endpt;if(t(a))this.V=t(b)?b-a:z()-a;G.d();this.mb=setInterval(r(this.La,this),15E3);this.La()};m.La=function(){var a=this.i.v,a=this.a.reading&&+this.a.reading||a>0;this.ka<this.n&&!a?this.ka++:(a?this.n=0:Va(this),this.ka=0,this.s.push(0),this.s.length>18&&this.s.shift(),this.qa&&z()-this.L>=this.Ka?this.terminate():this.J())};
m.qb=function(){this.s.push(1);var a=0;q(this.s,function(b){a+=b});a<3?(this.w=h,Va(this)):(this.terminate(),this.e.create("_SUPERFLY_nosample","1",600))};m.I=function(){};m.ma=function(){var a=Wa(this);this.m=Math.max(this.m,a)};function Wa(a){return L("Y","Top",!!a.a.scrollElement)}function Va(a){var b=a.n,b=b?Math.min(b*2,16):1;a.n=b}m.aa=function(a,b){if(!this.o)this.I(),this.terminate(),this.O=o.location.protocol+"//"+this.a.domain+this.a.path,this.a.path=X(a),b&&(this.a.title=b),this.d(),Ta(this)};
function Xa(a){if(a.O)return h;a=(document.referrer||"").indexOf("://"+o.location.host+"/");return a!=-1&&a<9}function Ya(a){a=a.O;if(!a&&(a=document.referrer||"")){var b=ra(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=X(b.pathname),a=sa(b)}return encodeURIComponent(a)}function Za(a){a=a.a.title.slice(0,100);return encodeURIComponent(a)}
function Ua(a){var b=o.navigator,c=o.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=o.performance;d=d.concat([b&&b.now?b.now():"",Ya(a),document.title,o.location.href,z(),za("Width"),N(),da()]);return d.join()}function $a(a){var b="",c=a.e.c("_chartbeat4");c&&(q(c.split("::"),function(a){b+="&z="+encodeURIComponent(a)}),a.e.remove("_chartbeat4"));return b}
function ab(a){var a=(a.e.c("_chartbeat2",h)||"").split("."),b=z(),c=b-+(a[1]||0);b-=+(a[2]||0);return a[0]&&c>18E5&&b<2592E6?0:1}m.terminate=function(){this.i.terminate();D(this.Ua);this.U!==g&&ga("load",this.U);clearInterval(this.mb)};m.C=function(){this.terminate();ga("unload",this.oa);this.oa=this.U=this.e=this.s=this.fa=this.a=i;this.i.C();this.i=i};function Y(){this.l=[];this.pa=[];"postMessage"in window&&s(window,"message",r(this.jb,this));this.ub="_p_";this.qa=k;this.Db=i;s(o,"beforeunload",r(this.pb,this));ba.call(this)}aa(Y);var bb=0;m=Y.prototype;
m.d=function(){Y.Y.d.call(this);var a=o.location;I(this.a,"pingServer","ping.chartbeat.net");I(this.a,"endServer","edge01.chartbeat.net");I(this.a,"title",document.title);I(this.a,"domain",a.host);I(this.a,"path",Na(!!this.a.useCanonical));I(this.a,"engaged",k);a=o.location.search||"";if(a.match(va))a=oa(a).__cb_debug,bb=parseInt(a,10);this.Q=this.a.adIdentifier||"data-cb-ad-id";this.a.domain=fa(this.a.domain);this.la=ab(this);this.k=this.e.c("_chartbeat2",h);this.t=this.Ha=0;this.cb=function(){var a=
z()-this.Ha;a<500?(this.t&&o.clearTimeout(this.t),this.t=o.setTimeout(r(this.J,this),500-a)):this.w||this.J()};this.bb=C("forcePing",this.cb,this);if(!this.k)this.a.utoken?this.k=this.a.utoken:(this.k=p(Ua(this),3),this.a.utoken=this.k);this.k=this.k.split(".")[0];cb(this);db(this);if((a=this.a.engagedAdFilters)&&a.length){this.a.engagedAdFilters=[];var b=this;q(a,function(a){b.P(a)})}this.ab=C("adEngaged",this.$a,this);this.pa=[]};m.pb=function(){this.J(h)};
m.I=function(){this.e.update("_chartbeat4",["t="+this.K,"E="+this.i.total(),"ad="+ia(eb(this)),"x="+Wa(this),"c="+Math.round((z()-this.L)/600)/100,"y="+N(),"w="+M()].join("&"),3600,g,g,1)};
function eb(a){var b=[];q(a.l.concat(a.pa),function(a){var a=a.u?a.u():a,d=encodeURIComponent(a.id),e=a.engagedSeconds,f=a.positionLeft,l=a.positionTop,j=a.width,n=a.height,w=encodeURIComponent(a.creativeId||""),x=encodeURIComponent(a.campaignId||""),E=encodeURIComponent(a.placementId||""),y=encodeURIComponent(a.siteId||""),H=encodeURIComponent(a.server_height||""),R=encodeURIComponent(a.server_width||""),A=encodeURIComponent(a.lineId||""),v=a.order,mb=a.refreshed||"0",nb=a.viewable?"1":"0";a.exclude&&
(x="");b.push(d+"="+[e,f,l,j,n,x,w,v+"."+mb,nb,E,y,H,R,A].join("::"))});return b.join("&")}
m.J=function(a){this.W++;this.Ha=z();var b=this.a,c=Wa(this);this.m=Math.max(this.m,c);this.t&&o.clearTimeout(this.t);var d="",e="";if(this.w)this.w=k,d=(Xa(this)?"&v=":"&r=")+Ya(this),this.O&&(d+="&vp=1"),e="&i="+Za(this);var f=this.V?"&b="+this.V:"";Na(!!b.useCanonical);var l=!b.noCookies&&this.e.isSupported(),a="https://"+(a?b.endServer:b.pingServer)+"/ping/ad?h="+encodeURIComponent("ads."+b.domain)+"&p="+encodeURIComponent(b.path)+"&u="+this.k+"&d="+ia(fa(o.location.host))+"&g="+b.uid+J(b,0,"sections")+
J(b,1,"authors")+J(b,2,"zone")+J(b,3,"sponsorName")+J(b,4,"type")+(l?"&n="+this.la:"&nc=1")+"&c="+Math.round((z()-this.L)/600)/100+"&x="+c+"&m="+this.m+"&y="+N()+"&o="+za("Width")+"&w="+M()+"&j="+(a?0:Math.round((this.n+2)*15E3/1E3))+"&E="+this.i.total()+d+f+"&t="+this.K+"&V=43"+e+"&tz="+(new Date).getTimezoneOffset()+(Ma(this.e)?"&l=1":"")+ua(b)+"&ad="+ia(eb(this))+(a?"":$a(this))+(a?"&zz=1":"")+"&sn="+this.W+"&_";this.o||ca(a,this.fa)};
function fb(a){a=wa(a.Q,"div");return ka(a,function(a){a=O(a);return a.height>1&&a.width>1})}function cb(a){var b=fb(a);q(b,function(b){if(!gb(a,b)){var d=new T(b,bb);a.l.push(d);d.$();if(b=K("data-cb-engaged-seconds",b))d=d.u(h),d.engagedSeconds=parseInt(b,10),a.P(d)}})}function gb(a,b){var c=k;q(a.l,function(a){if(a.h===b)return c=h,k});return c}m.$=function(){q(this.l,function(a){a.$()})};m.ma=function(){Y.Y.ma.call(this);cb(this)};m.jb=function(a){this.Ia(la(a.data),a.source)};
m.Ia=function(a,b){if(a.cbType!=="campaignMessage")return k;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return k}cb(this);var d=document.getElementsByTagName("iframe"),e=g;q(d,function(a){if(a.contentWindow===c)return e=a,k});if(!e)return k;var f=e.getAttribute(this.Q);if(f===i){d=xa(e,this.Q);if(d===k)return k;f=d.getAttribute(this.Q)}var l=g;q(this.l,function(a){if(f===a.q)return l=a,k});if(l===g)return k;Ja(l,a,e);if(a.exclude)l.ga=h;if(a.engagedSeconds)d=
{id:l.q},d.campaignId=a.campaignId,d.creativeId=a.creativeId,d.engagedSeconds=parseInt(a.engagedSeconds,10),this.P(d);d="cbdata::ack::"+this.K;"postMessage"in b&&b.postMessage(d,"*");return d};m.aa=function(){this.I();this.terminate();this.O=o.location.protocol+"//"+this.a.domain+this.a.path};
m.P=function(a){if(a&&t(a.engagedSeconds)&&!isNaN(a.engagedSeconds)){var b=this.a.engagedAdFilters;if(!b||b.length===g)this.a.engagedAdFilters=[],b=this.a.engagedAdFilters;var c={};c.engagedSeconds=a.engagedSeconds;q(["id","campaignId","creativeId"],function(b){u(a[b])&&(c[b]=a[b])});var d=k;q(b,function(a){d=ja(a,c);return!d});d||b.push(c)}};
m.$a=function(a,b){var c=this.a.engagedAdCallback;if(c){var d=this.a.engagedAdFilters;if(d&&d.length&&a){var e=a.engagedSeconds;q(d,function(d){if(d.engagedSeconds===e){var l=h;q(d,function(b,c){return l=b===a[c]});if(l)return a.element=b,c(a,e),k}})}}};m.sb=function(a){if(a){var b;q(this.l,function(c){if(c.q===a||c.h===a)return b=c,k});if(b){var c=b.u();c.refreshed="1";this.pa.push(c);b.reset()}}};
function db(a){if(bb===1){var b=document.createElement("div");b.setAttribute("style","position:fixed; left:0; right:0 ;top:0 ;bottom:0; background-color: rgba(0, 0, 0, 0.3); z-index:1000;");document.body.appendChild(b);var c=document.createElement("div");document.body.appendChild(c);var d=a.a;q(["sections","zone","sponsorName","type"],function(a){if(d[a]!==g){var b=document.createElement("div");b.textContent=a+": "+d[a];c.appendChild(b)}});c.children.length&&(a="background-color: #F1F7FB; z-index: 9000000; position: fixed;padding: 10px; border-radius: 5px; font-size: 12px;color: #658BA1; border: 1px solid #C8DAE8;font-family: 'Proxima-Nova','Helvetica Neue',Helvetica,Arial,sans-serif;top: "+
Math.round(M()*0.9)+"px;left: "+Math.round(ya("Width")*0.45)+"px;",c.setAttribute("style",a))}}m.terminate=function(){D(this.bb);D(this.ab);q(this.l,function(a){a.C()});this.l=[];o.clearTimeout(this.t);Y.Y.terminate.call(this)};if(!o.pSUPERFLY_pub){var hb=new Y;o.pSUPERFLY_pub=hb;Y.prototype.virtualPage=Y.prototype.aa;Y.prototype.addEngagedAdFilter=Y.prototype.P;Y.prototype.refreshAd=Y.prototype.sb;Y.prototype.updateCampaignData=Y.prototype.$;if("postMessage"in window!==h)Y.prototype.loadCampaign=Y.prototype.Ia;Ta(hb)};function ib(){var a=document.createElement("script");a.async=h;a.src=(o.location.protocol||"http:")+"//static.chartbeat.com/js/inpage.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function jb(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=V.f(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),ib())}};function kb(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,l,j,n,w,x,E;f&&f!==c;){l=f.nodeName.toLowerCase();e=f;j=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){n=f.children;w=0;for(x=0,E=n.length;x<E;x++){if(e===n[x]){l+="["+(1+x-w)+"]";break}n[x].nodeName!==j&&w++}}d.unshift(l)}return d.join("/")};function Z(){ba.call(this);for(var a=r(this.Pa,this),b=o._cbq||[];b.length;)a(b.shift());o._cbq={push:a};C("anchor",this.ob,this);"postMessage"in window&&s(o,"message",r(this.ib,this))}aa(Z);m=Z.prototype;
m.d=function(){Z.Y.d.call(this);this.ca=i;ta(this.a);var a=o.location;I(this.a,"pingServer","ping.chartbeat.net");I(this.a,"title",document.title);I(this.a,"domain",a.host);this.a.path=this.a.path?X(this.a.path):Na(!!this.a.useCanonical);this.ia=fa(a.host);this.a.domain=fa(this.a.domain);a=(this.e.c("_chartbeat2",h)||"").split(".");a.length>4&&(a=[]);var b=z(),c,d="1",e=a&&+a[2];c=a&&a[3];if(a&&e&&c)if(d=Math.abs((ha(b)-ha(e))/864E5)){d=Math.min(d,16)-1;for(e="";d--;)e+=0;d=(c+e+"1").slice(-16)}else d=
c;c=d;this.la=ab(this);a[0]||(a[0]=this.a.utoken||p(Ua(this),3),a[1]=b);a[2]=b;a[3]=c;this.wa=a[0];this.k=a.join(".");this.e.create("_chartbeat2",this.k,94608E3,h);this.a.utoken=this.wa;var f;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)f=(Math.min((Math.abs((ha(c)-ha(b))/864E5)||0)+1,16,a.length)-1).toString(16),f+=("0000"+parseInt(a,2).toString(16)).slice(-4);this.Da=f};m.Ta=function(a){this.ca=a};
m.I=function(){this.e.update("_chartbeat4",["t="+this.K,"E="+this.i.total(),"x="+Wa(this),"c="+Math.round((z()-this.L)/600)/100,"y="+N(),"w="+M()].join("&"),3600,g,g,1)};
m.J=function(){this.W++;var a=this.a,b=Wa(this);this.m=Math.max(this.m,b);var c=Math.round((z()-this.L)/600)/100,d=0,e=0,f=0,l=this.i.v;G.Va()?e=1:this.a.reading&&+this.a.reading||l>0||c<0.09?d=1:f=1;var j="",n="",w="",x="",E="",y=Xa(this);if(this.w){this.w=k;var j=(y?"&v=":"&r=")+Ya(this),n="&i="+Za(this),H=this.a.hudTrackable;H!==g&&(w="&L="+(H?"1":"0"));if(y&&(y=lb(this)))j="&v="+encodeURIComponent(y.path),x="&K="+[y.left,y.top,y.zb,encodeURIComponent(y.yb)].join("::"),y.Ma>1&&(x+="&l1="+y.Ma);
a.alias&&(E="&PA="+encodeURIComponent(a.alias));this.O&&(j+="&vp=1")}y=this.V?"&b="+this.V:"";H=this.ca?"&A="+this.ca:"";a=(o.location.protocol||"http:")+"//"+a.pingServer+"/ping?h="+encodeURIComponent(a.domain)+"&p="+encodeURIComponent(a.path)+"&u="+this.wa+"&d="+encodeURIComponent(this.ia)+"&g="+a.uid+J(a,0,"sections")+J(a,1,"authors")+J(a,3,"sponsorName")+J(a,4,"type")+(!a.noCookies&&this.e.isSupported()?"&n="+this.la:"&nc=1")+(this.Da?"&f="+this.Da:"")+"&c="+c+"&x="+b+"&m="+this.m+"&y="+N()+"&o="+
za("Width")+"&w="+M()+"&j="+Math.round((this.n+2)*15E3/1E3)+"&R="+d+"&W="+e+"&I="+f+"&E="+this.i.total()+"&e="+l+j+x+E+y+H+pa("C","utm_campaign",a.campaignTag)+pa("M","utm_medium",a.mediumTag)+"&t="+this.K+"&V=43"+$a(this)+n+w+"&tz="+(new Date).getTimezoneOffset()+(Ma(this.e)?"&l=1":"")+ua(a)+"&sn="+this.W+"&_";this.o||ca(a,this.fa)};
m.ib=function(a){var b=this.a;if(a.origin==="http://"+(b.playerdomain||this.ia)){var c=a.data;u(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Pa(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Za(this)+"&referrer="+Ya(this)+"&internal="+(Xa(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ia)+"&utoken="+this.wa,a.source.postMessage(b,"*"))}};
m.Pa=function(a){this.a[a[0]]=a[1];this.n=0};function ob(a){a=a.replace(/-{2,}/g,"-");a=ra(a);a.pathname=X(a.pathname);return a}
m.ob=function(a){var b=a.href||"",b=ob(b);if(!(b.hostname!==o.location.hostname||b.protocol.indexOf("http")!==0)){var b=sa(b),c=Aa(a,function(a){return a.id}),d=kb(a,c);c&&(d&&(d="/"+d),d="*[@id='"+c.id+"']"+d);c=p(d);d=encodeURIComponent(d).replace(/-/g,"%2D");d.length>512&&(d="");a=Q(a,g,h);this.e.update("_chartbeat5",[a.x,a.y,encodeURIComponent(this.a.path),encodeURIComponent(b),c,d].join(","),60,k,g,5)}};
function lb(a){var b=a.e.c("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,l=ob(o.location.href),j=sa(l);q(c,function(a,b){var c=a.split(","),l=ma(j,decodeURIComponent(c[3]));if(l===0)return d=c,e=b,k;if(f===g||l<f)f=l,d=c,e=b})}c.splice(e,1);a.e.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),zb:d[4]||"",yb:a,Ma:b}};if(!o.pSUPERFLY){var pb=new Z;o.pSUPERFLY=pb;Z.prototype.virtualPage=Z.prototype.aa;Z.prototype.activity=Z.prototype.Ta;var $=o.pSUPERFLY_pub;$&&$.virtualPage&&(Z.prototype.virtualPage=function(){var a=arguments.length?Array.prototype.slice.call(arguments,0):[];$.virtualPage();Z.prototype.aa.apply(pb,a);$.d();Ta($)});$&&$.addEngagedAdFilter&&(Z.prototype.addEngagedAdFilter=r($.addEngagedAdFilter,$));$&&$.refreshAd&&(Z.prototype.refreshAd=r($.refreshAd,$));Ta(pb);var qb=V.f(h);if(qb){s(o,"message",
jb);var rb;if(rb=qb.getItem("_cb_ip")){var sb=o.location;rb=!(!/^([^.]+[.])?chartbeat\.com$/.test(sb.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(sb.pathname))}rb&&ib()}};})();
