(function(z){
var zJ=function(a,b,c){b="new"===(b||a.ed);return c?(a=a.d.w.B().get(z.U.ap),b?-1:-a):a.Pm+(b?-1:1)};var AJ=function(a){z.Eu.call(this,a);this.Pm=0;this.ed="new"};var BJ=function(a,b){a.mV=b};var CJ=function(a){return a.get(a.j.hp)};
var DJ=function(a){return'\x3cdiv class\x3d"fyre '+(a.Zd?"fyre-liveblog ":"")+(a.Rg?"fyre-livechat ":"")+(a.TR?"fyre-bootstrap ":"")+(a.He?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ua?"fyre-avatar-disabled":"")+'"\x3e'+(a.Qu?(0,z.Nr)(a):"")+'\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+(a.Ua?
"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Kn?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'};var EJ=function(a){return'\x3ca href\x3d"'+(0,z.Pl)(a.Ba)+'" title\x3d"'+(0,z.Q)(a.$)+'" data-id\x3d"'+a.id+'" class\x3d"fyre-follower fyre-follower-'+a.AR+'"\x3e\x3cimg src\x3d"'+(0,z.Pl)(a.sd)+'" alt\x3d"'+(0,z.Q)(a.$)+'" onerror\x3d"javascript:this.src\x3d\''+(0,z.Q)(a.Wb)+"';\" /\x3e\x3c/a\x3e"};
var FJ=function(a){return(0,z.Wp)(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+(0,z.Q)(a.k.mM)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.Q)(a.k.ox)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.Q)(a.k.ro)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.Q)(a.k.px)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e"};var GJ=function(a){return'\x3cdiv class\x3d"tooltip"\x3e'+(0,z.Q)(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e'};var HJ=function(){};var IJ=function(a,b){z.Cj.call(this,b,a)};var JJ=function(a,b){z.wE.call(this,a,b)};var KJ=function(a,b){var c=a.d.Db;c.dh[4]&&((0,z.Tx)(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.cr)},a)),(0,z.Vx)(c,4,(0,z.t)(function(a){b.Xa(a,"threadBreakout",this.cr)})))};
var LJ=function(a,b){var c=[a.Sl,a.Ay];a.qg&&c.push(a.qg);a.Fs&&c.push(a.Fs);a.By&&c.push(a.By);(0,z.x)(c,function(a){(0,z.Xh)(a,"fyre-stream-sort-selected")});(0,z.F)(b,"fyre-stream-sort-selected")};var MJ=function(a,b){z.wE.call(this,a,b)};var NJ=function(a,b){z.uw.call(this,a,b);this.nl=!1;this.Da=new z.Cw;this.Da.mc(this);this.Dt="archiveShowMore"};var OJ=function(a,b){z.uE.call(this,a,b)};var PJ=function(a,b,c){z.$s.call(this,a,b,c);this.Ty=b||"";this.mg(GJ(this.t()))};
var QJ=function(a,b,c){z.Us.call(this,a,b||3,c)};var RJ=function(a,b){z.T.call(this,b);this.m=a};var SJ=function(a,b){z.T.call(this,b);this.Zb=a};var TJ=function(a,b){SJ.call(this,a,b)};var UJ=function(a,b,c,d,f){z.vE.call(this,a,b,c,d,f)};var VJ=function(a,b){z.EE.call(this,a,b);var c=a.w.Jb(),d=a.w.B();this.fg=new UJ(a,c,a.xl.Ha,d.Rg()||z.Tf);this.F(this.fg);a.Q.Ua||(this.fn=new TJ(c),this.F(this.fn));this.jr=new z.tE;this.F(this.jr)};var WJ=function(a){var b=z.I.hb();return!a.v.Zd()||b};
var XJ=function(a){z.Zx.call(this,a);this.xm=1};var YJ=function(a){z.Qr.call(this,a);(0,z.gu)(a.w);this.Rb=new VJ(a);this.tq.start();this.ml(this.Rb);(0,z.Ur)(this)};var ZJ=function(a,b){this.$B=IJ;this.iI=YJ;z.W.wo(b.strings||{});z.tl.call(this,a,b)};var $J=function(a){a.Zj&&(a.Zj.s(),delete a.Zj)};(0,z.v)(AJ,z.Eu);z.e=AJ.prototype;z.e.Zk=(0,z.l)(68);z.e.pE=(0,z.l)(70);z.e.qE=(0,z.l)(69);z.e.pE=(0,z.N)(70,function(a){this.La||(this.$n[a]=!1,(0,z.Fu)(this,a,function(a){a.N(a.wa.um)}))});
z.e.qE=(0,z.N)(69,function(a,b){if(!this.La){var c=this.d.w.B(),d=(0,z.Dt)(a,b),f=c.get(z.U.$s);c.set(z.U.ap,d.dT);(0,z.C)(d.$a,(0,z.t)(this.d.R.N,this.d.R,"bootstrap_author_received"));d.content=(0,z.gj)(d.content,function(a,b){return!(0,z.Qa)(f,b)});(0,z.C)(d.content,function(a){(0,z.D)(d.content,(0,z.Hu)(this,a))},this);(0,z.D)(this.xc,(0,z.fj)(d.content,(0,z.zb)(a)));this.Od(a,d.content);(0,z.Fu)(this,a,function(b){b.N(b.wa.pk,{Ad:a});b.set(b.j.Ze,!0)})}});
z.e.Zk=(0,z.N)(68,function(a,b){this.Pm=a;this.ed=b||this.ed;var c=this.Bd[a]=new z.Au;z.Xt.D();var d=this.d.w.B(),f=(0,z.t)(this.qE,this,a),g=(0,z.t)(this.pE,this,a),h=this.d.Q.Bm,d=d.get(z.U.Pc),h=z.w.gu(d,h)+String(a)+".json";(0,z.Yt)(0,h,f,g);return c});z.$E.prototype.Zk=(0,z.N)(67,function(a,b){this.Ak||(this.Ak=new AJ(this.K));var c=this.Ak,d=zJ(c,a,b);return c.Zk(d,a)});
z.Xt.prototype.Ih=(0,z.N)(59,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/hot/",z.w.L.td,z.w.We,a.ma);(new z.Ee({url:a,va:b,pa:c})).send()});z.Vu.prototype.Ih=(0,z.N)(58,function(a){var b={ma:this.d.w.B().id},c=z.Xt.D().Ih;(0,z.Wu)(this,c,b,a);return a});z.$E.prototype.Ih=(0,z.N)(57,function(){(0,z.av)(this);this.ui=new z.Vu(this.K,void 0);var a=new z.Au;this.ui.Ih(a);return a});
z.Xt.prototype.Fh=(0,z.N)(56,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/top/%s/",z.w.L.td,z.w.We,a.ma,a.gM);(new z.Ee({url:a,va:b,pa:c})).send({format:"stream"})});z.Vu.prototype.Fh=(0,z.N)(55,function(a,b){var c={ma:this.d.w.B().id,gM:a},d=z.Xt.D().Fh;(0,z.Wu)(this,d,c,b);return b});z.$E.prototype.Fh=(0,z.N)(54,function(a){(0,z.av)(this);this.ui=new z.Vu(this.K,void 0);var b=new z.Au;this.ui.Fh(a,b);return b});z.T.prototype.zF=(0,z.N)(53,function(){return this.ba});
z.zj.prototype.Kn=(0,z.N)(52,function(){return this.get(this.j.$o)});(0,z.v)(HJ,z.zl);(0,z.ba)(HJ);var aK={iW:"attachmentDelegate"};(0,z.D)(aK,z.oF);HJ.prototype.Hn=function(a){var b=HJ.b.Hn.call(this,a),c=a.attachmentDelegate;c&&(b.oM=c);b.hx=a[aK.kK]||null;return b};(0,z.v)(IJ,z.Cj);IJ.prototype.ly=function(a){this.pi=new z.Tt(this);this.Pt=new z.Lp(this,a);this.Dc=new z.ui(this);this.ab=new z.pu(this,a);this.xl=new z.wu(this);this.w=new z.eu(this,a);this.Hb=new z.$E(this,a);new z.ff;this.zo=new z.mv(this,a);this.Db=new z.Jx(this)};(0,z.v)(JJ,z.wE);z.e=JJ.prototype;z.e.t=function(){var a={},b=this.d.w,c=b.B();a.cx=b.B().Zd();a.aT=!z.I.get(z.I.j.$c);a.ql=b.ql(z.I.id);a.kN=2===c.get(z.U.tk);a.jN=3===c.get(z.U.tk);a.k={iS:z.W.get(z.W.g.qt),lS:z.W.get(z.W.g.rt),yR:z.W.get(z.W.g.iA),ox:z.W.get(z.W.g.vp),px:z.W.get(z.W.g.wp),ro:z.W.get(z.W.g.jB),Jo:z.W.get(z.W.g.zp),zV:z.W.get(z.W.g.zB)};return a};
z.e.G=function(a){JJ.b.G.call(this,a);a=this.c;var b;b=this.t();var c=(0,z.Wp)(b),d;d=b.cx?'\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.aT?b.ql?(0,z.Q)(b.k.lS):(0,z.Q)(b.k.iS):"")+"\x3c/a\x3e":"";b=c+d+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.Q)(b.k.ox)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.Q)(b.k.ro)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.Q)(b.k.px)+"\x3c/a\x3e"+(b.kN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.Q)(b.k.ro)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+(0,z.Q)(b.k.zV)+"\x3c/a\x3e":"")+(b.jN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.Q)(b.k.ro)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+(0,z.Q)(b.k.yR)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;this.Yk=this.n("fyre-follow-conversation");this.Fs=
this.n("fyre-stream-sort-hot-threads")||null;this.By=this.n("fyre-stream-sort-top-comments")||null;this.qg=this.n("fyre-stream-sort-back");this.Sl=this.n("fyre-stream-sort-newest");this.Ay=this.n("fyre-stream-sort-oldest");this.rH=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.xd()};z.e.l=function(){JJ.b.l.call(this);var a=this.p();z.I.on(z.I.wa.Jf,this.Bn,this);a.e(this.c,"click",this.Za);(0,z.x)([3,4,5],function(b){(0,z.xE)(this,a,b)},this);KJ(this,a)};
z.e.Za=function(a){a.preventDefault();a=a.target;if(!(0,z.Wh)(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.qg)if(a===this.Yk)this.oE();else switch(LJ(this,a),this.Rl(),a){case this.Fs:this.jD();break;case this.By:this.dispatchEvent({type:"sortTopComments",Qb:(0,z.t)(this.xd,this)});break;case this.Sl:this.Vm("new");break;case this.Ay:this.Vm("old")}};z.e.ki=function(a,b){a&&this.my(b);(0,z.Um)(this.rH,"display",a?"none":"block");(0,z.Um)(this.qg,"display",a?"block":"none")};
z.e.my=function(a){var b=this.Sl,c=this.Vm,d=z.W.get(z.W.g.at);4===a&&(b=this.Fs,c=this.jD,d=z.W.get(z.W.g.vI));this.qg.innerHTML=d;this.p().sf(this.qg,"click",(0,z.t)(function(a){a.stopPropagation();this.ki(!1);LJ(this,b);c.apply(this)},this))};z.e.yn=function(a){a.stopPropagation();this.ki(!1);LJ(this,this.Sl);this.Vm()};z.e.cr=function(a){var b=a.Qb;(0,z.D)(a,{Qb:(0,z.t)(function(){b();this.ki(!0,4)},this)})};
z.e.Vm=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Qb:(0,z.t)(this.xd,this)})};z.e.jD=function(){this.dispatchEvent({type:"sortHotThreads",Qb:(0,z.t)(this.xd,this)})};z.e.oE=function(){var a=this.d.w;a.B();var b=z.I.j;z.I.id?(b=a.ql(z.I.get(b.Y)),a.ej(!b),a=b?z.W.get(z.W.g.qt):z.W.get(z.W.g.rt),this.Yk.innerHTML=a):(0,z.Gh)(this.d.Dc,(0,z.t)(this.oE,this))};
z.e.Bn=function(){var a=this.d.w,b=a.B(),c=z.I.j,b=!b.Zd()||z.I.get(c.$c);this.Yk&&(b?(0,z.S)(this.Yk,!1):(a=a.ql(z.I.id)?z.W.get(z.W.g.rt):z.W.get(z.W.g.qt),this.Yk.innerHTML=a,(0,z.S)(this.Yk,!0)))};z.e.h=function(){JJ.b.h.call(this);z.I.off(null,null,this)};(0,z.v)(MJ,JJ);MJ.prototype.G=function(a){this.c=a;(0,z.El)(a,FJ,this.t());this.Sl=this.n("fyre-stream-sort-newest");this.Ay=this.n("fyre-stream-sort-oldest");this.rH=this.n("fyre-stream-sort-options");this.Yc=this.n("fyre-content-loading");this.xd()};MJ.prototype.Vm=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",oi:this.mV.oi,direction:a,Qb:(0,z.t)(this.xd,this)})};
MJ.prototype.t=function(){return{k:{mM:z.W.get(z.W.g.qI),ox:z.W.get(z.W.g.vp),px:z.W.get(z.W.g.wp),ro:z.W.get(z.W.g.jB),Jo:z.W.get(z.W.g.zp)}}};(0,z.v)(NJ,z.uw);z.e=NJ.prototype;z.e.Km=function(a){this.clear();(0,z.S)(this.c,!0);this.ed=a};z.e.clear=function(){this.cd.Cd();this.qb={};this.nj=[];for(this.eh=this.Dk=null;this.la&&0!=this.la.length;)this.ho(0).s()};z.e.G=function(a){NJ.b.G.call(this,a);(0,z.El)(this.c,z.Xp,this.t());this.Tj=this.n("fyre-stream-content");this.mi=this.n("fyre-stream-more");this.Da.S(this.mi);(0,z.S)(this.mi,!1)};z.e.h=function(){this.Da&&this.Da.s();this.Da=null;NJ.b.h.call(this)};
z.e.l=function(){NJ.b.l.call(this);this.p().e(this.Da,"showMore",this.mw)};z.e.t=function(){return{Qc:z.w.L.pb,Ju:!!this.Da,k:{sy:z.W.get(z.W.g.rI)}}};z.e.nw=function(){this.Da.Bs()};z.e.Gx=function(){this.dispatchEvent({type:this.Dt,direction:this.ed,target:this,Qb:(0,z.t)(this.nw,this),dj:(0,z.t)(this.NE,this)})};z.e.yo=function(){var a=this.K.Hb.Ak,b=this.ed,c=a.d.w.B(),b="old"===b,c=c.get(z.U.ap),c=!b&&a.Pm>-c;b&&-1>a.Pm||c?this.Da.show():this.Da.lb()};
z.e.start=function(){this.nl||(this.Gx(),this.nl=!0)};(0,z.v)(OJ,z.uE);OJ.prototype.t=function(){var a=this.m.get(z.U.Oc),b,c;this.m.Zd()?(b=z.W.get(z.W.g.ZJ),c=z.W.get(z.W.g.nA)):(b=z.W.get(z.W.g.Kf),c=z.W.get(z.W.g.gm));(0,z.Ea)(b,"%s")||(b="%s "+b);(0,z.Ea)(c,"%s")||(c="%s "+c);switch(a){case 1:b=(0,z.ua)(b,a);break;default:b=(0,z.ua)(c,a)}return{k:{vu:b}}};OJ.prototype.az=function(){var a=this.c,b;b=this.t();b="\x3cspan\x3e"+(0,z.Q)(b.k.vu)+"\x3c/span\x3e";a.innerHTML=b};(0,z.v)(PJ,z.$s);PJ.prototype.Bo=200;PJ.prototype.Kh=function(){return new QJ(this.Cc)};PJ.prototype.t=function(){var a={};a.message=this.Ty;return a};(0,z.v)(QJ,z.Us);
QJ.prototype.Ic=function(a,b,c){var d=(0,z.un)(this.element),d=new z.oh(d.width,d.height+25);b=(0,z.Ps)(this.element,this.uh,a,b,d,c,9);(0,z.an)(a.lastChild,0);b&&(d=new z.oh(0,-5),(0,z.Ps)(this.element,2,a,1,d,c,5),(0,z.an)(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};(0,z.v)(RJ,z.T);z.e=RJ.prototype;z.e.r=function(){this.c=(0,z.Hl)(EJ,this.t())};z.e.l=function(){RJ.b.l.call(this);this.Ra=new PJ(this.c,this.m.get("displayName"));this.p().e(this.c,"click",this.Za)};z.e.h=function(){RJ.b.h.call(this);this.Ra&&this.Ra.s()};z.e.t=function(){var a=z.Od,b={};b.sd=this.m.get(a.sb);b.Wb=this.m.get(a.ek);b.$=this.m.get(a.ta);b.id=this.m.id;b.AR=this.m.id.replace(/[@.]/g,"-");b.Ba=this.m.get(a.Tb);return b};
z.e.Za=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({u:this.m,type:"author_click"})};(0,z.v)(SJ,z.T);z.e=SJ.prototype;z.e.rA=10;z.e.h=function(){SJ.b.h.call(this);delete this.Zb};z.e.P=function(){SJ.b.P.call(this);this.Zb.off(null,null,this)};z.e.ZD=function(a){a=new RJ(a);var b=this.Tc();if(b===this.rA){var c=this.ho(b-1);c&&(c.s(),b--)}0<b?this.pe(a,0,!0):this.F(a,!0)};z.e.GQ=function(a){var b;this.hd(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.s())};
z.e.Oh=function(){this.Zb.on(this.Zb.wa.Zs,this.ZD,this);this.Zb.on(this.Zb.wa.At,this.GQ,this);var a=this.Zb.Bb.reverse().slice(0,this.rA);(0,z.x)(a,this.ZD,this)};(0,z.v)(TJ,SJ);(0,z.v)(UJ,z.vE);UJ.prototype.G=function(a){UJ.b.G.call(this,a);this.Kj()};UJ.prototype.Kj=function(){this.c.innerHTML=(0,z.$p)(this.t())};(function(a,b){function c(){var a=y.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){y.TU||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,function(a){b[a]=d(a);g.createElement(a);
return'c("'+a+'")'})+");return n}")(y,g)}function f(a){var b;if(a.oN)return a;if(y.SU&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";b=!!c.insertBefore(b.lastChild,
c.firstChild)}r||(b=!d(a));b&&(a.oN=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,r;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.NR&&a.NR("#modernizr{}",function(b){b.hidden=!0;m="none"==(a.getComputedStyle?
a.getComputedStyle(b,null):b.currentStyle).display});r=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var y={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.SU,shivMethods:!1!==
g.TU,type:"default",shivDocument:f};f(b)})(z.u.window,z.u.document);(0,z.v)(VJ,z.EE);
VJ.prototype.JG=function(a,b){if(!this.La){this.v=b;var c=b.get(z.U.mh),d=b.get(z.U.Kd);this.Ts=new z.BE(c,d,a.Q.Ua);this.F(this.Ts);this.cq=new OJ(a.w.B());this.F(this.cq);this.Nr=null;b.Kn()&&(this.$t=new MJ(a),this.F(this.$t),this.Bk=new NJ(a),this.F(this.Bk),BJ(this.$t,{oi:this.Bk}));this.ah=new JJ(a);this.F(this.ah);this.Fr((0,z.t)(function(a){this.Ib=a;this.F(this.Ib);a=this.Ib;this.ba&&a&&a.S(this.we,!0)},this));b.get(z.U.mm)&&!z.Tf&&CJ(this.v)&&(this.v.Rg()||this.v.Zd()||this.Rv())}};
VJ.prototype.t=function(){var a=!this.d.Q.Tp&&!z.w.Hu&&!this.d.Q.fD;return{KH:z.w.L.Uy,LH:(0,window.encodeURIComponent)(String(window.location.href)),Ua:this.d.Q.Ua,Rg:this.v.Rg(),Zd:this.v.Zd(),He:z.Tf,Qu:a,TR:this.d.Q.Tp,Kn:this.v.Kn()}};z.Iw={eW:"fyre-archive-stream",fW:"fyre-archive-stream-header",XZ:"fyre-top-content-stream",p_:"fyre-widget",mm:"fyre-featured-content-wrapper"};(0,z.D)(z.Iw,z.kI);z.e=VJ.prototype;
z.e.r=function(){this.c=(0,z.Hl)(DJ,this.t());var a=this.v.get(z.U.tk);if(1!==a){var b=this.d.Db,a=2===a?3:4,c=this.n("fyre-top-content-stream");(0,z.Kx)(b,a,c,this)}this.jr.S(this.n(z.Iw.LJ));this.Bk&&(b=this.n("fyre-archive-stream-header"),this.$t.S(b),this.Bk.S(this.n("fyre-archive-stream")));this.vh(1);this.we=this.n(z.Iw.kh);b=WJ(this);(0,z.S)(this.we,b)};
z.e.l=function(){VJ.b.l.call(this);var a=this.Ib;this.ba&&a&&a.S(this.we,!0);this.d.R.Lo("stream_data_received",this.EP,this);this.p().e(this,"request_content_context",this.eP).e(this,"request_content_reply",this.IQ);this.Bk&&this.Bk.start()};z.e.Oh=function(){this.fn&&this.fn.Oh();this.fg.Oh()};z.e.EP=function(){var a=this.v,b=a.get(z.U.hk);z.ih||b||(b=(0,z.t)(function(){this.Nr=new z.bK(this.d,a.get(z.U.Kd));this.F(this.Nr,!0)},this),(0,z.oc)(z.w.L.pb+z.w.vf.Nr,null,null,b))};
z.e.Rv=function(){var a=new z.mD(this.zF,this);a.mG=(0,z.t)(this.qU,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);(0,z.oc)(z.w.L.pb+z.w.vf.RN,null,null,b)};z.e.qU=function(){var a=this.n("fyre-featured-content-wrapper");this.dv=new z.AI(this.d);this.F(this.dv);this.dv.S(a);this.dv.Qg()};z.e.Fr=function(a){if(!this.d.Q.readOnly){var b=this.d.w.B();(0,z.Hv)(z.Ev.D(),"main",a,{K:this.d,ei:"new"},b);z.I.on(z.I.fc(z.I.j.Y),this.Uc,this)}};z.e.Uc=function(){var a=WJ(this);(0,z.S)(this.we,a)};
z.e.Nh=function(){0<(0,z.Kn)(this,this.Ib)&&(this.removeChild(this.Ib),this.Ib.s());this.Fr((0,z.t)(function(a){this.Ib=a;this.F(this.Ib);a=this.Ib;this.ba&&a&&a.S(this.we,!0);(0,z.S)(this.we,!0)},this))};z.e.Rh=function(a){null!=a&&(this.d.Db.dl(1),(0,window.setTimeout)((0,z.t)(function(){this.La||(0,z.FE)(this,a)},this),3E3))};z.e.eP=function(a){(0,z.FE)(this,a.Gk)};z.e.IQ=function(a){(0,z.FE)(this,a.Gk,function(a){(0,z.Dv)(a.Gb)})};
z.e.h=function(){VJ.b.h.call(this);z.I.off(z.I.fc(z.I.j.Y),this.Uc,this);this.v&&(this.v.off(null,null,this),this.v=null)};(0,z.v)(XJ,z.Zx);z.e=XJ.prototype;z.e.Wd=function(a,b){XJ.b.Wd.call(this,a,b);a.e(b,"repliesExpanded",this.lE);a.e(b,"sortHotThreads",this.RQ);a.e(b,"sortOrderChanged",this.QE);a.e(b,"sortTopComments",this.SQ);a.e(b,"archiveShowMore",this.PO);a.e(b,"archiveSortOrderChanged",this.QO)};
z.e.PO=function(a){var b=a.Qb||z.n;a=(0,z.t)(this.Be,this,a.target);var c=this.d.Hb;c.Ak||(c.Ak=new AJ(c.K));var c=c.Ak,d=zJ(c),f=c.fe[d];f&&(c.Pm=d);if(f)b(),a(f);else{c=this.d.Hb.Zk();d=c.j.Ze;if(c.get(d))b();else c.on(c.fc(d),b,this);(0,z.$x)(this,c,a)}};z.e.Mv=function(a,b){var c=2===b.qd,d=1!==b.qd;switch(b.type){case 0:var f=this.d.w.B(),f=(0,z.rk)(b,f),g=f.get(z.Fk),g=this.d.w.$a().get(g);f.set(z.sk,g);a.dw(f,c,d)}};
z.e.IE=function(a){if(1!==this.xm){var b=this.gV.ah;b.ki(!1);LJ(b,b.Sl);(0,z.D)(a,{direction:"new",Qb:z.n});this.QE(a)}};z.e.QO=function(a){(0,z.ay)(this);a.oi.Km(a.direction);var b=this.d.Hb.Zk(a.direction,!0),c=(0,z.t)(function(b){a.Qb();this.Be(a.oi,b)},this);(0,z.$x)(this,b,c,a.dj)};z.e.QE=function(a){var b=(0,z.cy)(this,1);(0,z.av)(this.d.Hb);b.Km(a.direction);var c=(0,z.$u)(this.d.Hb,a.direction),d=(0,z.t)(function(c){a.Qb();this.Be(b,c)},this);(0,z.$x)(this,c,d,a.dj)};
z.e.SQ=function(a){var b=(0,z.cy)(this,3),c=this.d.Hb.Fh("likes");(0,z.$x)(this,c,(0,z.t)(function(c){a.Qb();(0,z.sb)(c)?(0,z.tw)(b):this.Be(b,c)},this))};z.e.RQ=function(a){var b=(0,z.cy)(this,4),c=this.d.Hb.Ih();(0,z.$x)(this,c,(0,z.t)(function(c){a.Qb();(0,z.sb)(c)?(0,z.tw)(b):this.Be(b,c)},this))};(0,z.v)(YJ,z.Qr);z.e=YJ.prototype;z.e.c=null;z.e.h=function(){YJ.b.h.call(this);this.Hs.s();this.BC.s();this.Rb.ba&&this.Rb.s();this.If&&this.If.s();delete this.If};z.e.ml=function(a){YJ.b.ml.call(this,a);this.Hs=new XJ(this.d);this.Hs.handle(a);this.BC=new z.Yx(this.d);this.BC.handle(a)};z.e.Iy=function(){this.d.pi.stop()};z.e.lV=function(){this.d.xl.stop()};z.e.Qj=function(){this.d.pi.start()};z.e.jV=function(){this.d.xl.start()};
z.e.qa=function(){this.If&&this.If.s();this.Rb.qa(this.c);var a=(0,z.Sr)(this);this.Rb.Rh(a);this.d.R.N("render_complete")};(0,z.v)(ZJ,z.tl);ZJ.prototype.TB=HJ.D();ZJ.prototype.h=function(){ZJ.b.h.call(this);this.stop();delete this.Q;delete this.ha;$J(this);(0,z.yl)(this);this.cj&&(this.cj.s(),delete this.cj)};ZJ.prototype.Py=function(){this.stop();$J(this);ZJ.b.Py.call(this)};z.bg.main.xh.ga(ZJ);})(fyre.conv);
