/*
 * Copyright (c) 2001-2013 Christoph Mueller. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY CHRISTOPH MUELLER ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CHRISTOPH MUELLER OR
 * HIS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package de.must.middle;

/**
 * @author Christoph Mueller
 */
public class Res extends java.util.ListResourceBundle {
  static final Object[][] contents = new String[][]{
	{ "TEXT_OK_BUTTON", "OK" },
	{ "TEXT_CANCEL_BUTTON", "Cancel" },
  { "TEXT_CLOSE_BUTTON", "Close" },
	{ "TEXT_NEW_ENTRY", "New Entry" },
	{ "TEXT_APPLY_BUTTON", "Apply" },
  { "TEXT_CHOOSE_BUTTON", "Choose" },
	{ "TEXT_SAVE_AND_KEEP_WINDOW_OPEN", "Save and keep window open" },
	{ "TEXT_BUTTON_DELETE", "Delete" },
  { "TEXT_CHECK_USAGE", "Check usage" },
	{ "TEXT_ENTRY_IS_IN_USE", "Entry is in use" },
	{ "TEXT_ENTRY_MUST_NOT_BE_DELETED", "Entry must not be deleted," },
	{ "TEXT_BECAUSE_IT_IS_IN_USE", "because it is in use!" },
	{ "TEXT_THE_MAXIMUM_OF_ENTRIES_FOR", "The maximimum of entries for " },
	{ "TEXT_IS_REACHED", " is reached!" },
	{ "TEXT_WE_LIKE_TO_DELIVER_THE_FULL_LICENCE", "We like to deliver the full licence." },
	{ "TEXT_PRICES_SEE", "Prices see http://www.must.de" },
	{ "TEXT_INFOS_ABOUT_THE_LICENCE", "Information about the licence" },
	{ "TEXT_COPY_OF", "Kopie von " },
	{ "TEXT_FULL_LICENCE_SEE", "Full licence see http://www.must.de" },
	{ "TEXT_APPLY_CHANGES_FOR_ENABLING_NEW_CHOICE", "Apply changes for enabling new choice. " },
	{ "TEXT_SUBSELECTION_INFLUENCING_FOLLOWING_FIELDS", "Subselection influencing the following fields" },
	{ "TEXT_FORMALLY_INVALID", "Formally invalid" },
	{ "TEXT_IS_REQUIRED", "This is required" },
	{ "TEXT_ENTRY_ALREADY_EXISTING", "Entry alreay existing" },
	{ "TEXT_LIST_BUTTON", "List" },
	{ "TEXT_PRESENTS_SELECTED_ENTRY", "Presents details of the selected entry" },
	{ "TEXT_PROPERTIES", "Edits the selected entry" },
	{ "TEXT_COPIES_SELECTED_ENTRY", "Copies the selected entry" },
	{ "TEXT_PRINTS_SELECTED_ENTRY", "Prints the selected entry" },
	{ "TEXT_DELETES_SELECTED_ENTRY", "Deletes the selected entry" },
  { "TEXT_CHOOSES_SELECTED_ENTRY", "Chooses the  selected entry" },
	{ "TEXT_CLOSES_THIS_WINDOW", "Closes this window" },
	{ "TEXT_FILLS_LIST_ACCORDING_SELECTION", "Fills list accoding to the selection" },
	{ "TEXT_REDUCE_SELECTION_BEFORE_LISTING", "Reduce selection before listing" },
	{ "TEXT_ALL_WITH_BRACKETS", "<all>" },
  { "TEXT_NO_CHOICE_WITH_BRACKETS", "<no choice>" },
  { "TEXT_LOADING", "Loading..." },
	{ "TEXT_LOADING_SINGLE_ENTRY", "Loading single entry..." },
	{ "TEXT_LOADING_ENTRY_TO_COPY", "Loading entry to copy..." },
	{ "TEXT_ENTRY_DELETED", "Entry deleted." },
	{ "TEXT_ENTRY_COULD_NOT_BE_DELETED", "Entry could not be deleted." },
	{ "TEXT_DELETION_UNCOMPLETED", "Deletion uncompleted." },
	{ "TEXT_NO_ENTRY_IS_MATCHING_SELECTION", "No entry is matching the selection" },
	{ "TEXT_LOADING_SELECTION", "Loading selection..." },
	{ "TEXT_PARTIAL_LISTING", "(Partial listing)" },
	{ "TEXT_ENTRIES", " Entries" },
	{ "TEXT_SYNTAX_ERROR_ACCORDING_TO_DB_DRIVER", "Syntax error according to database driver" },
  { "TEXT_QUERY_WAS", "Query was:" },
	{ "TEXT_DESCRIPTION", "Description" },
	{ "TEXT_POS", "Pos" },
  { "TEXT_POS_TT", "Position - first criterion for alignment sequence" },
	{ "TEXT_SELECT_IMAGE_TO_IMPORT", "Select image file to import" },
  { "TEXT_REPEAT_INPUT", "Repeat input" },
  { "TEXT_ENTRY_RECORDED", "Entry recorded" },
  { "TEXT_ENTRIES_RECORDED", "Entries recorded" },
  { "TEXT_FORWARD", "Forward" },
  { "TEXT_BACKWARD", "Backward" },
  { "TEXT_DONE", "Done" },
  { "TEXT_CONFIRM_DELETION", "Confirm deletion" },
  { "TEXT_CONFIRMATION", "Confirmation" },
  { "TEXT_CHANGES", "Changes" },
  { "TEXT_YES", "Yes" },
  { "TEXT_NO", "No" },
  { "TEXT_THIS_ITEM_IS_GOING_TO_BE_DELETED", "This item is going to be deleted:" },
  { "TEXT_REMOVE", "Remove" },
  { "TEXT_REMOVED", "Will be removed by OK" },
  { "TEXT_EXCEPTIONAL_SORTING", "Exceptional sorting" },
  { "TEXT_INPUT_FORMALLY_INVALID", "Input formally invalid" },
  { "TEXT_HELP", "Help" },
  { "TEXT_HELP", "Help" },
  { "TEXT_INNOVATIONS_SEE", "Innovations see" },
  { "TEXT_OUTPUT", "Output" },
  { "TEXT_PRINTER", "Printer" },
  { "TEXT_SCREEN", "Screen" },
  { "TEXT_HTML_FILE", "HTML File" },
  { "TEXT_NAME_FOR_NO_CHOICE", "no choice" },
  { "TEXT_NO_STATEMENT", "no statement" },
  { "TEXT_HELP_ON_DATABASE_CONNECTION", "Help on database connection" },
  { "TEXT_THE_APPLICATION_COULD_NOT_CONNECT_TO_DATABASE", "The application could not connect to database" },
  { "TEXT_THE_RECEIVED_ERROR_MESSAGE_IS", "The received error message is" },
  { "TEXT_FOR_FURTHER_INFORMATION...", "For further information about database configuration please press help button" },
  { "TEXT_TABLE_CREATION_CONFIRMATION", "Confirm table creation" },
  { "TEXT_THE_CHOOSEN_DATABASE_DOESNT_CONTAIN", "The choosen database doesn't contain" },
  { "TEXT_-TABLES", " tables" },
  { "TEXT_CREATE_TABLES_NOW", "Create tables now" },
  { "TEXT_CONFIRM_TABLE_UPDATE", "Confirm table update" },
  { "TEXT_DATABASE_HAS_TO_BE_EXTENDED", "Database has to be extended." },
  { "TEXT_PREVIOUS_BACKAUP_IS_STRONGLY_RECOMMENDED", "Previous backup is strongly recommended." },
  { "TEXT_PROCESS_EXTENSION_NOW", "Process extension now?" },
  { "TEXT_SAVE_CHANGES_QUESTION", "Do you want to save changes?" },
  { "TEXT_SIGNON_TO_THE_SERVER", "Signon to the Server" },
  { "TEXT_SYSTEM", "System" },
  { "TEXT_USER_ID", "User ID" },
  { "TEXT_PASSWORD", "Password" },
  { "TEXT_MISSING_System", "Missing system" },
  { "TEXT_MISSING_USER_ID", "Missing user ID" },
  { "TEXT_MISSING_PASSWORD", "Missing password" },
  { "TEXT_CHECK", "Check" },
  { "TEXT_USER_OR_PASSWORD_INVALID", "User / password invalid" },
  { "TEXT_UNKNOWN_HOST", "Unknown host" },
  { "TEXT_PASSWORD_CHANGE", "Password change" },
  { "TEXT_OLD_PASSWORD", "Old password" },
  { "TEXT_NEW_PASSWORD", "New password" },
  { "TEXT_NEW_PASSWORD_REPEAT", "Repeat new password" },
  { "TEXT_PASSWORD_DIFFERENT", "New passwords differ" },
  { "TEXT_ACTION_FAILED", "Action failed" },
  { "TEXT_CHOOSE_DIRECTORY", "Choose directory" },
  { "TEXT_CHOOSE_FILE", "Choose file" },
  { "TEXT_CHOOSE_DIRECTORY_WITH_EXTERNAL_INFORMATION", "Choose directory with external information" },
  { "TEXT_CHOOSE_FILE_WITH_EXTERNAL_INFORMATION", "Choose file with external information" },
  { "TEXT_OPEN", "Open" },
  { "TEXT_DEFAULT_PRINTER", "Default Printer" },
  { "TEXT_PAGE", "Page" },
  { "TEXT_OF", "of" },
  { "TEXT_TERM_REPLACEMENT", "Term Replacement" },
  { "TEXT_UI_TERM_REPLACEMENT", "Term Replacement in User Interface" },
  { "TEXT_ORIGNAL", "Original" },
  { "TEXT_REPLACEMENT", "Replacement" },
  { "TEXT_USER_LOGIN", "User login" },
  { "TEXT_PREVIOUS_INQUIRY", "Previous inquiry" },
  { "TEXT_NEXT_INQUIRY", "Next inquiry" },
  { "TEXT_TYPE_DOT_REQUIRED", "File extension .dot required" },
  { "TEXT_FILE_NOT_FOUND", "File not found" },
  { "TEXT_CUT", "Cut" },
  { "TEXT_COPY", "Copy" },
  { "TEXT_PASTE", "Paste" },
  { "TEXT_SELECT_ALL", "Select All" },
  { "TEXT_UNDO_TYPING", "Undo Typing" },
  { "TEXT_GENERATE_WHERE_CONDITON", "Generate Where Condition" },
  { "TEXT_AND", "and" },
  { "TEXT_OR", "or" },
  { "TEXT_CLOSE_ALL_TABS", "Closes all tabs" },
  { "TEXT_LOGGED_OUT", "Your logged out now." },
  { "TEXT_LIMITING", "Limiting (searching) data" },
  { "TEXT_REPLACEMENTS_PROCEEDED", "Replacements proceeded" },
  { "TEXT_REMAINING_TIME", "Remaining time" },
  { "TEXT_RESUME", "Resume" },
  { "TEXT_KEY_EXTENSION", "Key extension" },
  { "TEXT_CASE_SENSITIVE", "Case sensitive" },
  { "TEXT_SUPERORDINATE", "Superordinate" },
  { "TEXT_SELECT_ALL", "Select all" },
  { "TEXT_DESELECT_ALL", "Deselect all" },
  { "TEXT_SAVE_OR_CANCEL", "Please save or cancel your input before closing (OK or Cancel)" },
  { "TEXT_RETURN_TO_CORRECT", "Return to previous page to correct input" },
  { "TEXT_COMPLETE_SO_CLOSE", "Process completed successfully. Tab may be closed now." },
  { "TEXT_DB_BACKUP", "Database Backup" },
  { "TEXT_OUTDIR", "Output directory" },
  { "TEXT_OUTFILE", "Output file" },
  { "TEXT_OVERRIDE_EXISTING_FILE", "Override existing file?" },
  { "TEXT_ATTENTION", "ATTENTION PLEASE!" },
  { "TEXT_RESTORE_DB", "Restore Database" },
  { "TEXT_SAVE_FILE", "Save file" },
  { "TEXT_SUCCESSFUL", "successful" },
  { "TEXT_CANCELED", "canceled" },
  { "TEXT_INFORMATION", "Information" },
  { "TEXT_SAVE_SUITABLE", "Please save file in suitable directory now." },
  { "TEXT_CANCELED_SO_CLOSE", "Process canceled. Tab may be closed now." },
  { "TEXT_NOT_EXISTEND", "Not existent" },
  { "TEXT_NO_WRITE_PERMISSION", "No write permission" },
  { "TEXT_FRAGMENT", "fragment" },
  { "TEXT_WORD", "word" },
  { "TEXT_EXACT", "exact" },
  { "TEXT_STANDARD", "Standard" },
  { "TEXT_FAILURE", "Failure" },
  { "TEXT_NOT_COMPLETED", "The operation could not be completed." },
  { "TEXT_REASON", "Reason" },
  { "TEXT_BORDER", "Border" },
  { "TEXT_SHOW_GRID", "Show table grid" },
  { "TEXT_CONTAINS", "contains" },
  { "TEXT_STARTS_WITH", "starts with" },
  { "TEXT_DOESNT_CONTAIN", "doesn't contain" },
  { "TEXT_IS_EQUALS", "is equals" },
  { "TEXT_IS_NOT", "is not" },
  { "TEXT_GREATER_EQUALS", "greater equals" },
  { "TEXT_LOWER_EQUALS", "lower equals" },
  { "TEXT_COMBINATION", "Combination" },
  { "TEXT_AND_BEFORE_OR", "and before or" },
  { "TEXT_OR_BEFORE_AND", "or before and" },
  };

  private Res instance;
  
  @Override
  public Object[][] getContents() {
    return contents;
  }

}
