/*
 * Copyright (c) 2001-2013 Christoph Mueller. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * THIS SOFTWARE IS PROVIDED BY CHRISTOPH MUELLER ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CHRISTOPH MUELLER OR
 * HIS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package de.must.middle;

/**
 * @author Christoph Mueller
 */
public class Res_de_DE extends java.util.ListResourceBundle {
  static final Object[][] contents = new String[][]{
	{ "TEXT_OK_BUTTON", "OK" },
	{ "TEXT_CANCEL_BUTTON", "Abbrechen" },
  { "TEXT_CLOSE_BUTTON", "Schließen" },
	{ "TEXT_NEW_ENTRY", "Neuer Eintrag" },
	{ "TEXT_APPLY_BUTTON", "Übernehmen" },
  { "TEXT_CHOOSE_BUTTON", "Auswählen" },
	{ "TEXT_SAVE_AND_KEEP_WINDOW_OPEN", "Speichern und Fenster geöffnet halten" },
	{ "TEXT_BUTTON_DELETE", "Entfernen" },
  { "TEXT_CHECK_USAGE", "Verwendungsprüfung" },
	{ "TEXT_ENTRY_IS_IN_USE", "Eintrag wird verwendet." },
	{ "TEXT_ENTRY_MUST_NOT_BE_DELETED", "Dieser Eintrag kann nicht gelöscht werden," },
	{ "TEXT_BECAUSE_IT_IS_IN_USE", "da er noch verwendet wird!" },
	{ "TEXT_THE_MAXIMUM_OF_ENTRIES_FOR", "Die maximale Anzahl Eintragungen der " },
	{ "TEXT_IS_REACHED", " ist erreicht!" },
	{ "TEXT_WE_LIKE_TO_DELIVER_THE_FULL_LICENCE", "Gerne liefern wir Ihnen die Voll-Lizenz" },
	{ "TEXT_PRICES_SEE", "Preise siehe http://www.must.de" },
	{ "TEXT_INFOS_ABOUT_THE_LICENCE", "Information zur Lizenz" },
	{ "TEXT_COPY_OF", "Kopie von " },
	{ "TEXT_FULL_LICENCE_SEE", "Volllizenz siehe http://www.must.de" },
	{ "TEXT_APPLY_CHANGES_FOR_ENABLING_NEW_CHOICE", "Änderungen mit Übernehmen oder OK quittieren, damit Auswahl möglich " +
    "ist." },
	{ "TEXT_SUBSELECTION_INFLUENCING_FOLLOWING_FIELDS", "Unterauswahl für die nachfolgenden Felder." },
	{ "TEXT_FORMALLY_INVALID", "Formal ungültig" },
	{ "TEXT_IS_REQUIRED", "Diese Angabe ist erforderlich" },
	{ "TEXT_ENTRY_ALREADY_EXISTING", "Eintrag bereits vorhanden" },
	{ "TEXT_LIST_BUTTON", "Auflisten" },
	{ "TEXT_PRESENTS_SELECTED_ENTRY", "Präsentiert Details des gewählten Eintrags" },
	{ "TEXT_PROPERTIES", "Editiert den gewählten Eintrag" },
	{ "TEXT_COPIES_SELECTED_ENTRY", "Kopiert den gewählten Eintrag" },
	{ "TEXT_PRINTS_SELECTED_ENTRY", "Druckt den gewählten Eintrag" },
	{ "TEXT_DELETES_SELECTED_ENTRY", "Entfernt den gewählten Eintrag" },
  { "TEXT_CHOOSES_SELECTED_ENTRY", "Wählt den Eintrag aus" },
	{ "TEXT_CLOSES_THIS_WINDOW", "Schließt dieses Fenster" },
	{ "TEXT_FILLS_LIST_ACCORDING_SELECTION", "Füllt die Liste gemäß obiger Auswahl" },
	{ "TEXT_REDUCE_SELECTION_BEFORE_LISTING", "Vor Auflistung Auswahl einschränken" },
	{ "TEXT_ALL_WITH_BRACKETS", "<alle>" },
  { "TEXT_NO_CHOICE_WITH_BRACKETS", "<ohne>" },
  { "TEXT_LOADING", "Lade..." },
	{ "TEXT_LOADING_SINGLE_ENTRY", "Lade einzelnen Eintrag..." },
	{ "TEXT_LOADING_ENTRY_TO_COPY", "Lade zu kopierenden Eintrag..." },
	{ "TEXT_ENTRY_DELETED", "Eintrag gelöscht." },
	{ "TEXT_ENTRY_COULD_NOT_BE_DELETED", "Eintrag konnte nicht gelöscht werden." },
	{ "TEXT_DELETION_UNCOMPLETED", "Löschen abgebrochen." },
	{ "TEXT_NO_ENTRY_IS_MATCHING_SELECTION", "Kein Eintrag entspricht der Auswahl" },
	{ "TEXT_LOADING_SELECTION", "Lade Auswahl..." },
	{ "TEXT_PARTIAL_LISTING", "(Teilauflistung)" },
	{ "TEXT_ENTRIES", " Einträge" },
	{ "TEXT_SYNTAX_ERROR_ACCORDING_TO_DB_DRIVER", "Syntaxfehler laut Datenbanktreiber" },
  { "TEXT_QUERY_WAS", "Abfrage lautete:" },
	{ "TEXT_DESCRIPTION", "Beschreibung" },
	{ "TEXT_POS", "Pos" },
  { "TEXT_POS_TT", "Position - erstes Kriterium für die Anordnungs-Reihenfolge" },
	{ "TEXT_SELECT_IMAGE_TO_IMPORT", "Auswahl der zu importierenden Bilddatei" },
  { "TEXT_REPEAT_INPUT", "Weitere Erfassung" },
  { "TEXT_ENTRY_RECORDED", "Eintrag erfasst" },
  { "TEXT_ENTRIES_RECORDED", "Einträge erfasst" },
  { "TEXT_FORWARD", "Vorwärts" },
  { "TEXT_BACKWARD", "Rückwärts" },
  { "TEXT_DONE", "Fertig" },
  { "TEXT_CONFIRM_DELETION", "Löschen bestätigen" },
  { "TEXT_CONFIRMATION", "Bestätigung" },
  { "TEXT_CHANGES", "Änderungen" },
  { "TEXT_YES", "Ja" },
  { "TEXT_NO", "Nein" },
  { "TEXT_THIS_ITEM_IS_GOING_TO_BE_DELETED", "Dieser Eintrag soll gelöscht werden:" },
  { "TEXT_REMOVE", "Entfernen" },
  { "TEXT_REMOVED", "Wird mit OK entfernt" },
  { "TEXT_EXCEPTIONAL_SORTING", "Sondersortierung" },
  { "TEXT_INPUT_FORMALLY_INVALID", "Eingabe formal falsch" },
  { "TEXT_HELP", "Hilfe" },
  { "TEXT_INNOVATIONS_SEE", "Neuerungen siehe" },
  { "TEXT_OUTPUT", "Ausgabe" },
  { "TEXT_PRINTER", "Drucker" },
  { "TEXT_SCREEN", "Bildschirm" },
  { "TEXT_HTML_FILE", "HTML-Datei" },
  { "TEXT_NAME_FOR_NO_CHOICE", "ohne" },
  { "TEXT_NO_STATEMENT", "ohne Angabe" },
  { "TEXT_HELP_ON_DATABASE_CONNECTION", "Hilfe zur Datenbankverbindung" },
  { "TEXT_THE_APPLICATION_COULD_NOT_CONNECT_TO_DATABASE", "Die Anwendung konnte keine Datenbankverbindung herstellen" },
  { "TEXT_THE_RECEIVED_ERROR_MESSAGE_IS", "Die erhaltene Fehlermeldung lautet" },
  { "TEXT_FOR_FURTHER_INFORMATION...", "Für nähere Hinweise zur Einrichtung der Datenbank drücken sie bitte den Hilfe-Button" },
  { "TEXT_TABLE_CREATION_CONFIRMATION", "Neuerstellung der Tabellen bestätigen " },
  { "TEXT_THE_CHOOSEN_DATABASE_DOESNT_CONTAIN", "Die gewählte Datenbank enthält keine" },
  { "TEXT_-TABLES", "-Tabellen" },
  { "TEXT_CREATE_TABLES_NOW", "Tabellen jetzt erstellen" },
  { "TEXT_CONFIRM_TABLE_UPDATE", "Update der Tabellen bestätigen" },
  { "TEXT_DATABASE_HAS_TO_BE_EXTENDED", "Die gewählte Datenbank soll erweitert werden." },
  { "TEXT_PREVIOUS_BACKAUP_IS_STRONGLY_RECOMMENDED", "Die vorherige Sicherung der Datenbank wird dringend empfohlen." },
  { "TEXT_PROCESS_EXTENSION_NOW", "Erweiterung jetzt durchführen?" },
  { "TEXT_SAVE_CHANGES_QUESTION", "Möchten Sie die Änderungen speichern?" },
  { "TEXT_SIGNON_TO_THE_SERVER", "Anmeldung am Server" },
  { "TEXT_SYSTEM", "System" },
  { "TEXT_USER_ID", "Benutzer ID" },
  { "TEXT_PASSWORD", "Kennwort" },
  { "TEXT_MISSING_System", "Systemangabe fehlt" },
  { "TEXT_MISSING_USER_ID", "Benutzer-ID fehlt" },
  { "TEXT_MISSING_PASSWORD", "Kennwort fehlt" },
  { "TEXT_CHECK", "Check" },
  { "TEXT_USER_OR_PASSWORD_INVALID", "Benutzer / Kennwort ungültig" },
  { "TEXT_UNKNOWN_HOST", "Unbekanntes System" },
  { "TEXT_PASSWORD_CHANGE", "Kennwort-Änderung" },
  { "TEXT_OLD_PASSWORD", "Altes Kennwort" },
  { "TEXT_NEW_PASSWORD", "Neues Kennwort" },
  { "TEXT_NEW_PASSWORD_REPEAT", "Neues Kennwort, Wiederholung" },
  { "TEXT_PASSWORD_DIFFERENT", "Neue Kennwörter sind nicht identisch" },
  { "TEXT_ACTION_FAILED", "Aktion fehlgeschlagen" },
  { "TEXT_CHOOSE_DIRECTORY", "Ordner wählen" },
  { "TEXT_CHOOSE_FILE", "Datei wählen" },
  { "TEXT_CHOOSE_DIRECTORY_WITH_EXTERNAL_INFORMATION", "Ordner mit externen Informationen auswählen" },
  { "TEXT_CHOOSE_FILE_WITH_EXTERNAL_INFORMATION", "Datei mit externen Informationen auswählen" },
  { "TEXT_OPEN", "Öffnen" },
  { "TEXT_DEFAULT_PRINTER", "Standard-Drucker" },
  { "TEXT_PAGE", "Seite" },
  { "TEXT_OF", "von" },
  { "TEXT_TERM_REPLACEMENT", "Begriffs-Ersetzungen" },
  { "TEXT_UI_TERM_REPLACEMENT", "Begriffs-Ersetzungen in Anwendungsoberfläche" },
  { "TEXT_ORIGNAL", "Original" },
  { "TEXT_REPLACEMENT", "Ersatz" },
  { "TEXT_USER_LOGIN", "Benutzer-Anmeldung" },
  { "TEXT_PREVIOUS_INQUIRY", "Vorhergehende Auflistung" },
  { "TEXT_NEXT_INQUIRY", "Nächste Auflistung" },
  { "TEXT_TYPE_DOT_REQUIRED", "Dateityp .dot erforderlich" },
  { "TEXT_FILE_NOT_FOUND", "Datei nicht gefunden" },
  { "TEXT_CUT", "Ausschneiden" },
  { "TEXT_COPY", "Kopieren" },
  { "TEXT_PASTE", "Einfügen" },
  { "TEXT_SELECT_ALL", "Alles markieren" },
  { "TEXT_UNDO_TYPING", "Rückgängig" },
  { "TEXT_GENERATE_WHERE_CONDITON", "Generiere Where-Condition" },
  { "TEXT_AND", "und" },
  { "TEXT_OR", "oder" },
  { "TEXT_CLOSE_ALL_TABS", "Alle Tabs schließen" },
  { "TEXT_LOGGED_OUT", "Sie sind jetzt abgemeldet." },
  { "TEXT_LIMITING", "Einschränkende (suchende) Angaben" },
  { "TEXT_REPLACEMENTS_PROCEEDED", "Ersetzungen vollzogen" },
  { "TEXT_REMAINING_TIME", "Verbleibende Zeit" },
  { "TEXT_RESUME", "Neu beginnen" },
  { "TEXT_KEY_EXTENSION", "Schlüsselerweiterung" },
  { "TEXT_CASE_SENSITIVE", "groß-klein" },
  { "TEXT_SUPERORDINATE", "Übergeordnet" },
  { "TEXT_SELECT_ALL", "Alle selektieren" },
  { "TEXT_DESELECT_ALL", "Alle deselektieren" },
  { "TEXT_SAVE_OR_CANCEL", "Bitte speichern oder verwerfen Sie Ihre Eingabe vor dem Schließen (OK oder Abbrechen)" },
  { "TEXT_RETURN_TO_CORRECT", "Zur vorherigen Seite zurückkehren, um die Eingaben zu korrigieren" },
  { "TEXT_COMPLETE_SO_CLOSE", "Aktion erfolgreich. Tab kann geschlossen werden." },
  { "TEXT_DB_BACKUP", "Datensicherung" },
  { "TEXT_OUTDIR", "Ausgabe-Verzeichnis" },
  { "TEXT_OUTFILE", "Ausgabe-Datei" },
  { "TEXT_OVERRIDE_EXISTING_FILE", "Bestehende Datei ueberschreiben?" },
  { "TEXT_ATTENTION", "ACHTUNG!" },
  { "TEXT_RESTORE_DB", "Datenrücksicherung" },
  { "TEXT_SAVE_FILE", "Sicherungsdatei" },
  { "TEXT_SUCCESSFUL", "erfolgreich" },
  { "TEXT_CANCELED", "abgebrochen" },
  { "TEXT_INFORMATION", "Information" },
  { "TEXT_SAVE_SUITABLE", "Die zum Download angebotene Datei bitte nun an geeigneter Stelle speichern." },
  { "TEXT_CANCELED_SO_CLOSE", "Aktion abgebrochen. Tab kann geschlossen werden." },
  { "TEXT_NOT_EXISTEND", "Nicht existent" },
  { "TEXT_NO_WRITE_PERMISSION", "Keine Schreibberechtigung" },
  { "TEXT_FRAGMENT", "Fragment" },
  { "TEXT_WORD", "Wort" },
  { "TEXT_EXACT", "exakt" },
  { "TEXT_STANDARD", "Standard" },
  { "TEXT_FAILURE", "Fehlschlag" },
  { "TEXT_NOT_COMPLETED", "Aktion konnte nicht durchgeführt werden." },
  { "TEXT_REASON", "Ursache" },
  { "TEXT_BORDER", "Rahmen" },
  { "TEXT_SHOW_GRID", "Gitternetzlinien in Tabelle" },
  { "TEXT_CONTAINS", "enthält" },
  { "TEXT_STARTS_WITH", "beginnt mit" },
  { "TEXT_DOESNT_CONTAIN", "enthält nicht" },
  { "TEXT_IS_EQUALS", "exakt gleich" },
  { "TEXT_IS_NOT", "ungleich" },
  { "TEXT_GREATER_EQUALS", "größer gleich" },
  { "TEXT_LOWER_EQUALS", "kleiner gleich" },
  { "TEXT_COMBINATION", "Kombination" },
  { "TEXT_AND_BEFORE_OR", "und vor oder" },
  { "TEXT_OR_BEFORE_AND", "oder vor und" },
  };

  private Res_de_DE instance;

  @Override
  public Object[][] getContents() {
    return contents;
  }
  
}
